define({
  "map": {
    "error": "Nem sikerült létrehozni a térképet",
    "licenseError": {
      "message": "Az Ön fiókjának licence nem terjed ki a nem nyilvános konfigurálható alkalmazásokra. Igényelje a szervezete adminisztrátorától, hogy rendeljen Önhöz olyan felhasználótípust, amely tartalmazza az alapvető alkalmazásokat, vagy egy kiegészítő alapvető alkalmazásokra vonatkozó licencet.",
      "title": "Nincs licence"
    }
  },
  "onlineStatus": {
    "offline": "Jelenleg kapcsolat nélküli módban dolgozik. A beküldött űrlapok helyben lesznek mentve, amíg létre nem jön a kapcsolat a szerverrel.",
    "reconnecting": "Újracsatlakozás&hellip;",
    "pending": "A függőben lévő ${total} módosítás akkor lesz elküldve, amikor újból létrejön a hálózati kapcsolat."
  },
  "configure": {
    "mapdlg": {
      "items": {
        "organizationLabel": "Saját szervezet",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "Saját tartalom",
        "favoritesLabel": "Saját kedvencek"
      },
      "title": "Webtérkép kiválasztása",
      "searchTitle": "Keresés",
      "ok": "OK",
      "cancel": "Mégse",
      "placeholder": "Adjon meg egy keresőkifejezést"
    },
    "groupdlg": {
      "items": {
        "organizationLabel": "Saját szervezet",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "Saját tartalom",
        "favoritesLabel": "Saját kedvencek"
      },
      "title": "Csoport kiválasztása",
      "searchTitle": "Keresés",
      "ok": "OK",
      "cancel": "Mégse",
      "placeholder": "Adjon meg egy keresőkifejezést"
    },
    "sharedlg": {
      "items": {},
      "mailtoLinkDescription": "Itt van egy GeoForm-hivatkozás"
    }
  },
  "user": {
    "all": "Mind",
    "mgrs": "MGRS",
    "usng": "USNG",
    "utm": "UTM",
    "utm_northing": "Ordináta",
    "utm_easting": "Abszcissza",
    "utm_zone_number": "Zóna száma",
    "selectLayerTabText": "${formSection} Űrlap kiválasztása",
    "geoFormGeneralTabText": "${formSection} Adatok megadása",
    "locationInformationText": "${formSection} Hely kiválasztása",
    "submitInformationText": "${formSection} Űrlap kitöltése",
    "submitInstructions": "Adja hozzá ezt az információt a térképhez.",
    "myLocationText": "Aktuális hely",
    "locationDescriptionForMoreThanOneOption": "Adja meg a bejegyzés helyét a térképre kattintva/koppintva vagy a következő lehetőségek egyikének segítségével.",
    "locationDescriptionForOneOption": "Adja meg a bejegyzés helyét a térképre kattintva/koppintva vagy a következő lehetőség segítségével.",
    "locationDescriptionForNoOption": "Adja meg a bejegyzés helyét a térképre kattintva/koppintva.",
    "addressText": "Keresés",
    "geographic": "Szélesség/hosszúság",
    "locationTabText": "Hely",
    "locationPopupTitle": "Hely",
    "submitButtonText": "Bejegyzés beküldése",
    "submitButtonTextLoading": "Küldés&hellip;",
    "formValidationMessageAlertText": "A következő mezőket kötelező kitölteni:",
    "selectLocation": "Válasszon helyet a beküldésnek.",
    "emptylatitudeAlertMessage": "Adjon meg egy ${openLink}szélességi${closeLink} koordinátát.",
    "emptylongitudeAlertMessage": "Adjon meg egy ${openLink}hosszúsági${closeLink} koordinátát.",
    "shareUserTitleMessage": "Köszönjük a hozzájárulását!",
    "entrySubmitted": "A bejegyzés el lett küldve a térképre.",
    "shareThisForm": "Az űrlap megosztása",
    "shareUserTextMessage": "Értesítse a többi felhasználót a hozzájárulásról a következő lehetőségek segítségével.",
    "addAttachmentFailedMessage": "Nem lehet csatolmányt hozzáadni a réteghez",
    "addFeatureFailedMessage": "Nem lehet vektoros elemet hozzáadni a réteghez",
    "noLayerConfiguredMessage": "Nem sikerült betölteni vagy megkeresni egy szerkeszthető vektoroselem-réteget. Az űrlap megjelenítéséhez és a beküldések összegyűjtésének elkezdéséhez vegyen fel egy szerkeszthető vektoroselem-réteget a webtérképbe.",
    "placeholderLatitude": "Szélesség (Y)",
    "placeholderLongitude": "Hosszúság (X)",
    "latitude": "Szélesség",
    "longitude": "Hosszúság",
    "findMyLocation": "Add meg a helyzetem!",
    "finding": "Hely meghatározása&hellip;",
    "backToTop": "Vissza az elejére",
    "addressSearchText": "Itt fog megjelenni a beküldése. A tű húzásával pontosíthatja a helyet.",
    "shareModalFormText": "Űrlap hivatkozása",
    "close": "Bezárás",
    "locationNotFound": "A hely nem található.",
    "setLocation": "Hely beállítása",
    "find": "Cím vagy hely keresése",
    "attachment": "Csatolmány",
    "toggleDropdown": "Lenyíló be-/kikapcsolása",
    "invalidString": "Adjon meg egy érvényes értéket.",
    "invalidSmallNumber": "Adjon meg egy érvényes ${openStrong}egész${closeStrong} értéket -32768 és 32767 között.",
    "invalidNumber": "Adjon meg egy érvényes ${openStrong}egész${closeStrong} értéket -2147483648 és 2147483647 között.",
    "invalidFloat": "Adjon meg érvényes ${openStrong}lebegőpontos${closeStrong} értéket.",
    "invalidDouble": "Adjon meg érvényes ${openStrong}dupla${closeStrong} értéket.",
    "invalidLatLong": "Adjon meg érvényes szélességi és hosszúsági koordinátákat.",
    "invalidUTM": "Adjon meg érvényes UTM-koordinátákat.",
    "invalidUSNG": "Adjon meg érvényes USNG-koordinátákat.",
    "invalidMGRS": "Adjon meg érvényes MGRS-koordinátákat.",
    "geoformTitleText": "GeoForm",
    "domainDefaultText": "Kiválasztás&hellip;",
    "applyEditsFailedMessage": "Hiba történt a beküldésnél.",
    "applyEditsFailedRobot": "A beküldés el lett utasítva, mert nem felelt meg a robotészlelésnek.",
    "applyEditsAuthError": "A bejegyzést nem lehet elküldeni az Ön felhasználói szintje miatt. További segítségért forduljon a szervezet adminisztrátorához.",
    "requiredFields": "A következő mező kitöltése kötelező. Adjon meg egy érvényes értéket.",
    "requiredField": "(kötelező)",
    "error": "Hiba",
    "textRangeHintMessage": "${openStrong}Tipp:${closeStrong} ${minValue} minimális érték és ${maxValue} maximális érték",
    "dateRangeHintMessage": "${openStrong}Tipp:${closeStrong} ${minValue} kezdő dátum és ${maxValue} záró dátum",
    "remainingCharactersHintMessage": "${value} karakter maradt",
    "mapFullScreen": "Teljes képernyő",
    "mapRestore": "Visszaállítás",
    "filterSelectEmptyText": "Kiválasztás",
    "invalidLayerMessage": "Nem található érvényes réteg a GeoForm létrehozásához. Ha a GeoForm konfigurálása egy réteggel történt, akkor lehetséges, hogy réteg már nem érhető el, vagy nem sikerült az engedélyezése.",
    "selectedLayerText": "Mind",
    "fileUploadStatus": "Fájlfeltöltési állapot",
    "uploadingBadge": "&nbsp;Feltöltés&hellip;",
    "successBadge": "&nbsp;Feltöltve",
    "retryBadge": "Próbálja újra",
    "errorBadge": "Nem sikerült a feltöltés&nbsp;&nbsp;&nbsp;",
    "fileTooLargeError": "A fájl túl nagy a csatoláshoz",
    "exceededFileCountError": "Túllépte a csatolmányok engedélyezett maximális számát",
    "selectFileTitle": "Válasszon ki egy fájlt",
    "btnSelectFileText": "Fájl kiválasztása",
    "btnViewSubmissions": "Beküldések megtekintése"
  },
  "builder": {
    "gettingStarted": "Első lépések",
    "dateSettings": "Dátumbeállítások",
    "hiddenDateField": "Ezen dátummező elrejtése",
    "preventPastDates": "Ne engedélyezze a múltbeli dátumokat",
    "preventFutureDates": "Ne engedélyezze a jövőbeli dátumokat",
    "useCurrentDate": "Állítsa be az aktuális dátumot és időt ebben a mezőben",
    "configure": "Konfigurálás",
    "configureField": "„${fieldName}” mező konfigurálása",
    "invalidUser": "Nincs engedélye az elem megtekintésére",
    "invalidWebmapSelectionAlert": "A kiválasztott webtérkép nem tartalmaz használható érvényes réteget. A folytatáshoz vegyen fel egy szerkeszthető vektoroselem-réteget a webtérképbe.",
    "invalidWebmapSelectionAlert2": "További információ: ${openLink}Mi a vektoros adatszolgáltatás?${closeLink}",
    "selectFieldsText": "Űrlapmezők kiválasztása",
    "selectThemeText": "Űrlap témájának kiválasztása",
    "setViewerText": "Megtekintő konfigurálása",
    "introText": "Kezdés",
    "webmapText": "Webtérkép",
    "layerText": "Réteg",
    "detailsText": "Részletek",
    "fieldsText": "Mezők",
    "styleText": "Stílus",
    "viewerText": "Megtekintő",
    "optionText": "Beállítások",
    "previewText": "Előnézet",
    "publishText": "Közzététel",
    "optionsApplicationText": "Beállítások",
    "submitButtonText": "Küldés gomb szövege (választható)",
    "submitButtonDesc": "Feliratot adhat meg az új bejegyzések beküldésére szolgáló gombhoz. Ez a szöveg nem lesz lefordítva.",
    "viewSubmissionsText": "Beküldések megtekintése gomb szövege (választható)",
    "viewSubmissionsDesc": "Feliratot adhat meg a meglévő bejegyzések megtekintésére szolgáló gombhoz. Ez a szöveg nem lesz lefordítva.",
    "titleText": "Szerkesztő",
    "descriptionText": "A Geoform egy konfigurálható sablon egy ${link1}vektoros adatszolgáltatás{closeLink} adatainak űrlapon történő szerkesztéséhez. Ez az alkalmazás lehetővé teszi a felhasználók számára, hogy űrlapon adják meg az adatokat a térkép felugró ablaka helyett, miközben tovább élvezhetik a ${link2}webtérkép{closeLink} és a szerkeszthető vektoros adatszolgáltatások előnyeit. A GeoForm testreszabásához és használatához kövesse az alábbi lépéseket.",
    "btnPreviousText": "Előző",
    "btnNextText": "Következő",
    "webmapTabTitleText": "Webtérkép kiválasztása",
    "viewWebmap": "Webtérkép megtekintése",
    "webmapDetailsText": "A kiválasztott webtérkép: ${webMapTitleLink}${webMapTitle}${closeLink}. Másik webtérkép megadásához kattintson a „Webtérkép választása” gombra.",
    "btnSelectWebmapText": "Webtérkép választása",
    "btnSelectWebmapTextLoading": "Betöltés&hellip;",
    "layerTabTitleText": "Szerkeszthető réteg(ek) kiválasztása",
    "selectLayerLabelText": "Réteg",
    "selectLayerDefaultOptionText": "Réteg kiválasztása",
    "enableBasemapToggle": "Alaptérkép váltógombjának megjelenítése",
    "enableBasemapToggleDescription": "A GeoForm beállítható az alaptérkép váltógombjának megjelenítésére/elrejtésére.",
    "defaultBasemap": "Alaptérkép váltása",
    "secondaryBasemap": "Alapértelmezett alaptérkép",
    "detailsTabTitleText": "Űrlap részletei",
    "detailTitleLabelText": "Cím",
    "detailLogoLabelText": "Logókép",
    "descriptionLabelText": "Űrlap utasításai és részletei",
    "fieldDescriptionLabelText": "Súgószöveg (választható)",
    "fieldDescriptionHelpText": "Adjon meg rövid leírást vagy utasításokat a mezőhöz.",
    "fieldHintHelpText": "A mező helyőrző szövege.",
    "fieldTabFieldHeaderText": "Mező",
    "fieldTabLabelHeaderText": "Felirat",
    "fieldTabDisplayTypeHeaderText": "Megjelenítési formátum",
    "fieldTabOrderColumnText": "Sorrend",
    "fieldTabVisibleColumnText": "Engedélyezve",
    "displayFieldText": "Megjelenítési mező",
    "selectMenuOption": "Menü kiválasztása",
    "selectRadioOption": "Választógomb",
    "selectTextOption": "Szöveg",
    "selectDateOption": "Dátumválasztó",
    "selectRangeOption": "Érintéses görgető",
    "selectCheckboxOption": "Jelölőnégyzet",
    "selectMailOption": "E-mail",
    "selectUrlOption": "URL",
    "selectTextAreaOption": "Szövegterület",
    "previewApplicationText": "Alkalmazás előnézete",
    "saveApplicationText": "Alkalmazás mentése",
    "saveText": "Mentés",
    "toggleNavigationText": "Navigáció átváltása",
    "formPlaceholderText": "Saját űrlap",
    "shareBuilderInProgressTitleMessage": "GeoForm közzététele",
    "shareBuilderProgressBarMessage": "Várjon&hellip;",
    "shareBuilderTitleMessage": "Sikerült az elem mentése.",
    "shareBuilderTextMessage": "Elkezdheti az adatok gyűjtését másokkal megosztva",
    "shareModalFormText": "Űrlap hivatkozása",
    "shareBuilderSuccess": "Megtörtént a GeoForm frissítése és közzététele.",
    "geoformTitleText": "GeoForm",
    "layerTabText": "Ebből a rétegből (vagy ezekből a rétegekből) fog készülni a GeoForm. A rétegnek egy vektoros adatszolgáltatásnak kell lennie, amelynél engedélyezve van a szerkesztés az Ön közönségének megfelelő megosztási engedélyekkel. Az összes réteg kiválasztása esetén a felhasználó megadhatja az űrlapon, hogy melyik űrlapréteget választja a beküldéshez.",
    "detailsTabText": "Az alábbi Űrlap adatai mezőkben adhat meg címet, egyéni logót, valamint rövid leírást a GeoForm közönsége számára. A leírásban megadhatja más erőforrások hivatkozásait, a kapcsolattartói adatokat, ezenkívül akár a webtérképkészítő alkalmazást is, amely a GeoForm által összegyűjtött összes adatot tartalmazza.",
    "fieldsTabText": "Itt kiválaszthatja azokat a mezőket, amelyek láthatók lesznek a GeoForm közönsége számára, szerkesztheti a megjelenített feliratokat, és rövid leírást adhat meg, amellyel segítséget nyújt az adatbevitelhez.",
    "styleTabText": "A GeoForm stílust az alábbi témák közül választva alakíthatja ki.",
    "viewerTabText": "Adja meg a GeoForm által összegyűjtött beküldések megtekintési beállításait.",
    "publishTabText": "Ha befejezte a GeoForm testreszabását, mentse az alkalmazást, és kezdje el a megosztást a közönséggel. Bármikor visszatérhet a szerkesztőhöz, és folytathatja a testreszabást a visszajelzések alapján.",
    "headerSizeLabel": "Fejléc mérete",
    "smallHeader": "Kis fejléc használata",
    "bigHeader": "Nagy fejléc használata",
    "pushpinText": "Gombostű",
    "doneButtonText": "Mentés és kilépés",
    "fieldTabPlaceHolderHeaderText": "Útmutatás (választható)",
    "enableAttachmentLabelText": "${openStrong}Csatolmányok engedélyezése${closeStrong}",
    "enableAttachmentLabelHint": "Itt engedélyezheti vagy letilthatja a csatolmányokat",
    "attachmentIsRequiredLabelText": "${openStrong}Csatolmány szükséges${closeStrong}",
    "attachmentIsRequiredLabelHint": "Ha szükséges, előírhatja a felhasználók számára a csatolmányok kötelező megadását.",
    "attachmentLabelText": "Csatolmány gomb felirata",
    "attachmentLabelHint": "Ez a szöveg fog megjelenni a Csatolmány gomb mellett. Ezt a területet használhatja arra, hogy leírja, milyen elemeket adjon meg csatolmányként a közönsége (fényképet, videót, dokumentumot stb.), a kért fájlformátumot (.jpeg, .png, .docx, .pdf stb.), valamint az egyéb utasításokat.",
    "attachmentDescription": "Csatolmány leírása",
    "attachmentHint": "Ha szükséges, itt adhat meg további utasításokat a csatolmányokra vonatkozóan.",
    "jumbotronDescription": "Az űrlaphoz kicsi vagy nagy fejlécet használhat. A nagy fejlécben megadhatja, hogy mire való az alkalmazás, de több helyet foglal el a képernyőn.",
    "shareGeoformText": "Közösségi médiamegosztás gombjai",
    "shareDescription": "A közösségi médiagombokkal a közönség könnyen megoszthatja a GeoFormot, ha elkészítettek egy beküldendő anyagot.",
    "defaultMapExtent": "Alapértelmezett térképkiterjedés",
    "defaultMapExtentDescription": "A térkép visszaáll az alapértelmezett kiterjedésre a webtérképen a beküldés után. Ez bármikor kikapcsolható.",
    "pushpinOptionsDescription": "Válassza ki a térképen megjelenített gombostű színét. Olyan színt válasszon, amely eltér a térkép szimbólumainak színétől, hogy ezzel is segítsen a felhasználóknak elhelyezni a beküldést a térképen.",
    "selectLocationText": "Hely kiválasztása:",
    "myLocationText": "Saját helyzet",
    "searchText": "Keresés",
    "coordinatesText": "Szélességi és hosszúsági koordináták",
    "usng": "USNG-koordináták",
    "mgrs": "MGRS-koordináták",
    "utm": "UTM-koordináták",
    "selectLocationSDescription": "A felhasználók ezekkel a módszerekkel választhatnak helyet.",
    "dragTooltipText": "Húzza arra a helyre a mezőt, ahol meg szeretné jeleníteni.",
    "showHideLayerText": "Réteg megjelenítése",
    "showHideLayerHelpText": "A GeoForm beállítható a réteg megjelenítésére/elrejtésére. Ez a beállítás csak egyréteges konfiguráció esetén érhető el.",
    "enableOfflineSupport": "Kapcsolat nélküli támogatás engedélyezése",
    "enableOfflineSupportHelpText": "A beküldések tárolva lesznek, amikor nincs hálózati kapcsolat, és a kapcsolat helyreállása után lesznek leküldve.",
    "labelHelpMessage": "Felirat",
    "placeHolderHintMessage": "Útmutatás szövege",
    "placeHolderHelpMessage": "Súgószöveg",
    "selectTextOptionValue": "Szűrő kiválasztása",
    "disableLogo": "Logó letiltása",
    "disableLogoDescription": "A GeoForm beállítható az űrlapfejlécben található logó megjelenítésére/elrejtésére.",
    "locateOnLoadText": "Helyzet megadása betöltéskor",
    "locateOnLoadDescription": "A GeoForm beállítható az aktuális hely használatára az oldal betöltésekor.",
    "selectLayerFieldTabText": "Réteg kiválasztása",
    "allLayerSelectOptionText": "Összes réteg",
    "disableViewer": "Megjelenítő letiltása",
    "disableViewerDescription": "A GeoForm beállítható a megtekintő engedélyezésére/letiltására.",
    "displayFieldHintText": "A kiválasztott megjelenítendő mező címként lesz látható a megtekintőben."
  },
  "viewer": {
    "geocoderCancelText": "Mégse",
    "viewMapTabText": "Térkép",
    "sortHeaderText": "Rendezési szempont:",
    "geocoderPlaceholderText": "Irányítószám, város stb.",
    "noSearchResult": "Nincs találat",
    "legendTabTooltip": "Jelmagyarázat",
    "aboutUsTabTooltip": "A vállalatról",
    "mapTabTooltip": "Térkép",
    "btnDescendingText": "Csökk.",
    "btnAscendingText": "Növ.",
    "geometryUnavailableErrorMessage": "Nem sikerült megtalálni a vektoros elem geometriáját",
    "infoPopupOffErrorMessage": "Nincs megjeleníthető információ",
    "btnLoadMoreText": "Továbbiak betöltése",
    "unavailableTitleText": "Cím nélkül",
    "unavailableConfigMessage": "Nem sikerült a konfiguráció betöltése",
    "share": "Megosztás",
    "viewReportsTabText": "Jelentések",
    "viewLegendTabText": "Jelmagyarázat",
    "viewAboutusTabText": "További információ",
    "appLoadingFailedMessage": "Nem sikerült a megtekintő betöltése"
  }
});