define(
     ({
        map: {
            error: "Kan kaart niet maken"
        },
        onlineStatus: {
            offline: "U werkt momenteel offline. Uw in te dienen formulieren worden lokaal opgeslagen totdat er een verbinding met de server kan worden gemaakt.",
            reconnecting: "Opnieuw verbinding maken&hellip;",
            pending: "${total} bewerking(en) in behandeling wordt/worden verzonden wanneer opnieuw een netwerkverbinding is ingesteld."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Mijn Organisatie",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Mijn Content",
                    favoritesLabel: "Mijn Favorieten"
                },
                title: "Webmap selecteren",
                searchTitle: "Zoeken",
                ok: "OK",
                cancel: "Annuleren",
                placeholder: "Zoekterm invoeren"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Mijn Organisatie",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Mijn Content",
                    favoritesLabel: "Mijn Favorieten"
                },
                title: "Groep selecteren",
                searchTitle: "Zoeken",
                ok: "OK",
                cancel: "Annuleren",
                placeholder: "Zoekterm invoeren"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Noordwaarde",
            utm_easting: "Oostwaarde",
            utm_zone_number: "Zonenummer",
            geoFormGeneralTabText: "1. Informatie invoeren",
            locationInformationText: "2. Locatie selecteren",
            submitInformationText: "3. Formulier invullen",
            submitInstructions: "Deze informatie toevoegen aan de kaart.",
            myLocationText: "Huidige locatie",
            locationDescription: "Geef de locatie voor deze vermelding op door op de kaart te klikken/tikken of door een van de volgende opties te gebruiken.",
            addressText: "Zoeken",
            geographic: "Breedte-/lengtegraad",
            locationTabText: "Locatie",
            locationPopupTitle: "Locatie",
            submitButtonText: "Vermelding verzenden",
            submitButtonTextLoading: "Verzenden&hellip;",
            formValidationMessageAlertText: "De volgende velden zijn vereist:",
            selectLocation: "Selecteer een ${openLink}locatie${closeLink} voor uw verzending.",
            emptylatitudeAlertMessage: "Voer een ${openLink}breedtegraad${closeLink}-coördinaat in.",
            emptylongitudeAlertMessage: "Voer een ${openLink}lengtegraad${closeLink}-coördinaat in.",
            shareUserTitleMessage: "Bedankt voor uw bijdrage!",
            entrySubmitted: "Uw vermelding is verzonden naar de kaart.",
            shareThisForm: "Dit formulier delen",
            shareUserTextMessage: "Vertel anderen om bijdragen te leveren met behulp van de volgende opties.",
            addAttachmentFailedMessage: "Kan bijlage niet toevoegen aan laag",
            addFeatureFailedMessage: "Kan kenmerk niet toevoegen aan laag",
            noLayerConfiguredMessage: "Oeps! Hier is niets te zien. Om formulierinzendingen te gaan verzamelen, configureert u dit geografisch formulier en selecteert u een bewerkbare featureservicelaag die u wilt gebruiken.",
            placeholderLatitude: "Breedte (Y)",
            placeholderLongitude: "Lengte (X)",
            latitude: "Breedtegraad",
            longitude: "Lengtegraad",
            findMyLocation: "Mij zoeken",
            finding: "Zoeken&hellip;",
            backToTop: "Terug naar boven",
            addressSearchText: "Uw inzending wordt hier weergegeven. U kunt de speld slepen om de locatie te wijzigen.",
            shareModalFormText: "Link formulier",
            close: "Sluiten",
            locationNotFound: "Locatie is niet gevonden.",
            setLocation: "Locatie instellen",
            find: "Adres of plaats zoeken",
            attachment: "Bijlage",
            toggleDropdown: "Vervolgkeuzelijst in- en uitschakelen",
            invalidLatLong: "Voer geldige ${latLink}breedtegraad${closeLink}- en ${lngLink}lengtegraad${closeLink}-coördinaten in.",
            invalidUTM: "Voer geldige ${openLink}UTM${closeLink}-coördinaten in.",
            invalidUSNG: "Voer geldige ${openLink}USNG${closeLink}-coördinaten in.",
            invalidMGRS: "Voer geldige ${openLink}MGRS${closeLink}-coördinaten in.",
            geoformTitleText: "Geografisch formulier",
            domainDefaultText: "Selecteren&hellip;",
            applyEditsFailedMessage: "Uw invoer kan niet worden verzonden. Probeer het opnieuw.",
            requiredFields: "Er zijn enkele fouten opgetreden. Corrigeer deze hieronder.",
            requiredField: "(vereist)",
            error: "Fout",
            textRangeHintMessage: "${openStrong}Tip:${closeStrong} Minimumwaarde ${minValue} en Maximumwaarde ${maxValue}",
            dateRangeHintMessage: "${openStrong}Tip:${closeStrong} Minimumdatum ${minValue} en Maximumdatum ${maxValue}"
        },
        builder: {
            invalidUser: "U beschikt niet over de nodige machtigingen om dit item te bekijken",
            invalidWebmapSelectionAlert: "De geselecteerde webmap bevat geen geldige laag die gebruikt kan worden. Voeg een bewerkbare objectlaag toe aan uw webmap om verder te gaan.",
            invalidWebmapSelectionAlert2: "Voor meer informatie raadpleegt u ${openLink}Wat is een featureservice?${closeLink}",
            selectFieldsText: "Velden voor formulier selecteren",
            selectThemeText: "Thema voor formulier selecteren",
            webmapText: "Webmap",
            layerText: "Kaartlaag",
            detailsText: "Details",
            fieldsText: "Velden",
            styleText: "Stijl",
            optionText: "Opties",
            previewText: "Voorbeeld",
            publishText: "Publiceren",
            optionsApplicationText: "Opties",
            titleText: "Builder",
            descriptionText: "Een geografisch formulier is een configureerbare template voor op formulieren gebaseerde gegevensbewerking van een ${link1}Featureservice${closeLink}. Met deze applicatie kunnen gebruikers gegevens invoeren met behulp van een formulier in plaats van de pop-up van een kaart en kunnen ze profiteren van de voordelen van de ${link2}Webmap${closeLink} en bewerkbare Featureservices. Gebruik de volgende stappen om uw geografisch formulier aan te passen en te implementeren.",
            btnPreviousText: "Vorige",
            btnNextText: "Volgende",
            webmapTabTitleText: "Een webmap selecteren",
            viewWebmap: "Webmap bekijken",
            btnSelectWebmapText: "Webmap kiezen",
            btnSelectWebmapTextLoading: "Laden&hellip;",
            layerTabTitleText: "Bewerkbare kaartlaag selecteren",
            selectLayerLabelText: "Kaartlaag",
            selectLayerDefaultOptionText: "Kaartlaag selecteren",
            detailsTabTitleText: "Formulierdetails",
            detailTitleLabelText: "Titel",
            detailLogoLabelText: "Logoafbeelding",
            descriptionLabelText: "Help-tekst (optioneel)",
            fieldTabFieldHeaderText: "Veld",
            fieldTabLabelHeaderText: "Label",
            fieldTabDisplayTypeHeaderText: "Weergeven als",
            selectMenuOption: "Menu selecteren",
            selectRadioOption: "Keuzerondje",
            selectTextOption: "Tekst",
            selectCheckboxOption: "Selectievakje",
            selectMailOption: "E-mail",
            selectUrlOption: "URL",
            selectTextAreaOption: "Tekstgebied",
            previewApplicationText: "Voorbeeld van applicatie bekijken",
            saveApplicationText: "Applicatie opslaan",
            saveText: "Opslaan",
            toggleNavigationText: "Schakelen tussen navigatie",
            formPlaceholderText: "Mijn formulier",
            shareBuilderInProgressTitleMessage: "Geografisch formulier publiceren",
            shareBuilderProgressBarMessage: "Even geduld&hellip;",
            shareBuilderTitleMessage: "Item opgeslagen",
            shareBuilderTextMessage: "U kunt nu informatie verzamelen en met anderen delen.",
            shareModalFormText: "Link formulier",
            shareBuilderSuccess: "Uw geografische formulier is bijgewerkt en gepubliceerd!",
            geoformTitleText: "Geografisch formulier",
            layerTabText: "Dit is de laag waaruit het geografisch formulier wordt opgebouwd. De laag moet een featureservice zijn die is ingeschakeld voor bewerken met voor uw publiek geschikte deelmachtigingen.",
            detailsTabText: "Gebruik de vakken voor Formulierdetails hieronder om de titel en het logo aan te passen, en geef een korte omschrijving voor het publiek van uw geografisch formulier. In de beschrijving kunt u koppelingen naar andere bronnen en contactgegevens toevoegen en kunt u uw publiek zelfs doorsturen naar een webmapapplicatie met alle gegevens die werden verzameld met het geografisch formulier.",
            fieldsTabText: "Hier kunt u selecteren welke velden zichtbaar zijn voor het publiek van uw geografisch formulier, de labels bewerken die ze te zien krijgen en een korte beschrijving toevoegen om gegevensinvoer te vergemakkelijken.",
            styleTabText: "Bewerk u geografisch formulier naar eigen inzicht met behulp van onderstaande thema\'s.",
            publishTabText: "Als u uw geografisch formulier hebt aangepast, slaat u de applicatie op en begint u te delen met uw publiek. U kunt altijd terugkeren naar deze builder en doorgaan met aanpassen op basis van uw feedback.",
            smallHeader: "Kleine koptekst gebruiken",
            pushpinText: "Punaise",
            doneButtonText: "Applicatie-item weergeven",
            fieldTabPlaceHolderHeaderText: "Tip (optioneel)",
            attachmentLabelText: "Label van bijlage",
            attachmentLabelHint: "Vertel gebruikers welk type bestand ze moeten bijvoegen.",
            attachmentDescription: "Beschrijving van bijlage",
            attachmentHint: "Indien nodig kunt u hier aanvullende instructies voor bijlagen opgeven.",
            jumbotronDescription: "Met de Bootstrap Jumbotron kunt u gemakkelijk het doel van uw applicatie definiëren. Dit kan op elk moment worden uitgeschakeld.",
            shareGeoformText: "Geografisch formulier delen",
            shareDescription: "Dankzij het deelvenster voor delen kan uw publiek het geografisch formulier gemakkelijk delen met andere medewerkers zodra ze een verzending hebben gemaakt. Dit kan op elk moment worden uitgeschakeld.",
            defaultMapExtent: "Standaard kaartextent",
            defaultMapExtentDescription: "Na verzending wordt de kaart opnieuw ingesteld op de standaard kaartextent in uw webmap. Dit kan op elk moment worden uitgeschakeld.",
            pushpinOptionsDescription: "Kies uit een ruime keuze aan kleuren voor de punaise van de kaart. Deze moet verschillen van de symbolen op de kaart om gebruikers te helpen hun verzending op de kaart te plaatsen",
            selectLocationText: "Locatie selecteren op",
            myLocationText: "Mijn locatie",
            searchText: "Zoeken",
            coordinatesText: "Breedtegraad- en lengtegraadcoördinaten",
            usng: "USNG-coördinaten",
            mgrs: "MGRS-coördinaten",
            utm: "UTM-coördinaten",
            selectLocationSDescription: "Sta gebruikers toe om een locatie te selecteren met behulp van deze methoden."
        }
    })
);