define(
     ({
        map: {
            error: "Det gick inte att skapa kartan"
        },
        onlineStatus: {
            offline: "Du arbetar just nu offline. Inskickade formulär sparas lokalt tills det går att ansluta till servern.",
            reconnecting: "Återansluter&hellip;",
            pending: "${total} väntande redigering(ar) skickas in när nätverksanslutningen har återupprättats."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Min organisation",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Mitt innehåll",
                    favoritesLabel: "Mina favoriter"
                },
                title: "Välj webbkarta",
                searchTitle: "Sök",
                ok: "OK",
                cancel: "Avbryt",
                placeholder: "Ange sökterm"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Min organisation",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Mitt innehåll",
                    favoritesLabel: "Mina favoriter"
                },
                title: "Välj grupp",
                searchTitle: "Sök",
                ok: "OK",
                cancel: "Avbryt",
                placeholder: "Ange sökterm"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Nordlig",
            utm_easting: "Östlig",
            utm_zone_number: "Zonnummer",
            geoFormGeneralTabText: "1. Ange information",
            locationInformationText: "2. Välj plats",
            submitInformationText: "3. Fyll i formulär",
            submitInstructions: "Lägg till den här informationen i kartan.",
            myLocationText: "Aktuell plats",
            locationDescription: "Ange en plats för det här bidraget genom att klicka/peka på kartan eller använda något av följande alternativ.",
            addressText: "Sök",
            geographic: "Lat/lon",
            locationTabText: "Plats",
            locationPopupTitle: "Plats",
            submitButtonText: "Skicka in bidrag",
            submitButtonTextLoading: "Skickar in&hellip;",
            formValidationMessageAlertText: "Följande fält krävs:",
            selectLocation: "Välj en ${openLink}plats${closeLink} för ditt bidrag.",
            emptylatitudeAlertMessage: "Ange en ${openLink}latitud${closeLink}-koordinat.",
            emptylongitudeAlertMessage: "Ange en ${openLink}longitud${closeLink}-koordinat.",
            shareUserTitleMessage: "Tack för ditt bidrag!",
            entrySubmitted: "Ditt bidrag har lämnats in till kartan.",
            shareThisForm: "Dela det här formuläret",
            shareUserTextMessage: "Uppmana andra att bidra med följande alternativ.",
            addAttachmentFailedMessage: "Det gick inte att lägga till bilagan i lagret",
            addFeatureFailedMessage: "Det gick inte att lägga till geoobjektet i lagret",
            noLayerConfiguredMessage: "Oj! Här finns inget att se. Om du vill börja samla in formulärbidrag konfigurerar du GeoForm och väljer ett redigerbart geoobjekttjänstlager att använda.",
            placeholderLatitude: "Latitud (Y)",
            placeholderLongitude: "Longitud (X)",
            latitude: "Latitud",
            longitude: "Longitud",
            findMyLocation: "Hitta mig",
            finding: "Lokaliserar&hellip;",
            backToTop: "Tillbaka till start",
            addressSearchText: "Ditt bidrag kommer att visas här. Du kan dra nålen för att korrigera platsen.",
            shareModalFormText: "Formulärlänk",
            close: "Stäng",
            locationNotFound: "Det gick inte att hitta platsen.",
            setLocation: "Ange plats",
            find: "Sök efter adress eller plats",
            attachment: "Bilaga",
            toggleDropdown: "Växla listmenyn",
            invalidLatLong: "Ange giltiga koordinater för ${latLink}latitud${closeLink} och ${lngLink}longitud${closeLink}.",
            invalidUTM: "Ange giltiga ${openLink}UTM${closeLink}-koordinater.",
            invalidUSNG: "Ange giltiga ${openLink}USNG${closeLink}-koordinater.",
            invalidMGRS: "Ange giltiga ${openLink}MGRS${closeLink}-koordinater.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Välj&hellip;",
            applyEditsFailedMessage: "Ditt bidrag kan tyvärr inte lämnas in. Försök igen.",
            requiredFields: "Det förekommer några fel. Rätta till dem nedan.",
            requiredField: "(obligatoriskt)",
            error: "Fel",
            textRangeHintMessage: "${openStrong}Tips:${closeStrong} minsta värde ${minValue} och största värde ${maxValue}",
            dateRangeHintMessage: "${openStrong}Tips:${closeStrong} minsta datum ${minValue} och största datum ${maxValue}"
        },
        builder: {
            invalidUser: "Du har tyvärr inte behörighet att visa det här objektet",
            invalidWebmapSelectionAlert: "Den valda webbkartan innehåller inte någon giltigt lager som kan användas. Lägg till ett redigerbart geoobjektlager i webbkartan för att fortsätta.",
            invalidWebmapSelectionAlert2: "Mer information finns i ${openLink}Vad är geoobjekttjänster?${closeLink}",
            selectFieldsText: "Välj formulärfält",
            selectThemeText: "Välj formulärtema",
            webmapText: "Webbkarta",
            layerText: "Lager",
            detailsText: "Information",
            fieldsText: "Fält",
            styleText: "Format",
            optionText: "Alternativ",
            previewText: "Förhandsgranska",
            publishText: "Publicera",
            optionsApplicationText: "Alternativ",
            titleText: "Byggverktyg",
            descriptionText: "GeoForm är en konfigurerbar mall för formulärbaserad dataredigering av en ${link1}geoobjekttjänst${closeLink}. Med den här applikationen kan användare ange data via ett formulär i stället för en kartas popupfönster, samtidigt som de utnyttjar funktionerna i ${link2}webbkartan${closeLink} och de redigerbara geoobjekttjänsterna. Använd följande steg för att anpassa och distribuera GeoForm.",
            btnPreviousText: "Föregående",
            btnNextText: "Nästa",
            webmapTabTitleText: "Välj en webbkarta",
            viewWebmap: "Visa webbkarta",
            btnSelectWebmapText: "Välj webbkarta",
            btnSelectWebmapTextLoading: "Laddar&hellip;",
            layerTabTitleText: "Välj redigerbart lager",
            selectLayerLabelText: "Lager",
            selectLayerDefaultOptionText: "Välj lager",
            detailsTabTitleText: "Formulärinformation",
            detailTitleLabelText: "Titel",
            detailLogoLabelText: "Logobild",
            descriptionLabelText: "Hjälptext (valfritt)",
            fieldTabFieldHeaderText: "Fält",
            fieldTabLabelHeaderText: "Etikett",
            fieldTabDisplayTypeHeaderText: "Visa som",
            selectMenuOption: "Valmeny",
            selectRadioOption: "Alternativknapp",
            selectTextOption: "Text",
            selectCheckboxOption: "Kryssruta",
            selectMailOption: "E-post",
            selectUrlOption: "URL",
            selectTextAreaOption: "Textområde",
            previewApplicationText: "Förhandsgranska applikation",
            saveApplicationText: "Spara applikation",
            saveText: "Spara",
            toggleNavigationText: "Växla navigering",
            formPlaceholderText: "Mitt formulär",
            shareBuilderInProgressTitleMessage: "Publicerar GeoForm",
            shareBuilderProgressBarMessage: "Vänta&hellip;",
            shareBuilderTitleMessage: "Objektet har sparats",
            shareBuilderTextMessage: "Du kan börja samla in information genom att dela med andra",
            shareModalFormText: "Formulärlänk",
            shareBuilderSuccess: "Ditt GeoForm har uppdaterats och publicerats!",
            geoformTitleText: "GeoForm",
            layerTabText: "Det är detta lager du bygger ditt GeoForm från. Lagret måste vara en geoobjekttjänst som är aktiverad för redigering med delningsbehörigheter lämpliga för din publik.",
            detailsTabText: "Använd rutorna för formulärinformation nedan för att anpassa titeln, lägga till en anpassad logo och ange en kort beskrivning för GeoForm-publiken. I beskrivningen kan du lägga till länkar till andra resurser, kontaktinformation och till och med visa publiken till ett webbkartprogram som innehåller alla data som har samlats in med GeoForm",
            fieldsTabText: "Här kan du välja vilka fält som ska visas för din GeoForm-publik, redigera vilka etiketter som ska visas och ange en kort beskrivning som underlättar datainmatningen.",
            styleTabText: "Formatera ditt GeoForm med de teman som finns nedan enligt dina önskemål.",
            publishTabText: "Om du är färdig med anpassningen av ditt GeoForm kan du spara programmet och börja dela det med din publik. Då kan alltid återgå till byggverktyget och fortsätta att anpassa det utifrån den återkoppling du får.",
            smallHeader: "Använd liten rubrik",
            pushpinText: "Knappnål",
            doneButtonText: "Visa applikationsobjekt",
            fieldTabPlaceHolderHeaderText: "Tips (valfritt)",
            attachmentLabelText: "Etikett för bilagan",
            attachmentLabelHint: "Informera användare om vilken filtyp som ska bifogas.",
            attachmentDescription: "Beskrivning av bilaga",
            attachmentHint: "Vid behov kan du ange ytterligare information om bilagor här.",
            jumbotronDescription: "Med Bootstrap Jumbotron är det enkelt att definiera syftet med din applikation. Du kan inaktivera den när som helst.",
            shareGeoformText: "Dela GeoForm",
            shareDescription: "Med delningspanelen är det enkelt för din publik att dela GeoForm med andra som har lämnat ett bidrag. Du kan inaktivera den när som helst.",
            defaultMapExtent: "Standardutbredning för karta",
            defaultMapExtentDescription: "Kartan återgår till standardutbredningen i webbkartan efter bidraget. Detta går att inaktivera när som helst.",
            pushpinOptionsDescription: "Välj mellan flera olika färger på kartans knappnål. Den bör skilja sig från kartans symbologi för att hjälpa användaren placera sitt bidrag på kartan",
            selectLocationText: "Välj plats enligt",
            myLocationText: "Min plats",
            searchText: "Sök",
            coordinatesText: "Latitud- och longitudkoordinater",
            usng: "USNG-koordinater",
            mgrs: "MGRS-koordinater",
            utm: "UTM-koordinater",
            selectLocationSDescription: "Låt användare välja en plats med de här metoderna."
        }
    })
);