define(
    [{
        "id": "bootstrap",
        "name": "Bootstrap (Default)",
        "url": "js/vendor/bootstrap-3.2.0-dist/css/bootstrap-theme.min.css",
        "thumbnail": "images/themes/default.png",
        "refUrl": "http://bootswatch.com/default/"
    }, {
        "id": "amelia",
        "name": "Amelia",
        "url": "js/vendor/bootswatch-3.2.0-4/amelia/bootstrap.min.css",
        "thumbnail": "js/vendor/bootswatch-3.2.0-4/amelia/thumbnail.png",
        "refUrl": "http://bootswatch.com/amelia/"
    }, {
        "id": "cerulean",
        "name": "Cerulean",
        "url": "js/vendor/bootswatch-3.2.0-4/cerulean/bootstrap.min.css",
        "thumbnail": "js/vendor/bootswatch-3.2.0-4/cerulean/thumbnail.png",
        "refUrl": "http://bootswatch.com/cerulean/"
    }, {
        "id": "cosmo",
        "name": "Cosmo",
        "url": "js/vendor/bootswatch-3.2.0-4/cosmo/bootstrap.min.css",
        "thumbnail": "js/vendor/bootswatch-3.2.0-4/cosmo/thumbnail.png",
        "refUrl": "http://bootswatch.com/cosmo/"
    }, {
        "id": "cyborg",
        "name": "Cyborg",
        "url": "js/vendor/bootswatch-3.2.0-4/cyborg/bootstrap.min.css",
        "thumbnail": "js/vendor/bootswatch-3.2.0-4/cyborg/thumbnail.png",
        "refUrl": "http://bootswatch.com/cyborg/"
    }, {
        "id": "darkly",
        "name": "Darkly",
        "url": "js/vendor/bootswatch-3.2.0-4/darkly/bootstrap.min.css",
        "thumbnail": "js/vendor/bootswatch-3.2.0-4/darkly/thumbnail.png",
        "refUrl": "http://bootswatch.com/darkly/"
    }, {
        "id": "flatly",
        "name": "Flatly",
        "url": "js/vendor/bootswatch-3.2.0-4/flatly/bootstrap.min.css",
        "thumbnail": "js/vendor/bootswatch-3.2.0-4/flatly/thumbnail.png",
        "refUrl": "http://bootswatch.com/flatly/"
    }, {
        "id": "journal",
        "name": "Journal",
        "url": "js/vendor/bootswatch-3.2.0-4/journal/bootstrap.min.css",
        "thumbnail": "js/vendor/bootswatch-3.2.0-4/journal/thumbnail.png",
        "refUrl": "http://bootswatch.com/journal/"
    }, {
        "id": "lumen",
        "name": "Lumen",
        "url": "js/vendor/bootswatch-3.2.0-4/lumen/bootstrap.min.css",
        "thumbnail": "js/vendor/bootswatch-3.2.0-4/lumen/thumbnail.png",
        "refUrl": "http://bootswatch.com/lumen/"
    }, {
        "id": "paper",
        "name": "Paper",
        "url": "js/vendor/bootswatch-3.2.0-4/paper/bootstrap.min.css",
        "thumbnail": "js/vendor/bootswatch-3.2.0-4/paper/thumbnail.png",
        "refUrl": "http://bootswatch.com/paper/"
    }, {
        "id": "readable",
        "name": "Readable",
        "url": "js/vendor/bootswatch-3.2.0-4/readable/bootstrap.min.css",
        "thumbnail": "js/vendor/bootswatch-3.2.0-4/readable/thumbnail.png",
        "refUrl": "http://bootswatch.com/readable/"
    }, {
        "id": "sandstone",
        "name": "Sandstone",
        "url": "js/vendor/bootswatch-3.2.0-4/sandstone/bootstrap.min.css",
        "thumbnail": "js/vendor/bootswatch-3.2.0-4/sandstone/thumbnail.png",
        "refUrl": "http://bootswatch.com/sandstone/"
    }, {
        "id": "simplex",
        "name": "Simplex",
        "url": "js/vendor/bootswatch-3.2.0-4/simplex/bootstrap.min.css",
        "thumbnail": "js/vendor/bootswatch-3.2.0-4/simplex/thumbnail.png",
        "refUrl": "http://bootswatch.com/simplex/"
    }, {
        "id": "slate",
        "name": "Slate",
        "url": "js/vendor/bootswatch-3.2.0-4/slate/bootstrap.min.css",
        "thumbnail": "js/vendor/bootswatch-3.2.0-4/slate/thumbnail.png",
        "refUrl": "http://bootswatch.com/slate/"
    }, {
        "id": "spacelab",
        "name": "Spacelab",
        "url": "js/vendor/bootswatch-3.2.0-4/spacelab/bootstrap.min.css",
        "thumbnail": "js/vendor/bootswatch-3.2.0-4/spacelab/thumbnail.png",
        "refUrl": "http://bootswatch.com/spacelab/"
    }, {
        "id": "superhero",
        "name": "Superhero",
        "url": "js/vendor/bootswatch-3.2.0-4/superhero/bootstrap.min.css",
        "thumbnail": "js/vendor/bootswatch-3.2.0-4/superhero/thumbnail.png",
        "refUrl": "http://bootswatch.com/superhero/"
    }, {
        "id": "united",
        "name": "United",
        "url": "js/vendor/bootswatch-3.2.0-4/united/bootstrap.min.css",
        "thumbnail": "js/vendor/bootswatch-3.2.0-4/united/thumbnail.png",
        "refUrl": "http://bootswatch.com/united/"
    }, {
        "id": "yeti",
        "name": "Yeti",
        "url": "js/vendor/bootswatch-3.2.0-4/yeti/bootstrap.min.css",
        "thumbnail": "js/vendor/bootswatch-3.2.0-4/yeti/thumbnail.png",
        "refUrl": "http://bootswatch.com/yeti/"
    }]
);