define({
  "map": {
    "error": "No es pot crear el mapa",
    "licenseError": {
      "message": "El vostre compte no té llicència per utilitzar aplicacions configurables que no siguin públiques. Demaneu a l'administrador de l'organització que us assigni un tipus d'usuari que inclogui les aplicacions bàsiques o una llicència d'aplicacions bàsiques de complement.",
      "title": "Sense llicència"
    }
  },
  "onlineStatus": {
    "offline": "En aquest moment, esteu treballant fora de línia. Els enviaments dels formularis es desaran localment fins que es pugui establir la connexió amb el servidor.",
    "reconnecting": "S'està tornant a connectar&hellip;",
    "pending": "${total} canvis pendents s'enviaran quan es torni a establir una connexió de xarxa."
  },
  "configure": {
    "mapdlg": {
      "items": {
        "organizationLabel": "La meva organització",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "El meu contingut",
        "favoritesLabel": "Els meus favorits"
      },
      "title": "Seleccioneu un mapa web",
      "searchTitle": "Cerca",
      "ok": "D'acord",
      "cancel": "Cancel·la",
      "placeholder": "Introduïu un terme de cerca"
    },
    "groupdlg": {
      "items": {
        "organizationLabel": "La meva organització",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "El meu contingut",
        "favoritesLabel": "Els meus favorits"
      },
      "title": "Seleccioneu un grup",
      "searchTitle": "Cerca",
      "ok": "D'acord",
      "cancel": "Cancel·la",
      "placeholder": "Introduïu un terme de cerca"
    },
    "sharedlg": {
      "items": {},
      "mailtoLinkDescription": "A continuació teniu un enllaç al GeoForm"
    }
  },
  "user": {
    "all": "Tot",
    "mgrs": "MGRS",
    "usng": "USNG",
    "utm": "UTM",
    "utm_northing": "Valor nord",
    "utm_easting": "Valor est",
    "utm_zone_number": "Nombre de zona",
    "selectLayerTabText": "${formSection} Seleccioneu el formulari",
    "geoFormGeneralTabText": "${formSection} Introduïu la informació",
    "locationInformationText": "${formSection} Seleccioneu la ubicació",
    "submitInformationText": "${formSection} Empleneu el formulari",
    "submitInstructions": "Afegiu aquesta informació al mapa.",
    "myLocationText": "Ubicació actual",
    "locationDescriptionForMoreThanOneOption": "Feu clic, toqueu el mapa o feu servir una de les opcions següents per especificar la ubicació d'aquesta entrada.",
    "locationDescriptionForOneOption": "Feu clic, toqueu el mapa o feu servir l'opció següent per especificar la ubicació d'aquesta entrada.",
    "locationDescriptionForNoOption": "Feu clic o toqueu el mapa per especificar la ubicació d'aquesta entrada.",
    "addressText": "Cerca",
    "geographic": "Latitud/longitud",
    "locationTabText": "Ubicació",
    "locationPopupTitle": "Ubicació",
    "submitButtonText": "Envia l'entrada",
    "submitButtonTextLoading": "S'està enviant&hellip;",
    "formValidationMessageAlertText": "Els camps següents són necessaris:",
    "selectLocation": "Seleccioneu una ubicació per a l'enviament.",
    "emptylatitudeAlertMessage": "Introduïu una coordenada de ${openLink}latitud${closeLink}.",
    "emptylongitudeAlertMessage": "Introduïu una coordenada de ${openLink}longitud${closeLink}.",
    "shareUserTitleMessage": "Gràcies per la vostra contribució.",
    "entrySubmitted": "La vostra entrada s'ha enviat al mapa.",
    "shareThisForm": "Comparteix aquest formulari",
    "shareUserTextMessage": "Animeu a altres persones perquè hi contribueixin amb les opcions següents.",
    "addAttachmentFailedMessage": "No es pot afegir el fitxer adjunt a la capa",
    "addFeatureFailedMessage": "No es pot afegir l'entitat a la capa",
    "noLayerConfiguredMessage": "S'ha produït un error en carregar o cercar una capa d'entitats editable. Per mostrar el formulari i començar a recopilar enviaments, afegiu una capa d'entitats editable al mapa web.",
    "placeholderLatitude": "Latitud (Y)",
    "placeholderLongitude": "Longitud (X)",
    "latitude": "Latitud",
    "longitude": "Longitud",
    "findMyLocation": "Localitza'm",
    "finding": "S'està localitzant&hellip;",
    "backToTop": "Torna a dalt",
    "addressSearchText": "L'enviament apareixerà aquí. Podeu arrossegar la xinxeta per corregir la ubicació.",
    "shareModalFormText": "Enllaç del formulari",
    "close": "Tanca",
    "locationNotFound": "No s'ha trobat la ubicació.",
    "setLocation": "Defineix la ubicació",
    "find": "Cerca una adreça o un lloc",
    "attachment": "Fitxer adjunt",
    "toggleDropdown": "Activa/desactiva el menú desplegable",
    "invalidString": "Introduïu un valor vàlid.",
    "invalidSmallNumber": "Introduïu un valor ${openStrong}enter${closeStrong} vàlid entre –32.768 i 32.767.",
    "invalidNumber": "Introduïu un valor ${openStrong}enter${closeStrong} vàlid entre –2.147.483.648 i 2.147.483.647.",
    "invalidFloat": "Introduïu un valor de ${openStrong}coma flotant${closeStrong} vàlid.",
    "invalidDouble": "Introduïu un valor ${openStrong}doble${closeStrong} vàlid.",
    "invalidLatLong": "Introduïu unes coordenades de latitud i longitud vàlides.",
    "invalidUTM": "Introduïu unes coordenades UTM vàlides.",
    "invalidUSNG": "Introduïu unes coordenades USNG vàlides.",
    "invalidMGRS": "Introduïu unes coordenades MGRS vàlides.",
    "geoformTitleText": "GeoForm",
    "domainDefaultText": "Selecciona&hellip;",
    "applyEditsFailedMessage": "S'ha produït un error en l'enviament.",
    "applyEditsFailedRobot": "L'enviament s'ha rebutjat perquè s'ha produït un error en la detecció de robots.",
    "applyEditsAuthError": "L'entrada no es pot enviar a causa del tipus de nivell d'usuari. Poseu-vos en contacte amb l'administrador de l'organització per obtenir més ajuda.",
    "requiredFields": "El camp següent és obligatori. Proporcioneu una entrada vàlida.",
    "requiredField": "(obligatori)",
    "error": "Error",
    "textRangeHintMessage": "${openStrong}Suggeriment:${closeStrong} valor mínim ${minValue} i valor màxim ${maxValue}",
    "dateRangeHintMessage": "${openStrong}Suggeriment:${closeStrong} data mínima ${minValue} i data màxima ${maxValue}",
    "remainingCharactersHintMessage": "${value} caràcters restants",
    "mapFullScreen": "Pantalla completa",
    "mapRestore": "Restaura",
    "filterSelectEmptyText": "Selecciona",
    "invalidLayerMessage": "No s'ha trobat cap capa vàlida per crear el GeoForm. Si el GeoForm s'ha configurat amb una capa, és possible que aquesta ja no estigui disponible o que s'hagi produït un error en l'autorització.",
    "selectedLayerText": "Tot",
    "fileUploadStatus": "Estat de la pujada del fitxer",
    "uploadingBadge": "&nbsp;S'està pujant&hellip;",
    "successBadge": "&nbsp;S'ha pujat",
    "retryBadge": "Torna-ho a provar",
    "errorBadge": "Error de pujada&nbsp;&nbsp;&nbsp;",
    "fileTooLargeError": "El fitxer és massa gran per adjuntar-lo",
    "exceededFileCountError": "S'ha superat el nombre màxim de fitxers adjunts permesos",
    "selectFileTitle": "Selecciona un fitxer",
    "btnSelectFileText": "Selecciona el fitxer",
    "btnViewSubmissions": "Visualitza els enviaments"
  },
  "builder": {
    "gettingStarted": "Introducció",
    "dateSettings": "Configuració de la data",
    "hiddenDateField": "Amaga aquest camp de data",
    "preventPastDates": "Evita dates passades",
    "preventFutureDates": "Evita dates futures",
    "useCurrentDate": "Defineix aquest camp amb la data i hora actuals",
    "configure": "Configura",
    "configureField": "Configura el camp \"${fieldName}\"",
    "invalidUser": "No teniu permís per veure aquest element",
    "invalidWebmapSelectionAlert": "El mapa web seleccionat no conté cap capa vàlida per fer servir. Afegiu una capa d'entitats editable al mapa web per continuar.",
    "invalidWebmapSelectionAlert2": "Per obtenir més informació, consulteu ${openLink}Què és un servei d'entitats?${closeLink}",
    "selectFieldsText": "Seleccioneu els camps del formulari",
    "selectThemeText": "Seleccioneu el tema del formulari",
    "setViewerText": "Configura el visor",
    "introText": "Inicia",
    "webmapText": "Mapa web",
    "layerText": "Capa",
    "detailsText": "Detalls",
    "fieldsText": "Camps",
    "styleText": "Estil",
    "viewerText": "Visor",
    "optionText": "Opcions",
    "previewText": "Visualització prèvia",
    "publishText": "Publica",
    "optionsApplicationText": "Opcions",
    "submitButtonText": "Text del botó Envia (opcional)",
    "submitButtonDesc": "Opcionalment, afegiu una etiqueta al botó per enviar una entrada nova. Aquest text no es traduirà.",
    "viewSubmissionsText": "Text de Visualitza els enviaments (opcional)",
    "viewSubmissionsDesc": "Opcionalment, afegiu una etiqueta al botó per visualitzar les entrades existents. Aquest text no es traduirà.",
    "titleText": "Builder",
    "descriptionText": "El GeoForm és una plantilla configurable per a l'edició de dades basades en formularis d'un ${link1}servei d'entitats${closeLink}. Aquesta aplicació permet que els usuaris introdueixin dades a través d'un formulari en lloc de la finestra emergent d'un mapa i que aprofitin al mateix temps l'eficàcia del ${link2}mapa web${closeLink} i els serveis d'entitats editables. Realitzeu els passos següents per personalitzar i implementar el vostre GeoForm.",
    "btnPreviousText": "Anterior",
    "btnNextText": "Següent",
    "webmapTabTitleText": "Selecciona un mapa web",
    "viewWebmap": "Visualitza el mapa web",
    "webmapDetailsText": "El mapa web seleccionat és ${webMapTitleLink}${webMapTitle}${closeLink}. Per seleccionar-ne un de diferent, feu clic al botó \"Selecciona un mapa web\".",
    "btnSelectWebmapText": "Selecciona un mapa web",
    "btnSelectWebmapTextLoading": "S'està carregant&hellip;",
    "layerTabTitleText": "Selecciona les capes editables",
    "selectLayerLabelText": "Capa",
    "selectLayerDefaultOptionText": "Selecciona la capa",
    "enableBasemapToggle": "Mostra l'activació i desactivació del mapa base",
    "enableBasemapToggleDescription": "Podeu configurar el GeoForm perquè mostri o amagui l'opció Activació i desactivació del mapa base",
    "defaultBasemap": "Activació i desactivació del mapa base",
    "secondaryBasemap": "Mapa base per defecte",
    "detailsTabTitleText": "Detalls del formulari",
    "detailTitleLabelText": "Títol",
    "detailLogoLabelText": "Imatge del logotip",
    "descriptionLabelText": "Detalls i instruccions del formulari",
    "fieldDescriptionLabelText": "Text d'ajuda (opcional)",
    "fieldDescriptionHelpText": "Proporcioneu una descripció breu o instruccions per a aquest camp.",
    "fieldHintHelpText": "Text del marcador de posició per al camp.",
    "fieldTabFieldHeaderText": "Camp",
    "fieldTabLabelHeaderText": "Etiqueta",
    "fieldTabDisplayTypeHeaderText": "Mostra com a",
    "fieldTabOrderColumnText": "Ordre",
    "fieldTabVisibleColumnText": "Habilitat",
    "displayFieldText": "Camp que es mostra",
    "selectMenuOption": "Menú de selecció",
    "selectRadioOption": "Botó d'opció",
    "selectTextOption": "Text",
    "selectDateOption": "Selector de data",
    "selectRangeOption": "Control de gir tàctil",
    "selectCheckboxOption": "Casella de selecció",
    "selectMailOption": "Correu electrònic",
    "selectUrlOption": "URL",
    "selectTextAreaOption": "Àrea de text",
    "previewApplicationText": "Previsualitza l'aplicació",
    "saveApplicationText": "Desa l'aplicació",
    "saveText": "Desa",
    "toggleNavigationText": "Activa/desactiva la navegació",
    "formPlaceholderText": "El meu formulari",
    "shareBuilderInProgressTitleMessage": "S'està publicant el GeoForm",
    "shareBuilderProgressBarMessage": "Espereu&hellip;",
    "shareBuilderTitleMessage": "L'element s'ha desat correctament",
    "shareBuilderTextMessage": "Compartiu-ho amb altres persones per començar a recopilar informació",
    "shareModalFormText": "Enllaç del formulari",
    "shareBuilderSuccess": "El GeoForm s'ha actualitzat i publicat.",
    "geoformTitleText": "GeoForm",
    "layerTabText": "Aquestes són les capes a partir de les quals es crearà el GeoForm. La capa ha de ser un servei d'entitats habilitat per a l'edició i amb els permisos d'ús compartit adequats per al vostre públic. Si totes les capes estan seleccionades, el formulari permetrà que l'usuari triï a quina capa es farà l'enviament.",
    "detailsTabText": "Feu servir els quadres de detalls del formulari següents per personalitzar el títol, afegir un logotip personalitzat i proporcionar una descripció breu per als destinataris del GeoForm. A la descripció podeu afegir enllaços a altres recursos, informació de contacte i fins i tot dirigir el públic a una aplicació de cartografia web que contingui totes les dades recopilades amb el GeoForm.",
    "fieldsTabText": "Aquí podeu seleccionar quins camps seran visibles per als destinataris del GeoForm, editar les etiquetes que veuran i afegir una descripció breu per facilitar la introducció de dades.",
    "styleTabText": "Apliqueu un estil al GeoForm amb els temes següents en funció de les vostres preferències.",
    "viewerTabText": "Definiu les opcions per visualitzar els enviaments recopilats mitjançant el GeoForm.",
    "publishTabText": "Si heu acabat de personalitzar el GeoForm, deseu l'aplicació i compartiu-la amb el públic. Podeu tornar a aquest builder en qualsevol moment i continuar personalitzant-lo en funció dels comentaris.",
    "headerSizeLabel": "Mida de la capçalera",
    "smallHeader": "Utilitza una capçalera petita",
    "bigHeader": "Utilitza una capçalera gran",
    "pushpinText": "Xinxeta",
    "doneButtonText": "Desa i surt",
    "fieldTabPlaceHolderHeaderText": "Suggeriment (opcional)",
    "enableAttachmentLabelText": "${openStrong}Habilita els fitxers adjunts${closeStrong}",
    "enableAttachmentLabelHint": "Aquí podeu habilitar o deshabilitar els fitxers adjunts.",
    "attachmentIsRequiredLabelText": "${openStrong}Fitxer adjunt obligatori${closeStrong}",
    "attachmentIsRequiredLabelHint": "Si és necessari, es pot demanar als usuaris que proporcionin un fitxer adjunt.",
    "attachmentLabelText": "Etiqueta del botó Fitxer adjunt",
    "attachmentLabelHint": "Aquest text apareixerà al costat del botó Fitxer adjunt. Podeu fer servir aquest espai per descriure què voleu que adjunti el públic (una foto, un vídeo, un document, etc.), el format del fitxer que demaneu (.jpeg, .png, .docx, .pdf, etc.) i qualsevol instrucció addicional.",
    "attachmentDescription": "Descripció del fitxer adjunt",
    "attachmentHint": "Si és necessari, aquí podeu proporcionar instruccions addicionals per als fitxers adjunts.",
    "jumbotronDescription": "Feu servir una capçalera gran o petita per al formulari. Una capçalera gran us pot ajudar a definir l'objectiu de l'aplicació però ocupa més espai de la pantalla.",
    "shareGeoformText": "Botons per a l'ús compartit a les xarxes socials",
    "shareDescription": "Els botons de les xarxes socials permeten que el públic comparteixi fàcilment el vostre GeoForm després d'haver fet un enviament",
    "defaultMapExtent": "Extensió de mapa per defecte",
    "defaultMapExtentDescription": "El mapa es restablirà a l'extensió per defecte del vostre mapa web després de l'enviament. Aquesta opció es pot deshabilitar en qualsevol moment.",
    "pushpinOptionsDescription": "Trieu entre diferents colors per a la xinxeta del mapa. Hauria de ser diferent de la simbologia del mapa per facilitar que l'usuari introdueixi l'enviament al mapa.",
    "selectLocationText": "Selecciona la ubicació per",
    "myLocationText": "La meva ubicació",
    "searchText": "Cerca",
    "coordinatesText": "Coordenades de longitud i latitud",
    "usng": "Coordenades USNG",
    "mgrs": "Coordenades MGRS",
    "utm": "Coordenades UTM",
    "selectLocationSDescription": "Permet que els usuaris seleccionin una ubicació mitjançant aquests mètodes.",
    "dragTooltipText": "Arrossegueu el camp on voleu que aparegui",
    "showHideLayerText": "Mostra la capa",
    "showHideLayerHelpText": "Podeu configurar el GeoForm perquè mostri o amagui la capa. Aquesta opció només s'aplica a la configuració d'una sola capa.",
    "enableOfflineSupport": "Habilita el mode fora de línia",
    "enableOfflineSupportHelpText": "Permet emmagatzemar els enviaments quan no hi ha connexió de xarxa i enviar-los en restablir-se la connexió.",
    "labelHelpMessage": "Etiqueta",
    "placeHolderHintMessage": "Text de suggeriment",
    "placeHolderHelpMessage": "Text d'ajuda",
    "selectTextOptionValue": "Selecció de filtre",
    "disableLogo": "Deshabilita el logotip",
    "disableLogoDescription": "Podeu configurar el GeoForm perquè mostri o amagui el logotip a la capçalera del formulari",
    "locateOnLoadText": "Localitza en carregar",
    "locateOnLoadDescription": "Podeu configurar el GeoForm perquè faci servir la ubicació actual quan es carregui la pàgina",
    "selectLayerFieldTabText": "Selecciona la capa",
    "allLayerSelectOptionText": "Totes les capes",
    "disableViewer": "Deshabilita el visor",
    "disableViewerDescription": "Podeu configurar el GeoForm perquè habiliti o deshabiliti el visor",
    "displayFieldHintText": "El camp de visualització seleccionat es mostrarà al visor com a títol"
  },
  "viewer": {
    "geocoderCancelText": "Cancel·la",
    "viewMapTabText": "Mapa",
    "sortHeaderText": "Ordena per:",
    "geocoderPlaceholderText": "Codi postal, ciutat, etc.",
    "noSearchResult": "No s'ha trobat cap resultat",
    "legendTabTooltip": "Llegenda",
    "aboutUsTabTooltip": "Qui som",
    "mapTabTooltip": "Mapa",
    "btnDescendingText": "Descendent",
    "btnAscendingText": "Ascendent",
    "geometryUnavailableErrorMessage": "Error en cercar la geometria de l'entitat",
    "infoPopupOffErrorMessage": "No hi ha informació per mostrar",
    "btnLoadMoreText": "Carrega'n més",
    "unavailableTitleText": "Sense títol",
    "unavailableConfigMessage": "No es pot carregar la configuració",
    "share": "Comparteix",
    "viewReportsTabText": "Informes",
    "viewLegendTabText": "Llegenda",
    "viewAboutusTabText": "Quant a",
    "appLoadingFailedMessage": "S'ha produït un error en carregar el visor"
  }
});