define({
    root: ({
        builder: {
            invalidUser: "Sorry, you dont have permission to view this item",
            invalidWebmapSelectionAlert: "The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue.</br>For More Information please refer to <a target='_tab' href='http://resources.arcgis.com/en/help/main/10.2/index.html#//0154000002w8000000'>What is Feature Service?</a>",
            selectFieldsText: "Select Form Fields",
            selectThemeText: "Select Form Theme",
            webmapText: "Webmap",
            layerText: "Layer",
            detailsText: "Details",
            fieldsText: "Fields",
            styleText: "Style",
            optionText: "Options",
            previewText: "Preview",
            publishText: "Publish",
            optionsApplicationText: "Options",
            optionsDescriptionText: "The <a target='_tab' href='http://getbootstrap.com/components/#jumbotron'>Bootstrap Jumbotron</a> is too large for some applications. This can be disabled by checking this box.",
            titleText: "GeoForm Builder",
            descriptionText: "GeoForm is a configurable template for form-based data editing of a <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>Feature Service</a>. This application allows users to enter data through a form instead of a map’s pop-up while leveraging the power of the <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>Web Map</a> and editable Feature Services. Use the following steps to customize and deploy your GeoForm.",
            btnPreviousText: "Previous",
            btnNextText: "Next",
            webmapTabTitleText: "Choose a Webmap",
            viewWebmap: "View webmap",
            btnSelectWebmapText: "Select Webmap",
            btnSelectWebmapTextLoading: "Loading&hellip;",
            layerTabTitleText: "Select Editable Layer",
            selectLayerLabelText: "Layer",
            selectLayerDefaultOptionText: "Select Layer",
            detailsTabTitleText: "Form Details",
            detailTitleLabelText: "Title",
            detailLogoLabelText: "Logo Image",
            descriptionLabelText: "Help Text (optional)",
            fieldTabFieldHeaderText: "Field",
            fieldTabLabelHeaderText: "Label",
            fieldTabDisplayTypeHeaderText: "Display As",
            selectMenuOption: "Select Menu",
            selectRadioOption: "Radio Button",
            selectTextOption: "Text",
            selectCheckboxOption: "Checkbox",
            selectMailOption: "Email",
            selectUrlOption: "URL",
            selectTextAreaOption: "Textarea",
            previewApplicationText: "Preview Application",
            saveApplicationText: "Save Application",
            saveText: "Save",
            toggleNavigationText: "Toggle navigation",
            formPlaceholderText: "My Form",
            imageLogoPlaceholderText: "http://www.mysite.com/myimage.png",
            shareBuilderInProgressTitleMessage: "Publishing GeoForm",
            shareBuilderProgressBarMessage: "Please Wait&hellip;",
            shareBuilderTitleMessage: "Your GeoForm has been updated & published!",
            shareBuilderTextMessage: "You can start collecting information by sharing with others",
            shareModalFormText: "Form Link",
            geoformTitleText: "Geo Form",
            layerTabText: "This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience.",
            detailsTabText: "Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm.",
            fieldsTabText: "Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry.",
            styleTabText: "Style your GeoForm using the themes below based on your preference.",
            publishTabText: "Ifyou are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback.",
            smallHeader: "Use Small Header",
            pushpinText:"Push pin",
            doneButtonText:"View Application Item",
            fieldTabPlaceHolderHeaderText: "Hint (optional)",
            attachmentLabelText: "Attchment Label",
            attachmentLabelHint:"Tell users what type of file to attach.",
            attachmentDescription: "Attachment Description",
            attachmentHint: "If necessary, you can provide additional attachment instructions here.",
            jumbotronDescription: "The Bootstrap Jumbotron makes it easy to define the purpose of your application. This can be disabled at any time.",
            shareGeoformText: "Share Geoform",
            shareDescription: "The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time.",
            defaultMapExtent: "Default Map Extent",
            defaultMapExtentDescription: "The map will reset to the default extent in your web map after submission - this can be disabled at any time.",
            pushpinOptionsDescription: "Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map",
            selectLocationText: "Select Location By",
            myLocationText: "My Location",
	        searchText: "Search",
	        coordinatesText: "Latitude & Longitude Coordinates",
	        usng: "USNG Coordinates",
            mgrs: "MGRS Coordinates",
	        utm: "UTM Coordinates",
	        selectLocationSDescription: "Allow users to select a location using these methods."
        }
    })
});