define({
    root: ({
        builder: {
            invalidWebmapSelectionAlert: "Selected webmap does not contain any feature server",
            selectThemeText: "Select Form Theme",
            fieldLabelPlaceHolder: "Label this field",
            fieldDescPlaceHolder: "Describe this field",
            webmapText: "Webmap",
            layerText: "Layer",
            detailsText: "Details",
            fieldsText: "Fields",
            styleText: "Style",
            previewText: "Preview",
            publishText: "Publish",
            titleText: "GeoForm Builder",
            descriptionText: "GeoForm is a configurable template for form-based data editing of a <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//0154000002w8000000'>Feature Service</a>. This application allows users to enter data through a form instead of a map’s pop-up while leveraging the power of the <a target='_blank' href='http://resources.arcgis.com/en/help/main/10.1/index.html#//00sp0000001z000000'>Web Map</a> and editable Feature Services. Use this builder to customize and deploy your GeoForm following the steps on the left.",
            btnPreviousText: "Previous",
            btnNextText:"Next",
            webmapTabTitleText: "Choose a Webmap",
            btnSelectWebmapText:"Select Webmap",
            layerTabTitleText: "Select Editable Layer",
            selectLayerLabelText:"Layer",
            selectLayerDefaultOptionText:"Select Layer",
            detailsTabTitleText:"Form Details",
            detailTitleLabelText: "Title",
            detailLogoLabelText: "Logo Image",
            detailDescriptionLabelText: "Description",
            fieldTabDisplayHeaderText: "Display",
            fieldTabFieldHeaderText: "Field",
            fieldTabLabelHeaderText: "Label",
            fieldTabTypeHeaderText: "Type",
            fieldTabDescriptionHeaderText: "Description",
            previewApplicationText: "Preview Application",
            saveApplicationText: "Save Application",
            saveText: "Save",

            //Local string for user mode
            defaultTitleText: "Default Title",
            defaultDescriptionText: "Default Description",
            geoFormGeneralTabText: "General",
            locationInformationText: "Location Info",
            myLocationText: "My Location",
            addressText: "Address",
            cooridnatesText: "Coordinates",
            locationTabText: "Location",
            enterCoordinatesPlaceholder: "Enter Coordinates",
            submitButtonText: "Submit",
            clearButtonText: "Clear",
            fieldvalidationMessageAlertText: "Please enter a valid number",
            formValidationMessageAlertText: "Please verify the form for errors and resubmit the form",
            latlongValidationMessageAlert: "Please select x and y coordinates",
            emptylatitudeAlertMessage:"Please enter Latitude",
            emptylongitudeAlertMessage:"Please enter Longitude"
        }
    }),
    "fr": 1
});