define({
    root: ({
        user: {
            geoFormGeneralTabText: "1. Enter Information",
            locationInformationText: "2. Select Location",
            submitInformationText: "3. Complete Form",
            submitInstructions: "Add this information to the map.",
            myLocationText: "GPS",
            locationDescription: "Select a location for your submission using one of the following options or by clicking/tapping the map.",
            addressText: "Search",
            cooridnatesText: "Coordinates",
            locationTabText: "Location",
            enterCoordinatesPlaceholder: "Enter Coordinates",
            submitButtonText: "Submit new entry",
            submitButtonTextLoading: "Submitting&hellip;",
            fieldvalidationMessageAlertText: "Please enter a valid number",
            formValidationMessageAlertText: "The following fields are required. Please enter the following fields before submission:",
            validationFormatTypeSubstring: "The expected format is ",
            selectLocation: "Please select a location for your submission.",
            emptylatitudeAlertMessage: "Please enter a latitude coordinate",
            emptylongitudeAlertMessage: "Please enter a longitude coordinate",
            shareUserTitleMessage: "Thank you for your contribution!",
            shareUserTextMessage: "Your entry has been submitted. Share with others using the following options",
            addAttachmentFailedMessage: "Unable to add attachment to layer",
            addFeatureFailedMessage: "Unable to add feature to layer",
            noLayerConfiguredMessage: "Whoops! Nothing to see here. In order to start collecting form submissions, configure this GeoForm and select an editable Feature Service layer to use.",
            placeholderLatitude: "Latitude (Y)",
            placeholderLongitude: "Longitude (X)",
            latitude: "Latitude",
            longitude: "Longitude",
            findMyLocation: "Find my location",
            finding: "Locating&hellip;",
            myLocationTitleText: 'My Location',
            addressSearchText: "Your submission will appear here. You can drag the pin to correct the location.",
            shareDialogFormText: "Form Link",
            close: "Close",
            dateFormat: "mm/dd/yyyy",
            integerFormat: "Enter a number",
            locationNotFound: "Location could not be found.",
            floatFormat: "Enter a decimal number",
            setLocation: "Set location",
            invalidLatLong: "Please enter valid latitude and longitude coordinates."
        }
    })
});