define(
     ({
        map: {
            error: "Não foi possível criar o mapa"
        },
        onlineStatus: {
            offline: "Você está trabalhando offline. Envios de formulários serão salvos localmente até que uma conexão com o servidor possa ser feita.",
            reconnecting: "Reconectando&hellip;",
            pending: "${total} edições pendentes serão enviadas quando uma conexão de rede for reestabelecida."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Minha Organização",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Meu Conteúdo",
                    favoritesLabel: "Meus Favoritos"
                },
                title: "Selecionar Mapa da Web",
                searchTitle: "Pesquisar",
                ok: "Ok",
                cancel: "Cancelar",
                placeholder: "Inserir termo de pesquisa"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Minha Organização",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Meu Conteúdo",
                    favoritesLabel: "Meus Favoritos"
                },
                title: "Selecionar Grupo",
                searchTitle: "Pesquisar",
                ok: "Ok",
                cancel: "Cancelar",
                placeholder: "Inserir termo de pesquisa"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Deslocar para Norte",
            utm_easting: "Deslocar para Leste",
            utm_zone_number: "Número da Zona",
            geoFormGeneralTabText: "1. Inserir Informações",
            locationInformationText: "2. Selecionar Local",
            submitInformationText: "3. Completar Formulário",
            submitInstructions: "Adicione estas informações no mapa.",
            myLocationText: "ã_Current Location_Ç",
            locationDescription: "ã_Specify the location for this entry by clicking/tapping the map or by using one of the following options._Ç",
            addressText: "Pesquisar",
            geographic: "ã_Lat/Lon_Ç",
            locationTabText: "Local",
            locationPopupTitle: "ã_Location_Ç",
            submitButtonText: "ã_Submit Entry_Ç",
            submitButtonTextLoading: "Enviando&hellip;",
            formValidationMessageAlertText: "Os seguintes campos são exigidos:",
            selectLocation: "Selecione um ${openLink}local${closeLink} para sua apresentação.",
            emptylatitudeAlertMessage: "Insira uma coordenada de ${openLink}latitude${closeLink}.",
            emptylongitudeAlertMessage: "Insira uma coordenada de ${openLink}longitude${closeLink}.",
            shareUserTitleMessage: "Agradecemos a sua contribuição!",
            entrySubmitted: "ã_Your entry has been submitted to the map._Ç",
            shareThisForm: "ã_Share This Form_Ç",
            shareUserTextMessage: "ã_Tell others to contribute using the following options._Ç",
            addAttachmentFailedMessage: "Não foi possível adicionar anexo na camada",
            addFeatureFailedMessage: "Não foi possível adicionar feição no mapa",
            noLayerConfiguredMessage: "Whoops! Nada para ver aqui. Para iniciar a coleta de apresentações do formulário, configure este GeoForm e selecione a camada de Serviço da Feição editável a ser utilizada.",
            placeholderLatitude: "Latitude (Y)",
            placeholderLongitude: "Longitude (X)",
            latitude: "Latitude",
            longitude: "Longitude",
            findMyLocation: "ã_Locate Me_Ç",
            finding: "Localização&hellip;",
            backToTop: "Voltar ao topo",
            addressSearchText: "Sua apresentação aparecerá aqui. Você pode arrastar o alfinete para corrigir o local.",
            shareModalFormText: "Link do Formulário",
            close: "Fechar",
            locationNotFound: "Não foi possível encontrar o local.",
            setLocation: "ã_Set Location_Ç",
            find: "ã_Find address or place_Ç",
            attachment: "Anexo",
            toggleDropdown: "Alternar Menu Suspenso",
            invalidLatLong: "Insira coordenadas de ${latLink}latitude${closeLink} e ${lngLink}longitude${closeLink} válidas.",
            invalidUTM: "Insira coordenadas ${openLink}UTM${closeLink} válidas.",
            invalidUSNG: "Insira coordenadas ${openLink}USNG${closeLink} válidas.",
            invalidMGRS: "Insira coordenadas ${openLink}MGRS${closeLink} válidas.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Selecionar&hellip;",
            applyEditsFailedMessage: "Desculpe, sua entrada não pode ser enviada. Tente novamente.",
            requiredFields: "Há alguns erros. Corrija abaixo.",
            requiredField: "ã_(required)_Ç",
            error: "Erro",
            textRangeHintMessage: "ã_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_Ç",
            dateRangeHintMessage: "ã_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_Ç"
        },
        builder: {
            invalidUser: "ã_Sorry, you dont have permission to view this item_Ç",
            invalidWebmapSelectionAlert: "ã_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._Ç",
            invalidWebmapSelectionAlert2: "ã_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_Ç",
            selectFieldsText: "ã_Select Form Fields_Ç",
            selectThemeText: "ã_Select Form Theme_Ç",
            webmapText: "ã_Webmap_Ç",
            layerText: "ã_Layer_Ç",
            detailsText: "ã_Details_Ç",
            fieldsText: "ã_Fields_Ç",
            styleText: "ã_Style_Ç",
            optionText: "ã_Options_Ç",
            previewText: "ã_Preview_Ç",
            publishText: "ã_Publish_Ç",
            optionsApplicationText: "ã_Options_Ç",
            titleText: "ã_Builder_Ç",
            descriptionText: "ã_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a map’s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm._Ç",
            btnPreviousText: "ã_Previous_Ç",
            btnNextText: "ã_Next_Ç",
            webmapTabTitleText: "ã_Select a Webmap_Ç",
            viewWebmap: "ã_View webmap_Ç",
            btnSelectWebmapText: "ã_Choose Webmap_Ç",
            btnSelectWebmapTextLoading: "ã_Loading&hellip;_Ç",
            layerTabTitleText: "ã_Select Editable Layer_Ç",
            selectLayerLabelText: "ã_Layer_Ç",
            selectLayerDefaultOptionText: "ã_Select Layer_Ç",
            detailsTabTitleText: "ã_Form Details_Ç",
            detailTitleLabelText: "ã_Title_Ç",
            detailLogoLabelText: "ã_Logo Image_Ç",
            descriptionLabelText: "ã_Help Text (optional)_Ç",
            fieldTabFieldHeaderText: "ã_Field_Ç",
            fieldTabLabelHeaderText: "ã_Label_Ç",
            fieldTabDisplayTypeHeaderText: "ã_Display As_Ç",
            selectMenuOption: "ã_Select Menu_Ç",
            selectRadioOption: "ã_Radio Button_Ç",
            selectTextOption: "ã_Text_Ç",
            selectCheckboxOption: "ã_Checkbox_Ç",
            selectMailOption: "ã_Email_Ç",
            selectUrlOption: "ã_URL_Ç",
            selectTextAreaOption: "ã_Textarea_Ç",
            previewApplicationText: "ã_Preview Application_Ç",
            saveApplicationText: "ã_Save Application_Ç",
            saveText: "ã_Save_Ç",
            toggleNavigationText: "ã_Toggle navigation_Ç",
            formPlaceholderText: "ã_My Form_Ç",
            shareBuilderInProgressTitleMessage: "ã_Publishing GeoForm_Ç",
            shareBuilderProgressBarMessage: "ã_Please Wait&hellip;_Ç",
            shareBuilderTitleMessage: "ã_Success! Item saved_Ç",
            shareBuilderTextMessage: "ã_You can start collecting information by sharing with others_Ç",
            shareModalFormText: "ã_Form Link_Ç",
            shareBuilderSuccess: "ã_Your GeoForm has been updated & published!_Ç",
            geoformTitleText: "ã_Geo Form_Ç",
            layerTabText: "ã_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._Ç",
            detailsTabText: "ã_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm._Ç",
            fieldsTabText: "ã_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._Ç",
            styleTabText: "ã_Style your GeoForm using the themes below based on your preference._Ç",
            publishTabText: "ã_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._Ç",
            smallHeader: "ã_Use Small Header_Ç",
            pushpinText: "ã_Push pin_Ç",
            doneButtonText: "ã_View Application Item_Ç",
            fieldTabPlaceHolderHeaderText: "ã_Hint (optional)_Ç",
            attachmentLabelText: "ã_Attchment Label_Ç",
            attachmentLabelHint: "ã_Tell users what type of file to attach._Ç",
            attachmentDescription: "ã_Attachment Description_Ç",
            attachmentHint: "ã_If necessary, you can provide additional attachment instructions here._Ç",
            jumbotronDescription: "ã_The Bootstrap Jumbotron makes it easy to define the purpose of your application. This can be disabled at any time._Ç",
            shareGeoformText: "ã_Share Geoform_Ç",
            shareDescription: "ã_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time._Ç",
            defaultMapExtent: "ã_Default Map Extent_Ç",
            defaultMapExtentDescription: "ã_The map will reset to the default extent in your web map after submission - this can be disabled at any time._Ç",
            pushpinOptionsDescription: "ã_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_Ç",
            selectLocationText: "ã_Select Location By_Ç",
            myLocationText: "ã_My Location_Ç",
            searchText: "ã_Search_Ç",
            coordinatesText: "ã_Latitude & Longitude Coordinates_Ç",
            usng: "ã_USNG Coordinates_Ç",
            mgrs: "ã_MGRS Coordinates_Ç",
            utm: "ã_UTM Coordinates_Ç",
            selectLocationSDescription: "ã_Allow users to select a location using these methods._Ç"
        }
    })
);