define(
   ({
    map: {
      error: "Não foi possível criar o mapa"
    },
    onlineStatus: {
      offline: "Você está atualmente trabalhando offline. As submissões de formulário serão salvas localmente até que uma conexão ao servidor possa ser feita.",
      reconnecting: "Reconectando&hellip;",
      pending: "${total} edições pendentes serão submetidas quando uma conexão de rede for reestabelecida."
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "Minha Organização",
          onlineLabel: "ArcGIS Online",
          contentLabel: "Meu Conteúdo",
          favoritesLabel: "Meus Favoritos"
        },
        title: "Selecionar Mapa da Web",
        searchTitle: "Pesquisar",
        ok: "Ok",
        cancel: "Cancelar",
        placeholder: "Inserir termo de pesquisa"
      },
      groupdlg: {
        items: {
          organizationLabel: "Minha Organização",
          onlineLabel: "ArcGIS Online",
          contentLabel: "Meu Conteúdo",
          favoritesLabel: "Meus Favoritos"
        },
        title: "Selecionar Grupo",
        searchTitle: "Pesquisar",
        ok: "Ok",
        cancel: "Cancelar",
        placeholder: "Inserir termo de pesquisa"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "Aqui está um link para um GeoForm"
      }
    },
    user: {
      all: "Todos",
      mgrs: "MGRS",
      usng: "USNG",
      utm: "UTM",
      utm_northing: "Norte",
      utm_easting: "Leste",
      utm_zone_number: "Número da Zona",
      selectLayerTabText: "${formSection} Selecionar Formulário",
      geoFormGeneralTabText: "${formSection} Inserir Informações",
      locationInformationText: "${formSection} Selecionar Localização",
      submitInformationText: "${formSection} Completar Formulário",
      submitInstructions: "Adicione estas informações no mapa.",
      myLocationText: "Local Atual",
      locationDescriptionForMoreThanOneOption: "Especifique a localização para esta entrada ao clicar/tocar no mapa ou utilizando uma das seguintes opções.",
      locationDescriptionForOneOption: "Especifique a localização para esta entrada ao clicar/tocar no mapa ou utilizando a seguinte opção.",
      locationDescriptionForNoOption: "Especifique a localização para esta entrada ao clicar/tocar no mapa.",
      addressText: "Pesquisar",
      geographic: "Lat/Long",
      locationTabText: "Local",
      locationPopupTitle: "Local",
      submitButtonText: "Enviar Entrada",
      submitButtonTextLoading: "Enviando&hellip;",
      formValidationMessageAlertText: "Os seguintes campos são exigidos:",
      selectLocation: "Selecione uma localização para sua submissão.",
      emptylatitudeAlertMessage: "Insira uma coordenada de ${openLink}latitude${closeLink}.",
      emptylongitudeAlertMessage: "Insira uma coordenada de ${openLink}longitude${closeLink}.",
      shareUserTitleMessage: "Agradecemos a sua contribuição!",
      entrySubmitted: "Sua entrada foi enviada ao mapa.",
      shareThisForm: "Compartilhar Este Formulário",
      shareUserTextMessage: "Peça aos outros para contribuir utilizando as seguintes opções",
      addAttachmentFailedMessage: "Não foi possível adicionar anexo na camada",
      addFeatureFailedMessage: "Não foi possível adicionar feição no mapa",
      noLayerConfiguredMessage: "Ocorreu um erro ao carregar ou localizar uma camada de feição editável. Para exibir o formulário e iniciar a coleta de submissões, adicione uma Camada de Feição editável no Mapa da Web.",
      placeholderLatitude: "Latitude (Y)",
      placeholderLongitude: "Longitude (X)",
      latitude: "Latitude",
      longitude: "Longitude",
      findMyLocation: "Localize-me",
      finding: "Localizando&hellip;",
      backToTop: "Voltar ao topo",
      addressSearchText: "Sua apresentação aparecerá aqui. Você pode arrastar o alfinete para corrigir o local.",
      shareModalFormText: "Link do Formulário",
      close: "Fechar",
      locationNotFound: "Não foi possível encontrar o local.",
      setLocation: "Definir Local",
      find: "Localizar endereço ou lugar",
      attachment: "Anexo",
      toggleDropdown: "Alternar Suspensão",
      invalidString: "Insira um valor válido.",
      invalidSmallNumber: "Insira um valor ${openStrong}inteiro${closeStrong} válido entre -32768 e 32767.",
      invalidNumber: "Insira um valor ${openStrong}inteiro${closeStrong} válido entre -2147483648 e 2147483647.",
      invalidFloat: "Insira um valor de ${openStrong}ponto flutuante${closeStrong} válido.",
      invalidDouble: "Insira um valor ${openStrong}duplo${closeStrong} válido.",
      invalidLatLong: "Insira coordenadas de latitude e longitude válidas.",
      invalidUTM: "Insira coordenadas UTM válidas.",
      invalidUSNG: "Insira coordenadas USNG válidas.",
      invalidMGRS: "Insira coordenadas MGRS válidas.",
      geoformTitleText: "GeoForm",
      domainDefaultText: "Selecionar&hellip;",
      applyEditsFailedMessage: "Desculpe, sua entrada não pode ser enviada. Tente novamente.",
      requiredFields: "O seguinte campo é obrigatório. Forneça uma entrada válida.",
      requiredField: "(exigido)",
      error: "Erro",
      textRangeHintMessage: "${openStrong}Dica:${closeStrong} valor Mínimo ${minValue} e valor Máximo ${maxValue}",
      dateRangeHintMessage: "${openStrong}Dica:${closeStrong} Data Mínima ${minValue} e Data Máxima ${maxValue}",
      remainingCharactersHintMessage: "${value} caracteres remanescentes",
      mapFullScreen: "Tela Cheia",
      mapRestore: "Restaurar",
      filterSelectEmptyText: "Selecionar",
      invalidLayerMessage: "Uma camada válida para criar o GeoForm não foi localizada. Se o GeoForm foi configurado com uma camada, a camada pode não estar mais disponível ou a autorização falhou.",
      selectedLayerText: "Todos",
      fileUploadStatus: "Status de Transferência do Arquivo",
      uploadingBadge: "&nbsp;Carregando&hellip;",
      successBadge: "&nbsp;Carregado",
      retryBadge: "Tentar Novamente",
      errorBadge: "Erro ao carregar&nbsp;&nbsp;&nbsp;",
      fileTooLargeError: "Arquivo muito grande para anexar",
      exceededFileCountError: "Número máximo de anexos permitidos excedido",
      selectFileTitle: "Selecione um arquivo",
      btnSelectFileText: "Selecionar Arquivo",
      btnViewSubmissions: "Visualizar Submissões"
    },
    builder: {
      gettingStarted: "Guia de Introdução",
      dateSettings: "Configurações de Data",
      hiddenDateField: "Ocultar este campo de data",
      preventPastDates: "Prevenir datas passadas",
      preventFutureDates: "Prevenir datas futuras",
      useCurrentDate: "Deixe este campo com a data e hora atual",
      configure: "Configurar",
      configureField: "Configurar Campo \'${fieldName}\'",
      invalidUser: "Desculpe, você não tem permissão para visualizar este item",
      invalidWebmapSelectionAlert: "O mapa da web selecionado não contém uma camada válida para utilizar. Adicione uma Camada de Feição editável ao seu mapa da web para continuar.",
      invalidWebmapSelectionAlert2: "Para Mais Informações, consulte ${openLink}O que é Serviço da Feição?${closeLink}",
      selectFieldsText: "Selecionar Campos do Formulário",
      selectThemeText: "Selecionar Tema do Formulário",
      setViewerText: "Configurar Visualizador",
      introText: "Inicial",
      webmapText: "Mapa da Web",
      layerText: "Camada",
      detailsText: "Detalhes",
      fieldsText: "Campos",
      styleText: "Estilo",
      viewerText: "Visualizador",
      optionText: "Opções",
      previewText: "Visualizar",
      publishText: "Publicar",
      optionsApplicationText: "Opções",
      submitButtonText: "Texto do Botão de Enviar (Opcional)",
      submitButtonDesc: "Opcionalmente rotule o botão para enviar uma nova entrada. Este texto não será traduzido.",
      viewSubmissionsText: "Visualizar Texto de Submissões (Opcional)",
      viewSubmissionsDesc: "Opcionalmente rotule o botão para visualizar entradas existentes. Este texto não será traduzido.",
      titleText: "Construtor",
      descriptionText: "O GeoForm é um modelo configurável para edição de dados baseada em formulário de um ${link1}Serviço da Feição${closeLink}. Este aplicativo permite aos usuários inserir dados por um formulário, ao invés de um pop-up do mapa enquanto alavancar a potência do ${link2}Mapa da Web${closeLink} e Serviços da Feição editáveis. Utilize as seguintes etapas para personalizar e implantar seu GeoForm.",
      btnPreviousText: "Anterior",
      btnNextText: "Avançar",
      webmapTabTitleText: "Selecione um Mapa da Web",
      viewWebmap: "Visualizar mapa da web",
      webmapDetailsText: "O mapa da web selecionado é ${webMapTitleLink}${webMapTitle}${closeLink}. Para selecionar um mapa da web diferente, clique no botão \'Escolher Mapa da Web\'",
      btnSelectWebmapText: "Escolher Mapa da Web",
      btnSelectWebmapTextLoading: "Carregando&hellip;",
      layerTabTitleText: "Selecionar Camada Editável",
      selectLayerLabelText: "Camada",
      selectLayerDefaultOptionText: "Selecionar Camada",
      enableBasemapToggle: "Mostrar Alternância de Mapa Base",
      enableBasemapToggleDescription: "Você pode configurar o GeoForm para Mostrar/Ocultar a Alternância de Mapa Base",
      defaultBasemap: "Alternar Mapa da Web",
      secondaryBasemap: "Mapa Base Padrão",
      detailsTabTitleText: "Detalhes do Formulário",
      detailTitleLabelText: "Título",
      detailLogoLabelText: "Imagem do Logo",
      descriptionLabelText: "Instruções e Detalhes do Formulário",
      fieldDescriptionLabelText: "Texto de Ajuda (opcional)",
      fieldDescriptionHelpText: "Forneça uma pequena descrição ou instruções para este campo.",
      fieldHintHelpText: "Texto reservado para este campo.",
      fieldTabFieldHeaderText: "Campo",
      fieldTabLabelHeaderText: "Rótulo",
      fieldTabDisplayTypeHeaderText: "Exibir Como",
      fieldTabOrderColumnText: "Ordenar",
      fieldTabVisibleColumnText: "Habilitado",
      displayFieldText: "Exibir Campo",
      selectMenuOption: "Menu de Seleção",
      selectRadioOption: "Botão Rádio",
      selectTextOption: "Texto",
      selectDateOption: "Selecionador de Data",
      selectRangeOption: "Roleta de Toque",
      selectCheckboxOption: "Caixa de seleção",
      selectMailOption: "E-mail",
      selectUrlOption: "URL",
      selectTextAreaOption: "Área de Texto",
      previewApplicationText: "Visualizar Aplicativo",
      saveApplicationText: "Salvar Aplicativo",
      saveText: "Salvar",
      toggleNavigationText: "Alternar navegação",
      formPlaceholderText: "Meu Formulário",
      shareBuilderInProgressTitleMessage: "Publicando GeoFormulário",
      shareBuilderProgressBarMessage: "Aguarde&hellip;",
      shareBuilderTitleMessage: "Bem Sucedido! Item salvo",
      shareBuilderTextMessage: "Você pode iniciar a coleta de informações, compartilhando com outros",
      shareModalFormText: "Link do Formulário",
      shareBuilderSuccess: "Seu GeoFormulário foi atualizado e publicado!",
      geoformTitleText: "Geo Formulário",
      layerTabText: "Esta é a camada da qual o GeoForm será construído. A camada deve ser um serviço da feição que está habilitado para edição com permissões de compartilhamento apropriadas para seu público. Se todas as camadas estiverem selecionadas, o formulário permitirá a um usuário escolher para qual camada de formulário enviar.",
      detailsTabText: "Utilize as caixas de Detalhe do Formulário abaixo para personalizar o Título, adicionar um logotipo personalizado e fornecer uma breve descrição para o seu público do GeoForm. Na descrição você pode adicionar links para outros recursos, informações de contato e também pontos para seu público em um aplicativo de mapeamento da web apresentando todos os dados coletados com o GeoForm.",
      fieldsTabText: "Aqui você pode selecionar quais campos serão visíveis para o público do GeoFormulário, editar os Rótulos que eles visualizarão e adicionar uma pequena Descrição para ajudar com a entrada de dados.",
      styleTabText: "Crie o estilo do seu GeoFormulário utilizando os temas abaixo baseado na sua preferência.",
      viewerTabText: "Configure opções para visualizar as submissões coletadas do GeoForm.",
      publishTabText: "Se você terminou de personalizar seu GeoForm, salve o aplicativo e comece a compartilhar com seu público. Você pode sempre retornar a este construtor e continuar a personalizá-lo com base em comentários.",
      headerSizeLabel: "Tamanho do Cabeçalho",
      smallHeader: "Utilizar Cabeçalho Pequeno",
      bigHeader: "Utilizar Cabeçalho Grande",
      pushpinText: "Alfinete",
      doneButtonText: "Salvar e Sair",
      fieldTabPlaceHolderHeaderText: "Dica (opcional)",
      enableAttachmentLabelText: "${openStrong}Habilitar Anexos${closeStrong}",
      enableAttachmentLabelHint: "Você pode habilitar/desabilitar os anexos aqui",
      attachmentIsRequiredLabelText: "${openStrong}Anexo Exigido${closeStrong}",
      attachmentIsRequiredLabelHint: "Se necessário, usuários podem ser solicitados para inserir um anexo.",
      attachmentLabelText: "Rótulo de Botão do Anexo",
      attachmentLabelHint: "Este texto aparecerá próximo ao Botão do Anexo. Você pode utilizar este espaço para descrever o que você gostaria que seu público anexasse (fotografia, vídeo, documento, etc.), o formato do arquivo que você está solicitando (.jpeg, .png, .docx, .pdf, etc.), e quaisquer instruções adicionais",
      attachmentDescription: "Descrição do Anexo",
      attachmentHint: "Se necessário, você pode fornecer instruções do anexo adicionais aqui.",
      jumbotronDescription: "Utilize um cabeçalho grande ou pequeno para seu formulário. Um cabeçalho grande pode ajudar a definir o propósito do seu aplicativo, mas ocupa mais espaço na sua tela",
      shareGeoformText: "Mídia social compartilhando botões",
      shareDescription: "Os botões de mídia social permitem ao seu público compartilhar facilmente seu GeoForm após fazerem uma submissão",
      defaultMapExtent: "Extensão de Mapa Padrão",
      defaultMapExtentDescription: "O mapa irá reconfigurar para a extensão padrão no seu mapa da web após a apresentação - isto pode ser desativado a qualquer momento.",
      pushpinOptionsDescription: "Escolha entre uma variedade de cores para o alfinete do mapa, ele deve ser diferente da simbologia do mapa para ajudar o usuário a colocar sua apresentação no mapa",
      selectLocationText: "Selecionar Local Por",
      myLocationText: "Meu Local",
      searchText: "Pesquisar",
      coordinatesText: "Coordinates",
      usng: "Coordenadas USNG",
      mgrs: "Coordenadas MGRS",
      utm: "Coordenadas UTM",
      selectLocationSDescription: "Permite aos usuários selecionar um local utilizando estes métodos.",
      dragTooltipText: "Arraste o campo onde você deseja que ele apareça",
      showHideLayerText: "Mostrar Camada",
      showHideLayerHelpText: "Você pode configurar o GeoForm para Mostrar/Ocultar Camada. Esta opção se aplica somente a uma única configuração de camada.",
      enableOfflineSupport: "Habilitar suporte offline",
      enableOfflineSupportHelpText: "Armazene submissões quando não existir nenhuma conexão de rede e envie-as quando uma conexão for restaurada.",
      labelHelpMessage: "Rótulo",
      placeHolderHintMessage: "Texto de Dica",
      placeHolderHelpMessage: "Texto de Ajuda",
      selectTextOptionValue: "Seleção de Filtro",
      disableLogo: "Desabilitar Logo",
      disableLogoDescription: "Você pode configurar o GeoForm para Mostrar/Ocultar o Logo no cabeçalho do formulário",
      locateOnLoadText: "Localizar ao Carregar",
      locateOnLoadDescription: "Você pode configurar o GeoForm para utilizar a localização atual ao carregar a página",
      selectLayerFieldTabText: "Selecionar Camada",
      allLayerSelectOptionText: "Todas as Camadas",
      disableViewer: "Desabilitar Visualizador",
      disableViewerDescription: "Você pode configurar o GeoForm para habilitar/desabilitar o visualizador",
      displayFieldHintText: "O campo de visualização selecionado será mostrado no visualizador como um título"
    },
    viewer: {
      geocoderCancelText: "Cancelar",
      viewMapTabText: "Mapa",
      sortHeaderText: "Classificar Por:",
      geocoderPlaceholderText: "Código Postal, cidade, etc.",
      noSearchResult: "Nenhum resultado encontrado",
      legendTabTooltip: "Legenda",
      aboutUsTabTooltip: "Sobre Nós",
      mapTabTooltip: "Mapa",
      btnDescendingText: "Desc",
      btnAscendingText: "Asc",
      geometryUnavailableErrorMessage: "Erro ao localizar a geometria da feição",
      infoPopupOffErrorMessage: "Nenhum informação para exibir",
      btnLoadMoreText: "Carregar Mais",
      unavailableTitleText: "Sem título",
      unavailableConfigMessage: "Não foi possível carregar a configuração",
      share: "Compartilhar o",
      viewReportsTabText: "Relatórios",
      viewLegendTabText: "Legenda",
      viewAboutusTabText: "Sobre",
      appLoadingFailedMessage: "Ocorreu um erro ao carregar o visualizador"
    }
  })
);