define(
     ({
        map: {
            error: "Não foi possível criar o mapa"
        },
        onlineStatus: {
            offline: "Você está trabalhando offline. Envios de formulários serão salvos localmente até que uma conexão com o servidor possa ser feita.",
            reconnecting: "Reconectando&hellip;",
            pending: "${total} edições pendentes serão enviadas quando uma conexão de rede for reestabelecida."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Minha Organização",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Meu Conteúdo",
                    favoritesLabel: "Meus Favoritos"
                },
                title: "Selecionar Mapa da Web",
                searchTitle: "Pesquisar",
                ok: "Ok",
                cancel: "Cancelar",
                placeholder: "Inserir termo de pesquisa"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Minha Organização",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Meu Conteúdo",
                    favoritesLabel: "Meus Favoritos"
                },
                title: "Selecionar Grupo",
                searchTitle: "Pesquisar",
                ok: "Ok",
                cancel: "Cancelar",
                placeholder: "Inserir termo de pesquisa"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Deslocar para Norte",
            utm_easting: "Deslocar para Leste",
            utm_zone_number: "Número da Zona",
            geoFormGeneralTabText: "1. Inserir Informações",
            locationInformationText: "2. Selecionar Local",
            submitInformationText: "3. Completar Formulário",
            submitInstructions: "Adicione estas informações no mapa.",
            myLocationText: "Local atual",
            locationDescription: "Especifique um local para sua entrada clicando/tocando no mapa ou utilizando uma das seguintes opções.",
            addressText: "Pesquisar",
            geographic: "Lat/Long",
            locationTabText: "Local",
            locationPopupTitle: "Local",
            submitButtonText: "Enviar Entrada",
            submitButtonTextLoading: "Enviando&hellip;",
            formValidationMessageAlertText: "Os seguintes campos são exigidos:",
            selectLocation: "Selecione um ${openLink}local${closeLink} para sua apresentação.",
            emptylatitudeAlertMessage: "Insira uma coordenada de ${openLink}latitude${closeLink}.",
            emptylongitudeAlertMessage: "Insira uma coordenada de ${openLink}longitude${closeLink}.",
            shareUserTitleMessage: "Agradecemos a sua contribuição!",
            entrySubmitted: "Sua entrada foi enviada para o mapa.",
            shareThisForm: "Compartilhar Este Formulário",
            shareUserTextMessage: "Peça aos outros para contribuir utilizando as seguintes opções.",
            addAttachmentFailedMessage: "Não foi possível adicionar anexo na camada",
            addFeatureFailedMessage: "Não foi possível adicionar feição no mapa",
            noLayerConfiguredMessage: "Ocorreu um erro ao carregar ou localizar uma camada de feição editável. Para exibir o formulário e começar a coletar as submissões, adicione uma Camada de Feição editável no Mapa da Web.",
            placeholderLatitude: "Latitude (Y)",
            placeholderLongitude: "Longitude (X)",
            latitude: "Latitude",
            longitude: "Longitude",
            findMyLocation: "Localize-me",
            finding: "Localização&hellip;",
            backToTop: "Voltar ao topo",
            addressSearchText: "Sua apresentação aparecerá aqui. Você pode arrastar o alfinete para corrigir o local.",
            shareModalFormText: "Link do Formulário",
            close: "Fechar",
            locationNotFound: "Não foi possível encontrar o local.",
            setLocation: "Configurar Local",
            find: "Localizar endereço ou lugar",
            attachment: "Anexo",
            toggleDropdown: "Alternar Menu Suspenso",
            invalidLatLong: "Insira coordenadas de ${latLink}latitude${closeLink} e ${lngLink}longitude${closeLink} válidas.",
            invalidUTM: "Insira coordenadas ${openLink}UTM${closeLink} válidas.",
            invalidUSNG: "Insira coordenadas ${openLink}USNG${closeLink} válidas.",
            invalidMGRS: "Insira coordenadas ${openLink}MGRS${closeLink} válidas.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Selecionar&hellip;",
            applyEditsFailedMessage: "Desculpe, sua entrada não pode ser enviada. Tente novamente.",
            requiredFields: "Há alguns erros. Corrija abaixo.",
            requiredField: "(exigido)",
            error: "Erro",
            textRangeHintMessage: "${openStrong}Dica:${closeStrong} Valor mínimo ${minValue} e Valor máximo ${maxValue}",
            dateRangeHintMessage: "${openStrong}Dica:${closeStrong} Data mínima ${minValue} e Data máxima ${maxValue}"
        },
        builder: {
            invalidUser: "Desculpe, você não tem permissão para visualizar este item",
            invalidWebmapSelectionAlert: "O mapa da web selecionado não contém uma camada válido para uso. Adicione um FeatureLayer editável no seu mapa da web para continuar.",
            invalidWebmapSelectionAlert2: "Para Mais Informações, consulte ${openLink}O que é Serviço da Feição?${closeLink}",
            selectFieldsText: "Selecionar Campos do Formulário",
            selectThemeText: "Selecionar do Tema",
            webmapText: "Mapa da Web",
            layerText: "Camada",
            detailsText: "Detalhes",
            fieldsText: "Campos",
            styleText: "Estilo",
            optionText: "Opções",
            previewText: "Visualizar",
            publishText: "Publicar",
            optionsApplicationText: "Opções",
            titleText: "Construtor",
            descriptionText: "O GeoForm é um modelo configurável para edição de dados baseado em formulário de um ${link1}Serviço da Feição${closeLink}. Este aplicativo permite aos usuários inserir dados através de um formulário, ao invés de um pop-up de mapa, aproveitando o poder do ${link2}Mapa da Web${closeLink} e Serviços da Feição editáveis. Utilize as seguintes etapas para personalizar e implantar o GeoForm.",
            btnPreviousText: "Anterior",
            btnNextText: "Avançar",
            webmapTabTitleText: "Selecionar um Mapa da Web",
            viewWebmap: "Visualizar mapa da web",
            btnSelectWebmapText: "Escolher Mapa da Web",
            btnSelectWebmapTextLoading: "Carregando&hellip;",
            layerTabTitleText: "Selecionar Camada Editável",
            selectLayerLabelText: "Camada",
            selectLayerDefaultOptionText: "Selecionar Camada",
            detailsTabTitleText: "Detalhes do Formulário",
            detailTitleLabelText: "Título",
            detailLogoLabelText: "Imagem do Logo",
            descriptionLabelText: "Texto de Ajuda (opcional)",
            fieldTabFieldHeaderText: "Campo",
            fieldTabLabelHeaderText: "Rótulo",
            fieldTabDisplayTypeHeaderText: "Exibir Como",
            selectMenuOption: "Menu de Seleção",
            selectRadioOption: "Botão de Rádio",
            selectTextOption: "Texto",
            selectCheckboxOption: "Caixa de seleção",
            selectMailOption: "E-mail",
            selectUrlOption: "URL",
            selectTextAreaOption: "Área do texto",
            previewApplicationText: "Visualizar Aplicativo",
            saveApplicationText: "Salvar Aplicativo",
            saveText: "Salvar",
            toggleNavigationText: "Alternar navegação",
            formPlaceholderText: "Meu Formulário",
            shareBuilderInProgressTitleMessage: "Publicando GeoFormulário",
            shareBuilderProgressBarMessage: "Aguarde&hellip;",
            shareBuilderTitleMessage: "Bem Sucedido! Item salvo",
            shareBuilderTextMessage: "Você pode iniciar a coleta de informações, compartilhando com outros",
            shareModalFormText: "Link do Formulário",
            shareBuilderSuccess: "Seu GeoFormulário foi atualizado e publicado!",
            geoformTitleText: "Geo Formulário",
            layerTabText: "Esta é a camada de onde o GeoFormulário será construído. A camada deve ser um serviço da feição que está habilitado para edição com permissões de compartilhamento apropriadas para o seu público.",
            detailsTabText: "Utilize as caixas de Detalhe do Formulário abaixo para personalizar o Título, adicionar um logotipo personalizado e fornecer uma breve descrição para o seu público do GeoForm. Na descrição você pode adicionar links para outros recursos, informações de contato e também pontos para seu público em um aplicativo de mapeamento da web apresentando todos os dados coletados com o GeoForm.",
            fieldsTabText: "Aqui você pode selecionar quais campos serão visíveis para o público do GeoFormulário, editar os Rótulos que eles visualizarão e adicionar uma pequena Descrição para ajudar com a entrada de dados.",
            styleTabText: "Crie o estilo do seu GeoFormulário utilizando os temas abaixo baseado na sua preferência.",
            publishTabText: "Se você terminou de personalizar seu GeoForm, salve o aplicativo e comce a compartilhar com seu público. Você pode sempre retornar a este construtor e continuar a personalizá-lo com base na resposta.",
            smallHeader: "Utilizar Cabeçalho Pequeno",
            pushpinText: "Alfinete",
            doneButtonText: "Visualizar Item do Aplicativo",
            fieldTabPlaceHolderHeaderText: "Dica (opcional)",
            attachmentLabelText: "Rótulo do Anexo",
            attachmentLabelHint: "Conte-nos qual tipo de arquivo anexar.",
            attachmentDescription: "Descrição do Anexo",
            attachmentHint: "Se necessário, você pode fornecer instruções de anexo adicionais aqui.",
            jumbotronDescription: "O Bootstrap Jumbotron torna mais fácil definir a finalidade do seu aplicativo. Isto pode ser desabilitado a qualquer momento.",
            shareGeoformText: "Compartilhar GeoForm",
            shareDescription: "O painel de compartilhamento torna mais fácil para o público compartilhar o GeoForm com outros colaboradores, uma vez que fizeram uma apresentação - isto pode ser desativado a qualquer momento.",
            defaultMapExtent: "Extensão de Mapa Padrão",
            defaultMapExtentDescription: "O mapa irá reconfigurar para a extensão padrão no seu mapa da web após a apresentação - isto pode ser desativado a qualquer momento.",
            pushpinOptionsDescription: "Escolha entre uma variedade de cores para o alfinete do mapa, ele deve ser diferente da simbologia do mapa para ajudar o usuário a colocar sua apresentação no mapa",
            selectLocationText: "Selecionar Local Por",
            myLocationText: "Meu Local",
            searchText: "Pesquisar",
            coordinatesText: "Coordinates",
            usng: "Coordenadas USNG",
            mgrs: "Coordenadas MGRS",
            utm: "Coordenadas UTM",
            selectLocationSDescription: "Permite aos usuários selecionar um local utilizando estes métodos."
        }
    })
);