define(
   ({
    map: {
      error: "Karttaa ei voi luoda"
    },
    onlineStatus: {
      offline: "Työskentelet tällä hetkellä offline-tilassa. Lomakkeiden lähetykset tallennetaan paikallisesti, kunnes palvelinyhteys voidaan muodostaa.",
      reconnecting: "Muodostetaan yhteyttä uudelleen&hellip;",
      pending: "${total} odottavaa muokkausta lähetetään, kun verkkoyhteys on luotu uudelleen."
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "Oma organisaatio",
          onlineLabel: "ArcGIS Online",
          contentLabel: "Oma sisältö",
          favoritesLabel: "Omat suosikit"
        },
        title: "Valitse Web-kartta",
        searchTitle: "Etsi",
        ok: "OK",
        cancel: "Peruuta",
        placeholder: "Anna hakuehto"
      },
      groupdlg: {
        items: {
          organizationLabel: "Oma organisaatio",
          onlineLabel: "ArcGIS Online",
          contentLabel: "Oma sisältö",
          favoritesLabel: "Omat suosikit"
        },
        title: "Valitse ryhmä",
        searchTitle: "Etsi",
        ok: "OK",
        cancel: "Peruuta",
        placeholder: "Anna hakuehto"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "Tässä on linkki GeoForm-malliin"
      }
    },
    user: {
      mgrs: "MGRS",
      usng: "USNG",
      utm: "UTM",
      utm_northing: "Pohjois",
      utm_easting: "Itäinen",
      utm_zone_number: "Vyöhykkeen numero",
      selectLayerTabText: "${formSection} Valitse lomake",
      geoFormGeneralTabText: "${formSection} Anna tiedot",
      locationInformationText: "${formSection} Valitse sijainti",
      submitInformationText: "${formSection} Täytä lomake",
      submitInstructions: "Lisää nämä tiedot karttaan.",
      myLocationText: "Nykyinen sijainti",
      locationDescriptionForMoreThanOneOption: "Määritä syötteen sijainti käyttämällä jotain seuraavista vaihtoehdoista tai napsauttamalla/ napauttamalla karttaa.",
      locationDescriptionForOneOption: "Määritä merkinnän sijainti käyttämällä seuraavaa vaihtoehtoa tai napsauttamalla/ napauttamalla karttaa.",
      locationDescriptionForNoOption: "Määritä merkinnän sijainti napsauttamalla/napauttamalla karttaa.",
      addressText: "Etsi",
      geographic: "Lev/pit",
      locationTabText: "Sijainti",
      locationPopupTitle: "Sijainti",
      submitButtonText: "Lähetä syöte",
      submitButtonTextLoading: "Lähetetään&hellip;",
      formValidationMessageAlertText: "Seuraavat kentät ovat pakollisia:",
      selectLocation: "Valitse sijainti lähetystä varten.",
      emptylatitudeAlertMessage: "Anna koordinaatti: ${openLink}latitude${closeLink}.",
      emptylongitudeAlertMessage: "Anna koordinaatti: ${openLink}longitude${closeLink}.",
      shareUserTitleMessage: "Kiitos osallistumisestasi!",
      entrySubmitted: "Syöte on lähetetty karttaan.",
      shareThisForm: "Jaa tämä lomake",
      shareUserTextMessage: "Pyydä muita käyttämään lisäyksiin seuraavia valintoja.",
      addAttachmentFailedMessage: "Ei voi lisätä liitettä karttatasoon",
      addFeatureFailedMessage: "Ei voi lisätä kohdetta karttatasoon",
      noLayerConfiguredMessage: "Muokattavan kohdekarttatason lataamisessa tai haussa tapahtui virhe. Jotta voit näyttää lomakkeen ja alkaa kerätä lähetyksiä, lisää muokattava kohdekarttataso Web-karttaan.",
      placeholderLatitude: "Leveysaste (Y)",
      placeholderLongitude: "Pituusaste (X)",
      latitude: "Leveysaste",
      longitude: "Pituusaste",
      findMyLocation: "Paikanna minut",
      finding: "Paikannetaan&hellip;",
      backToTop: "Alkuun",
      addressSearchText: "Lähetyksesi tulee näkyviin tähän. Voit korjata sijainnin vetämällä nastaa.",
      shareModalFormText: "Lomakkeen linkki",
      close: "Sulje",
      locationNotFound: "Sijaintia ei löytynyt.",
      setLocation: "Määritä sijainti",
      find: "Etsi osoite tai paikka",
      attachment: "Liite",
      toggleDropdown: "Vaihda luetteloiden välillä",
      invalidString: "Anna kelvollinen arvo.",
      invalidSmallNumber: "Kirjoita kelvollinen ${openStrong}kokonaisluku${closeStrong}arvo väliltä -32768–32767.",
      invalidNumber: "Kirjoita kelvollinen ${openStrong}kokonaisluku${closeStrong}arvo väliltä -2147483648–2147483647.",
      invalidFloat: "Kirjoita kelvollinen ${openStrong}liukuluku${closeStrong}arvo.",
      invalidDouble: "Kirjoita kelvollinen ${openStrong}kaksoistarkkuuksinen liukuluku${closeStrong}arvo.",
      invalidLatLong: "Anna kelvolliset pituus- ja leveysasteiden koordinaatit.",
      invalidUTM: "Anna kelvolliset UTM-koordinaatit.",
      invalidUSNG: "Anna kelvolliset USNG-koordinaatit.",
      invalidMGRS: "Anna kelvolliset MGRS-koordinaatit.",
      geoformTitleText: "GeoForm",
      domainDefaultText: "Valitse&hellip;",
      applyEditsFailedMessage: "Syötettä ei voi lähettää. Yritä uudelleen.",
      requiredFields: "Ilmeni virheitä. Korjaa ne alla.",
      requiredField: "(pakollinen)",
      error: "Virhe",
      textRangeHintMessage: "${openStrong}Vihje:${closeStrong} Vähimmäisarvo ${minValue} ja enimmäisarvo ${maxValue}",
      dateRangeHintMessage: "${openStrong}Vihje:${closeStrong} aikaisin ${minValue} ja myöhäisin päivämäärä ${maxValue}",
      remainingCharactersHintMessage: "${value} merkkiä jäljellä",
      mapFullScreen: "Koko näyttö",
      mapRestore: "Palauta",
      filterSelectEmptyText: "Valitse",
      invalidLayerMessage: "Lomakekarttatasoa ei ole. Määritä sovellus ja määritä karttataso.",
      selectedLayerText: "Kaikki",
      fileUploadStatus: "Tiedoston lataustila",
      uploadingBadge: "&nbsp;Ladataan palvelimelle&hellip;",
      successBadge: "&nbsp;Ladattu palvelimelle",
      retryBadge: "Yritä uudelleen",
      errorBadge: "Virhe palvelimelle latauksessa&nbsp;&nbsp;&nbsp;",
      fileTooLargeError: "Tiedosto on liian suuri liitettäväksi",
      exceededFileCountError: "Liitteiden sallittu enimmäismäärä on ylittynyt",
      selectFileTitle: "Valitse tiedosto",
      btnViewSubmissions: "Näytä lähetykset",
      dateFormat: "Å_MM/DD/YYYY h:mm a_ö"
    },
    builder: {
      invalidUser: "Sinulla ei ole oikeuksia tarkastella tätä kohdetta",
      invalidWebmapSelectionAlert: "Valittu Web-kartta ei sisällä kelvollista käytettävää karttatasoa. Jatka lisäämällä muokattava kohdekarttataso Web-karttaasi.",
      invalidWebmapSelectionAlert2: "Lisätietoja on kohdassa ${openLink}Mikä on kohdepalvelu?${closeLink}",
      selectFieldsText: "Valitse lomakekentät",
      selectThemeText: "Valitse lomaketeema",
      webmapText: "Web-kartta",
      layerText: "Karttataso",
      detailsText: "Yksityiskohdat",
      fieldsText: "Kentät",
      styleText: "Tyyli",
      optionText: "Valinnat",
      previewText: "Esikatselu",
      publishText: "Julkaise",
      optionsApplicationText: "Valinnat",
      titleText: "Muodostusohjelma",
      descriptionText: "GeoForm on muunneltavissa oleva mallipohja, joka on tarkoitettu ${link1}kohdepalvelun${closeLink} aineiston lomakepohjaiseen muokkaukseen. Tällä sovelluksella käyttäjät voivat syöttää tietoja lomakkeen kautta kartan ponnahdusikkunan sijaan ja hyödyntää samalla ${link2}Web-kartan${closeLink} ja muokattavien kohdepalvelujen kätevyyttä ja tehoa. Voit mukauttaa GeoForm-mallipohjaa ja ottaa sen käyttöön seuraavia ohjeita noudattamalla.",
      btnPreviousText: "Edellinen",
      btnNextText: "Seuraava",
      webmapTabTitleText: "Valitse Web-kartta",
      viewWebmap: "Näytä Web-kartta",
      webmapDetailsText: "Valittu Web-kartta on ${webMapTitleLink}${webMapTitle}${closeLink}. Jos haluat valita toisen Web-kartan, napsauta Valitse Web-kartta -painiketta",
      btnSelectWebmapText: "Valitse Web-kartta",
      btnSelectWebmapTextLoading: "Lataa&hellip;",
      layerTabTitleText: "Valitse muokattava karttataso",
      selectLayerLabelText: "Karttataso",
      selectLayerDefaultOptionText: "Valitse karttataso",
      defaultBasemap: "Taustakartan vaihto",
      secondaryBasemap: "Oletustaustakartta",
      detailsTabTitleText: "Lomakkeen tiedot",
      detailTitleLabelText: "Otsikko",
      detailLogoLabelText: "Logokuva",
      descriptionLabelText: "Lomakkeen ohjeet ja tiedot",
      fieldDescriptionLabelText: "Ohjeteksti (valinnainen)",
      fieldTabFieldHeaderText: "Kenttä",
      fieldTabLabelHeaderText: "Tunnusteksti",
      fieldTabDisplayTypeHeaderText: "Näytä muodossa",
      fieldTabOrderColumnText: "Järjestä",
      fieldTabVisibleColumnText: "Käytössä",
      displayFieldText: "Näyttökenttä",
      selectMenuOption: "Valitse valikko",
      selectRadioOption: "Valintanappi",
      selectTextOption: "Teksti",
      selectDateOption: "Päivämäärävalitsin",
      selectRangeOption: "Touch-Spinner",
      selectCheckboxOption: "Valintaruutu",
      selectMailOption: "Sähköposti",
      selectUrlOption: "URL-osoite",
      selectTextAreaOption: "Tekstialue",
      previewApplicationText: "Esikatsele sovellus",
      saveApplicationText: "Tallenna sovellus",
      saveText: "Tallenna",
      toggleNavigationText: "Käytä siirtymistä",
      formPlaceholderText: "Oma lomake",
      shareBuilderInProgressTitleMessage: "GeoForm-mallin julkaisu",
      shareBuilderProgressBarMessage: "Odota&hellip;",
      shareBuilderTitleMessage: "Kohteen tallennus onnistui",
      shareBuilderTextMessage: "Voit alkaa kerätä tietoja jakamalla ne muiden kanssa",
      shareModalFormText: "Lomakkeen linkki",
      shareBuilderSuccess: "GeoForm-mallisi on päivitetty ja julkaistu!",
      geoformTitleText: "GeoForm",
      layerTabText: "Tämä on karttataso, jonka perusteella GeoForm rakennetaan. Karttatason on oltava kohdepalvelu, jota voi muokata ja jolla on kohderyhmää vastaavat jakamisoikeudet.",
      detailsTabText: "Alla olevia Lomakkeen tiedot -ruutuja käyttämällä voit mukauttaa otsikon, lisätä mukautetun logon ja antaa lyhyen GeoForm-kohderyhmän kuvauksen. Voit lisätä kuvaukseen linkkejä muihin resursseihin ja yhteystietoihin sekä osoittaa kohderyhmällesi Web-karttasovelluksen, joka sisältää kaikki GeoForm-lomakkeella kerätyt tiedot.",
      fieldsTabText: "Tässä voit valita, mitkä kentät GeoForm-kohderyhmäsi näkee, muokata heidän näkemiään tunnustekstejä ja lisätä lyhyen kuvauksen, joka auttaa tietojen syöttämisessä.",
      styleTabText: "Voit määrittää GeoForm-tyylisi käyttämällä alla olevia teemoja sen mukaan, mitä haluat.",
      publishTabText: "Jos olet saanut valmiiksi GeoForm-mallisi mukautuksen, tallenna sovellus ja ala jakaa sitä kohderyhmäsi kanssa. Voit palata tähän muodostusohjelmaan milloin tahansa ja jatkaa sen mukautusta palautteen perusteella.",
      headerSizeLabel: "Ylätunnisteen koko",
      smallHeader: "Käytä pientä ylätunnistetta",
      bigHeader: "Käytä suurta ylätunnistetta",
      pushpinText: "Karttaneula",
      doneButtonText: "Tallenna ja lopeta",
      fieldTabPlaceHolderHeaderText: "Vihje (valinnainen)",
      enableAttachmentLabelText: "${openStrong}Ota liitteet käyttöön${closeStrong}",
      enableAttachmentLabelHint: "Voit ottaa liitteet käyttöön tai poistaa ne käytöstä tässä",
      attachmentIsRequiredLabelText: "${openStrong}Liite on pakollinen${closeStrong}",
      attachmentIsRequiredLabelHint: "Käyttäjiltä voi tarvittaessa vaatia liitteen määritystä.",
      attachmentLabelText: "Liite-painikkeen tunnusteksti",
      attachmentLabelHint: "Tämä teksti näkyy Liite-painikkeen vieressä. Tähän kohtaan voit lisätä kuvauksen liitettävistä tiedoista (valokuva, video, dokumentti jne.), pyytämästäsi tiedostomuodosta (.jpeg, .png, .docx, .pdf jne.) tai kirjoittaa muita lisäohjeita.",
      attachmentDescription: "Liitteen kuvaus",
      attachmentHint: "Voit tarvittaessa antaa liitteen lisäohjeita tässä.",
      jumbotronDescription: "Käytä lomakkeessa suurta tai pientä ylätunnistetta. Suuresta ylätunnisteesta voi olla hyötyä sovelluksen käyttötarkoituksen kuvaamisessa, mutta se vie enemmän tilaa näytöllä.",
      shareGeoformText: "Jaa GeoForm",
      shareDescription: "Jakamisruudun ansiosta kohderyhmän on helppo jakaa GeoForm muiden kollegojen kanssa lähetyksen jälkeen - se voidaan poistaa käytöstä milloin tahansa.",
      defaultMapExtent: "Kartan oletuslaajuus",
      defaultMapExtentDescription: "Lähettämisen jälkeen kartta palautuu Web-kartassasi oletuslaajuuteen - se voidaan poistaa käytöstä milloin tahansa.",
      pushpinOptionsDescription: "Valitse tarjotuista vaihtoehdoista karttaneulan väri, joka erottuu hyvin kartan symboleista ja helpottaa lähetyksen sijoittamista karttaan",
      selectLocationText: "Sijainnin valintaperuste",
      myLocationText: "Oma sijainti",
      searchText: "Etsi",
      coordinatesText: "Pituus- ja leveysasteiden koordinaatit",
      usng: "USNG-koordinaatit",
      mgrs: "MGRS-koordinaatit",
      utm: "UTM-koordinaatit",
      selectLocationSDescription: "Antaa käyttäjille mahdollisuuden valita sijainnin eri menetelmillä.",
      dragTooltipText: "Vedä kenttä kohtaan, jossa haluat sen näkyvän",
      showHideLayerText: "Näytä karttataso",
      showHideLayerHelpText: "Voit näyttää tai piilottaa karttatason määrittämällä GeoForm-lomakkeen. Tämä asetus koskee vain yhden karttatason asennusta.",
      labelHelpMessage: "Tunnusteksti",
      placeHolderHintMessage: "Vihjeteksti",
      placeHolderHelpMessage: "Ohjeteksti",
      selectTextOptionValue: "Suodatuksen valinta",
      disableLogo: "Poista logo käytöstä",
      disableLogoDescription: "Voit näyttää tai piilottaa lomakkeen ylätunnisteen logon määrittämällä GeoForm-mallin",
      locateOnLoadText: "Paikanna ladattaessa",
      locateOnLoadDescription: "Voit määrittää GeoForm-lomakkeen käyttämään nykyistä sijaintia sivua ladattaessa",
      selectLayerFieldTabText: "Valitse karttataso",
      allLayerSelectOptionText: "Kaikki",
      disableViewer: "Poista katseluohjelma käytöstä",
      disableViewerDescription: "Voit määrittää GeoForm-lomakkeen poistamaan katseluohjelman käytöstä tai ottamaan sen käyttöön",
      displayFieldHintText: "Valittu näyttökenttä näkyy katseluohjelmatilassa otsikkokenttänä"
    },
    viewer: {
      geocoderCancelText: "Peruuta",
      viewReportsTabText: "Lähetykset",
      viewLegendTabText: "Selite",
      viewAboutusTabText: "Tietoja",
      viewMapTabText: "Kartta",
      sortHeaderText: "Lajitteluperuste:",
      btnSubmitReportText: "Lähetä rapotti",
      geocoderPlaceholderText: "Postinumero, kaupunki jne.",
      noSearchResult: "Tulosta ei löytynyt",
      recordsTabTooltip: "Näytä lähetykset",
      legendTabTooltip: "Selite",
      aboutUsTabTooltip: "Tietoja meistä",
      mapTabTooltip: "Kartta",
      appLoadingFailedMessage: "Katseluohjelmatila ei ole käytettävissä",
      btnDescendingText: "Laskeva",
      btnAscendingText: "Nouseva",
      geometryUnavailableErrorMessage: "Kohteen geometriaa ei löydy",
      infoPopupOffErrorMessage: "InfoPopup on poissa käytöstä",
      btnLoadMoreText: "Lataa lisää",
      unavailableTitleText: "Nimetön",
      unavailableConfigMessage: "Määritystiedoston lataus ei onnistu"
    }
  })
);