define(
     ({
        map: {
            error: "Karttaa ei voi luoda"
        },
        onlineStatus: {
            offline: "Työskentelet tällä hetkellä offline-tilassa. Lomakkeiden lähetykset tallennetaan paikallisesti, kunnes palvelinyhteys voidaan muodostaa.",
            reconnecting: "Muodostetaan yhteyttä uudelleen&hellip;",
            pending: "${total} odottavaa muokkausta lähetetään, kun verkkoyhteys on luotu uudelleen."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Organisaationi",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Oma sisältö",
                    favoritesLabel: "Omat suosikit"
                },
                title: "Valitse Web-kartta",
                searchTitle: "Etsi",
                ok: "OK",
                cancel: "Peruuta",
                placeholder: "Anna hakuehto"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Organisaationi",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Oma sisältö",
                    favoritesLabel: "Omat suosikit"
                },
                title: "Valitse ryhmä",
                searchTitle: "Etsi",
                ok: "OK",
                cancel: "Peruuta",
                placeholder: "Anna hakuehto"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Pohjois",
            utm_easting: "Itäinen",
            utm_zone_number: "Vyöhykkeen numero",
            geoFormGeneralTabText: "1. Anna tiedot",
            locationInformationText: "2. Valitse sijainti",
            submitInformationText: "3. Täytä lomake",
            submitInstructions: "Lisää nämä tiedot karttaan.",
            myLocationText: "Nykyinen sijainti",
            locationDescription: "Määritä syötteen sijainti käyttämällä jotain seuraavista vaihtoehdoista tai napsauttamalla/ napauttamalla karttaa.",
            addressText: "Etsi",
            geographic: "Lev/pit",
            locationTabText: "Sijainti",
            locationPopupTitle: "Sijainti",
            submitButtonText: "Lähetä syöte",
            submitButtonTextLoading: "Lähetetään&hellip;",
            formValidationMessageAlertText: "Seuraavat kentät ovat pakollisia:",
            selectLocation: "Valitse ${openLink}location${closeLink} lähetystä varten.",
            emptylatitudeAlertMessage: "Anna koordinaatti: ${openLink}latitude${closeLink}.",
            emptylongitudeAlertMessage: "Anna koordinaatti: ${openLink}longitude${closeLink}.",
            shareUserTitleMessage: "Kiitos osallistumisestasi!",
            entrySubmitted: "Syöte on lähetetty karttaan.",
            shareThisForm: "Jaa tämä lomake",
            shareUserTextMessage: "Pyydä muita käyttämään lisäyksiin seuraavia valintoja.",
            addAttachmentFailedMessage: "Ei voi lisätä liitettä karttatasoon",
            addFeatureFailedMessage: "Ei voi lisätä kohdetta karttatasoon",
            noLayerConfiguredMessage: "Oho! Täällä ei ole mitään nähtävää. Jotta voit alkaa kerätä lomakkeen lähetyksiä, määritä tämä GeoForm ja valitse käytettäväksi muokattava kohdepalvelun karttataso.",
            placeholderLatitude: "Leveysaste (Y)",
            placeholderLongitude: "Pituusaste (X)",
            latitude: "Leveysaste",
            longitude: "Pituusaste",
            findMyLocation: "Paikanna minut",
            finding: "Paikannetaan&hellip;",
            backToTop: "Alkuun",
            addressSearchText: "Lähetyksesi tulee näkyviin tähän. Voit korjata sijainnin vetämällä nastaa.",
            shareModalFormText: "Lomakkeen linkki",
            close: "Sulje",
            locationNotFound: "Sijaintia ei löytynyt.",
            setLocation: "Määritä sijainti",
            find: "Etsi osoite tai paikka",
            attachment: "Liite",
            toggleDropdown: "Vaihda luetteloiden välillä",
            invalidLatLong: "Anna kelvolliset koordinaatit: ${latLink}latitude${closeLink} ja ${lngLink}longitude${closeLink}.",
            invalidUTM: "Anna kelvolliset ${openLink}UTM${closeLink}-koordinaatit.",
            invalidUSNG: "Anna kelvolliset ${openLink}USNG${closeLink}-koordinaatit.",
            invalidMGRS: "Anna kelvolliset ${openLink}MGRS${closeLink}-koordinaatit.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Valitse&hellip;",
            applyEditsFailedMessage: "Syötettä ei voi lähettää. Yritä uudelleen.",
            requiredFields: "Ilmeni virheitä. Korjaa ne alla.",
            requiredField: "(pakollinen)",
            error: "Virhe",
            textRangeHintMessage: "${openStrong}Vihje:${closeStrong} Vähimmäisarvo ${minValue} ja enimmäisarvo ${maxValue}",
            dateRangeHintMessage: "${openStrong}Vihje:${closeStrong} aikaisin ${minValue} ja myöhäisin päivämäärä ${maxValue}"
        },
        builder: {
            invalidUser: "Sinulla ei ole oikeuksia tarkastella tätä kohdetta",
            invalidWebmapSelectionAlert: "Valittu Web-kartta ei sisällä kelvollista käytettävää karttatasoa. Jatka lisäämällä muokattava kohdekarttataso Web-karttaasi.",
            invalidWebmapSelectionAlert2: "Lisätietoja on kohdassa ${openLink}Mikä on kohdepalvelu?${closeLink}",
            selectFieldsText: "Valitse lomakekentät",
            selectThemeText: "Valitse lomaketeema",
            webmapText: "Web-kartta",
            layerText: "Karttataso",
            detailsText: "Yksityiskohdat",
            fieldsText: "Kentät",
            styleText: "Tyyli",
            optionText: "Valinnat",
            previewText: "Esikatselu",
            publishText: "Julkaise",
            optionsApplicationText: "Valinnat",
            titleText: "Muodostusohjelma",
            descriptionText: "GeoForm on määritettävissä oleva mallipohja, joka on tarkoitettu ${link1}kohdepalvelun${closeLink} aineiston lomakepohjaiseen muokkaukseen. Tällä sovelluksella käyttäjät voivat syöttää tietoja lomakkeen kautta kartan ponnahdusikkunan sijaan ja hyödyntää samalla ${link2}Web-kartan${closeLink} ja muokattavien kohdepalvelujen kätevyyttä ja tehoa. Voit mukauttaa GeoForm-mallipohjaa ja ottaa sen käyttöön seuraavia ohjeita noudattamalla.",
            btnPreviousText: "Edellinen",
            btnNextText: "Seuraava",
            webmapTabTitleText: "Valitse Web-kartta",
            viewWebmap: "Näytä Web-kartta",
            btnSelectWebmapText: "Valitse Web-kartta",
            btnSelectWebmapTextLoading: "Lataa&hellip;",
            layerTabTitleText: "Valitse muokattava karttataso",
            selectLayerLabelText: "Karttataso",
            selectLayerDefaultOptionText: "Valitse karttataso",
            detailsTabTitleText: "Lomakkeen tiedot",
            detailTitleLabelText: "Otsikko",
            detailLogoLabelText: "Logokuva",
            descriptionLabelText: "Ohjeteksti (valinnainen)",
            fieldTabFieldHeaderText: "Kenttä",
            fieldTabLabelHeaderText: "Tunnusteksti",
            fieldTabDisplayTypeHeaderText: "Näytä muodossa",
            selectMenuOption: "Valitse valikko",
            selectRadioOption: "Valintanappi",
            selectTextOption: "Teksti",
            selectCheckboxOption: "Valintaruutu",
            selectMailOption: "Sähköposti",
            selectUrlOption: "URL",
            selectTextAreaOption: "Tekstialue",
            previewApplicationText: "Esikatsele sovellus",
            saveApplicationText: "Tallenna sovellus",
            saveText: "Tallenna",
            toggleNavigationText: "Käytä siirtymistä",
            formPlaceholderText: "Oma lomake",
            shareBuilderInProgressTitleMessage: "GeoForm-mallin julkaisu",
            shareBuilderProgressBarMessage: "Odota&hellip;",
            shareBuilderTitleMessage: "Kohteen tallennus onnistui",
            shareBuilderTextMessage: "Voit alkaa kerätä tietoja jakamalla ne muiden kanssa",
            shareModalFormText: "Lomakkeen linkki",
            shareBuilderSuccess: "GeoForm-mallisi on päivitetty ja julkaistu!",
            geoformTitleText: "GeoForm",
            layerTabText: "Tämä on karttataso, jonka perusteella GeoForm rakennetaan. Karttatason on oltava kohdepalvelu, jota voi muokata ja jolla on kohderyhmää vastaavat jakamisoikeudet.",
            detailsTabText: "Alla olevia Lomakkeen tiedot -ruutuja käyttämällä voit mukauttaa otsikon, lisätä mukautetun logon ja antaa lyhyen GeoForm-kohderyhmän kuvauksen. Voit lisätä kuvaukseen linkkejä muihin resursseihin ja yhteystietoihin sekä osoittaa kohderyhmällesi Web-karttasovelluksen, joka sisältää kaikki GeoForm-lomakkeella kerätyt tiedot.",
            fieldsTabText: "Tässä voit valita, mitkä kentät GeoForm-kohderyhmäsi näkee, muokata heidän näkemiään tunnustekstejä ja lisätä lyhyen kuvauksen, joka auttaa tietojen syöttämisessä.",
            styleTabText: "Voit määrittää GeoForm-tyylisi käyttämällä alla olevia teemoja sen mukaan, mitä haluat.",
            publishTabText: "Jos olet saanut valmiiksi GeoForm-mallisi mukautuksen, tallenna sovellus ja ala jakaa sitä kohderyhmäsi kanssa. Voit palata tähän muodostusohjelmaan milloin tahansa ja jatkaa sen mukautusta palautteen perusteella.",
            smallHeader: "Käytä pientä ylätunnistetta",
            pushpinText: "Karttaneula",
            doneButtonText: "Näytä sovelluskohde",
            fieldTabPlaceHolderHeaderText: "Vihje (valinnainen)",
            attachmentLabelText: "Liitteen tunnusteksti",
            attachmentLabelHint: "Kerro käyttäjille liitettävän tiedoston tyyppi.",
            attachmentDescription: "Liitteen kuvaus",
            attachmentHint: "Voit tarvittaessa antaa liitteen lisäohjeita tässä.",
            jumbotronDescription: "Bootstrap Jumbotronin avulla määritetään sovelluksen tarkoitus. Se voidaan poistaa käytöstä milloin tahansa.",
            shareGeoformText: "Jaa GeoForm",
            shareDescription: "Jakamisruudun ansiosta kohderyhmän on helppo jakaa GeoForm muiden avustajien kanssa lähetyksen jälkeen - se voidaan poistaa käytöstä milloin tahansa.",
            defaultMapExtent: "Kartan oletuslaajuus",
            defaultMapExtentDescription: "Lähettämisen jälkeen kartta palautuu Web-kartassasi oletuslaajuuteen - se voidaan poistaa käytöstä milloin tahansa.",
            pushpinOptionsDescription: "Valitse tarjotuista vaihtoehdoista karttaneulan väri, joka erottuu hyvin kartan symboleista ja helpottaa lähetyksen sijoittamista karttaan",
            selectLocationText: "Sijainnin valintaperuste",
            myLocationText: "Oma sijainti",
            searchText: "Etsi",
            coordinatesText: "Pituus- ja leveysasteiden koordinaatit",
            usng: "USNG-koordinaatit",
            mgrs: "MGRS-koordinaatit",
            utm: "UTM-koordinaatit",
            selectLocationSDescription: "Antaa käyttäjille mahdollisuuden valita sijainnin eri menetelmillä."
        }
    })
);