define(
     ({
        map: {
            error: "Kaardi loomine ebaõnnestus"
        },
        onlineStatus: {
            offline: "Töötate praegu võrguühenduseta režiimis. Esitatud vormid salvestatakse kohalikult, kuni serveriga luuakse ühendus.",
            reconnecting: "Ühenduse taastamine&hellip;",
            pending: "${total} ootel kutse(t) edastatakse võrguühenduse taastamisel."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Minu organisatsioon",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Minu sisu",
                    favoritesLabel: "Minu lemmikud"
                },
                title: "Vali veebikaart",
                searchTitle: "Otsi",
                ok: "Ok",
                cancel: "Tühista",
                placeholder: "Sisesta otsingutingimus"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Minu organisatsioon",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Minu sisu",
                    favoritesLabel: "Minu lemmikud"
                },
                title: "Vali grupp",
                searchTitle: "Otsi",
                ok: "Ok",
                cancel: "Tühista",
                placeholder: "Sisesta otsingutingimus"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Y-koordinaat",
            utm_easting: "X-koordinaat",
            utm_zone_number: "Tsooni number",
            geoFormGeneralTabText: "1. Sisestage teave",
            locationInformationText: "2. Valige asukoht",
            submitInformationText: "3. Täitke vorm",
            submitInstructions: "Lisage see teave kaardile.",
            myLocationText: "Š_Current Location_ä",
            locationDescription: "Š_Specify the location for this entry by clicking/tapping the map or by using one of the following options._ä",
            addressText: "Otsi",
            geographic: "Š_Lat/Lon_ä",
            locationTabText: "Asukoht",
            locationPopupTitle: "Š_Location_ä",
            submitButtonText: "Š_Submit Entry_ä",
            submitButtonTextLoading: "Edastamine&hellip;",
            formValidationMessageAlertText: "Järgmised väljad on kohustuslikud:",
            selectLocation: "Valige oma edastuse ${openLink}asukoht${closeLink}.",
            emptylatitudeAlertMessage: "Sisestage ${openLink}laiuse${closeLink} koordinaat.",
            emptylongitudeAlertMessage: "Sisestage ${openLink}pikkuse${closeLink} koordinaat.",
            shareUserTitleMessage: "Täname panuse eest!",
            entrySubmitted: "Š_Your entry has been submitted to the map._ä",
            shareThisForm: "Š_Share This Form_ä",
            shareUserTextMessage: "Š_Tell others to contribute using the following options._ä",
            addAttachmentFailedMessage: "Manuse lisamine kihile ebaõnnestus",
            addFeatureFailedMessage: "Objekti lisamine kihile ebaõnnestus",
            noLayerConfiguredMessage: "Oih! Siin ei ole midagi. Vormi edastuste kogumiseks seadistage see GeoForm ja valige muudetav objektiteenus, mida kasutada.",
            placeholderLatitude: "Laiuskraad (Y)",
            placeholderLongitude: "Pikkuskraad (X)",
            latitude: "Laiuskraad",
            longitude: "Pikkuskraad",
            findMyLocation: "Š_Locate Me_ä",
            finding: "Asukoha määramine&hellip;",
            backToTop: "Tagasi algusse",
            addressSearchText: "Teie edastus kuvatakse siin. Asukoha korrigeerimiseks lohistage nõela.",
            shareModalFormText: "Vormi link",
            close: "Sulge",
            locationNotFound: "Asukohta ei leitud.",
            setLocation: "Š_Set Location_ä",
            find: "Š_Find address or place_ä",
            attachment: "Manus",
            toggleDropdown: "Vaheta rippmenüüd",
            invalidLatLong: "Sisestage õiged ${latLink}laiuse${closeLink} ja ${lngLink}pikkuse${closeLink} koordinaadid.",
            invalidUTM: "Sisestage õiged ${openLink}UTM${closeLink}-koordinaadid.",
            invalidUSNG: "Sisestage õiged ${openLink}USNG${closeLink}-koordinaadid.",
            invalidMGRS: "Sisestage õiged ${openLink}MGRS${closeLink}-koordinaadid.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Vali&hellip;",
            applyEditsFailedMessage: "Kahjuks ei saa teie kirjet edastada. Proovige uuesti.",
            requiredFields: "Esines mõningaid vigu. Parandage need allpool.",
            requiredField: "Š_(required)_ä",
            error: "Viga",
            textRangeHintMessage: "Š_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_ä",
            dateRangeHintMessage: "Š_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_ä"
        },
        builder: {
            invalidUser: "Š_Sorry, you dont have permission to view this item_ä",
            invalidWebmapSelectionAlert: "Š_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._ä",
            invalidWebmapSelectionAlert2: "Š_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_ä",
            selectFieldsText: "Š_Select Form Fields_ä",
            selectThemeText: "Š_Select Form Theme_ä",
            webmapText: "Š_Webmap_ä",
            layerText: "Š_Layer_ä",
            detailsText: "Š_Details_ä",
            fieldsText: "Š_Fields_ä",
            styleText: "Š_Style_ä",
            optionText: "Š_Options_ä",
            previewText: "Š_Preview_ä",
            publishText: "Š_Publish_ä",
            optionsApplicationText: "Š_Options_ä",
            titleText: "Š_Builder_ä",
            descriptionText: "Š_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a map’s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm._ä",
            btnPreviousText: "Š_Previous_ä",
            btnNextText: "Š_Next_ä",
            webmapTabTitleText: "Š_Select a Webmap_ä",
            viewWebmap: "Š_View webmap_ä",
            btnSelectWebmapText: "Š_Choose Webmap_ä",
            btnSelectWebmapTextLoading: "Š_Loading&hellip;_ä",
            layerTabTitleText: "Š_Select Editable Layer_ä",
            selectLayerLabelText: "Š_Layer_ä",
            selectLayerDefaultOptionText: "Š_Select Layer_ä",
            detailsTabTitleText: "Š_Form Details_ä",
            detailTitleLabelText: "Š_Title_ä",
            detailLogoLabelText: "Š_Logo Image_ä",
            descriptionLabelText: "Š_Help Text (optional)_ä",
            fieldTabFieldHeaderText: "Š_Field_ä",
            fieldTabLabelHeaderText: "Š_Label_ä",
            fieldTabDisplayTypeHeaderText: "Š_Display As_ä",
            selectMenuOption: "Š_Select Menu_ä",
            selectRadioOption: "Š_Radio Button_ä",
            selectTextOption: "Š_Text_ä",
            selectCheckboxOption: "Š_Checkbox_ä",
            selectMailOption: "Š_Email_ä",
            selectUrlOption: "Š_URL_ä",
            selectTextAreaOption: "Š_Textarea_ä",
            previewApplicationText: "Š_Preview Application_ä",
            saveApplicationText: "Š_Save Application_ä",
            saveText: "Š_Save_ä",
            toggleNavigationText: "Š_Toggle navigation_ä",
            formPlaceholderText: "Š_My Form_ä",
            shareBuilderInProgressTitleMessage: "Š_Publishing GeoForm_ä",
            shareBuilderProgressBarMessage: "Š_Please Wait&hellip;_ä",
            shareBuilderTitleMessage: "Š_Success! Item saved_ä",
            shareBuilderTextMessage: "Š_You can start collecting information by sharing with others_ä",
            shareModalFormText: "Š_Form Link_ä",
            shareBuilderSuccess: "Š_Your GeoForm has been updated & published!_ä",
            geoformTitleText: "Š_Geo Form_ä",
            layerTabText: "Š_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._ä",
            detailsTabText: "Š_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm._ä",
            fieldsTabText: "Š_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._ä",
            styleTabText: "Š_Style your GeoForm using the themes below based on your preference._ä",
            publishTabText: "Š_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._ä",
            smallHeader: "Š_Use Small Header_ä",
            pushpinText: "Š_Push pin_ä",
            doneButtonText: "Š_View Application Item_ä",
            fieldTabPlaceHolderHeaderText: "Š_Hint (optional)_ä",
            attachmentLabelText: "Š_Attchment Label_ä",
            attachmentLabelHint: "Š_Tell users what type of file to attach._ä",
            attachmentDescription: "Š_Attachment Description_ä",
            attachmentHint: "Š_If necessary, you can provide additional attachment instructions here._ä",
            jumbotronDescription: "Š_The Bootstrap Jumbotron makes it easy to define the purpose of your application. This can be disabled at any time._ä",
            shareGeoformText: "Š_Share Geoform_ä",
            shareDescription: "Š_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time._ä",
            defaultMapExtent: "Š_Default Map Extent_ä",
            defaultMapExtentDescription: "Š_The map will reset to the default extent in your web map after submission - this can be disabled at any time._ä",
            pushpinOptionsDescription: "Š_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_ä",
            selectLocationText: "Š_Select Location By_ä",
            myLocationText: "Š_My Location_ä",
            searchText: "Š_Search_ä",
            coordinatesText: "Š_Latitude & Longitude Coordinates_ä",
            usng: "Š_USNG Coordinates_ä",
            mgrs: "Š_MGRS Coordinates_ä",
            utm: "Š_UTM Coordinates_ä",
            selectLocationSDescription: "Š_Allow users to select a location using these methods._ä"
        }
    })
);