define(
     ({
        map: {
            error: "无法创建地图"
        },
        onlineStatus: {
            offline: "您目前正在离线工作。连接到服务器之前，提交的表单将保存在本地。",
            reconnecting: "重新连接&hellip;",
            pending: "重新建立网络连接时将提交 ${total} 个挂起的编辑内容。"
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "我的组织",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "我的内容",
                    favoritesLabel: "我的收藏夹"
                },
                title: "选择 Web 地图",
                searchTitle: "搜索",
                ok: "确定",
                cancel: "取消",
                placeholder: "输入搜索词"
            },
            groupdlg: {
                items: {
                    organizationLabel: "我的组织",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "我的内容",
                    favoritesLabel: "我的收藏夹"
                },
                title: "选择组",
                searchTitle: "搜索",
                ok: "确定",
                cancel: "取消",
                placeholder: "输入搜索词"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "北移",
            utm_easting: "东移",
            utm_zone_number: "区域编号",
            geoFormGeneralTabText: "1. 输入信息",
            locationInformationText: "2. 选择位置",
            submitInformationText: "3. 完成表单",
            submitInstructions: "将此信息添加到地图。",
            myLocationText: "当前位置",
            locationDescription: "通过单击/点击地图或使用以下选项之一来指定此输入的位置。",
            addressText: "搜索",
            geographic: "经纬度",
            locationTabText: "位置",
            locationPopupTitle: "位置",
            submitButtonText: "提交输入内容",
            submitButtonTextLoading: "正在提交&hellip;",
            formValidationMessageAlertText: "以下为必填字段:",
            selectLocation: "请选择用于提交的${openLink}位置${closeLink}。",
            emptylatitudeAlertMessage: "请输入${openLink}纬度${closeLink}坐标。",
            emptylongitudeAlertMessage: "请输入${openLink}经度${closeLink}坐标。",
            shareUserTitleMessage: "感谢您所做的贡献!",
            entrySubmitted: "您的输入已提交至地图。",
            shareThisForm: "共享此表",
            shareUserTextMessage: "通知其他用户继续使用以下选项。",
            addAttachmentFailedMessage: "无法向图层添加附件",
            addFeatureFailedMessage: "无法向图层添加要素",
            noLayerConfiguredMessage: "加载或查找可编辑要素图层时出错。为显示格式和开始采集提交内容，请将可编辑的要素图层添加到 Web 地图中。",
            placeholderLatitude: "纬度 (Y)",
            placeholderLongitude: "经度 (X)",
            latitude: "纬度",
            longitude: "经度",
            findMyLocation: "查找我的位置",
            finding: "正在定位&hellip;",
            backToTop: "返回顶部",
            addressSearchText: "将在此处显示您的提交。您可以拖动图钉以更正位置。",
            shareModalFormText: "表单链接",
            close: "关闭",
            locationNotFound: "无法找到位置。",
            setLocation: "设置位置",
            find: "查找地址或地点",
            attachment: "附件",
            toggleDropdown: "切换下拉菜单",
            invalidLatLong: "请输入有效的${latLink}纬度${closeLink}和${lngLink}经度${closeLink}坐标。",
            invalidUTM: "请输入有效的 ${openLink}UTM${closeLink} 坐标。",
            invalidUSNG: "请输入有效的 ${openLink}USNG${closeLink} 坐标。",
            invalidMGRS: "请输入有效的 ${openLink}MGRS${closeLink} 坐标。",
            geoformTitleText: "GeoForm",
            domainDefaultText: "选择&hellip;",
            applyEditsFailedMessage: "抱歉，无法提交您的输入。请重试。",
            requiredFields: "存在一些错误。请在下方进行更正。",
            requiredField: "(必填项)",
            error: "错误",
            textRangeHintMessage: "${openStrong}提示:${closeStrong} 最小值 ${minValue} 和最大值 ${maxValue}",
            dateRangeHintMessage: "${openStrong}提示:${closeStrong} 最小日期 ${minValue} 和最大日期 ${maxValue}"
        },
        builder: {
            invalidUser: "抱歉，您无权查看此项目",
            invalidWebmapSelectionAlert: "所选 web 地图未包含可以使用的有效图层。请向您的 web 地图中添加可编辑的要素图层以继续。",
            invalidWebmapSelectionAlert2: "有关详细信息，请参阅 ${openLink}什么是要素服务?${closeLink}",
            selectFieldsText: "选择表单字段",
            selectThemeText: "选择表单主题",
            webmapText: "Web 地图",
            layerText: "图层",
            detailsText: "详细信息",
            fieldsText: "字段",
            styleText: "样式",
            optionText: "选项",
            previewText: "预览",
            publishText: "发布",
            optionsApplicationText: "选项",
            titleText: "构建器",
            descriptionText: "GeoForm 是${link1}要素服务${closeLink}的基于表单的数据编辑的可配置模板。此应用程序允许用户在利用 ${link2}Web 地图${closeLink}和可编辑的要素服务时通过表单而不是地图的弹出窗口来输入数据。请使用以下步骤自定义并部署 GeoForm。",
            btnPreviousText: "上一步",
            btnNextText: "下一步",
            webmapTabTitleText: "选择 web 地图",
            viewWebmap: "查看 web 地图",
            btnSelectWebmapText: "选择 web 地图",
            btnSelectWebmapTextLoading: "正在加载&hellip;",
            layerTabTitleText: "选择可编辑图层",
            selectLayerLabelText: "图层",
            selectLayerDefaultOptionText: "选择图层",
            detailsTabTitleText: "表单详细信息",
            detailTitleLabelText: "标题",
            detailLogoLabelText: "徽标图像",
            descriptionLabelText: "帮助文本 (可选)",
            fieldTabFieldHeaderText: "字段",
            fieldTabLabelHeaderText: "标注",
            fieldTabDisplayTypeHeaderText: "显示为",
            selectMenuOption: "选择菜单",
            selectRadioOption: "单选按钮",
            selectTextOption: "文本",
            selectCheckboxOption: "复选框",
            selectMailOption: "电子邮件",
            selectUrlOption: "URL",
            selectTextAreaOption: "文本区",
            previewApplicationText: "预览应用程序",
            saveApplicationText: "保存应用程序",
            saveText: "保存",
            toggleNavigationText: "切换导航",
            formPlaceholderText: "我的表单",
            shareBuilderInProgressTitleMessage: "发布 GeoForm",
            shareBuilderProgressBarMessage: "请稍候&hellip;",
            shareBuilderTitleMessage: "成功! 项目已保存",
            shareBuilderTextMessage: "可通过与其他成员共享来启动收集信息",
            shareModalFormText: "表单链接",
            shareBuilderSuccess: "已更新并发布 GeoForm!",
            geoformTitleText: "地理表单",
            layerTabText: "这是创建 GeoForm 所基于的图层。该图层必须是为编辑并共享适于受众的权限而启用的要素服务。",
            detailsTabText: "使用下方的\“表单详细信息\”框自定义标题、添加自定义徽标并为 GeoForm 受众提供简短描述。您可以在描述中添加其他资源的链接和联系信息，甚至可以将您的受众指向包含所有通过 GeoForm 所收集数据的 Web 制图应用程序。",
            fieldsTabText: "您可以在此处选择对 GeoForm 受众可见的字段，编辑受众可见的标签并添加简短描述以帮助输入数据。",
            styleTabText: "根据首选项使用下方的专题设置 GeoForm 样式。",
            publishTabText: "如果完成了自定义 GeoForm，请保存应用程序并与受众共享。您可随时返回至此构建器并根据反馈继续进行自定义。",
            smallHeader: "使用小标题",
            pushpinText: "图钉",
            doneButtonText: "查看应用程序项目",
            fieldTabPlaceHolderHeaderText: "提示 (可选)",
            attachmentLabelText: "附件标注",
            attachmentLabelHint: "告诉用户附加哪种类型的文件。",
            attachmentDescription: "附件描述",
            attachmentHint: "如有必要，可在此处提供其他附件说明。",
            jumbotronDescription: "Bootstrap Jumbotron 可使您更轻松地定义应用程序的用途。该功能可随时禁用。",
            shareGeoformText: "共享 Geoform",
            shareDescription: "通过共享面板，受众可以在提交后与其他协作者轻松共享 GeoForm - 可随时禁用此功能。",
            defaultMapExtent: "默认地图范围",
            defaultMapExtentDescription: "地图在提交后将重置为 web 地图中的默认范围 - 可随时禁用此功能。",
            pushpinOptionsDescription: "可从多种地图图钉颜色中选择，该颜色应不同于地图符号系统颜色以帮助用户将其提交内容放在地图上",
            selectLocationText: "位置选择依据",
            myLocationText: "我的位置",
            searchText: "搜索",
            coordinatesText: "经纬度坐标",
            usng: "USNG 坐标",
            mgrs: "MGRS 坐标",
            utm: "UTM 坐标",
            selectLocationSDescription: "允许用户使用这些方法选择位置"
        }
    })
);