define(
   ({
    map: {
      error: "无法创建地图"
    },
    onlineStatus: {
      offline: "您目前正在离线工作。连接到服务器之前，提交的表单将保存在本地。",
      reconnecting: "正在重新连接&hellip;",
      pending: "重新建立网络连接时将提交 ${total} 个挂起的编辑内容。"
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "我的组织",
          onlineLabel: "ArcGIS Online",
          contentLabel: "我的内容",
          favoritesLabel: "我的收藏夹"
        },
        title: "选择 Web 地图",
        searchTitle: "搜索",
        ok: "确定",
        cancel: "取消",
        placeholder: "输入搜索词"
      },
      groupdlg: {
        items: {
          organizationLabel: "我的组织",
          onlineLabel: "ArcGIS Online",
          contentLabel: "我的内容",
          favoritesLabel: "我的收藏夹"
        },
        title: "选择群组",
        searchTitle: "搜索",
        ok: "确定",
        cancel: "取消",
        placeholder: "输入搜索词"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "此处是 GeoForm 链接"
      }
    },
    user: {
      mgrs: "MGRS",
      usng: "USNG",
      utm: "UTM",
      utm_northing: "北移",
      utm_easting: "东移",
      utm_zone_number: "区域编号",
      selectLayerTabText: "${formSection} 选择表单",
      geoFormGeneralTabText: "${formSection} 输入信息",
      locationInformationText: "${formSection} 选择位置",
      submitInformationText: "${formSection} 完成表单",
      submitInstructions: "将此信息添加到地图。",
      myLocationText: "当前位置",
      locationDescriptionForMoreThanOneOption: "通过单击/点击地图或使用以下任一选项来指定此条目的位置。",
      locationDescriptionForOneOption: "通过单击/点击地图或使用以下选项来指定此条目的位置。",
      locationDescriptionForNoOption: "通过单击/点击地图来指定此条目的位置。",
      addressText: "搜索",
      geographic: "经纬度",
      locationTabText: "位置",
      locationPopupTitle: "位置",
      submitButtonText: "提交输入内容",
      submitButtonTextLoading: "正在提交&hellip;",
      formValidationMessageAlertText: "以下为必填字段:",
      selectLocation: "请选择提交时所处的位置。",
      emptylatitudeAlertMessage: "请输入${openLink}纬度${closeLink}坐标。",
      emptylongitudeAlertMessage: "请输入${openLink}经度${closeLink}坐标。",
      shareUserTitleMessage: "感谢您所做的贡献!",
      entrySubmitted: "您的输入已提交至地图。",
      shareThisForm: "共享此表单",
      shareUserTextMessage: "使用以下选项告知其他用户贡献力量吧。",
      addAttachmentFailedMessage: "无法向图层添加附件",
      addFeatureFailedMessage: "无法向图层添加要素",
      noLayerConfiguredMessage: "加载或查找可编辑要素图层时出错。为显示表单并开始采集提交内容，请将可编辑的要素图层添加到 Web 地图中。",
      placeholderLatitude: "纬度(Y)",
      placeholderLongitude: "经度(X)",
      latitude: "纬度",
      longitude: "经度",
      findMyLocation: "我的位置",
      finding: "正在定位&hellip;",
      backToTop: "返回顶部",
      addressSearchText: "将在此处显示您的提交。您可以拖动图钉以更正位置。",
      shareModalFormText: "表单链接",
      close: "关闭",
      locationNotFound: "位置查找失败。",
      setLocation: "设置位置",
      find: "查找地址或地点",
      attachment: "附件",
      toggleDropdown: "切换下拉菜单",
      invalidString: "请输入有效值。",
      invalidSmallNumber: "请输入有效${openStrong}整数${closeStrong}值，范围在 -32768 到 32767 之间。",
      invalidNumber: "请输入有效${openStrong}整数${closeStrong}值，范围在 -2147483648 到 2147483647 之间。",
      invalidFloat: "请输入有效${openStrong}浮点${closeStrong}值。",
      invalidDouble: "请输入有效${openStrong}双精度${closeStrong}值。",
      invalidLatLong: "请输入有效的经纬度坐标。",
      invalidUTM: "请输入有效的 UTM 坐标。",
      invalidUSNG: "请输入有效的 USNG 坐标。",
      invalidMGRS: "请输入有效的 MGRS 坐标。",
      geoformTitleText: "GeoForm",
      domainDefaultText: "选择&hellip;",
      applyEditsFailedMessage: "抱歉，无法提交您的输入。请重试。",
      requiredFields: "存在一些错误。请在下方进行更正。",
      requiredField: "(必填)",
      error: "错误",
      textRangeHintMessage: "${openStrong}提示:${closeStrong} 最小值 ${minValue} 和最大值 ${maxValue}",
      dateRangeHintMessage: "${openStrong}提示:${closeStrong} 最小日期 ${minValue} 和最大日期 ${maxValue}",
      remainingCharactersHintMessage: "剩余 ${value} 个字符",
      mapFullScreen: "全屏",
      mapRestore: "恢复",
      filterSelectEmptyText: "选择",
      invalidLayerMessage: "表单图层不存在。请配置应用程序并设置该图层。",
      selectedLayerText: "全部",
      fileUploadStatus: "文件上传状态",
      uploadingBadge: "&nbsp;正在上传&hellip;",
      successBadge: "&nbsp;已上传",
      retryBadge: "重试",
      errorBadge: "上传期间出错&nbsp;&nbsp;&nbsp;",
      fileTooLargeError: "文件过大，无法附加",
      exceededFileCountError: "超出允许的最大附件数",
      selectFileTitle: "选择一个文件",
      btnViewSubmissions: "查看提交内容",
      dateFormat: "试_MM/DD/YYYY h:mm a_验"
    },
    builder: {
      invalidUser: "抱歉，您无权查看此项目",
      invalidWebmapSelectionAlert: "所选 web 地图未包含可以使用的有效图层。请向您的 web 地图中添加可编辑的要素图层以继续。",
      invalidWebmapSelectionAlert2: "有关详细信息，请参阅${openLink}什么是要素服务?${closeLink}",
      selectFieldsText: "选择表单字段",
      selectThemeText: "选择表单主题",
      webmapText: "Web 地图",
      layerText: "图层",
      detailsText: "详细信息",
      fieldsText: "字段",
      styleText: "样式",
      optionText: "选项",
      previewText: "预览",
      publishText: "发布",
      optionsApplicationText: "选项",
      titleText: "构建器",
      descriptionText: "GeoForm 是一种可配置模板，可用于编辑${link1}要素服务${closeLink}的基于表单的数据。用户可通过该应用程序使用表单输入数据(而非通过地图的弹出窗口)，同时使用 ${link2}Web 地图${closeLink}的强大功能和可编辑要素服务。请使用以下步骤自定义并部署 GeoForm。",
      btnPreviousText: "上一页",
      btnNextText: "下一页",
      webmapTabTitleText: "选择 web 地图",
      viewWebmap: "查看 web 地图",
      webmapDetailsText: "所选 web 地图为 ${webMapTitleLink}${webMapTitle}${closeLink}。要选择其他 Web 地图，请单击“选择 Web 地图”按钮",
      btnSelectWebmapText: "选择 web 地图",
      btnSelectWebmapTextLoading: "正在加载&hellip;",
      layerTabTitleText: "选择可编辑图层",
      selectLayerLabelText: "图层",
      selectLayerDefaultOptionText: "选择图层",
      defaultBasemap: "底图切换",
      secondaryBasemap: "默认底图",
      detailsTabTitleText: "表单详细信息",
      detailTitleLabelText: "标题",
      detailLogoLabelText: "徽标图像",
      descriptionLabelText: "表单说明和详细信息",
      fieldDescriptionLabelText: "帮助文本(可选)",
      fieldTabFieldHeaderText: "字段",
      fieldTabLabelHeaderText: "标注",
      fieldTabDisplayTypeHeaderText: "显示为",
      fieldTabOrderColumnText: "顺序",
      fieldTabVisibleColumnText: "已启用",
      displayFieldText: "显示字段",
      selectMenuOption: "选择菜单",
      selectRadioOption: "单选按钮",
      selectTextOption: "文本",
      selectDateOption: "日期选取器",
      selectRangeOption: "Touch-Spinner",
      selectCheckboxOption: "复选框",
      selectMailOption: "电子邮件",
      selectUrlOption: "URL",
      selectTextAreaOption: "文本区",
      previewApplicationText: "预览应用程序",
      saveApplicationText: "保存应用程序",
      saveText: "保存",
      toggleNavigationText: "切换导航",
      formPlaceholderText: "我的表单",
      shareBuilderInProgressTitleMessage: "发布 GeoForm",
      shareBuilderProgressBarMessage: "请稍候&hellip;",
      shareBuilderTitleMessage: "成功! 项目已保存",
      shareBuilderTextMessage: "可通过与其他成员共享来启动收集信息",
      shareModalFormText: "表单链接",
      shareBuilderSuccess: "已更新并发布 GeoForm!",
      geoformTitleText: "地理表单",
      layerTabText: "这是创建 GeoForm 所基于的图层。该图层必须是要素服务，且为受众启用了编辑权限。",
      detailsTabText: "使用下方的“表单详细信息”框自定义标题、添加自定义徽标并为 GeoForm 受众提供简短描述。您可以在描述中添加其他资源的链接和联系信息，甚至可以将您的受众指向包含所有通过 GeoForm 所收集数据的 Web 制图应用程序。",
      fieldsTabText: "您可以在此处选择对 GeoForm 受众可见的字段，编辑受众可见的标签并添加简短描述以帮助输入数据。",
      styleTabText: "根据首选项使用下方的专题设置 GeoForm 样式。",
      publishTabText: "如果完成了自定义 GeoForm，请保存应用程序并与受众共享。您可随时返回至此构建器并根据反馈继续进行自定义。",
      headerSizeLabel: "标题大小",
      smallHeader: "使用小标题",
      bigHeader: "使用大标题",
      pushpinText: "图钉",
      doneButtonText: "保存并退出",
      fieldTabPlaceHolderHeaderText: "提示(可选)",
      enableAttachmentLabelText: "${openStrong}启用附件${closeStrong}",
      enableAttachmentLabelHint: "可在此启用/禁用附件",
      attachmentIsRequiredLabelText: "${openStrong}所需附件${closeStrong}",
      attachmentIsRequiredLabelHint: "如有必要，可能会要求用户输入附件。",
      attachmentLabelText: "附件按钮标注",
      attachmentLabelHint: "此文本将显示在“附件”按钮旁边。可利用此空间来描述您希望受众按照您要求的文件格式(.jpeg、.png、.docx 和 .pdf 等等)附加的内容(照片、视频和文档等等)以及任何附加说明",
      attachmentDescription: "附件描述",
      attachmentHint: "如有必要，可在此处提供其他附件说明。",
      jumbotronDescription: "为表单使用大标题或小标题。大标题可帮助定义应用程序的目的，但会占用更多的屏幕空间",
      shareGeoformText: "共享 Geoform",
      shareDescription: "通过共享面板，受众可以在提交后与其他协作者轻松共享 GeoForm - 可随时禁用此功能。",
      defaultMapExtent: "默认地图范围",
      defaultMapExtentDescription: "地图在提交后将重置为 web 地图中的默认范围 - 可随时禁用此功能。",
      pushpinOptionsDescription: "可为地图图钉选择不同的颜色，该颜色应不同于地图符号系统颜色以帮助用户将其提交内容放在地图上",
      selectLocationText: "位置选择依据",
      myLocationText: "我的位置",
      searchText: "搜索",
      coordinatesText: "经纬度坐标",
      usng: "USNG 坐标",
      mgrs: "MGRS 坐标",
      utm: "UTM 坐标",
      selectLocationSDescription: "允许用户使用这些方法选择位置。",
      dragTooltipText: "将字段拖放到预期的显示位置",
      showHideLayerText: "显示图层",
      showHideLayerHelpText: "可配置 GeoForm 以显示/隐藏图层。此选项仅适用于单个图层配置。",
      labelHelpMessage: "标注",
      placeHolderHintMessage: "提示文本",
      placeHolderHelpMessage: "帮助文本",
      selectTextOptionValue: "过滤器选择",
      disableLogo: "禁用徽标",
      disableLogoDescription: "可配置 GeoForm 以在表单标题中显示/隐藏徽标",
      locateOnLoadText: "在加载中定位",
      locateOnLoadDescription: "可配置 GeoForm 以使用页面加载中的当前位置",
      selectLayerFieldTabText: "选择图层",
      allLayerSelectOptionText: "全部",
      disableViewer: "禁用查看器",
      disableViewerDescription: "可配置 GeoForm 以禁用/启用查看器",
      displayFieldHintText: "选择的显示字段将在查看器模式下显示为标题字段"
    },
    viewer: {
      geocoderCancelText: "取消",
      viewReportsTabText: "提交",
      viewLegendTabText: "图例",
      viewAboutusTabText: "关于",
      viewMapTabText: "地图",
      sortHeaderText: "排序方式:",
      btnSubmitReportText: "提交报告",
      geocoderPlaceholderText: "邮政编码、城市等",
      noSearchResult: "未找到结果",
      recordsTabTooltip: "查看提交内容",
      legendTabTooltip: "图例",
      aboutUsTabTooltip: "关于我们",
      mapTabTooltip: "地图",
      appLoadingFailedMessage: "查看器模式不可用",
      btnDescendingText: "降序",
      btnAscendingText: "升序",
      geometryUnavailableErrorMessage: "无法找到要素几何",
      infoPopupOffErrorMessage: "信息弹出窗口已关闭",
      btnLoadMoreText: "加载更多",
      unavailableTitleText: "无标题",
      unavailableConfigMessage: "无法加载配置"
    }
  })
);