define(
   ({
    map: {
      error: "Impossible de créer la carte"
    },
    onlineStatus: {
      offline: "Vous travaillez actuellement en mode hors connexion. Les envois de formulaires seront enregistrés localement jusqu\'à l\'établissement d\'une connexion au serveur.",
      reconnecting: "Reconnexion&hellip;",
      pending: "${total} modifications en attente seront envoyées lorsqu\'une connexion réseau sera rétablie."
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "Mon organisation",
          onlineLabel: "ArcGIS Online",
          contentLabel: "Mon contenu",
          favoritesLabel: "Mes favoris"
        },
        title: "Sélectionner une carte Web",
        searchTitle: "Rechercher",
        ok: "OK",
        cancel: "Annuler",
        placeholder: "Saisir un terme de recherche"
      },
      groupdlg: {
        items: {
          organizationLabel: "Mon organisation",
          onlineLabel: "ArcGIS Online",
          contentLabel: "Mon contenu",
          favoritesLabel: "Mes favoris"
        },
        title: "Sélectionner un groupe",
        searchTitle: "Rechercher",
        ok: "OK",
        cancel: "Annuler",
        placeholder: "Saisir un terme de recherche"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "Voici un lien vers un formulaire géographique"
      }
    },
    user: {
      all: "Tous",
      mgrs: "MGRS",
      usng: "USNG",
      utm: "UTM",
      utm_northing: "Ordonnée",
      utm_easting: "Abscisse",
      utm_zone_number: "Numéro de fuseau",
      selectLayerTabText: "${formSection} Sélectionner un formulaire",
      geoFormGeneralTabText: "${formSection} Saisir des informations",
      locationInformationText: "${formSection} Sélectionner un emplacement",
      submitInformationText: "${formSection} Remplir le formulaire",
      submitInstructions: "Ajoutez ces informations à la carte.",
      myLocationText: "Emplacement actuel",
      locationDescriptionForMoreThanOneOption: "Spécifiez l\'emplacement de cette entrée en cliquant/touchant la carte ou en utilisant l\'une des options suivantes.",
      locationDescriptionForOneOption: "Spécifiez l\'emplacement de cette entrée en cliquant/touchant la carte ou en utilisant l\'option suivante.",
      locationDescriptionForNoOption: "Spécifiez l\'emplacement de cette entrée en cliquant/touchant la carte.",
      addressText: "Rechercher",
      geographic: "Lat/Lon",
      locationTabText: "Emplacement",
      locationPopupTitle: "Emplacement",
      submitButtonText: "Envoyer une entrée",
      submitButtonTextLoading: "Envoi&hellip;",
      formValidationMessageAlertText: "Les champs suivants sont requis :",
      selectLocation: "Sélectionnez un emplacement pour votre envoi.",
      emptylatitudeAlertMessage: "Entrez une coordonnée de ${openLink}latitude${closeLink}.",
      emptylongitudeAlertMessage: "Entrez une coordonnée de ${openLink}longitude${closeLink}.",
      shareUserTitleMessage: "Merci de votre contribution !",
      entrySubmitted: "Votre entrée a été envoyée à la carte.",
      shareThisForm: "Partager ce formulaire",
      shareUserTextMessage: "Demandez aux autres utilisateurs d\'apporter leur contribution en utilisant les options suivantes.",
      addAttachmentFailedMessage: "Impossible d\'ajouter une pièce jointe à la couche",
      addFeatureFailedMessage: "Impossible d\'ajouter une entité à la couche",
      noLayerConfiguredMessage: "Une erreur est survenue lors du chargement ou de la recherche d\'une couche d\'entités modifiable. Pour afficher le formulaire et commencer à collecter les envois, ajoutez une couche d\'entités modifiable à la carte Web.",
      placeholderLatitude: "Latitude (Y)",
      placeholderLongitude: "Longitude (X)",
      latitude: "Latitude",
      longitude: "Longitude",
      findMyLocation: "Localiser mon emplacement",
      finding: "Localisation&hellip;",
      backToTop: "Haut",
      addressSearchText: "Votre envoi apparaîtra ici. Vous pouvez faire glisser l\'épingle pour corriger l\'emplacement.",
      shareModalFormText: "Lien du formulaire",
      close: "Fermer",
      locationNotFound: "L\'emplacement est introuvable.",
      setLocation: "Définir l\'emplacement",
      find: "Rechercher une adresse ou un lieu",
      attachment: "Pièce jointe",
      toggleDropdown: "Activer/Désactiver le menu déroulant",
      invalidString: "Entrez une valeur valide.",
      invalidSmallNumber: "Entrez une valeur ${openStrong}entière${closeStrong} valide comprise entre -32768 et 32767.",
      invalidNumber: "Entrez une valeur ${openStrong}entière${closeStrong} valide comprise entre -2147483648 et 2147483647.",
      invalidFloat: "Entrez une valeur ${openStrong}à virgule flottante${closeStrong} valide.",
      invalidDouble: "Entrez une valeur ${openStrong}double${closeStrong} valide.",
      invalidLatLong: "Entrez des coordonnées de latitude et de longitude valides.",
      invalidUTM: "Entrez des coordonnées UTM valides.",
      invalidUSNG: "Entrez des coordonnées USNG valides.",
      invalidMGRS: "Entrez des coordonnées MGRS valides.",
      geoformTitleText: "Formulaire géographique",
      domainDefaultText: "Sélectionner&hellip;",
      applyEditsFailedMessage: "Votre entrée ne peut pas être envoyée. Réessayez.",
      requiredFields: "Le champ suivant est obligatoire. Fournissez une entrée valide.",
      requiredField: "(requis)",
      error: "Erreur",
      textRangeHintMessage: "${openStrong}Astuce :${closeStrong} valeur minimale ${minValue} et valeur maximale ${maxValue}",
      dateRangeHintMessage: "${openStrong}Astuce :${closeStrong} date minimum ${minValue} et date maximum ${maxValue}",
      remainingCharactersHintMessage: "${value} caractères restants",
      mapFullScreen: "Plein écran",
      mapRestore: "Restaurer",
      filterSelectEmptyText: "Sélectionner",
      invalidLayerMessage: "La couche de formulaire n\'existe pas. Configurez l\'application et définissez la couche.",
      selectedLayerText: "Tout",
      fileUploadStatus: "Statut de chargement du fichier",
      uploadingBadge: "&nbsp;Chargement&hellip;",
      successBadge: "&nbsp;Chargé",
      retryBadge: "Réessayer",
      errorBadge: "Erreur de chargement&nbsp;&nbsp;&nbsp;",
      fileTooLargeError: "Fichier trop volumineux pour être joint",
      exceededFileCountError: "Le nombre maximum de pièces jointes autorisées a été dépassé",
      selectFileTitle: "Sélectionner un fichier",
      btnSelectFileText: "Sélectionner un fichier",
      btnViewSubmissions: "Consulter les envois"
    },
    builder: {
      gettingStarted: "Prise en main",
      dateSettings: "Paramètres de date",
      hiddenDateField: "Masquer ce champ de date",
      preventPastDates: "Bloquer les dates passées",
      preventFutureDates: "Bloquer les dates futures",
      useCurrentDate: "Définir ce champ avec la date et de l\'heure actuelles",
      configure: "Configurer",
      configureField: "Configurer le champ \'${fieldName}\'",
      invalidUser: "Vous n'êtes pas autorisé à consulter cet élément",
      invalidWebmapSelectionAlert: "La carte Web sélectionnée ne contient aucune couche valide à utiliser. Veuillez ajouter une couche d\'entités modifiable dans votre carte Web pour continuer.",
      invalidWebmapSelectionAlert2: "Pour plus d\'informations, consultez la rubrique ${openLink}Qu\'est-ce qu\'un service d\'entités ?${closeLink}",
      selectFieldsText: "Sélectionner les champs du formulaire",
      selectThemeText: "Sélectionner le thème du formulaire",
      setViewerText: "Configurer la visionneuse",
      introText: "Départ",
      webmapText: "Carte Web",
      layerText: "Couche",
      detailsText: "Détails",
      fieldsText: "Champs",
      styleText: "Style",
      viewerText: "Viewer",
      optionText: "Options",
      previewText: "Aperçu",
      publishText: "Publier",
      optionsApplicationText: "Options",
      titleText: "Générateur",
      descriptionText: "Le formulaire géographique est un modèle configurable permettant la mise à jour des données d\'un ${link1}service d\'entités${closeLink}. Cette application permet aux utilisateurs de saisir des données dans un formulaire plutôt que dans la fenêtre contextuelle d\'une carte, tout en exploitant la puissance de la ${link2}carte Web${closeLink} et des services d\'entités modifiables. Procédez comme suit pour personnaliser et déployer votre formulaire géographique.",
      btnPreviousText: "Précédent",
      btnNextText: "Suivant",
      webmapTabTitleText: "Sélectionner une carte Web",
      viewWebmap: "Afficher la carte Web",
      webmapDetailsText: "La carte Web sélectionnée est ${webMapTitleLink}${webMapTitle}${closeLink}. Pour sélectionner une autre carte Web, cliquez sur le bouton \'Choisir une carte Web\'",
      btnSelectWebmapText: "Choisir une carte Web",
      btnSelectWebmapTextLoading: "Chargement&hellip;",
      layerTabTitleText: "Sélectionner des couches modifiables",
      selectLayerLabelText: "Couche",
      selectLayerDefaultOptionText: "Sélectionner une couche",
      enableBasemapToggle: "Activer/Désactiver l\'affichage des fonds de carte",
      enableBasemapToggleDescription: "Vous pouvez configurer le formulaire géographique de façon à afficher/masquer les fonds de carte",
      defaultBasemap: "Activer/Désactiver les fonds de carte",
      secondaryBasemap: "Fond de carte par défaut",
      detailsTabTitleText: "Détails du formulaire",
      detailTitleLabelText: "Titre",
      detailLogoLabelText: "Image du logo",
      descriptionLabelText: "Instructions et détails sur le formulaire",
      fieldDescriptionLabelText: "Texte d\'aide (facultatif)",
      fieldDescriptionHelpText: "Fournissez une brève description ou des instructions pour ce champ.",
      fieldHintHelpText: "Texte d\'espace réservé pour le champ.",
      fieldTabFieldHeaderText: "Champ",
      fieldTabLabelHeaderText: "Etiquette",
      fieldTabDisplayTypeHeaderText: "Afficher comme",
      fieldTabOrderColumnText: "Ordre",
      fieldTabVisibleColumnText: "Activé",
      displayFieldText: "Champ d\'affichage",
      selectMenuOption: "Menu de sélection",
      selectRadioOption: "Case d\'option",
      selectTextOption: "Texte",
      selectDateOption: "Sélecteur de dates",
      selectRangeOption: "Activateur tactile",
      selectCheckboxOption: "Case à cocher",
      selectMailOption: "Messagerie électronique",
      selectUrlOption: "URL",
      selectTextAreaOption: "Espace de texte",
      previewApplicationText: "Aperçu de l\'application",
      saveApplicationText: "Enregistrer l\'application",
      saveText: "Enregistrer",
      toggleNavigationText: "Activer/Désactiver la navigation",
      formPlaceholderText: "Mon formulaire",
      shareBuilderInProgressTitleMessage: "Publication du formulaire géographique",
      shareBuilderProgressBarMessage: "Veuillez patienter&hellip;",
      shareBuilderTitleMessage: "Elément enregistré",
      shareBuilderTextMessage: "Vous pouvez commencer à collecter des informations en partageant l\'élément avec d\'autres",
      shareModalFormText: "Lien du formulaire",
      shareBuilderSuccess: "Votre formulaire géographique a été mis à jour et publié !",
      geoformTitleText: "Formulaire géographique",
      layerTabText: "Il s\'agit de la couche dont sera issu le formulaire géographique. La couche doit être un service d\'entités autorisé à effectuer des mises à jour avec des autorisations de partage appropriées à votre public. Si toutes les couches sont sélectionnées, le formulaire permettra à l\'utilisateur de choisir la couche de formulaire à utiliser pour l\'envoi.",
      detailsTabText: "Utilisez les zones Détails du formulaire ci-dessous pour adapter le titre, ajouter un logo personnalisé et fournir une brève description pour le public de votre formulaire géographique. Dans la description, vous pouvez ajouter des liens vers d\'autres ressources, des coordonnées et même diriger votre public vers une application cartographique Web qui présente toutes les données collectées avec le formulaire géographique.",
      fieldsTabText: "Vous pouvez ici sélectionner les champs qui seront visibles au public de votre formulaire géographique, modifier les étiquettes qu\'il verra et ajouter une brève description pour faciliter la saisie de données.",
      styleTabText: "Stylisez votre formulaire géographique à l\'aide des thèmes ci-dessous en fonction de vos préférences.",
      viewerTabText: "Définissez les options d\'affichage des envois collectés depuis le formulaire géographique.",
      publishTabText: "Si vous avez terminé la personnalisation de votre formulaire géographique, enregistrez l\'application et commencez à la partager avec votre public. Vous pouvez toujours revenir dans ce générateur et poursuivre la personnalisation en fonction des commentaires que vous recevez.",
      headerSizeLabel: "Taille de l\'en-tête",
      smallHeader: "Utiliser un petit en-tête",
      bigHeader: "Utiliser un grand en-tête",
      pushpinText: "Punaise",
      doneButtonText: "Enregistrer et quitter",
      fieldTabPlaceHolderHeaderText: "Astuce (facultatif)",
      enableAttachmentLabelText: "${openStrong}Activer les pièces jointes${closeStrong}",
      enableAttachmentLabelHint: "Vous pouvez activer/désactiver les pièces jointes ici",
      attachmentIsRequiredLabelText: "${openStrong}Pièce jointe requise${closeStrong}",
      attachmentIsRequiredLabelHint: "Le cas échéant, les utilisateurs peuvent être invités à entrer une pièce jointe.",
      attachmentLabelText: "Etiquette du bouton Pièce jointe",
      attachmentLabelHint: "Ce texte apparaîtra en regard du bouton Pièce jointe. Vous pouvez utiliser cet espace pour décrire ce que vous souhaitez que votre public joigne (photo, vidéo, document, etc.), le format de fichier que vous demandez (.jpeg, .png, .docx, .pdf, etc.) et des instructions complémentaires.",
      attachmentDescription: "Description de la pièce jointe",
      attachmentHint: "Si cela est nécessaire, vous pouvez indiquer des informations supplémentaires sur les pièces jointes à cet endroit.",
      jumbotronDescription: "Utilisez un en-tête de grande ou de petite taille pour votre formulaire. Un grand en-tête permet de mieux définir l\'objectif de votre application, mais il prend plus d\'espace à l\'écran.",
      shareGeoformText: "Boutons de partage par réseaux sociaux",
      shareDescription: "Les boutons de réseaux sociaux permettent à votre audience de partager facilement votre formulaire géographique une fois l\'envoi effectué",
      defaultMapExtent: "Etendue de la carte par défaut",
      defaultMapExtentDescription: "La carte est réinitialisée sur l\'étendue par défaut de votre carte Web après l\'envoi. Vous pouvez désactiver cette fonction à tout moment.",
      pushpinOptionsDescription: "Attribuez la couleur de votre choix à la punaise de la carte. Elle doit être différente de la symbologie de la carte afin d\'aider l\'utilisateur à placer son envoi sur la carte",
      selectLocationText: "Sélectionner l\'emplacement par",
      myLocationText: "Mon emplacement",
      searchText: "Rechercher",
      coordinatesText: "Coordonnées de latitude et longitude",
      usng: "Coordonnées USNG",
      mgrs: "Coordonnées MGRS",
      utm: "Coordonnées UTM",
      selectLocationSDescription: "Autorisez les utilisateurs à sélectionner un emplacement à l\'aide de ces méthodes.",
      dragTooltipText: "Faites glisser le champ à l\'endroit où il doit apparaître",
      showHideLayerText: "Afficher la couche",
      showHideLayerHelpText: "Vous pouvez configurer le formulaire géographique de façon à afficher/masquer la couche. Cette option s\'applique uniquement à une configuration à une seule couche.",
      labelHelpMessage: "Etiquette",
      placeHolderHintMessage: "Astuce textuelle",
      placeHolderHelpMessage: "Texte d\'aide",
      selectTextOptionValue: "Filtrer la sélection",
      disableLogo: "Désactiver le logo",
      disableLogoDescription: "Vous pouvez configurer le formulaire géographique de façon à afficher/masquer le logo dans l\'en-tête du formulaire",
      locateOnLoadText: "Localiser au chargement",
      locateOnLoadDescription: "Vous pouvez configurer le formulaire géographique de façon à utiliser l\'emplacement actuel lors du chargement de la page",
      selectLayerFieldTabText: "Sélectionner une couche",
      allLayerSelectOptionText: "Toutes les couches",
      disableViewer: "Désactiver la visionneuse",
      disableViewerDescription: "Vous pouvez configurer le formulaire géographique de façon à activer/désactiver la visionneuse",
      displayFieldHintText: "Le champ d\'affichage sélectionné apparaît dans la visionneuse comme titre"
    },
    viewer: {
      geocoderCancelText: "Annuler",
      viewMapTabText: "Carte",
      sortHeaderText: "Trier par :",
      geocoderPlaceholderText: "Code postal, ville, etc.",
      noSearchResult: "Aucun résultat trouvé",
      recordsTabTooltip: "Consulter les envois",
      legendTabTooltip: "Légende",
      aboutUsTabTooltip: "A propos de la société",
      mapTabTooltip: "Carte",
      btnDescendingText: "Décroissant",
      btnAscendingText: "Croissant",
      geometryUnavailableErrorMessage: "Erreur lors de la recherche de la géométrie de l\'entité",
      infoPopupOffErrorMessage: "Aucune information à afficher",
      btnLoadMoreText: "Charger plus",
      unavailableTitleText: "Sans titre",
      unavailableConfigMessage: "Chargement de la configuration impossible",
      share: "Partager",
      viewReportsTabText: "Rapports",
      viewLegendTabText: "Légende",
      viewAboutusTabText: "A propos",
      btnSubmitReportText: "Envoyer un rapport",
      appLoadingFailedMessage: "Une erreur s’est produite lors du chargement de la visionneuse"
    }
  })
);