define(
   ({
    map: {
      error: "マップを作成できません"
    },
    onlineStatus: {
      offline: "現在、オフラインで作業しています。フォームの送信は、サーバに接続できるようになるまでローカルに保存されます。",
      reconnecting: "再接続しています&hellip;",
      pending: "ネットワーク接続が再び確立されると、保留中の ${total} 個の編集内容が送信されます。"
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "組織",
          onlineLabel: "ArcGIS Online",
          contentLabel: "マイ コンテンツ",
          favoritesLabel: "お気に入り"
        },
        title: "Web マップの選択",
        searchTitle: "検索",
        ok: "OK",
        cancel: "キャンセル",
        placeholder: "検索語句の入力"
      },
      groupdlg: {
        items: {
          organizationLabel: "組織",
          onlineLabel: "ArcGIS Online",
          contentLabel: "マイ コンテンツ",
          favoritesLabel: "お気に入り"
        },
        title: "グループの選択",
        searchTitle: "検索",
        ok: "OK",
        cancel: "キャンセル",
        placeholder: "検索語句の入力"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "GeoForm へのリンクはこちら"
      }
    },
    user: {
      all: "須_All__鷗",
      mgrs: "MGRS",
      usng: "USNG",
      utm: "UTM",
      utm_northing: "北距",
      utm_easting: "東距",
      utm_zone_number: "ゾーン ナンバー",
      selectLayerTabText: "${formSection} フォームの選択",
      geoFormGeneralTabText: "${formSection} 情報の入力",
      locationInformationText: "${formSection} 位置の選択",
      submitInformationText: "${formSection} フォームの入力",
      submitInstructions: "この情報をマップに追加します。",
      myLocationText: "現在の位置",
      locationDescriptionForMoreThanOneOption: "マップをクリックまたはタップするか、次のオプションのいずれかを使用して、このエントリの位置を指定します。",
      locationDescriptionForOneOption: "マップをクリック/タップするか、次のオプションを使用して、このエントリの場所を指定します。",
      locationDescriptionForNoOption: "マップをクリック/タップして、このエントリの場所を指定します。",
      addressText: "検索",
      geographic: "緯度/経度",
      locationTabText: "位置",
      locationPopupTitle: "位置",
      submitButtonText: "エントリの送信",
      submitButtonTextLoading: "送信しています&hellip;",
      formValidationMessageAlertText: "次のフィールドが必要です:",
      selectLocation: "送信する場所を選択してください。",
      emptylatitudeAlertMessage: "${openLink}緯度${closeLink}座標を入力してください。",
      emptylongitudeAlertMessage: "${openLink}経度${closeLink}座標を入力してください。",
      shareUserTitleMessage: "ご協力ありがとうございました。",
      entrySubmitted: "エントリがマップに送信されました。",
      shareThisForm: "このフォームを共有",
      shareUserTextMessage: "次のオプションを使用して、他のユーザに提供を求めます。",
      addAttachmentFailedMessage: "添付ファイルをレイヤに追加できません",
      addFeatureFailedMessage: "フィーチャをレイヤに追加できません",
      noLayerConfiguredMessage: "編集可能なフィーチャ レイヤを読み込み中または検索中にエラーが発生しました。フォームを表示してコレクションの送信を開始するには、編集可能なフィーチャ レイヤを Web マップに追加します。",
      placeholderLatitude: "緯度 (Y)",
      placeholderLongitude: "経度 (X)",
      latitude: "緯度",
      longitude: "経度",
      findMyLocation: "現在の場所を検索",
      finding: "位置を検索しています&hellip;",
      backToTop: "トップへ戻る",
      addressSearchText: "送信内容はここに表示されます。ピンをドラッグして、位置を修正できます。",
      shareModalFormText: "フォーム リンク",
      close: "閉じる",
      locationNotFound: "場所が見つかりませんでした。",
      setLocation: "場所の設定",
      find: "住所または場所の検索",
      attachment: "添付ファイル",
      toggleDropdown: "ドロップダウンの切り替え",
      invalidString: "須_Please enter a valid value_________鷗.",
      invalidSmallNumber: "須_Please enter a valid ${openStrong}integer${closeStrong} value between -32768 and 32767___________________________鷗.",
      invalidNumber: "-2147483648 から 2147483647 の間の有効な${openStrong}整数${closeStrong}の値を入力してください。",
      invalidFloat: "有効な${openStrong}浮動小数点${closeStrong}の値を入力してください。",
      invalidDouble: "有効な ${openStrong}double${closeStrong} の値を入力してください。",
      invalidLatLong: "有効な緯度および経度座標を入力してください。",
      invalidUTM: "有効な UTM 座標を入力してください。",
      invalidUSNG: "有効な USNG 座標を入力してください。",
      invalidMGRS: "有効な MGRS 座標を入力してください。",
      geoformTitleText: "GeoForm",
      domainDefaultText: "選択&hellip;",
      applyEditsFailedMessage: "エントリが送信できません。もう一度やり直してください。",
      requiredFields: "須_The following field is required. Please provide a valid entry____________________鷗.",
      requiredField: "(必須)",
      error: "エラー",
      textRangeHintMessage: "${openStrong}ヒント:${closeStrong} 最小値 ${minValue} および最大値 ${maxValue}",
      dateRangeHintMessage: "${openStrong}ヒント:${closeStrong} 最小日付 ${minValue} および最大日付 ${maxValue}",
      remainingCharactersHintMessage: "残り ${value} 文字",
      mapFullScreen: "全画面表示",
      mapRestore: "元に戻す",
      filterSelectEmptyText: "選択",
      invalidLayerMessage: "フォーム レイヤが存在しません。アプリケーションを構成して、レイヤを設定してください。",
      selectedLayerText: "すべて",
      fileUploadStatus: "ファイル アップロード ステータス",
      uploadingBadge: "&nbsp;アップロードしています&hellip;",
      successBadge: "&nbsp;アップロードしました",
      retryBadge: "再試行",
      errorBadge: "アップロード中にエラーが発生しました&nbsp;&nbsp;&nbsp;",
      fileTooLargeError: "ファイルが大きすぎて添付できません",
      exceededFileCountError: "須_Exceeded maximum number of attachments allowed_______________鷗",
      selectFileTitle: "ファイルの選択",
      btnSelectFileText: "須_Select File____鷗",
      btnViewSubmissions: "送信内容の表示"
    },
    builder: {
      gettingStarted: "須_Getting Started______鷗",
      dateSettings: "須_Date Settings_____鷗",
      hiddenDateField: "須_Hide this date field_______鷗",
      preventPastDates: "須_Prevent past dates______鷗",
      preventFutureDates: "須_Prevent future dates_______鷗",
      useCurrentDate: "須_Set this field with the current date and time_______________鷗",
      configure: "須_Configure____鷗",
      configureField: "須_Configure Field '${fieldName}'__________鷗",
      invalidUser: "このアイテムを表示する権限がありません",
      invalidWebmapSelectionAlert: "選択した Web マップに、有効なレイヤが含まれていません。編集可能なフィーチャ レイヤを Web マップに追加して、続行してください。",
      invalidWebmapSelectionAlert2: "詳細については、「${openLink}フィーチャ サービスとは${closeLink}」をご参照ください。",
      selectFieldsText: "フォーム フィールドの選択",
      selectThemeText: "フォームのテーマの選択",
      setViewerText: "須_Configure Viewer______鷗",
      introText: "須_Start___鷗",
      webmapText: "Web マップ",
      layerText: "レイヤ",
      detailsText: "詳細",
      fieldsText: "フィールド",
      styleText: "スタイル",
      viewerText: "須_Viewer___鷗",
      optionText: "オプション",
      previewText: "プレビュー",
      publishText: "公開",
      optionsApplicationText: "オプション",
      titleText: "ビルダ",
      descriptionText: "GeoForm は、フォームベースで${link1}フィーチャ サービス${closeLink}のデータを編集できる構成可能なテンプレートです。このアプリケーションを使用すると、${link2}Web マップ${closeLink}と編集可能なフィーチャ サービスを活用しながら、マップのポップアップの代わりにフォームを使用してデータを入力できます。GeoForm をカスタマイズおよび配置するには、以下の手順を実行します。",
      btnPreviousText: "前へ",
      btnNextText: "次へ",
      webmapTabTitleText: "Web マップの選択",
      viewWebmap: "Web マップの表示",
      webmapDetailsText: "選択した Web マップは、${webMapTitleLink}${webMapTitle}${closeLink} です。別の Web マップを選択するには、[Web マップの選択] ボタンをクリックしてください。",
      btnSelectWebmapText: "Web マップの選択",
      btnSelectWebmapTextLoading: "読み込んでいます...",
      layerTabTitleText: "須_Select Editable Layer(s)________鷗",
      selectLayerLabelText: "レイヤ",
      selectLayerDefaultOptionText: "レイヤの選択",
      enableBasemapToggle: "須_Show Basemap Toggle_______鷗",
      enableBasemapToggleDescription: "須_You can configure the GeoForm to Show/Hide the Basemap Toggle___________________鷗",
      defaultBasemap: "ベースマップの切り替え",
      secondaryBasemap: "デフォルト ベースマップ",
      detailsTabTitleText: "フォームの詳細",
      detailTitleLabelText: "タイトル",
      detailLogoLabelText: "ロゴ画像",
      descriptionLabelText: "手順および詳細の作成",
      fieldDescriptionLabelText: "ヘルプ テキスト (オプション)",
      fieldDescriptionHelpText: "須_Provide a short description or instructions for this field___________________鷗.",
      fieldHintHelpText: "須_Placeholder text for the field__________鷗.",
      fieldTabFieldHeaderText: "フィールド",
      fieldTabLabelHeaderText: "ラベル",
      fieldTabDisplayTypeHeaderText: "表示方法",
      fieldTabOrderColumnText: "順序",
      fieldTabVisibleColumnText: "有効",
      displayFieldText: "表示フィールド",
      selectMenuOption: "メニューの選択",
      selectRadioOption: "ラジオ ボタン",
      selectTextOption: "テキスト",
      selectDateOption: "日付ピッカー",
      selectRangeOption: "タッチ スピナー",
      selectCheckboxOption: "チェックボックス",
      selectMailOption: "電子メール",
      selectUrlOption: "URL",
      selectTextAreaOption: "テキスト エリア",
      previewApplicationText: "アプリケーションのプレビュー",
      saveApplicationText: "アプリケーションの保存",
      saveText: "保存",
      toggleNavigationText: "ナビゲーションの切り替え",
      formPlaceholderText: "マイ フォーム",
      shareBuilderInProgressTitleMessage: "GeoForm を公開しています",
      shareBuilderProgressBarMessage: "お待ちください&hellip",
      shareBuilderTitleMessage: "アイテムを正常に保存しました",
      shareBuilderTextMessage: "他のユーザと共有することで情報の収集を開始できます",
      shareModalFormText: "フォーム リンク",
      shareBuilderSuccess: "GeoForm が更新および公開されました。",
      geoformTitleText: "GeoForm",
      layerTabText: "須_This is the layer(s) that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience. If all layers are selected, the form will allow a user to choose which form layer to submit to___________________________________________________________________________________鷗.",
      detailsTabText: "以下の [フォームの詳細] ボックスを使用して、タイトルをカスタマイズしたり、カスタム ロゴを追加したり、GeoForm のユーザ向けに短い説明を入力します。説明欄の中では、他のリソースや連絡先情報へのリンクを追加したり、GeoForm で収集したデータのすべてを収録した Web マップ アプリケーションのリンクをユーザに示したりすることができます。",
      fieldsTabText: "ここで、GeoForm のユーザに表示する属性フィールドを選択したり、ラベルを編集したり、データ入力を補助する短い説明を追加したりできます。",
      styleTabText: "必要に応じて、以下のテーマを使用して GeoForm のスタイルを設定します。",
      viewerTabText: "須_Set options for viewing submissions collected from the GeoForm____________________鷗.",
      publishTabText: "GeoForm のカスタマイズが完了したら、アプリケーションを保存して、ユーザとの共有を開始します。いつでもこのビルダに戻り、ユーザからのフィードバックに基づいてカスタマイズを再開することができます",
      headerSizeLabel: "ヘッダー サイズ",
      smallHeader: "小さいヘッダーを使用",
      bigHeader: "大きいヘッダーを使用",
      pushpinText: "押しピン",
      doneButtonText: "保存して終了",
      fieldTabPlaceHolderHeaderText: "ヒント (オプション)",
      enableAttachmentLabelText: "${openStrong}アタッチメント（添付情報）の有効化${closeStrong}",
      enableAttachmentLabelHint: "ここでアタッチメントを有効化/無効化できます",
      attachmentIsRequiredLabelText: "${openStrong}必要なアタッチメント${closeStrong}",
      attachmentIsRequiredLabelHint: "必要であれば、ユーザはアタッチメントの入力を必須にすることができます。",
      attachmentLabelText: "[アタッチメント] ボタンのラベル",
      attachmentLabelHint: "このテキストは、[アタッチメント] ボタンの横に表示されます。このスペースを使用して、ユーザが添付するコンテンツ (写真、ビデオ、ドキュメントなど)、必要なファイル形式 (*.jpeg、*.png、*.docx、*.pdf など)、その他指示について記載することができます。",
      attachmentDescription: "アタッチメントの説明",
      attachmentHint: "必要に応じて、アタッチメントに関する追加の指示をここに入力できます。",
      jumbotronDescription: "フォームに大きな見出しまたは小さな見出しを使用します。大きな見出しは、アプリケーションの目的を定義するのに便利ですが、画面に占める面積が広くなります。",
      shareGeoformText: "須_Social media sharing buttons_________鷗",
      shareDescription: "須_Social media buttons allow your audience to easily share your GeoForm once they have made a submission________________________________鷗",
      defaultMapExtent: "デフォルトのマップ範囲",
      defaultMapExtentDescription: "データの送信後、マップが Web マップのデフォルトの範囲にリセットされます。この機能は、いつでも無効にできます。",
      pushpinOptionsDescription: "マップの押しピンの色を選択します。ユーザがマップで使用する際に便利なように、マップのシンボルとは違う色にします。",
      selectLocationText: "位置の指定方法",
      myLocationText: "現在の場所",
      searchText: "検索",
      coordinatesText: "緯度および経度座標",
      usng: "USNG 座標",
      mgrs: "MGRS 座標",
      utm: "UTM 座標",
      selectLocationSDescription: "ユーザはこれらの方法を使用して位置を指定できます。",
      dragTooltipText: "フィールドを表示したい場所にドラッグ",
      showHideLayerText: "レイヤの表示",
      showHideLayerHelpText: "須_You can configure the GeoForm to Show/Hide Layer. This option only applies to a single layer setup_______________________________鷗.",
      labelHelpMessage: "ラベル",
      placeHolderHintMessage: "ヒント",
      placeHolderHelpMessage: "ヘルプ テキスト",
      selectTextOptionValue: "フィルタ選択",
      disableLogo: "ロゴの無効化",
      disableLogoDescription: "フォーム ヘッダー内のロゴを表示/非表示することができます。",
      locateOnLoadText: "読み込み時に現在位置を検索",
      locateOnLoadDescription: "ページの読み込み時に現在の位置を使用できます",
      selectLayerFieldTabText: "レイヤの選択",
      allLayerSelectOptionText: "須_All Layers____鷗",
      disableViewer: "ビューアの無効化",
      disableViewerDescription: "須_You can configure the GeoForm to disable/enable the viewer__________________鷗",
      displayFieldHintText: "須_Selected display field will be shown in the viewer as a title___________________鷗"
    },
    viewer: {
      geocoderCancelText: "キャンセル",
      viewMapTabText: "マップ",
      sortHeaderText: "並べ替え:",
      geocoderPlaceholderText: "郵便番号、市区町村など。",
      noSearchResult: "結果が見つかりません",
      recordsTabTooltip: "送信内容の表示",
      legendTabTooltip: "凡例",
      aboutUsTabTooltip: "須_About Us___鷗",
      mapTabTooltip: "マップ",
      btnDescendingText: "降順",
      btnAscendingText: "昇順",
      geometryUnavailableErrorMessage: "須_Erorr finding the geometry of the feature_____________鷗",
      infoPopupOffErrorMessage: "須_No information to display_________鷗",
      btnLoadMoreText: "さらに読み込み",
      unavailableTitleText: "無題",
      unavailableConfigMessage: "構成を読み込めません",
      share: "須_Share___鷗",
      viewReportsTabText: "須_Reports___鷗",
      viewLegendTabText: "凡例",
      viewAboutusTabText: "情報",
      btnSubmitReportText: "レポートの送信",
      appLoadingFailedMessage: "須_There was an error loading the viewer____________鷗"
    }
  })
);