define(
     ({
        map: {
            error: "マップを作成できません"
        },
        onlineStatus: {
            offline: "現在、オフラインで作業しています。フォームの送信は、サーバに接続できるようになるまでローカルに保存されます。",
            reconnecting: "再接続しています&hellip;",
            pending: "ネットワーク接続が再び確立されると、保留中の ${total} 個の編集内容が送信されます。"
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "組織",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "マイ コンテンツ",
                    favoritesLabel: "お気に入り"
                },
                title: "Web マップの選択",
                searchTitle: "検索",
                ok: "OK",
                cancel: "キャンセル",
                placeholder: "検索語句の入力"
            },
            groupdlg: {
                items: {
                    organizationLabel: "組織",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "マイ コンテンツ",
                    favoritesLabel: "お気に入り"
                },
                title: "グループの選択",
                searchTitle: "検索",
                ok: "OK",
                cancel: "キャンセル",
                placeholder: "検索語句の入力"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "北距",
            utm_easting: "東距",
            utm_zone_number: "ゾーン ナンバー",
            geoFormGeneralTabText: "1. 情報の入力",
            locationInformationText: "2. 位置の選択",
            submitInformationText: "3. フォームの入力",
            submitInstructions: "この情報をマップに追加します。",
            myLocationText: "現在の位置",
            locationDescription: "マップをクリックまたはタップするか、次のオプションのいずれかを使用して、このエントリの位置を指定します。",
            addressText: "検索",
            geographic: "緯度/経度",
            locationTabText: "位置",
            locationPopupTitle: "位置",
            submitButtonText: "エントリの送信",
            submitButtonTextLoading: "送信しています&hellip;",
            formValidationMessageAlertText: "次のフィールドが必要です:",
            selectLocation: "送信の${openLink}位置${closeLink}を選択してください。",
            emptylatitudeAlertMessage: "${openLink}緯度${closeLink}座標を入力してください。",
            emptylongitudeAlertMessage: "${openLink}経度${closeLink}座標を入力してください。",
            shareUserTitleMessage: "ご協力ありがとうございました。",
            entrySubmitted: "エントリがマップに送信されました。",
            shareThisForm: "このフォームを共有",
            shareUserTextMessage: "次のオプションを使用して、他のユーザに提供を求めます。",
            addAttachmentFailedMessage: "添付ファイルをレイヤに追加できません",
            addFeatureFailedMessage: "フィーチャをレイヤに追加できません",
            noLayerConfiguredMessage: "編集可能なフィーチャ レイヤを読み込み中または検索中にエラーが発生しました。フォームを表示してコレクションの送信を開始するには、編集可能なフィーチャ レイヤを Web マップに追加します。",
            placeholderLatitude: "緯度 (Y)",
            placeholderLongitude: "経度 (X)",
            latitude: "緯度",
            longitude: "経度",
            findMyLocation: "現在の場所を検索",
            finding: "位置を検索しています&hellip;",
            backToTop: "トップへ戻る",
            addressSearchText: "送信内容はここに表示されます。ピンをドラッグして、位置を修正できます。",
            shareModalFormText: "フォーム リンク",
            close: "閉じる",
            locationNotFound: "場所が見つかりませんでした。",
            setLocation: "場所の設定",
            find: "住所または場所の検索",
            attachment: "添付ファイル",
            toggleDropdown: "ドロップダウンの切り替え",
            invalidLatLong: "有効な${latLink}緯度${closeLink}および${lngLink}経度${closeLink}座標を入力してください。",
            invalidUTM: "有効な ${openLink}UTM${closeLink} 座標を入力してください。",
            invalidUSNG: "有効な ${openLink}USNG${closeLink} 座標を入力してください。",
            invalidMGRS: "有効な ${openLink}MGRS${closeLink} 座標を入力してください。",
            geoformTitleText: "GeoForm",
            domainDefaultText: "選択&hellip;",
            applyEditsFailedMessage: "エントリが送信できません。もう一度やり直してください。",
            requiredFields: "エラーが発生しました。以下で修正してください。",
            requiredField: "(必須)",
            error: "エラー",
            textRangeHintMessage: "${openStrong}ヒント:${closeStrong} 最小値 ${minValue} および最大値 ${maxValue}",
            dateRangeHintMessage: "${openStrong}ヒント:${closeStrong} 最小日付 ${minValue} および最大日付 ${maxValue}"
        },
        builder: {
            invalidUser: "このアイテムを表示する権限がありません",
            invalidWebmapSelectionAlert: "選択した Web マップに、使用する有効なレイヤが含まれていません。編集可能なフィーチャ レイヤを Web マップに追加して、続行してください。",
            invalidWebmapSelectionAlert2: "詳細については、「${openLink}フィーチャ サービスとは${closeLink}」をご参照ください。",
            selectFieldsText: "フォーム フィールドの選択",
            selectThemeText: "フォームの主題の選択",
            webmapText: "Web マップ",
            layerText: "レイヤ",
            detailsText: "詳細",
            fieldsText: "フィールド",
            styleText: "スタイル",
            optionText: "オプション",
            previewText: "プレビュー",
            publishText: "公開",
            optionsApplicationText: "オプション",
            titleText: "ビルダ",
            descriptionText: "GeoForm は、フォームベースで${link1}フィーチャ サービス${closeLink}のデータを編集できる構成可能なテンプレートです。このアプリケーションを使用すると、${link2}Web マップ${closeLink}と編集可能なフィーチャ サービスを活用しながら、マップのポップアップの代わりにフォームを使用してデータを入力できます。GeoForm をカスタマイズおよび配置するには、次の手順を実行します。",
            btnPreviousText: "前へ",
            btnNextText: "次へ",
            webmapTabTitleText: "Web マップの選択",
            viewWebmap: "Web マップの表示",
            btnSelectWebmapText: "Web マップの選択",
            btnSelectWebmapTextLoading: "読み込んでいます...",
            layerTabTitleText: "編集可能レイヤの選択",
            selectLayerLabelText: "レイヤ",
            selectLayerDefaultOptionText: "レイヤの選択",
            detailsTabTitleText: "フォームの詳細",
            detailTitleLabelText: "タイトル",
            detailLogoLabelText: "ロゴ画像",
            descriptionLabelText: "ヘルプ テキスト (オプション)",
            fieldTabFieldHeaderText: "フィールド",
            fieldTabLabelHeaderText: "ラベル",
            fieldTabDisplayTypeHeaderText: "表示方法",
            selectMenuOption: "メニューの選択",
            selectRadioOption: "ラジオ ボタン",
            selectTextOption: "テキスト",
            selectCheckboxOption: "チェックボックス",
            selectMailOption: "電子メール",
            selectUrlOption: "URL",
            selectTextAreaOption: "テキストエリア",
            previewApplicationText: "アプリケーションのプレビュー",
            saveApplicationText: "アプリケーションの保存",
            saveText: "保存",
            toggleNavigationText: "ナビゲーションの切り替え",
            formPlaceholderText: "マイ フォーム",
            shareBuilderInProgressTitleMessage: "GeoForm を公開しています",
            shareBuilderProgressBarMessage: "お待ちください&hellip",
            shareBuilderTitleMessage: "アイテムを正常に保存しました",
            shareBuilderTextMessage: "他のユーザと共有することで情報の収集を開始できます",
            shareModalFormText: "フォーム リンク",
            shareBuilderSuccess: "GeoForm が更新および公開されました。",
            geoformTitleText: "GeoForm",
            layerTabText: "これは GeoForm の構築元になるレイヤです。このレイヤは、一般ユーザが適切な共有権限を持ち、編集機能が有効なフィーチャ サービスである必要があります。",
            detailsTabText: "以下の [フォームの詳細] ボックスを使用して、タイトルをカスタマイズしたり、カスタム ロゴを追加したり、GeoForm の一般ユーザ向けに短い説明を入力したりします。説明では、他のリソースや連絡先情報へのリンクを追加したり、GeoForm で収集したデータのすべてを備えた Web マップ アプリケーションを一般ユーザに示したりすることができます。",
            fieldsTabText: "ここで、GeoForm の一般ユーザに表示するフィールドを選択したり、ラベルを編集したり、データ入力を補助する短い説明を追加したりできます。",
            styleTabText: "必要に応じて、以下のテーマを使用して GeoForm のスタイルを設定します。",
            publishTabText: "GeoForm のカスタマイズが完了したら、アプリケーションを保存して、一般ユーザとの共有を開始します。いつでもこのビルダに戻り、フィードバックに基づいてカスタマイズを続けることができます。",
            smallHeader: "小さいヘッダーを使用",
            pushpinText: "ピンをプッシュ",
            doneButtonText: "アプリケーション アイテムの表示",
            fieldTabPlaceHolderHeaderText: "ヒント (オプション)",
            attachmentLabelText: "添付ファイル ラベル",
            attachmentLabelHint: "添付されるファイルのタイプをユーザに伝えます。",
            attachmentDescription: "添付ファイルの説明",
            attachmentHint: "必要に応じて、添付ファイルの追加の指示をここに入力できます。",
            jumbotronDescription: "Bootstrap Jumbotron により、アプリケーションの目的の定義が容易になります。これは、いつでも無効にできます。",
            shareGeoformText: "Geoform の共有",
            shareDescription: "いったん送信すると、共有パネルにより、一般ユーザが他の協力者と GeoForm を容易に共有できるようになります。これは、いつでも無効にできます。",
            defaultMapExtent: "デフォルトのマップ範囲",
            defaultMapExtentDescription: "送信後、マップは Web マップのデフォルトの範囲にリセットされます。これは、いつでも無効にできます。",
            pushpinOptionsDescription: "マップの押しピンの色を選択します。ユーザがマップで使用する際に便利なように、マップのシンボルとは違う色にします。",
            selectLocationText: "位置の選択で使用",
            myLocationText: "現在の場所",
            searchText: "検索",
            coordinatesText: "緯度および経度座標",
            usng: "USNG 座標",
            mgrs: "MGRS 座標",
            utm: "UTM 座標",
            selectLocationSDescription: "ユーザはこれらの方法を使用して位置を選択できます。"
        }
    })
);