define({
  "map": {
    "error": "Kreiranje mape nije moguće"
  },
  "onlineStatus": {
    "offline": "Trenutno radite van mreže. Obrasci prosleđivanja će biti sačuvani samo lokalno dok veza sa serverom ne bude uspostavljena.",
    "reconnecting": "Ponovno povezivanje&hellip;",
    "pending": "${Total} izmene na čekanju će biti prosleđene kada se veza sa mrežom ponovo uspostavi."
  },
  "configure": {
    "mapdlg": {
      "items": {
        "organizationLabel": "Moja organizacija",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "Moj sadržaj",
        "favoritesLabel": "Moj omiljeni sadržaj"
      },
      "title": "Izaberi veb mapu",
      "searchTitle": "Pretraži",
      "ok": "U redu",
      "cancel": "Otkaži",
      "placeholder": "Unesite pojam za pretragu"
    },
    "groupdlg": {
      "items": {
        "organizationLabel": "Moja organizacija",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "Moj sadržaj",
        "favoritesLabel": "Moj omiljeni sadržaj"
      },
      "title": "Izaberite grupu",
      "searchTitle": "Pretraži",
      "ok": "U redu",
      "cancel": "Otkaži",
      "placeholder": "Unesite pojam za pretragu"
    },
    "sharedlg": {
      "items": {},
      "mailtoLinkDescription": "Ovde se nalazi link za GeoForm aplikaciju"
    }
  },
  "user": {
    "all": "Sve",
    "mgrs": "Referentni sistem vojne pravougle koordinatne mreže (MGRS)",
    "usng": "Nacionalna koordinatna mreža SAD (USNG)",
    "utm": "Univerzalni Transverzalni Merkatorov koordinatni sistem (UTM)",
    "utm_northing": "Razdaljina u odnosu na X osu",
    "utm_easting": "Razdaljina u odnosu na Y osu",
    "utm_zone_number": "Broj zone",
    "selectLayerTabText": "${formSection} Izaberite obrazac",
    "geoFormGeneralTabText": "${formSection} Unesite informaciju",
    "locationInformationText": "${formSection} Izaberite lokaciju",
    "submitInformationText": "${formSection} Popunite obrazac",
    "submitInstructions": "Dodajte ovu informaciju na mapu.",
    "myLocationText": "Trenutna lokacija",
    "locationDescriptionForMoreThanOneOption": "Odredite lokaciju za ovaj unos klikom/dodirom na mapu ili korišćenjem neke od sledećih opcija.",
    "locationDescriptionForOneOption": "Odredite lokaciju za ovaj unos klikom/dodirom na mapu ili korišćenjem sledeće opcije.",
    "locationDescriptionForNoOption": "Odredite lokaciju za ovaj unos klikom/dodirom na mapu.",
    "addressText": "Pretraži",
    "geographic": "duž./šir.",
    "locationTabText": "Lokacija",
    "locationPopupTitle": "Lokacija",
    "submitButtonText": "Prosledi unos",
    "submitButtonTextLoading": "Prosleđivanje&hellip;",
    "formValidationMessageAlertText": "Sledeća polja su obavezna:",
    "selectLocation": "Izaberite lokaciju za prosleđivanje",
    "emptylatitudeAlertMessage": "Unesite koordinatu ${openLink}geografske širine${closeLink}.",
    "emptylongitudeAlertMessage": "Unesite koordinatu ${openLink}geografske dužine${closeLink}.",
    "shareUserTitleMessage": "Hvala vam na doprinosu!",
    "entrySubmitted": "Vaš unos je prosleđen na mapu.",
    "shareThisForm": "Podeli ovaj obrazac",
    "shareUserTextMessage": "Recite ostalima da daju doprinos koristeći sledeće opcije.",
    "addAttachmentFailedMessage": "Dodavanje priloga sloju nije moguće",
    "addFeatureFailedMessage": "Dodavanje geoobjekta sloju nije moguće",
    "noLayerConfiguredMessage": "Došlo je do greške pri učitavanju ili traženju geoobjekta koji je moguće menjati u sloju. Na veb mapu dodajte sloj geoobjekata koji je moguće izmeniti da biste prikazali obrazac i počeli da prikupljate prosleđene stavke.",
    "placeholderLatitude": "Geografska širina (Y)",
    "placeholderLongitude": "Geografska dužina (X)",
    "latitude": "Geografska širina",
    "longitude": "Geografska dužina",
    "findMyLocation": "Lociraj me",
    "finding": "Lociranje&hellip;",
    "backToTop": "Nazad na vrh",
    "addressSearchText": "Vaša prosleđena stavka će se pojaviti ovde. Možete da prevučete pribadaču da ispravite lokaciju.",
    "shareModalFormText": "Link za obrazac",
    "close": "Zatvori",
    "locationNotFound": "Pronalaženje lokacije nije moguće.",
    "setLocation": "Podesi lokaciju.",
    "find": "Pronađi adresu ili mesto",
    "attachment": "Prilog",
    "toggleDropdown": "Uključi/isključi padajuću listu",
    "invalidString": "Unesite validnu vrednost.",
    "invalidSmallNumber": "Unesite validnu vrednost ${openStrong}celog broja${closeStrong} između -32768 i 32767.",
    "invalidNumber": "Unesite validnu vrednost ${openStrong}celog broja${closeStrong} između -2147483648 i 2147483647.",
    "invalidFloat": "Unesite validnu vrednost ${openStrong}plutajuće tačke${closeStrong}.",
    "invalidDouble": "Unesite validnu ${openStrong}dvostruku${closeStrong} vrednost.",
    "invalidLatLong": "Unesite validnu vrednost koordinata geografske širine i dužine.",
    "invalidUTM": "Unesite validne UTM koordinate.",
    "invalidUSNG": "Unesite validne USNG koordinate.",
    "invalidMGRS": "Unesite validne MGRS koordinate.",
    "geoformTitleText": "GeoForm aplikacija",
    "domainDefaultText": "Izaberi&hellip;",
    "applyEditsFailedMessage": "Došlo je do greške u prosleđivanju.",
    "applyEditsFailedRobot": "Prosleđivanje je odbačeno, jer nije prošlo otkrivanje robota.",
    "applyEditsAuthError": "Vaš unos ne može da bude prosleđen usled tipa vašeg korisničkog nivoa. Obratite se administratoru svoje organizacije za dalju pomoć.",
    "requiredFields": "Sledeće polje je obavezno. Obezbedite validan unos.",
    "requiredField": "(obavezno)",
    "error": "Greška",
    "textRangeHintMessage": "${openStrong}Podsetnik:${closeStrong} Minimalna vrednost ${minValue} i maksimalna vrednost ${maxValue}",
    "dateRangeHintMessage": "${openStrong}Podsetnik:${closeStrong} Minimalna vrednost datuma ${minValue} i maksimalna vrednost datuma ${maxValue}",
    "remainingCharactersHintMessage": "Preostalo karaktera ${value}",
    "mapFullScreen": "Ceo ekran",
    "mapRestore": "Vrati u prethodno stanje",
    "filterSelectEmptyText": "Izaberi",
    "invalidLayerMessage": "Nije pronađen validan sloj za kreiranje aplikacije GeoForm. Ako je GeoForm aplikacija konfigurisana sa slojem, sloj možda više nije dostupan ili autorizacija nije uspela.",
    "selectedLayerText": "Sve",
    "fileUploadStatus": "Status otpremanja datoteke",
    "uploadingBadge": "&nbsp;Otpremanje&hellip;",
    "successBadge": "&nbsp;Otpremljeno",
    "retryBadge": "Pokušajte ponovo",
    "errorBadge": "Greška pri otpremanju&nbsp;&nbsp;",
    "fileTooLargeError": "Datoteka je prevelika da bi bila priložena",
    "exceededFileCountError": "Premašen je maksimalni broj dozvoljenih priloga",
    "selectFileTitle": "Izaberite datoteku",
    "btnSelectFileText": "Izaberite datoteku",
    "btnViewSubmissions": "Prikaži prosleđene stavke"
  },
  "builder": {
    "gettingStarted": "Prvi koraci",
    "dateSettings": "Postavke datuma",
    "hiddenDateField": "Sakrij polje datume",
    "preventPastDates": "Spreči datume iz prošlost",
    "preventFutureDates": "Spreči datume iz budućnosti",
    "useCurrentDate": "Podesi u ovom polju trenutni datum i vreme",
    "configure": "Konfiguriši",
    "configureField": "Konfigurišite polje '${fieldName}'",
    "invalidUser": "Žao nam je, nemate dozvolu da pregledate ovu stavku",
    "invalidWebmapSelectionAlert": "Izabrana veb mapa ne sadrži slojeve validne za korišćenje. Na veb mapu dodajte sloj geoobjekata koje je moguće menjati da biste nastavili.",
    "invalidWebmapSelectionAlert2": "Više informacija potražite na ${openLink}Šta je servis geoobjekata?${closeLink}",
    "selectFieldsText": "Izaberite polja obrasca",
    "selectThemeText": "Izaberite temu obrasca",
    "setViewerText": "Konfigurišite Preglednik",
    "introText": "Pokretanje",
    "webmapText": "Veb mapa",
    "layerText": "Sloj",
    "detailsText": "Detalji",
    "fieldsText": "Polja",
    "styleText": "Stil",
    "viewerText": "Preglednik",
    "optionText": "Opcije",
    "previewText": "Pregledaj",
    "publishText": "Objavi",
    "optionsApplicationText": "Opcije",
    "submitButtonText": "Tekst polja za prosleđivanje (opciono)",
    "submitButtonDesc": "Opciono označite dugme da prosledite novi unos. Ovaj tekst neće biti preveden.",
    "viewSubmissionsText": "Pogledaj tekst prosleđenih stavki (opciono)",
    "viewSubmissionsDesc": "Opciono označite dugme da pregledate postojeće unose. Ovaj tekst neće biti preveden.",
    "titleText": "Alatka za izradu",
    "descriptionText": "GeoForm je konfigurabilni šablon za izmenu podataka ${link1}servisa geoobjekata${closeLink} u okviru obrasca. Ova aplikacija omogućava korisnicima da unose podatke kroz formular umesto preko iskačućih prozora u mapi dok koristi prednosti ${link2}veb mape${closeLink} i servisa geoobjekata koje je moguće menjati. Pratite sledeće korake da prilagodite i postavite GeoForm aplikaciju.",
    "btnPreviousText": "Prethodno",
    "btnNextText": "Sledeće",
    "webmapTabTitleText": "Izaberi veb mapu",
    "viewWebmap": "Prikaži veb mapu",
    "webmapDetailsText": "Izabrana veb mapa je ${webMapTitleLink}${webMapTitle}${closeLink}. Da izaberete drugu veb mapu, kliknite na dugme „Odaberi veb mapu“.",
    "btnSelectWebmapText": "Odaberi veb mapu",
    "btnSelectWebmapTextLoading": "Učitavanja&hellip;",
    "layerTabTitleText": "Izaberite sloj(eve) koji/koje je moguće izmeniti",
    "selectLayerLabelText": "Sloj",
    "selectLayerDefaultOptionText": "Izaberite sloj",
    "enableBasemapToggle": "Prikaži preklopnik pozadinske mape",
    "enableBasemapToggleDescription": "Možete da konfigurišete GeoForm aplikaciju da prikažete/sakrijete preklopnik pozadinske mape",
    "defaultBasemap": "Preklopnik pozadinske mape",
    "secondaryBasemap": "Podrazumevana pozadinska mapa",
    "detailsTabTitleText": "Detalji obrasca",
    "detailTitleLabelText": "Naslov",
    "detailLogoLabelText": "Slika logotipa",
    "descriptionLabelText": "Instrukcije i detalji obrasca",
    "fieldDescriptionLabelText": "Tekst pomoći (opciono)",
    "fieldDescriptionHelpText": "Obezbedite kratak opis ili instrukcije za ovo polje.",
    "fieldHintHelpText": "Rezervisano polje za tekst.",
    "fieldTabFieldHeaderText": "Polje",
    "fieldTabLabelHeaderText": "Oznaka",
    "fieldTabDisplayTypeHeaderText": "Prikaži kao",
    "fieldTabOrderColumnText": "redosled",
    "fieldTabVisibleColumnText": "Omogućeno",
    "displayFieldText": "Prikaži polje",
    "selectMenuOption": "Izaberi meni",
    "selectRadioOption": "Radio dugme",
    "selectTextOption": "Tekst",
    "selectDateOption": "Birač datuma",
    "selectRangeOption": "Brojač dodira",
    "selectCheckboxOption": "Polje za potvrdu",
    "selectMailOption": "E-pošta",
    "selectUrlOption": "URL adresa",
    "selectTextAreaOption": "Oblast za tekst",
    "previewApplicationText": "Pregledaj aplikaciju",
    "saveApplicationText": "Sačuvaj aplikaciju",
    "saveText": "Sačuvaj",
    "toggleNavigationText": "Uključi/isključi navigaciju",
    "formPlaceholderText": "Moj obrazac",
    "shareBuilderInProgressTitleMessage": "Objavljivanje GeoForm aplikacije",
    "shareBuilderProgressBarMessage": "Sačekajte&hellip;",
    "shareBuilderTitleMessage": "Uspešno! Stavka je sačuvana",
    "shareBuilderTextMessage": "Možete da počnete da prikupljate informacije deljenjem sa drugima",
    "shareModalFormText": "Link za obrazac",
    "shareBuilderSuccess": "GeoForm aplikacija je ažurirana i objavljena!",
    "geoformTitleText": "Geo Form",
    "layerTabText": "Ovo je/su sloj/slојеvi od kojih će GeoForm aplikacija biti izrađena. Sloj mora da bude servis geoobjekata koje je moguće izmeniti sa odgovarajućim dozvolama za deljenje sa javnošću. Ako su svi slojevi izabrani, obrazac će omogućiti korisniku da izabere iz kojeg sloja želi da prosledi stavke.",
    "detailsTabText": "Koristite polja detalja obrasca ispod da prilagodite naslov, dodate prilagođeni logotip i ostavite kratak opis za korisnike vaše GeoForm aplikacije. U opis možete da dodate linkove ka drugim resursima, kontakt informacije ili da čak uputite korisnike vaše aplikacije na aplikaciju za veb mapiranje koja sadrži sve podatke sakupljene pomoću GeoForm aplikacije.",
    "fieldsTabText": "Ovde možete da izaberete koja polja želite da budu vidljiva korisnicima vaše GeoForm aplikacije, da uredite oznake koje će da vide i da dodate kratak opis da im pomognete sa unosom podataka.",
    "styleTabText": "Stilizujte GeoForm aplikaciju korišćenjem tema ispod, zasnovanih na vašim parametrima.",
    "viewerTabText": "Podesite opcije za prikaz prosleđenih stavki sakupljenih preko GeoForm aplikacije.",
    "publishTabText": "Ako ste završili sa prilagođavanjem GeoForm aplikacije, sačuvajte aplikaciju i otpočnite deljenje sa korisnicima. Uvek možete da se vratite u ovu alatku za izradu i da nastavite prilagođavanje na osnovu povratnih informacija.",
    "headerSizeLabel": "Veličina zaglavlja",
    "smallHeader": "Koristi manje zaglavlje",
    "bigHeader": "Koristi veće zaglavlje",
    "pushpinText": "Čioda",
    "doneButtonText": "Sačuvaj i izađi",
    "fieldTabPlaceHolderHeaderText": "Podsetnik (opciono)",
    "enableAttachmentLabelText": "${openStrong}Omogući priloge${closeStrong}",
    "enableAttachmentLabelHint": "Ovde možete da omogućite/onemogućite priloge",
    "attachmentIsRequiredLabelText": "${openStrong}Prilozi su obavezni${closeStrong}",
    "attachmentIsRequiredLabelHint": "Ukoliko je potrebno, korisnicima može da bude zatraženo da unesu jedan prilog.",
    "attachmentLabelText": "Oznaka za dugme priloga",
    "attachmentLabelHint": "Ovaj tekst će se pojaviti pored dugmeta za prilog. Možete da koristite ovaj prostor da opišete šta biste želeli da korisnici prilože (fotografiju, video zapis, dokument, itd.), format datoteke koju tražite (.jpeg, .png, .docx, .pdf, itd.) i bilo kakve dodatne instrukcije",
    "attachmentDescription": "Opis priloga",
    "attachmentHint": "Ako je neophodno, ovde možete da obezbedite dodatne instrukcije za priloge.",
    "jumbotronDescription": "Koristite veliko ili malo zaglavlje iz obrasca. Veliko zaglavlje može da definiše svrhu aplikacije ali zauzima više mesta na ekranu",
    "shareGeoformText": "Dugmad za deljenje na društvenim medijima",
    "shareDescription": "Dugmad za deljenje na društvenim medijima omogućavaju korisnicima da jednostavno dele GeoForm aplikaciju kada jednom proslede stavku",
    "defaultMapExtent": "Podrazumevani obuhvat mape",
    "defaultMapExtentDescription": "Obuhvat mape će se vratiti na podrazumevanu vrednost vaše veb mape nakon prosleđivanja - ovo možete da onemogućite u bilo kom trenutku.",
    "pushpinOptionsDescription": "Odaberite boju za čiodu na mapi među mnoštvom boja; trebalo bi da se razlikuje od simbologije mape da bi pomogla korisnicima da postave svoje prosleđene stavke na mapu",
    "selectLocationText": "Izaberite lokaciju po",
    "myLocationText": "Moja lokacija",
    "searchText": "Pretraži",
    "coordinatesText": "Koordinate geografske širine i dužine",
    "usng": "USNG koordinate",
    "mgrs": "MGRS koordinate",
    "utm": "UTM koordinate",
    "selectLocationSDescription": "Dozvolite korisnicima da izaberu lokaciju korišćenjem ovih metoda.",
    "dragTooltipText": "Prevucite polje tamo gde želite da se pojavi",
    "showHideLayerText": "Pokaži sloj",
    "showHideLayerHelpText": "Aplikaciju GeoForm možete da konfigurišete da prikaže/sakrije sloj. Ova opcija se odnosi na podešavanje samo jednog sloja.",
    "enableOfflineSupport": "Omogućite podršku van mreže",
    "enableOfflineSupportHelpText": "Skladištite prosleđene stavke kada nema mrežne veze i prosledite ih kada se mreža ponovo uspostavi.",
    "labelHelpMessage": "Oznaka",
    "placeHolderHintMessage": "Tekst podsetnika",
    "placeHolderHelpMessage": "Tekst pomoći",
    "selectTextOptionValue": "Izbor filtera",
    "disableLogo": "Onemogući logotip",
    "disableLogoDescription": "Možete da konfigurišete GeoForm aplikaciju da prikažete/sakrijete logotip iz zaglavlja",
    "locateOnLoadText": "Lociraj pri učitavanju",
    "locateOnLoadDescription": "Možete da konfigurišete GeoForm da koristi trenutnu lokaciju pri učitavanju stranice",
    "selectLayerFieldTabText": "Izaberite sloj",
    "allLayerSelectOptionText": "Svi slojevi",
    "disableViewer": "Onemogući preglednik",
    "disableViewerDescription": "Možete da konfigurišete GeoForm aplikaciju da prikažete/sakrijete preglednik",
    "displayFieldHintText": "Izabrano polje za prikaz će se pokazati u pregledaču kao naslov"
  },
  "viewer": {
    "geocoderCancelText": "Otkaži",
    "viewMapTabText": "Mapa",
    "sortHeaderText": "Sortiraj po:",
    "geocoderPlaceholderText": "Poštanski broj, grad, itd.",
    "noSearchResult": "Nema pronađenog rezultata",
    "legendTabTooltip": "Legenda",
    "aboutUsTabTooltip": "O nama",
    "mapTabTooltip": "Mapa",
    "btnDescendingText": "Opadajuće",
    "btnAscendingText": "Rastuće",
    "geometryUnavailableErrorMessage": "Greška pri pronalaženju geometrije geoobjekta",
    "infoPopupOffErrorMessage": "Nema informacija za prikaz",
    "btnLoadMoreText": "Učitaj više",
    "unavailableTitleText": "Bez naslova",
    "unavailableConfigMessage": "Učitavanje konfiguracije nije moguće",
    "share": "Podeli",
    "viewReportsTabText": "Izveštaji",
    "viewLegendTabText": "Legenda",
    "viewAboutusTabText": "Više informacija",
    "appLoadingFailedMessage": "Došlo je do greške pri učitavanju preglednika"
  }
});