define({
  "map": {
    "error": "Tidak dapat membuat peta"
  },
  "onlineStatus": {
    "offline": "Anda saat ini bekerja offline. Pengiriman formulir akan disimpan secara lokal hingga koneksi ke server dapat dilakukan.",
    "reconnecting": "Menghubungkan kembali&hellip;",
    "pending": "${total} edit yang masih tertunda akan dikirimkan saat koneksi jaringan terhubung kembali."
  },
  "configure": {
    "mapdlg": {
      "items": {
        "organizationLabel": "Organisasi Saya",
        "onlineLabel": "ArcGIS Daring",
        "contentLabel": "Konten Saya",
        "favoritesLabel": "Favorit Saya"
      },
      "title": "Pilih Peta Web",
      "searchTitle": "Cari",
      "ok": "Oke",
      "cancel": "Batal",
      "placeholder": "Masukkan istilah pencarian"
    },
    "groupdlg": {
      "items": {
        "organizationLabel": "Organisasi Saya",
        "onlineLabel": "ArcGIS Daring",
        "contentLabel": "Konten Saya",
        "favoritesLabel": "Favorit Saya"
      },
      "title": "Pilih Grup",
      "searchTitle": "Cari",
      "ok": "Oke",
      "cancel": "Batal",
      "placeholder": "Masukkan istilah pencarian"
    },
    "sharedlg": {
      "items": {},
      "mailtoLinkDescription": "Ini adalah tautan ke GeoForm"
    }
  },
  "user": {
    "all": "Semua",
    "mgrs": "MGRS",
    "usng": "USNG",
    "utm": "UTM",
    "utm_northing": "Lintang Utara",
    "utm_easting": "Bujur Timur",
    "utm_zone_number": "Nomor Zona",
    "selectLayerTabText": "${formSection} Pilih Formulir",
    "geoFormGeneralTabText": "${formSection} Masukkan Informasi",
    "locationInformationText": "${formSection} Pilih lokasi",
    "submitInformationText": "${formSection} Lengkapi Formulir",
    "submitInstructions": "Tambah info ini pada peta.",
    "myLocationText": "Lokasi Saat ini",
    "locationDescriptionForMoreThanOneOption": "Tentukan lokasi untuk entri ini dengan mengeklik/mengetuk peta atau dengan menggunakan salah satu opsi berikut.",
    "locationDescriptionForOneOption": "Tentukan lokasi untuk entri ini dengan mengeklik/mengetuk peta atau dengan menggunakan opsi berikut.",
    "locationDescriptionForNoOption": "Tentukan lokasi untuk entri ini dengan mengeklik/mengetuk peta.",
    "addressText": "Cari",
    "geographic": "Lintang/Bujur",
    "locationTabText": "Lokasi",
    "locationPopupTitle": "Lokasi",
    "submitButtonText": "Kirim Entri",
    "submitButtonTextLoading": "Mengirimkan&hellip;",
    "formValidationMessageAlertText": "Bidang berikut ini diperlukan:",
    "selectLocation": "Silakan pilih lokasi untuk kiriman Anda.",
    "emptylatitudeAlertMessage": "Silakan masukkan koordinat ${openLink}garis lintang${closeLink}.",
    "emptylongitudeAlertMessage": "Silakan masukkan koordinat ${openLink}garis bujur${closeLink}.",
    "shareUserTitleMessage": "Terima kasih atas kontribusi Anda!",
    "entrySubmitted": "Entri Anda telah dikirimkan ke peta",
    "shareThisForm": "Bagikan Formulir Ini",
    "shareUserTextMessage": "Sampaikan kepada orang lain untuk berkontribusi menggunakan opsi berikut.",
    "addAttachmentFailedMessage": "Tidak dapat menambahkan lampiran ke lapisan",
    "addFeatureFailedMessage": "Tidak dapat menambahkan fitur ke lapisan",
    "noLayerConfiguredMessage": "Ada kesalahan saat memuat atau menemukan lapisan fitur yang dapat diedit. Untuk dapat menampilkan formulir dan mulai mengumpulkan kiriman, tambah Lapisan Fitur yang dapat diedit ke Peta web.",
    "placeholderLatitude": "Garis Lintang (Y)",
    "placeholderLongitude": "Garis Bujur (X)",
    "latitude": "Garis Lintang",
    "longitude": "Garis Bujur",
    "findMyLocation": "Temukan Saya",
    "finding": "Menemukan&hellip;",
    "backToTop": "Kembali ke atas",
    "addressSearchText": "Kiriman Anda akan muncul di sini. Anda dapat menyeret pin untuk memperbaiki lokasi.",
    "shareModalFormText": "Tautan Formulir",
    "close": "Tutup",
    "locationNotFound": "Lokasi tidak dapat ditemukan.",
    "setLocation": "Atur Lokasi",
    "find": "Temukan alamat atau tempat",
    "attachment": "Lampiran",
    "toggleDropdown": "Hidupkan/matikan Tarik-Turun",
    "invalidString": "Harap masukkan nilai yang valid.",
    "invalidSmallNumber": "Mohon masukkan nilai ${openStrong}bilangan bulat${closeStrong} yang valid antara -32768 dan 32767.",
    "invalidNumber": "Mohon masukkan nilai ${openStrong}bilangan bulat${closeStrong} yang valid antara -2147483648 dan 2147483647.",
    "invalidFloat": "Mohon masukkan nilai ${openStrong}bilangan titik mengambang${closeStrong} yang valid .",
    "invalidDouble": "Mohon masukkan nilai ${openStrong}ganda${closeStrong} yang valid.",
    "invalidLatLong": "Mohon masukkan koordinat garis lintang dan garis bujur yang valid.",
    "invalidUTM": "Mohon masukkan koordinat UTM yang valid.",
    "invalidUSNG": "Mohon masukkan koordinat USNG yang valid.",
    "invalidMGRS": "Mohon masukkan koordinat MGRS yang valid.",
    "geoformTitleText": "GeoForm",
    "domainDefaultText": "Pilih&hellip;",
    "applyEditsFailedMessage": "Terjadi kesalahan pengiriman.",
    "applyEditsFailedRobot": "Pengiriman ditolak karena tidak lulus deteksi robot.",
    "applyEditsAuthError": "Entri Anda tidak dapat dikirim karena tipe level pengguna Anda. Harap hubungi administrator organisasi Anda untuk meminta bantuan lebih lanjut.",
    "requiredFields": "Bidang berikut ini diperlukan. Silakan berikan entri yang valid.",
    "requiredField": "(diperlukan)",
    "error": "Kesalahan",
    "textRangeHintMessage": "${openStrong}Petunjuk:${closeStrong} Nilai minimum ${minValue} dan Nilai maksimum ${maxValue}",
    "dateRangeHintMessage": "${openStrong}Petunjuk:${closeStrong} Tanggal Minimum ${minValue} dan Tanggal Maksimum ${maxValue}",
    "remainingCharactersHintMessage": "${value} karakter tersisa",
    "mapFullScreen": "Layar Penuh",
    "mapRestore": "Pulihkan",
    "filterSelectEmptyText": "Pilih",
    "invalidLayerMessage": "Lapisan yang valid untuk membuat GeoForm tidak ditemukan. Jika GeoForm belum dikonfigurasikan dengan lapisan, lapisan tersebut mungkin tidak lagi tersedia, atau otorisasi gagal.",
    "selectedLayerText": "Semua",
    "fileUploadStatus": "Status Unggahan File",
    "uploadingBadge": "&nbsp;Mengunggah&hellip;",
    "successBadge": "&nbsp;Diunggah",
    "retryBadge": "Coba lagi",
    "errorBadge": "Kesalahan saat mengunggah&nbsp;&nbsp;&nbsp;",
    "fileTooLargeError": "File terlalu besar untuk dilampirkan",
    "exceededFileCountError": "Melebihi jumlah maksimal lampiran yang diperbolehkan",
    "selectFileTitle": "Pilih file",
    "btnSelectFileText": "Pilih File",
    "btnViewSubmissions": "Tampilkan Kiriman"
  },
  "builder": {
    "gettingStarted": "Persiapan untuk Memulai",
    "dateSettings": "Pengaturan Tanggal",
    "hiddenDateField": "Sembunyikan bidang tanggal ini",
    "preventPastDates": "Cegah tanggal masa lalu",
    "preventFutureDates": "Cegah tanggal masa mendatang",
    "useCurrentDate": "Atur bidang ini dengan tanggal and waktu saat ini",
    "configure": "Konfigurasikan",
    "configureField": "Konfigurasikan Bidang '${fieldName}'",
    "invalidUser": "Maaf, Anda tidak memiliki izin untuk menampilkan item ini.",
    "invalidWebmapSelectionAlert": "Peta web yang dipilih tidak berisi lapisan yang valid untuk digunakan. Tambahkan Lapisan Fitur yang dapat diedit ke peta web Anda untuk melanjutkan.",
    "invalidWebmapSelectionAlert2": "Untuk Info Lebih Lanjut, buka ${openLink}Apa itu Layanan Fitur?${closeLink}",
    "selectFieldsText": "Pilih Bidang Isian Borang",
    "selectThemeText": "Pilih Tema Formulir",
    "setViewerText": "Konfigurasikan Penampil",
    "introText": "Mulai",
    "webmapText": "Peta web",
    "layerText": "Lapisan",
    "detailsText": "Detail",
    "fieldsText": "Bidang",
    "styleText": "Gaya",
    "viewerText": "Penampil",
    "optionText": "Opsi",
    "previewText": "Pratinjau",
    "publishText": "Terbitkan",
    "optionsApplicationText": "Opsi",
    "submitButtonText": "Kirim Teks Tombol (Opsional)",
    "submitButtonDesc": "Atau, berikan label pada tombol untuk mengirimkan entri baru. Teks ini tidak akan diterjemahkan.",
    "viewSubmissionsText": "Tampilkan Teks Kiriman (Opsional)",
    "viewSubmissionsDesc": "Atau, berikan label pada tombol untuk menampilkan entri yang ada. Teks ini tidak akan diterjemahkan.",
    "titleText": "Penyusun",
    "descriptionText": "GeoForm adalah pola dasar yang dapat dikonfigurasi untuk pengeditan data berbasis formulir dari ${link1}Layanan Fitur${closeLink}. Aplikasi ini memungkinkan pengguna untuk memasukkan data melalui formulir, bukan popup peta, dengan menggunakan daya ${link2}Peta Web${closeLink} dan Layanan Fitur yang dapat diedit. Gunakan langkah-langkah berikut untuk menyesuaikan dan menerapkan GeoForm Anda.",
    "btnPreviousText": "Sebelumnya",
    "btnNextText": "Berikutnya",
    "webmapTabTitleText": "Pilih Peta web",
    "viewWebmap": "Tampilkan peta web",
    "webmapDetailsText": "Peta web yang dipilih adalah ${webMapTitleLink}${webMapTitle}${closeLink}. Untuk memilih peta web yang berbeda, klik tombol 'Pilih Peta web'",
    "btnSelectWebmapText": "Pilih Peta web",
    "btnSelectWebmapTextLoading": "Memuat&hellip;",
    "layerTabTitleText": "Pilih Lapisan yang Dapat Diedit",
    "selectLayerLabelText": "Lapisan",
    "selectLayerDefaultOptionText": "Pilih Lapisan",
    "enableBasemapToggle": "Tampilkan Hidupkan/Matikan Peta dasar",
    "enableBasemapToggleDescription": "Anda dapat konfigurasikan GeoForm untuk Menampilkan/Menyembunyikan Hidupkan/Matikan Peta Dasar",
    "defaultBasemap": "Hidupkan/Matikan Peta dasar",
    "secondaryBasemap": "Peta Dasar Default",
    "detailsTabTitleText": "Detail Formulir",
    "detailTitleLabelText": "Judul",
    "detailLogoLabelText": "Gambar Logo",
    "descriptionLabelText": "Instruksi & Detail Formulir",
    "fieldDescriptionLabelText": "Teks Bantuan (opsional)",
    "fieldDescriptionHelpText": "Berikan deskripsi atau instruksi ringkas untuk bidang ini.",
    "fieldHintHelpText": "Tempat teks untuk bidang.",
    "fieldTabFieldHeaderText": "Bidang",
    "fieldTabLabelHeaderText": "Label",
    "fieldTabDisplayTypeHeaderText": "Tampilkan Sebagai",
    "fieldTabOrderColumnText": "Urutkan",
    "fieldTabVisibleColumnText": "Diaktifkan",
    "displayFieldText": "Tampilkan Bidang",
    "selectMenuOption": "Pilih Menu",
    "selectRadioOption": "Tombol Radio",
    "selectTextOption": "Teks",
    "selectDateOption": "Pemilih Tanggal",
    "selectRangeOption": "Touch-Spinner (Pemutar Sentuh)",
    "selectCheckboxOption": "Kotak centang",
    "selectMailOption": "Email",
    "selectUrlOption": "URL",
    "selectTextAreaOption": "Area Teks",
    "previewApplicationText": "Pratinjau Aplikasi",
    "saveApplicationText": "Simpan Aplikasi",
    "saveText": "Simpan",
    "toggleNavigationText": "Hidupkan/matikan navigasi",
    "formPlaceholderText": "Formulir Saya",
    "shareBuilderInProgressTitleMessage": "Menerbitkan GeoForm",
    "shareBuilderProgressBarMessage": "Harap Tunggu&hellip;",
    "shareBuilderTitleMessage": "Berhasil! Item disimpan",
    "shareBuilderTextMessage": "Anda dapat mulai mengumpulkan informasi dengan cara berbagi dengan yang lainnya",
    "shareModalFormText": "Tautan Formulir",
    "shareBuilderSuccess": "GeoForm Anda telah diperbarui & diterbitkan!",
    "geoformTitleText": "GeoForm",
    "layerTabText": "Ini adalah lapisan tempat GeoForm dibuat. Lapisan ini harus berupa layanan fitur yang diaktifkan untuk pengeditan dengan izin berbagi yang sesuai dengan audiens Anda. Jika seluruh lapisan dipilih, formulir akan memungkinkan pengguna untuk memilih lapisan formulir mana yang akan dikirimkan.",
    "detailsTabText": "Gunakan kotak Detail Formulir di bawah untuk menyesuaikan Judul, menambah logo kustom, dan memberikan deskripsi singkat untuk audiens GeoForm. Pada deskripsi, Anda dapat menambahkan tautan ke sumber daya lain, informasi kontak, dan bahkan mengarahkan audiens ke aplikasi pemetaan web yang berisi seluruh data yang dikumpulkan menggunakan GeoForm.",
    "fieldsTabText": "Di sini Anda dapat memilih bidang mana yang akan terlihat oleh audiens GeoForm, mengedit Label yang akan mereka lihat, dan menambahkan Deskripsi singkat untuk membantu entri data.",
    "styleTabText": "Ubah gaya GeoForm Anda menggunakan tema di bawah ini sesuai selera.",
    "viewerTabText": "Tentukan opsi untuk menampilkan kiriman yang dikumpulkan dari GeoForm.",
    "publishTabText": "Jika Anda telah selesai menyesuaikan GeoForm, simpan aplikasi dan mulailah berbagi dengan audiens. Anda selalu dapat kembalikan ke penyusun ini dan melanjutkan penyesuaian berdasarkan tanggapan.",
    "headerSizeLabel": "Ukuran Header",
    "smallHeader": "Gunakan Header Kecil",
    "bigHeader": "Gunakan Header Besar",
    "pushpinText": "Pin tekan",
    "doneButtonText": "Simpan dan Keluar",
    "fieldTabPlaceHolderHeaderText": "Petunjuk (opsional)",
    "enableAttachmentLabelText": "${openStrong}Aktifkan Lampiran${closeStrong}",
    "enableAttachmentLabelHint": "Anda dapat mengaktifkan/menonaktifkan lampiran di sini",
    "attachmentIsRequiredLabelText": "${openStrong}Lampiran Diperlukan${closeStrong}",
    "attachmentIsRequiredLabelHint": "Jika diperlukan, pengguna dapat diharuskan untuk memasukkan lampiran.",
    "attachmentLabelText": "Label Tombol Lampiran",
    "attachmentLabelHint": "Teks ini akan muncul di samping Tombol Lampiran. Anda dapat menggunakan ruang ini untuk menjelaskan apa yang harus dilampirkan audiens (foto, video, dokumen, dll.), format file yang Anda minta (.jpeg, .png, .docx, .pdf, dll.), dan instruksi tambahan lainnya.",
    "attachmentDescription": "Deskripsi Lampiran",
    "attachmentHint": "Jika diperlukan, Anda dapat memberikan instruksi lampiran tambahan di sini.",
    "jumbotronDescription": "Gunakan header besar atau kecil untuk formulir Anda. Header besar dapat membantu menentukan tujuan aplikasi, namun akan menghabiskan lebih banyak ruang di layar.",
    "shareGeoformText": "Tombol berbagi media sosial",
    "shareDescription": "Tombol media sosial memungkinkan audiens untuk berbagi GeoForm dengan mudah setelah mereka selesai mengirimkan",
    "defaultMapExtent": "Jangkauan Peta Default",
    "defaultMapExtentDescription": "Peta akan diatur ulang menjadi jangkauan default di peta web setelah pengiriman - ini dapat dinonaktifkan kapan saja.",
    "pushpinOptionsDescription": "Pilih dari beberapa warna untuk pin tekan peta, warna harus berbeda dengan simbologi peta untuk membantu pengguna menempatkan kiriman pada peta",
    "selectLocationText": "Pilih Lokasi Menurut",
    "myLocationText": "Lokasi Saya",
    "searchText": "Cari",
    "coordinatesText": "Koordinat Garis Lintang & Garis Bujur",
    "usng": "Koordinat USNG",
    "mgrs": "Koordinat MGRS",
    "utm": "Koordinat UTM",
    "selectLocationSDescription": "Izinkan pengguna untuk memilih lokasi menggunakan metode ini.",
    "dragTooltipText": "Seret bidang ke tempat Anda ingin memunculkannya",
    "showHideLayerText": "Tampilkan Lapisan",
    "showHideLayerHelpText": "Anda dapat mengonfigurasikan GeoForm untuk Menampilkan/Menyembunyikan Lapisan. Opsi ini hanya diterapkan untuk persiapan lapisan tunggal.",
    "enableOfflineSupport": "Aktifkan dukungan offline",
    "enableOfflineSupportHelpText": "Simpan kiriman saat tidak ada koneksi jaringan dan kirim saat koneksi dipulihkan.",
    "labelHelpMessage": "Label",
    "placeHolderHintMessage": "Teks Petunjuk",
    "placeHolderHelpMessage": "Teks Bantuan",
    "selectTextOptionValue": "Pilihan Filter",
    "disableLogo": "Nonaktifkan Logo",
    "disableLogoDescription": "Anda dapat mengonfigurasikan GeoForm untuk Menampilkan/Menyembunyikan Logo di header formulir",
    "locateOnLoadText": "Temukan Saat Memuat",
    "locateOnLoadDescription": "Anda dapat mengonfigurasi GeoForm untuk menggunakan lokasi saat ini ketika memuat halaman",
    "selectLayerFieldTabText": "Pilih Lapisan",
    "allLayerSelectOptionText": "Semua Lapisan",
    "disableViewer": "Nonaktifkan Penampil",
    "disableViewerDescription": "Anda dapat mengonfigurasi GeoForm untuk menonaktifkan/mengaktifkan penampil",
    "displayFieldHintText": "Bidang tampilan yang dipilih akan ditampilkan pada penampil sebagai judul"
  },
  "viewer": {
    "geocoderCancelText": "Batal",
    "viewMapTabText": "Peta",
    "sortHeaderText": "Urutkan Menurut:",
    "geocoderPlaceholderText": "Kode Pos, kota, dll.",
    "noSearchResult": "Tidak ada hasil yang ditemukan",
    "legendTabTooltip": "Legenda",
    "aboutUsTabTooltip": "Tentang Kami",
    "mapTabTooltip": "Peta",
    "btnDescendingText": "Turun",
    "btnAscendingText": "Naik",
    "geometryUnavailableErrorMessage": "Kesalahan saat menemukan geometri fitur",
    "infoPopupOffErrorMessage": "Tidak ada informasi untuk ditampilkan",
    "btnLoadMoreText": "Muat Lebih Banyak",
    "unavailableTitleText": "Tidak berjudul",
    "unavailableConfigMessage": "Tidak dapat memuat konfigurasi",
    "share": "Bagikan",
    "viewReportsTabText": "Laporan",
    "viewLegendTabText": "Legenda",
    "viewAboutusTabText": "Tentang",
    "appLoadingFailedMessage": "Ada kesalahan saat memuat penampil"
  }
});