define(
   ({
    map: {
      error: "Žemėlapio sukurti nepavyko"
    },
    onlineStatus: {
      offline: "Dabar dirbate atsijungę. Kol bus užmegztas ryšys su serveriu, formų turinys bus saugomas lokaliai.",
      reconnecting: "Prisijungiama iš naujo&hellip;",
      pending: "Atkūrus tinklo ryšį, bus pateikta laukiančių pakeitimų: ${total}."
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "Mano organizacija",
          onlineLabel: "ArcGIS Online",
          contentLabel: "Mano turinys",
          favoritesLabel: "Mano mėgstamiausi"
        },
        title: "Pasirinkti internetinį žemėlapį",
        searchTitle: "Ieškoti",
        ok: "Gerai",
        cancel: "Atšaukti",
        placeholder: "Įveskite paieškos frazę"
      },
      groupdlg: {
        items: {
          organizationLabel: "Mano organizacija",
          onlineLabel: "ArcGIS Online",
          contentLabel: "Mano turinys",
          favoritesLabel: "Mano mėgstamiausi"
        },
        title: "Pasirinkite grupę",
        searchTitle: "Ieškoti",
        ok: "Gerai",
        cancel: "Atšaukti",
        placeholder: "Įveskite paieškos frazę"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "Čia yra nuoroda į GeoForm"
      }
    },
    user: {
      mgrs: "MGRS",
      usng: "USNG",
      utm: "UTM",
      utm_northing: "Ilgumos poslinkis",
      utm_easting: "Platumos poslinkis",
      utm_zone_number: "Zonos numeris",
      selectLayerTabText: "${formSection} Pasirinkite formą",
      geoFormGeneralTabText: "${formSection} Įveskite informaciją",
      locationInformationText: "${formSection} Pasirinkite vietą",
      submitInformationText: "${formSection} Baikite pildyti formą",
      submitInstructions: "Įtraukite šią informaciją į žemėlapį.",
      myLocationText: "Dabartinė vieta",
      locationDescriptionForMoreThanOneOption: "Nurodykite šio įrašo vietą spustelėdami / bakstelėdami žemėlapį arba naudodami vieną iš toliau pateiktų parinkčių.",
      locationDescriptionForOneOption: "Nurodykite šio įrašo vietą paspausdami / bakstelėdami žemėlapį arba naudodami šią parinktį.",
      locationDescriptionForNoOption: "Nurodykite šio įrašo vietą paspausdami / bakstelėdami žemėlapį.",
      addressText: "Ieškoti",
      geographic: "Platuma / ilguma",
      locationTabText: "Vieta",
      locationPopupTitle: "Vieta",
      submitButtonText: "Pateikite įrašą",
      submitButtonTextLoading: "Pateikiama&hellip;",
      formValidationMessageAlertText: "Šie laukai yra privalomi:",
      selectLocation: "Nurodykite pateikimo vietą.",
      emptylatitudeAlertMessage: "Įveskite ${openLink}platumos${closeLink} koordinatę.",
      emptylongitudeAlertMessage: "Įveskite ${openLink}ilgumos${closeLink} koordinatę.",
      shareUserTitleMessage: "Dėkojame už prisidėjimą!",
      entrySubmitted: "Įrašas įkeltas į žemėlapį.",
      shareThisForm: "Bendrinkite šią formą",
      shareUserTextMessage: "Paskatinkite kitus prisidėti naudojant šias parinktis.",
      addAttachmentFailedMessage: "Prie sluoksnio pridėti priedo nepavyko",
      addFeatureFailedMessage: "Į sluoksnį elemento pridėti nepavyko",
      noLayerConfiguredMessage: "Ieškant redaguojamo elementų sluoksnio arba jį įkeliant įvyko klaida. Norėdami peržiūrėti formą ir padėti rinkti pateikimus, internetiniame žemėlapyje pridėkite redaguojamą elementų sluoksnį.",
      placeholderLatitude: "Platuma (Y)",
      placeholderLongitude: "Ilguma (X)",
      latitude: "Platuma",
      longitude: "Ilguma",
      findMyLocation: "Rasti mane",
      finding: "Randama&hellip;",
      backToTop: "Atgal į viršų",
      addressSearchText: "Čia bus rodoma jūsų pateiktis. Norėdami pataisyti vietą, perkelkite smeigtuką.",
      shareModalFormText: "Formos nuoroda",
      close: "Užverti",
      locationNotFound: "Vietos surasti nepavyko.",
      setLocation: "Nustatyti vietą",
      find: "Surasti adresą arba vietą",
      attachment: "Priedas",
      toggleDropdown: "Perjungti išskleidimą",
      invalidString: "Įveskite leistiną reikšmę.",
      invalidSmallNumber: "Įveskite leistiną ${openStrong}sveikojo skaičiaus${closeStrong} reikšmę nuo -32768 iki 32767.",
      invalidNumber: "Įveskite leistiną ${openStrong}sveikojo skaičiaus${closeStrong} reikšmę nuo -2147483648 iki 2147483647.",
      invalidFloat: "Įveskite leistiną ${openStrong}slankiojo kablelio skaičiaus${closeStrong} reikšmę.",
      invalidDouble: "Įveskite leistiną ${openStrong}dvigubo tikslumo skaičiaus${closeStrong} reikšmę.",
      invalidLatLong: "Įveskite tinkamas platumos ir ilgumos koordinates.",
      invalidUTM: "Įveskite tinkamas UTM koordinates.",
      invalidUSNG: "Įveskite tinkamas USNG koordinates.",
      invalidMGRS: "Įveskite tinkamas MGRS koordinates.",
      geoformTitleText: "GeoForm",
      domainDefaultText: "Pasirinkti&hellip;",
      applyEditsFailedMessage: "Atsiprašome, tačiau įrašo pateikti nepavyko. Bandykite dar kartą.",
      requiredFields: "Yra klaidų. Ištaisykite jas žemiau.",
      requiredField: "(privaloma)",
      error: "Klaida",
      textRangeHintMessage: "${openStrong}Patarimas:${closeStrong} minimali vertė ${minValue} ir maksimali vertė ${maxValue}",
      dateRangeHintMessage: "${openStrong}Patarimas:${closeStrong} minimali data ${minValue} ir maksimali data ${maxValue}",
      remainingCharactersHintMessage: "Liko simbolių: ${value}",
      mapFullScreen: "Visas ekranas",
      mapRestore: "Atkurti",
      filterSelectEmptyText: "Pasirinkti",
      invalidLayerMessage: "Formos sluoksnio nėra. Konfigūruokite aplikaciją ir nustatykite sluoksnį.",
      selectedLayerText: "Viskas",
      fileUploadStatus: "Failo įkėlimo būsena",
      uploadingBadge: "&nbsp;Įkeliama&hellip;",
      successBadge: "&nbsp;Įkelta",
      retryBadge: "Pakartoti",
      errorBadge: "Įkėlimo klaida&nbsp;&nbsp;&nbsp;",
      fileTooLargeError: "Failas yra per didelis pridėti",
      exceededFileCountError: "Viršytas maksimalus leidžiamas priedų skaičius",
      selectFileTitle: "Pasirinkite failą",
      btnViewSubmissions: "Peržiūrėti pateikimus",
      dateFormat: "yyy MM dd hh:mm"
    },
    builder: {
      invalidUser: "Atsiprašome, tačiau neturite teisės peržiūrėti šį elementą",
      invalidWebmapSelectionAlert: "Pasirinktame internetiniame žemėlapyje nėra tinkamo naudoti sluoksnio. Norėdami tęsti, į internetinį žemėlapį pridėkite redaguojamą Elementų sluoksnį.",
      invalidWebmapSelectionAlert2: "Norėdami gauti daugiau informacijos, žr. ${openLink}Kas yra elementų paslauga?${closeLink}",
      selectFieldsText: "Pasirinkite formos laukus",
      selectThemeText: "Pasirinkite formos temą",
      webmapText: "Internetinis žemėlapis",
      layerText: "Sluoksnis",
      detailsText: "Smulkesnė informacija",
      fieldsText: "Laukai",
      styleText: "Stilius",
      optionText: "Parinktys",
      previewText: "Peržiūra",
      publishText: "Publikuoti",
      optionsApplicationText: "Parinktys",
      titleText: "Kūrimo priemonė",
      descriptionText: "GeoForm – tai konfigūruojamas šablonas, skirtas ${link1}elementų paslaugai${closeLink} redaguoti, naudojant formą. Naudodami šią aplikaciją vartotojai gali įvesti duomenis per formas, o ne žemėlapio iškylančius langus, naudodami ${link2}internetinio žemėlapio${closeLink} ir redaguojamų elementų paslaugų galimybes. Atlikite toliau nurodytus veiksmus, kad įdiegtumėte ir adaptuotumėte GeoForm.",
      btnPreviousText: "Ankstesnis",
      btnNextText: "Kitas",
      webmapTabTitleText: "Pasirinkti internetinį žemėlapį",
      viewWebmap: "Peržiūrėti internetinį žemėlapį",
      webmapDetailsText: "Pasirinktas internetinis žemėlapis yra ${webMapTitleLink}${webMapTitle}${closeLink}. Norėdami pasirinkti kitą internetinį žemėlapį, paspauskite mygtuką \"Pasirinkti internetinį žemėlapį\"",
      btnSelectWebmapText: "Pasirinkti internetinį žemėlapį",
      btnSelectWebmapTextLoading: "Įkeliama&hellip;",
      layerTabTitleText: "Pasirinkti redaguojamą sluoksnį",
      selectLayerLabelText: "Sluoksnis",
      selectLayerDefaultOptionText: "Pasirinkti sluoksnį",
      defaultBasemap: "Pagrindo žemėlapio perjungiklis",
      secondaryBasemap: "Numatytasis pagrindo žemėlapis",
      detailsTabTitleText: "Smulkesnė formos informacija",
      detailTitleLabelText: "Pavadinimas",
      detailLogoLabelText: "Logotipo paveikslėlis",
      descriptionLabelText: "Formos nurodymai ir informacija",
      fieldDescriptionLabelText: "Pagalbos tekstas (neprivalomas)",
      fieldTabFieldHeaderText: "Laukas",
      fieldTabLabelHeaderText: "Žymė",
      fieldTabDisplayTypeHeaderText: "Rodyti kaip",
      fieldTabOrderColumnText: "Tvarka",
      fieldTabVisibleColumnText: "Leidžiama",
      displayFieldText: "Rodyti lauką",
      selectMenuOption: "Pasirinkite meniu",
      selectRadioOption: "Išrinkimo mygtukas",
      selectTextOption: "Tekstas",
      selectDateOption: "Datos parinkiklis",
      selectRangeOption: "Lietiminis suktukas",
      selectCheckboxOption: "Žymimasis langelis",
      selectMailOption: "El. paštas",
      selectUrlOption: "URL",
      selectTextAreaOption: "Teksto sritis",
      previewApplicationText: "Peržiūrėti aplikaciją",
      saveApplicationText: "Įrašyti aplikaciją",
      saveText: "Įrašyti",
      toggleNavigationText: "Perjungti navigaciją",
      formPlaceholderText: "Mano forma",
      shareBuilderInProgressTitleMessage: "GeoForm publikuojama",
      shareBuilderProgressBarMessage: "Palaukite&hellip;",
      shareBuilderTitleMessage: "Pavyko! Elementas įrašytas",
      shareBuilderTextMessage: "Galite pradėti rinkti informaciją bendrindami su kitais",
      shareModalFormText: "Formos nuoroda",
      shareBuilderSuccess: "Jūsų GeoForm atnaujinta ir publikuota!",
      geoformTitleText: "Geoforma",
      layerTabText: "Tai sluoksnis, iš kurio bus sukurta GeoForm. Šis sluoksnis turi būti elementų paslauga, įgalinta redaguoti naudojant jūsų auditorijai tinkamą bendrinimo teisę.",
      detailsTabText: "Naudokite žemiau esančius formos išsamios informacijos laukus – adaptuokite pavadinimą, pridėkite adaptuotą logotipą ir pateikite trumpą aprašą auditorijai naudosiančiai GeoForm. Aprašyme galite pridėti nuorodų į kitus šaltinius, kontaktinę informaciją ir netgi nukreipti auditoriją į interneto žemėlapių aplikaciją, kurioje yra publikuojami duomenys, surinkti naudojant GeoForm.",
      fieldsTabText: "Čia galite pasirinkti, kurie laukai bus matomi auditorijai naudosiančiai GeoForm, redaguoti jiems matomas žymes ir pridėti trumpą aprašą, kad būtų lengviau įvesti duomenis.",
      styleTabText: "Suteikite GeoForm pageidaujamą stilių, naudodami žemiau pateiktas temas.",
      publishTabText: "Jei baigėte adaptuoti GeoForm, įrašykite pateiktį ir pradėkite bendrinti su auditorija. Visada galėsite grįžti į šią kūrimo priemonę ir toliau adaptuoti remdamiesi atsiliepimais.",
      headerSizeLabel: "Antraštės dydis",
      smallHeader: "Naudoti mažą antraštę",
      bigHeader: "Naudoti didelę antraštę",
      pushpinText: "Smeigtukas",
      doneButtonText: "Išsaugoti ir išeiti",
      fieldTabPlaceHolderHeaderText: "Patarimas (nebūtina)",
      enableAttachmentLabelText: "${openStrong}Leisti priedus${closeStrong}",
      enableAttachmentLabelHint: "Čia galite įjungti / išjungti priedus",
      attachmentIsRequiredLabelText: "${openStrong}Priedas būtinas${closeStrong}",
      attachmentIsRequiredLabelHint: "Jei būtina, galima reikalauti vartotojų pridėti priedą.",
      attachmentLabelText: "Priedo mygtuko žymė",
      attachmentLabelHint: "Tai tekstas, kuris bus rodomas šalia mygtuko Priedas. Galite naudoti šią vietą norėdami apibūdinti, ką auditorija turėtų pridėti (nuotrauką, vaizdo įrašą, dokumentą ir kt.), pageidaujamą failų formatą (.jpeg, .png, .docx, .pdf ir kt.), ir bet kokius papildomus nurodymus.",
      attachmentDescription: "Priedo aprašymas",
      attachmentHint: "Jeigu reikia, papildomus pridėjimo nurodymus galite pateikti čia.",
      jumbotronDescription: "Formai naudokite didelę arba mažą antraštę. Didelė antraštė gali geriau apibūdinti pateikties paskirtį, bet ji užims daugiau vietos ekrane.",
      shareGeoformText: "Bendrinti Geoform",
      shareDescription: "Atlikę pateikimą, bendrinimo skydelyje jūsų auditorija gali lengvai bendrinti GeoForm su kitais bendradarbiais. Šią funkciją galima bet kada išjungti.",
      defaultMapExtent: "Numatyta žemėlapio aprėptis",
      defaultMapExtentDescription: "Pateikus, internetiniame žemėlapyje bus nustatyta numatyta žemėlapio aprėptis. Tai galima bet kada išjungti.",
      pushpinOptionsDescription: "Žemėlapio smeigtuką rinkitės iš įvairių spalvų – jis turi išsiskirti iš žemėlapio simbolių, kad vartotojas galėtų padėti žemėlapyje savo pateiktį",
      selectLocationText: "Pasirinkite vietą pagal",
      myLocationText: "Mano vieta",
      searchText: "Ieškoti",
      coordinatesText: "Platumos ir ilgumos koordinatės",
      usng: "USNG koordinatės",
      mgrs: "MGRS koordinatės",
      utm: "UTM koordinatės",
      selectLocationSDescription: "Vartotojai gali pasirinkti vietą šiais būdais.",
      dragTooltipText: "Nuvilkite lauką ten, kur jis turėtų būti",
      showHideLayerText: "Rodyti sluoksnį",
      showHideLayerHelpText: "Galite konfigūruoti GeoForm rodyti / slėpti sluoksnį. Ši parinktis taikoma tik vieno sluoksnio sąranka.",
      labelHelpMessage: "Žymė",
      placeHolderHintMessage: "Patarimo tekstas",
      placeHolderHelpMessage: "Pagalbos tekstas",
      selectTextOptionValue: "Filtro pasirinkimas",
      disableLogo: "Išjungti logotipą",
      disableLogoDescription: "Galite konfigūruoti GeoForm, kad logotipas būtų rodomas / slepiamas formos antraštėje",
      locateOnLoadText: "Nustatyti įkeliant",
      locateOnLoadDescription: "Galite konfigūruoti GeoForm ir naudoti dabartinę vietą puslapiui įkelti",
      selectLayerFieldTabText: "Pasirinkti sluoksnį",
      allLayerSelectOptionText: "Viskas",
      disableViewer: "Išjungti peržiūros programą",
      disableViewerDescription: "Galite konfigūruoti GeoForm ir įjungti / išjungti peržiūros priemonę",
      displayFieldHintText: "Pasirinktas rodymo laukas bus rodomas viewerMode kaip pavadinimo laukas"
    },
    viewer: {
      geocoderCancelText: "Atšaukti",
      viewReportsTabText: "Pateiktys",
      viewLegendTabText: "Legenda",
      viewAboutusTabText: "Apie",
      viewMapTabText: "Žemėlapis",
      sortHeaderText: "Rūšiuoti pagal:",
      btnSubmitReportText: "Pateikti ataskaitą",
      geocoderPlaceholderText: "Pašto kodas, miestas, kt.",
      noSearchResult: "Rezultatų nerasta",
      recordsTabTooltip: "Peržiūrėti pateikimus",
      legendTabTooltip: "Legenda",
      aboutUsTabTooltip: "Apie mus",
      mapTabTooltip: "Žemėlapis",
      appLoadingFailedMessage: "ViewerMode nepasiekiamas",
      btnDescendingText: "Mažėj",
      btnAscendingText: "Didėj",
      geometryUnavailableErrorMessage: "Nepavyko rasti elemento geometrijos",
      infoPopupOffErrorMessage: "InfoPopup išjungtas",
      btnLoadMoreText: "Įkelti daugiau",
      unavailableTitleText: "Bevardis",
      unavailableConfigMessage: "Nepavyko įkelti konfigūracijos"
    }
  })
);