define(
     ({
        map: {
            error: "Karte kann nicht erstellt werden"
        },
        onlineStatus: {
            offline: "Sie arbeiten derzeit offline. Gesendete Formulare werden lokal gespeichert, bis eine Verbindung mit dem Server hergestellt werden kann.",
            reconnecting: "Verbindung erneut herstellen&hellip;",
            pending: "${total} ausstehende Änderung(en) wird/werden übermittelt, sobald die Netzwerkverbindung wiederhergestellt ist."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Eigene Organisation",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Eigene Inhalte",
                    favoritesLabel: "Eigene Favoriten"
                },
                title: "Webkarte auswählen",
                searchTitle: "Suchen",
                ok: "OK",
                cancel: "Abbrechen",
                placeholder: "Suchbegriff eingeben"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Eigene Organisation",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Eigene Inhalte",
                    favoritesLabel: "Eigene Favoriten"
                },
                title: "Gruppe auswählen",
                searchTitle: "Suchen",
                ok: "OK",
                cancel: "Abbrechen",
                placeholder: "Suchbegriff eingeben"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Hochwert",
            utm_easting: "Rechtswert",
            utm_zone_number: "Zonennummer",
            geoFormGeneralTabText: "1. Informationen eingeben",
            locationInformationText: "2. Position auswählen",
            submitInformationText: "3. Formular ausfüllen",
            submitInstructions: "Fügen Sie der Karte diese Informationen hinzu.",
            myLocationText: "Aktuelle Position",
            locationDescription: "Geben Sie die Position für diesen Eintrag an, indem Sie auf die Karte klicken/tippen oder eine der folgenden Optionen verwenden.",
            addressText: "Suchen",
            geographic: "Breitengrad/Längengrad",
            locationTabText: "Position",
            locationPopupTitle: "Position",
            submitButtonText: "Eintrag senden",
            submitButtonTextLoading: "Wird übermittelt&hellip;",
            formValidationMessageAlertText: "Die folgenden Felder sind erforderlich:",
            selectLocation: "Wählen Sie eine ${openLink}Position${closeLink} für die Übermittlung aus.",
            emptylatitudeAlertMessage: "Geben Sie eine ${openLink}Breitengrad${closeLink}koordinate ein.",
            emptylongitudeAlertMessage: "Geben Sie eine ${openLink}Längengrad${closeLink}koordinate ein.",
            shareUserTitleMessage: "Vielen Dank für Ihren Beitrag!",
            entrySubmitted: "Der Eintrag wurde an die Karte gesendet.",
            shareThisForm: "Dieses Formular freigeben",
            shareUserTextMessage: "Fordern Sie andere Benutzer auf, Inhalte mit den folgenden Optionen bereitzustellen.",
            addAttachmentFailedMessage: "Anlage kann dem Layer nicht hinzugefügt werden",
            addFeatureFailedMessage: "Feature kann dem Layer nicht hinzugefügt werden",
            noLayerConfiguredMessage: "Beim Laden oder Suchen eines editierbaren Feature-Layers ist ein Fehler aufgetreten. Um das Formular anzuzeigen und mit der Erfassung von Übermittlungen zu beginnen, fügen Sie der Webkarte einen editierbaren Feature-Layer hinzu.",
            placeholderLatitude: "Breitengrad (Y)",
            placeholderLongitude: "Längengrad (X)",
            latitude: "Breitengrad",
            longitude: "Längengrad",
            findMyLocation: "Eigenen Standort suchen",
            finding: "Standortsuche&hellip;",
            backToTop: "Nach oben",
            addressSearchText: "Ihr gesendetes Formular wird hier angezeigt. Sie können den Pin ziehen, um die Position zu korrigieren.",
            shareModalFormText: "Formular-Link",
            close: "Schließen",
            locationNotFound: "Position konnte nicht gefunden werden.",
            setLocation: "Position festlegen",
            find: "Adresse oder Ort suchen",
            attachment: "Anlage",
            toggleDropdown: "Dropdown ein-/ausschalten",
            invalidLatLong: "Geben Sie gültige ${latLink}Breitengrad${closeLink}- und ${lngLink}Längengrad${closeLink}koordinaten ein.",
            invalidUTM: "Geben Sie gültige ${openLink}UTM${closeLink}-Koordinaten ein.",
            invalidUSNG: "Geben Sie gültige ${openLink}USNG${closeLink}-Koordinaten ein.",
            invalidMGRS: "Geben Sie gültige ${openLink}MGRS${closeLink}-Koordinaten ein.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Auswählen&hellip;",
            applyEditsFailedMessage: "Ihr Eintrag konnte nicht übermittelt werden. Versuchen Sie es erneut.",
            requiredFields: "Es sind einige Fehler aufgetreten. Beheben Sie sie unten.",
            requiredField: "(erforderlich)",
            error: "Fehler",
            textRangeHintMessage: "${openStrong}Hinweis:${closeStrong} Minimalwert ${minValue} und Maximalwert ${maxValue}",
            dateRangeHintMessage: "${openStrong}Hinweis:${closeStrong} Mindestdatum ${minValue} und maximal auswählbares Datum ${maxValue}"
        },
        builder: {
            invalidUser: "Sie verfügen leider nicht über die Berechtigungen zum Anzeigen dieses Elements",
            invalidWebmapSelectionAlert: "Die ausgewählte Webkarte enthält keinen gültigen Layer. Fügen Sie einen editierbaren Feature-Layer in Ihre Webkarte ein, um den Vorgang fortzusetzen.",
            invalidWebmapSelectionAlert2: "Weitere Informationen finden Sie unter ${openLink}Was ist ein Feature-Service?${closeLink}",
            selectFieldsText: "Formularfelder auswählen",
            selectThemeText: "Formular-Design auswählen",
            webmapText: "Webkarte",
            layerText: "Layer",
            detailsText: "Details",
            fieldsText: "Felder",
            styleText: "Style",
            optionText: "Optionen",
            previewText: "Vorschau",
            publishText: "Veröffentlichen",
            optionsApplicationText: "Optionen",
            titleText: "Builder",
            descriptionText: "GeoForm ist eine konfigurierbare Vorlage zur formularbasierten Datenbearbeitung eines ${link1}Feature-Service${closeLink}. Diese Anwendung ermöglicht die Eingabe von Daten über ein Formular statt über das Pop-up einer Karte und nutzt gleichzeitig das Potenzial der ${link2}Webkarte${closeLink} und editierbarer Feature-Services. Führen Sie die folgenden Schritte aus, um Ihre GeoForm-Vorlage anzupassen und bereitzustellen.",
            btnPreviousText: "Zurück",
            btnNextText: "Weiter",
            webmapTabTitleText: "Webkarte auswählen",
            viewWebmap: "Webkarte anzeigen",
            btnSelectWebmapText: "Webkarte auswählen",
            btnSelectWebmapTextLoading: "Wird geladen&hellip;",
            layerTabTitleText: "Editierbaren Layer auswählen",
            selectLayerLabelText: "Layer",
            selectLayerDefaultOptionText: "Layer auswählen",
            detailsTabTitleText: "Formulardetails",
            detailTitleLabelText: "Titel",
            detailLogoLabelText: "Logo-Bild",
            descriptionLabelText: "Hilfetext (optional)",
            fieldTabFieldHeaderText: "Feld",
            fieldTabLabelHeaderText: "Beschriftung",
            fieldTabDisplayTypeHeaderText: "Anzeigen als",
            selectMenuOption: "Menü auswählen",
            selectRadioOption: "Optionsschaltfläche",
            selectTextOption: "Text",
            selectCheckboxOption: "Kontrollkästchen",
            selectMailOption: "E-Mail",
            selectUrlOption: "URL",
            selectTextAreaOption: "Textbereich",
            previewApplicationText: "Vorschau der Anwendung anzeigen",
            saveApplicationText: "Anwendung speichern",
            saveText: "Speichern",
            toggleNavigationText: "Navigation ein-/ausschalten",
            formPlaceholderText: "Eigenes Formular",
            shareBuilderInProgressTitleMessage: "GeoForm wird veröffentlicht",
            shareBuilderProgressBarMessage: "Bitte warten&hellip;",
            shareBuilderTitleMessage: "Erfolgreich! Element wurde gespeichert",
            shareBuilderTextMessage: "Sie können mit der Erfassung von Informationen beginnen, indem Sie es für andere Benutzer freigeben",
            shareModalFormText: "Formular-Link",
            shareBuilderSuccess: "GeoForm wurde aktualisiert und veröffentlicht!",
            geoformTitleText: "GeoForm",
            layerTabText: "Dies ist der Layer, aus dem die GeoForm erstellt wird. Der Layer muss ein Feature-Service sein, für den die Bearbeitung aktiviert ist, und dessen Freigabeberechtigungen für Ihre Zielgruppe geeignet sind.",
            detailsTabText: "Verwenden Sie die Formulardetailfelder, um den Titel anzupassen, ein benutzerdefiniertes Logo hinzuzufügen und eine kurze Beschreibung Ihrer GeoForm-Zielgruppe bereitzustellen. In der Beschreibung können Sie Links zu anderen Ressourcen sowie Kontaktinformationen hinzufügen und Ihre Zielgruppe sogar auf eine Web Mapping-Anwendung verweisen, die alle in der GeoForm-Vorlage erfassten Daten darstellt.",
            fieldsTabText: "Hier können Sie festlegen welche Felder für Ihre GeoForm-Zielgruppe sichtbar sind, die Beschriftungen bearbeiten, die sie sehen können, und eine kurze Beschreibung hinzufügen, um die Dateneingabe zu vereinfachen.",
            styleTabText: "Legen Sie das GeoForm-Design anhand der folgenden Themen nach Ihren Vorlieben fest.",
            publishTabText: "Wenn Sie Ihre GeoForm-Vorlage angepasst haben, speichern Sie die Anwendung, und teilen Sie diese mit Ihrer Zielgruppe. Sie können jederzeit zu diesem Builder zurückkehren und die Anpassung je nach Feedback fortsetzen.",
            smallHeader: "Kleine Kopfzeile verwenden",
            pushpinText: "Push-Pin",
            doneButtonText: "Anwendungselement anzeigen",
            fieldTabPlaceHolderHeaderText: "Hinweis (optional)",
            attachmentLabelText: "Anlagenbeschriftung",
            attachmentLabelHint: "Informieren Sie Benutzer, welcher Dateityp angehängt werden soll.",
            attachmentDescription: "Anlagenbeschreibung",
            attachmentHint: "Bei Bedarf können Sie hier zusätzliche Anweisungen zu Anlagen bereitstellen.",
            jumbotronDescription: "Das Bootstrap-Jumbotron vereinfacht die Definition des Zwecks Ihrer Anwendung. Diese Option kann jederzeit deaktiviert werden.",
            shareGeoformText: "Geoform freigeben",
            shareDescription: "Das Freigabefenster unterstützt Ihre Zielgruppe bei der Freigabe der GeoForm für andere Kollegen, nachdem sie ein Formular gesendet haben - diese Option kann jederzeit deaktiviert werden.",
            defaultMapExtent: "Standardmäßige Kartenausdehnung",
            defaultMapExtentDescription: "Die Karte wird nach der Übermittlung in Ihrer Webkarte auf die Standardausdehnung zurückgesetzt - diese Option kann jederzeit deaktiviert werden.",
            pushpinOptionsDescription: "Treffen Sie eine Auswahl aus einer Vielzahl von Farben für den Karten-Push-Pin, der sich von der Kartensymbologie unterscheiden sollte, um dem Benutzer die Positionierung der Übermittlung auf der Karte zu erleichtern",
            selectLocationText: "Position auswählen nach",
            myLocationText: "Eigener Standort",
            searchText: "Suchen",
            coordinatesText: "Breiten- und Längengradkoordinaten",
            usng: "USNG-Koordinaten",
            mgrs: "MGRS-Koordinaten",
            utm: "UTM-Koordinaten",
            selectLocationSDescription: "Benutzern das Auswählen einer Position anhand dieser Methoden erlauben."
        }
    })
);