define({
  "map": {
    "error": "Karte kann nicht erstellt werden"
  },
  "onlineStatus": {
    "offline": "Sie arbeiten derzeit offline. Gesendete Formulare werden lokal gespeichert, bis eine Verbindung mit dem Server hergestellt werden kann.",
    "reconnecting": "Verbindung erneut herstellen&hellip;",
    "pending": "${total} ausstehende Änderung(en) wird/werden übermittelt, sobald die Netzwerkverbindung wiederhergestellt ist."
  },
  "configure": {
    "mapdlg": {
      "items": {
        "organizationLabel": "Eigene Organisation",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "Eigene Inhalte",
        "favoritesLabel": "Eigene Favoriten"
      },
      "title": "Webkarte auswählen",
      "searchTitle": "Suchen",
      "ok": "OK",
      "cancel": "Abbrechen",
      "placeholder": "Suchbegriff eingeben"
    },
    "groupdlg": {
      "items": {
        "organizationLabel": "Eigene Organisation",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "Eigene Inhalte",
        "favoritesLabel": "Eigene Favoriten"
      },
      "title": "Gruppe auswählen",
      "searchTitle": "Suchen",
      "ok": "OK",
      "cancel": "Abbrechen",
      "placeholder": "Suchbegriff eingeben"
    },
    "sharedlg": {
      "items": {},
      "mailtoLinkDescription": "Im Folgenden finden Sie einen Link zu einer GeoForm"
    }
  },
  "user": {
    "all": "Alle",
    "mgrs": "MGRS",
    "usng": "USNG",
    "utm": "UTM",
    "utm_northing": "Hochwert",
    "utm_easting": "Rechtswert",
    "utm_zone_number": "Zonennummer",
    "selectLayerTabText": "${formSection} Formular auswählen",
    "geoFormGeneralTabText": "${formSection} Informationen eingeben",
    "locationInformationText": "${formSection} Position auswählen",
    "submitInformationText": "${formSection} Formular ausfüllen",
    "submitInstructions": "Fügen Sie der Karte diese Informationen hinzu.",
    "myLocationText": "Aktuelle Position",
    "locationDescriptionForMoreThanOneOption": "Geben Sie die Position für diesen Eintrag an, indem Sie auf die Karte klicken/tippen oder eine der folgenden Optionen verwenden.",
    "locationDescriptionForOneOption": "Geben Sie die Position für diesen Eintrag an, indem Sie auf die Karte klicken/tippen oder die folgende Option verwenden.",
    "locationDescriptionForNoOption": "Geben Sie die Position für diesen Eintrag an, indem Sie auf die Karte klicken/tippen.",
    "addressText": "Suchen",
    "geographic": "Breitengrad/Längengrad",
    "locationTabText": "Position",
    "locationPopupTitle": "Position",
    "submitButtonText": "Eintrag senden",
    "submitButtonTextLoading": "Wird übermittelt&hellip;",
    "formValidationMessageAlertText": "Die folgenden Felder sind erforderlich:",
    "selectLocation": "Wählen Sie eine Position für die Eingaben aus.",
    "emptylatitudeAlertMessage": "Geben Sie eine ${openLink}Breitengrad${closeLink}koordinate ein.",
    "emptylongitudeAlertMessage": "Geben Sie eine ${openLink}Längengrad${closeLink}koordinate ein.",
    "shareUserTitleMessage": "Vielen Dank für Ihren Beitrag!",
    "entrySubmitted": "Der Eintrag wurde an die Karte gesendet.",
    "shareThisForm": "Dieses Formular freigeben",
    "shareUserTextMessage": "Fordern Sie andere Benutzer auf, Inhalte mit den folgenden Optionen bereitzustellen.",
    "addAttachmentFailedMessage": "Anlage kann dem Layer nicht hinzugefügt werden",
    "addFeatureFailedMessage": "Feature kann dem Layer nicht hinzugefügt werden",
    "noLayerConfiguredMessage": "Beim Laden oder Suchen eines editierbaren Feature-Layers ist ein Fehler aufgetreten. Um das Formular anzuzeigen und mit der Erfassung von Eingaben zu beginnen, fügen Sie der Webkarte einen editierbaren Feature-Layer hinzu.",
    "placeholderLatitude": "Breitengrad (Y)",
    "placeholderLongitude": "Längengrad (X)",
    "latitude": "Breitengrad",
    "longitude": "Längengrad",
    "findMyLocation": "Eigenen Standort suchen",
    "finding": "Standortsuche&hellip;",
    "backToTop": "Nach oben",
    "addressSearchText": "Ihr gesendetes Formular wird hier angezeigt. Sie können den Pin ziehen, um die Position zu korrigieren.",
    "shareModalFormText": "Formular-Link",
    "close": "Schließen",
    "locationNotFound": "Position wurde nicht gefunden.",
    "setLocation": "Position festlegen",
    "find": "Adresse oder Ort suchen",
    "attachment": "Anlage",
    "toggleDropdown": "Dropdown ein-/ausschalten",
    "invalidString": "Geben Sie einen gültigen Wert ein.",
    "invalidSmallNumber": "Geben Sie einen gültigen ${openStrong}ganzzahligen${closeStrong} Wert zwischen -32768 und 32767 ein.",
    "invalidNumber": "Geben Sie einen gültigen ${openStrong}ganzzahligen${closeStrong} Wert zwischen -2147483648 und 2147483647 ein.",
    "invalidFloat": "Geben Sie einen gültigen ${openStrong}Gleitkomma${closeStrong}wert ein.",
    "invalidDouble": "Geben Sie einen gültigen ${openStrong}Double${closeStrong}-Wert ein.",
    "invalidLatLong": "Geben Sie gültige Breitengrad- und Längengradkoordinaten ein.",
    "invalidUTM": "Geben Sie gültige UTM-Koordinaten ein.",
    "invalidUSNG": "Geben Sie gültige USNG-Koordinaten ein.",
    "invalidMGRS": "Geben Sie gültige MGRS-Koordinaten ein.",
    "geoformTitleText": "GeoForm",
    "domainDefaultText": "Auswählen&hellip;",
    "applyEditsFailedMessage": "Ihr Eintrag konnte nicht übermittelt werden. Versuchen Sie es erneut.",
    "requiredFields": "Das folgende Feld ist erforderlich. Nehmen Sie eine gültige Eingabe vor.",
    "requiredField": "(erforderlich)",
    "error": "Fehler",
    "textRangeHintMessage": "${openStrong}Hinweis:${closeStrong} Minimalwert ${minValue} und Maximalwert ${maxValue}",
    "dateRangeHintMessage": "${openStrong}Hinweis:${closeStrong} Mindestdatum ${minValue} und maximal auswählbares Datum ${maxValue}",
    "remainingCharactersHintMessage": "${value} verbleibende Zeichen",
    "mapFullScreen": "Vollbild",
    "mapRestore": "Wiederherstellen",
    "filterSelectEmptyText": "Auswählen",
    "invalidLayerMessage": "Es wurde kein gültiger Layer zum Erstellen des GeoForm gefunden. Falls das GeoForm mit einem Layer konfiguriert wurde, ist dieser möglicherweise nicht mehr verfügbar oder die Autorisierung war nicht erfolgreich.",
    "selectedLayerText": "Alle",
    "fileUploadStatus": "Upload-Status der Datei",
    "uploadingBadge": "&nbsp;Wird hochgeladen&hellip;",
    "successBadge": "&nbsp;Hochgeladen",
    "retryBadge": "Wiederholen",
    "errorBadge": "Fehler beim Hochladen&nbsp;&nbsp;&nbsp;",
    "fileTooLargeError": "Datei ist zu groß, um sie anzuhängen",
    "exceededFileCountError": "Maximal zulässige Anzahl von Anlagen wurde überschritten",
    "selectFileTitle": "Datei auswählen",
    "btnSelectFileText": "Datei auswählen",
    "btnViewSubmissions": "Übermittlungen anzeigen"
  },
  "builder": {
    "gettingStarted": "Erste Schritte",
    "dateSettings": "Datumseinstellungen",
    "hiddenDateField": "Dieses Datumsfeld ausblenden",
    "preventPastDates": "In der Vergangenheit liegendes Datum vermeiden",
    "preventFutureDates": "In der Zukunft liegendes Datum vermeiden",
    "useCurrentDate": "Legen Sie in diesem Feld das aktuelle Datum und die aktuelle Uhrzeit fest",
    "configure": "Konfigurieren",
    "configureField": "Das Feld '${fieldName}' konfigurieren",
    "invalidUser": "Sie verfügen leider nicht über die Berechtigungen zum Anzeigen dieses Elements",
    "invalidWebmapSelectionAlert": "Die ausgewählte Webkarte enthält keinen gültigen Layer. Fügen Sie einen editierbaren Feature-Layer in Ihre Webkarte ein, um den Vorgang fortzusetzen.",
    "invalidWebmapSelectionAlert2": "Weitere Informationen finden Sie unter ${openLink}Was ist ein Feature-Service?${closeLink}",
    "selectFieldsText": "Formularfelder auswählen",
    "selectThemeText": "Formular-Design auswählen",
    "setViewerText": "Viewer konfigurieren",
    "introText": "Starten",
    "webmapText": "Webkarte",
    "layerText": "Layer",
    "detailsText": "Details",
    "fieldsText": "Felder",
    "styleText": "Style",
    "viewerText": "Viewer",
    "optionText": "Optionen",
    "previewText": "Vorschau",
    "publishText": "Veröffentlichen",
    "optionsApplicationText": "Optionen",
    "submitButtonText": "Text für die Schaltfläche \"Senden\" (optional)",
    "submitButtonDesc": "Optionale Beschriftung für die Schaltfläche zum Senden eines neuen Eintrags. Dieser Text wird nicht übersetzt.",
    "viewSubmissionsText": "Text zum Anzeigen übermittelter Daten (optional)",
    "viewSubmissionsDesc": "Optionale Beschriftung für die Schaltfläche zum Anzeigen der vorhandenen Einträge. Dieser Text wird nicht übersetzt.",
    "titleText": "Builder",
    "descriptionText": "GeoForm ist eine konfigurierbare Vorlage zur formularbasierten Datenbearbeitung eines ${link1}Feature-Service${closeLink}. Diese Anwendung ermöglicht die Eingabe von Daten über ein Formular statt über das Pop-up einer Karte und nutzt gleichzeitig das Potenzial der ${link2}Webkarte${closeLink} und editierbarer Feature-Services. Führen Sie die folgenden Schritte aus, um Ihre GeoForm-Vorlage anzupassen und bereitzustellen.",
    "btnPreviousText": "Zurück",
    "btnNextText": "Weiter",
    "webmapTabTitleText": "Webkarte auswählen",
    "viewWebmap": "Webkarte anzeigen",
    "webmapDetailsText": "Die ausgewählte Webkarte ist ${webMapTitleLink}${webMapTitle}${closeLink}. Um eine andere Webkarte auszuwählen, klicken Sie auf die Schaltfläche 'Webkarte auswählen'",
    "btnSelectWebmapText": "Webkarte auswählen",
    "btnSelectWebmapTextLoading": "Wird geladen&hellip;",
    "layerTabTitleText": "Editierbare(n) Layer auswählen",
    "selectLayerLabelText": "Layer",
    "selectLayerDefaultOptionText": "Layer auswählen",
    "enableBasemapToggle": "\"Grundkarte wechseln\" anzeigen",
    "enableBasemapToggleDescription": "Sie können das GeoForm konfigurieren, um \"Grundkarte wechseln\" ein-/auszublenden",
    "defaultBasemap": "Grundkarte wechseln",
    "secondaryBasemap": "Standardgrundkarte",
    "detailsTabTitleText": "Formulardetails",
    "detailTitleLabelText": "Titel",
    "detailLogoLabelText": "Logo-Bild",
    "descriptionLabelText": "Formularanweisungen und Details",
    "fieldDescriptionLabelText": "Hilfetext (optional)",
    "fieldDescriptionHelpText": "Geben Sie eine kurze Beschreibung oder Anweisung für dieses Feld ein.",
    "fieldHintHelpText": "Platzhaltertext für das Feld.",
    "fieldTabFieldHeaderText": "Feld",
    "fieldTabLabelHeaderText": "Beschriftung",
    "fieldTabDisplayTypeHeaderText": "Anzeigen als",
    "fieldTabOrderColumnText": "Auftrag",
    "fieldTabVisibleColumnText": "Aktiviert",
    "displayFieldText": "Anzeigefeld",
    "selectMenuOption": "Menü auswählen",
    "selectRadioOption": "Optionsschaltfläche",
    "selectTextOption": "Text",
    "selectDateOption": "Datumsauswahl",
    "selectRangeOption": "Berührungssensitives Drehfeld",
    "selectCheckboxOption": "Kontrollkästchen",
    "selectMailOption": "E-Mail",
    "selectUrlOption": "URL",
    "selectTextAreaOption": "Textbereich",
    "previewApplicationText": "Vorschau der Anwendung anzeigen",
    "saveApplicationText": "Anwendung speichern",
    "saveText": "Speichern",
    "toggleNavigationText": "Navigation ein-/ausschalten",
    "formPlaceholderText": "Eigenes Formular",
    "shareBuilderInProgressTitleMessage": "GeoForm wird veröffentlicht",
    "shareBuilderProgressBarMessage": "Bitte warten&hellip;",
    "shareBuilderTitleMessage": "Erfolgreich! Element wurde gespeichert",
    "shareBuilderTextMessage": "Sie können mit der Erfassung von Informationen beginnen, indem Sie es für andere Benutzer freigeben",
    "shareModalFormText": "Formular-Link",
    "shareBuilderSuccess": "GeoForm wurde aktualisiert und veröffentlicht!",
    "geoformTitleText": "GeoForm",
    "layerTabText": "Dies ist/sind der/die Layer, aus dem/denen das GeoForm erstellt wird. Der Layer muss ein Feature-Service sein, der zum Bearbeiten mit Freigabeberechtigungen aktiviert ist, die Ihrer Zielgruppe entsprechen. Wenn alle Layer ausgewählt sind, kann ein Benutzer über das Formular auswählen, an welchen Formular-Layer die Daten gesendet werden sollen.",
    "detailsTabText": "Verwenden Sie die Formulardetailfelder, um den Titel anzupassen, ein benutzerdefiniertes Logo hinzuzufügen und eine kurze Beschreibung Ihrer GeoForm-Zielgruppe bereitzustellen. In der Beschreibung können Sie Links zu anderen Ressourcen sowie Kontaktinformationen hinzufügen und Ihre Zielgruppe sogar auf eine Web Mapping-Anwendung verweisen, die alle in der GeoForm-Vorlage erfassten Daten darstellt.",
    "fieldsTabText": "Hier können Sie festlegen welche Felder für Ihre GeoForm-Zielgruppe sichtbar sind, die Beschriftungen bearbeiten, die sie sehen können, und eine kurze Beschreibung hinzufügen, um die Dateneingabe zu vereinfachen.",
    "styleTabText": "Legen Sie das GeoForm-Design anhand der folgenden Themen nach Ihren Vorlieben fest.",
    "viewerTabText": "Legen Sie Optionen zum Anzeigen übermittelter Daten fest, die über das GeoForm erfasst wurden.",
    "publishTabText": "Wenn Sie Ihre GeoForm-Vorlage angepasst haben, speichern Sie die Anwendung, und teilen Sie diese mit Ihrer Zielgruppe. Sie können jederzeit zu diesem Builder zurückkehren und die Anpassung je nach Feedback fortsetzen.",
    "headerSizeLabel": "Kopfzeilengröße",
    "smallHeader": "Kleine Kopfzeile verwenden",
    "bigHeader": "Große Kopfzeile verwenden",
    "pushpinText": "Push-Pin",
    "doneButtonText": "Speichern und beenden",
    "fieldTabPlaceHolderHeaderText": "Hinweis (optional)",
    "enableAttachmentLabelText": "${openStrong}Anlagen aktivieren${closeStrong}",
    "enableAttachmentLabelHint": "Anlagen können hier aktiviert/deaktiviert werden",
    "attachmentIsRequiredLabelText": "${openStrong}Anlage erforderlich${closeStrong}",
    "attachmentIsRequiredLabelHint": "Bei Bedarf kann die Eingabe einer Anlage durch den Benutzer erforderlich sein.",
    "attachmentLabelText": "Beschriftung der Schaltfläche \"Anlage\"",
    "attachmentLabelHint": "Dieser Text wird neben der Schaltfläche \"Anlage\" angezeigt. In diesem Bereich können Sie die Elemente, die Ihre Zielgruppe anhängen soll (Foto, Video, Dokument usw.) und das erforderliche Dateiformat (.jpeg, .png, .docx, .pdf usw.) beschreiben sowie zusätzliche Anweisungen bereitstellen",
    "attachmentDescription": "Anlagenbeschreibung",
    "attachmentHint": "Bei Bedarf können Sie hier zusätzliche Anweisungen zu Anlagen bereitstellen.",
    "jumbotronDescription": "Eine kleine oder große Überschrift für Ihr Formular verwenden. Eine große Kopfzeile vereinfacht die Definition des Zwecks Ihrer Anwendung, beansprucht jedoch auch mehr Platz auf Ihrem Bildschirm.",
    "shareGeoformText": "Freigabeschaltflächen für Social Media",
    "shareDescription": "Mit Schaltflächen für Social Media kann Ihre Zielgruppe Ihr GeoForm nach dem Senden der Daten problemlos freigeben",
    "defaultMapExtent": "Standardmäßige Kartenausdehnung",
    "defaultMapExtentDescription": "Die Karte wird nach der Übermittlung in Ihrer Webkarte auf die Standardausdehnung zurückgesetzt - diese Option kann jederzeit deaktiviert werden.",
    "pushpinOptionsDescription": "Treffen Sie eine Auswahl aus einer Vielzahl von Farben für den Karten-Push-Pin, der sich von der Kartensymbolisierung unterscheiden sollte, um dem Benutzer die Positionierung der Übermittlung auf der Karte zu erleichtern",
    "selectLocationText": "Position auswählen nach",
    "myLocationText": "Eigener Standort",
    "searchText": "Suchen",
    "coordinatesText": "Breiten- und Längengradkoordinaten",
    "usng": "USNG-Koordinaten",
    "mgrs": "MGRS-Koordinaten",
    "utm": "UTM-Koordinaten",
    "selectLocationSDescription": "Benutzern das Auswählen einer Position anhand dieser Methoden erlauben.",
    "dragTooltipText": "Das Feld an die Position ziehen, an der es angezeigt werden soll",
    "showHideLayerText": "Layer anzeigen",
    "showHideLayerHelpText": "Sie können das GeoForm konfigurieren, um den Layer ein-/auszublenden. Diese Option gilt nur für eine einzelne Layer-Einrichtung.",
    "enableOfflineSupport": "Offline-Unterstützung aktivieren",
    "enableOfflineSupportHelpText": "Übermittelte Daten bei fehlender Netzwerkverbindung speichern und erst übertragen, wenn eine Verbindung hergestellt wurde.",
    "labelHelpMessage": "Beschriftung",
    "placeHolderHintMessage": "Hinweistext",
    "placeHolderHelpMessage": "Hilfetext",
    "selectTextOptionValue": "Filterauswahl",
    "disableLogo": "Logo deaktivieren",
    "disableLogoDescription": "Sie können das GeoForm konfigurieren, um das Logo in der Formularkopfzeile ein-/auszublenden",
    "locateOnLoadText": "Beim Laden suchen",
    "locateOnLoadDescription": "Sie können das GeoForm konfigurieren, um die aktuelle Position auf der Seite beim Laden zu verwenden",
    "selectLayerFieldTabText": "Layer auswählen",
    "allLayerSelectOptionText": "Alle Layer",
    "disableViewer": "Viewer deaktivieren",
    "disableViewerDescription": "Sie können das GeoForm konfigurieren, um den Viewer zu deaktivieren/aktivieren",
    "displayFieldHintText": "Ausgewähltes Anzeigefeld wird im Viewer als Titel angezeigt"
  },
  "viewer": {
    "geocoderCancelText": "Abbrechen",
    "viewMapTabText": "Karte",
    "sortHeaderText": "Sortieren nach:",
    "geocoderPlaceholderText": "Postleitzahl, Stadt usw.",
    "noSearchResult": "Kein Ergebnis gefunden",
    "legendTabTooltip": "Legende",
    "aboutUsTabTooltip": "Über uns",
    "mapTabTooltip": "Karte",
    "btnDescendingText": "Absteigend",
    "btnAscendingText": "Aufsteigend",
    "geometryUnavailableErrorMessage": "Die Geometrie des Features konnte nicht gefunden werden",
    "infoPopupOffErrorMessage": "Keine Informationen zur Anzeige verfügbar",
    "btnLoadMoreText": "Weitere laden",
    "unavailableTitleText": "Unbenannt",
    "unavailableConfigMessage": "Konfiguration kann nicht geladen werden",
    "share": "Freigeben",
    "viewReportsTabText": "Berichte",
    "viewLegendTabText": "Legende",
    "viewAboutusTabText": "Info",
    "appLoadingFailedMessage": "Beim Laden des Viewers ist ein Fehler aufgetreten"
  }
});