define(
   ({
    map: {
      error: "Karte kann nicht erstellt werden"
    },
    onlineStatus: {
      offline: "Sie arbeiten derzeit offline. Gesendete Formulare werden lokal gespeichert, bis eine Verbindung mit dem Server hergestellt werden kann.",
      reconnecting: "Verbindung erneut herstellen&hellip;",
      pending: "${total} ausstehende Änderung(en) wird/werden übermittelt, sobald die Netzwerkverbindung wiederhergestellt ist."
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "Eigene Organisation",
          onlineLabel: "ArcGIS Online",
          contentLabel: "Eigene Inhalte",
          favoritesLabel: "Eigene Favoriten"
        },
        title: "Webkarte auswählen",
        searchTitle: "Suchen",
        ok: "OK",
        cancel: "Abbrechen",
        placeholder: "Suchbegriff eingeben"
      },
      groupdlg: {
        items: {
          organizationLabel: "Eigene Organisation",
          onlineLabel: "ArcGIS Online",
          contentLabel: "Eigene Inhalte",
          favoritesLabel: "Eigene Favoriten"
        },
        title: "Gruppe auswählen",
        searchTitle: "Suchen",
        ok: "OK",
        cancel: "Abbrechen",
        placeholder: "Suchbegriff eingeben"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "Im Folgenden finden Sie einen Link zu einer GeoForm"
      }
    },
    user: {
      all: "ä_All__Ü",
      mgrs: "MGRS",
      usng: "USNG",
      utm: "UTM",
      utm_northing: "Hochwert",
      utm_easting: "Rechtswert",
      utm_zone_number: "Zonennummer",
      selectLayerTabText: "${formSection} Formular auswählen",
      geoFormGeneralTabText: "${formSection} Informationen eingeben",
      locationInformationText: "${formSection} Position auswählen",
      submitInformationText: "${formSection} Formular ausfüllen",
      submitInstructions: "Fügen Sie der Karte diese Informationen hinzu.",
      myLocationText: "Aktuelle Position",
      locationDescriptionForMoreThanOneOption: "Geben Sie die Position für diesen Eintrag an, indem Sie auf die Karte klicken/tippen oder eine der folgenden Optionen verwenden.",
      locationDescriptionForOneOption: "Geben Sie die Position für diesen Eintrag an, indem Sie auf die Karte klicken/tippen oder die folgende Option verwenden.",
      locationDescriptionForNoOption: "Geben Sie die Position für diesen Eintrag an, indem Sie auf die Karte klicken/tippen.",
      addressText: "Suchen",
      geographic: "Breitengrad/Längengrad",
      locationTabText: "Position",
      locationPopupTitle: "Position",
      submitButtonText: "Eintrag senden",
      submitButtonTextLoading: "Wird übermittelt&hellip;",
      formValidationMessageAlertText: "Die folgenden Felder sind erforderlich:",
      selectLocation: "Wählen Sie eine Position für die Eingaben aus.",
      emptylatitudeAlertMessage: "Geben Sie eine ${openLink}Breitengrad${closeLink}koordinate ein.",
      emptylongitudeAlertMessage: "Geben Sie eine ${openLink}Längengrad${closeLink}koordinate ein.",
      shareUserTitleMessage: "Vielen Dank für Ihren Beitrag!",
      entrySubmitted: "Der Eintrag wurde an die Karte gesendet.",
      shareThisForm: "Dieses Formular freigeben",
      shareUserTextMessage: "Fordern Sie andere Benutzer auf, Inhalte mit den folgenden Optionen bereitzustellen.",
      addAttachmentFailedMessage: "Anlage kann dem Layer nicht hinzugefügt werden",
      addFeatureFailedMessage: "Feature kann dem Layer nicht hinzugefügt werden",
      noLayerConfiguredMessage: "Beim Laden oder Suchen eines editierbaren Feature-Layers ist ein Fehler aufgetreten. Um das Formular anzuzeigen und mit der Erfassung von Eingaben zu beginnen, fügen Sie der Webkarte einen editierbaren Feature-Layer hinzu.",
      placeholderLatitude: "Breitengrad (Y)",
      placeholderLongitude: "Längengrad (X)",
      latitude: "Breitengrad",
      longitude: "Längengrad",
      findMyLocation: "Eigenen Standort suchen",
      finding: "Standortsuche&hellip;",
      backToTop: "Nach oben",
      addressSearchText: "Ihr gesendetes Formular wird hier angezeigt. Sie können den Pin ziehen, um die Position zu korrigieren.",
      shareModalFormText: "Formular-Link",
      close: "Schließen",
      locationNotFound: "Position wurde nicht gefunden.",
      setLocation: "Position festlegen",
      find: "Adresse oder Ort suchen",
      attachment: "Anlage",
      toggleDropdown: "Dropdown ein-/ausschalten",
      invalidString: "ä_Please enter a valid value_________Ü.",
      invalidSmallNumber: "ä_Please enter a valid ${openStrong}integer${closeStrong} value between -32768 and 32767___________________________Ü.",
      invalidNumber: "Geben Sie einen gültigen ${openStrong}Ganzzahl${closeStrong}wert zwischen -2147483648 und 2147483647 ein.",
      invalidFloat: "Geben Sie einen gültigen ${openStrong}Gleitkomma${closeStrong}wert ein.",
      invalidDouble: "Geben Sie einen gültigen ${openStrong}Double${closeStrong}-Wert ein.",
      invalidLatLong: "Geben Sie gültige Breitengrad- und Längengradkoordinaten ein.",
      invalidUTM: "Geben Sie gültige UTM-Koordinaten ein.",
      invalidUSNG: "Geben Sie gültige USNG-Koordinaten ein.",
      invalidMGRS: "Geben Sie gültige MGRS-Koordinaten ein.",
      geoformTitleText: "GeoForm",
      domainDefaultText: "Auswählen&hellip;",
      applyEditsFailedMessage: "Ihr Eintrag konnte nicht übermittelt werden. Versuchen Sie es erneut.",
      requiredFields: "ä_The following field is required. Please provide a valid entry____________________Ü.",
      requiredField: "(erforderlich)",
      error: "Fehler",
      textRangeHintMessage: "${openStrong}Hinweis:${closeStrong} Minimalwert ${minValue} und Maximalwert ${maxValue}",
      dateRangeHintMessage: "${openStrong}Hinweis:${closeStrong} Mindestdatum ${minValue} und maximal auswählbares Datum ${maxValue}",
      remainingCharactersHintMessage: "${value} verbleibende Zeichen",
      mapFullScreen: "Vollbild",
      mapRestore: "Wiederherstellen",
      filterSelectEmptyText: "Auswählen",
      invalidLayerMessage: "Formular-Layer ist nicht vorhanden. Konfigurieren Sie die Anwendung, und legen Sie den Layer fest.",
      selectedLayerText: "Alle",
      fileUploadStatus: "Upload-Status der Datei",
      uploadingBadge: "&nbsp;Wird hochgeladen&hellip;",
      successBadge: "&nbsp;Hochgeladen",
      retryBadge: "Wiederholen",
      errorBadge: "Fehler beim Hochladen&nbsp;&nbsp;&nbsp;",
      fileTooLargeError: "Datei ist zu groß, um sie anzuhängen",
      exceededFileCountError: "ä_Exceeded maximum number of attachments allowed_______________Ü",
      selectFileTitle: "Datei auswählen",
      btnSelectFileText: "ä_Select File____Ü",
      btnViewSubmissions: "Übermittlungen anzeigen"
    },
    builder: {
      gettingStarted: "ä_Getting Started______Ü",
      dateSettings: "ä_Date Settings_____Ü",
      hiddenDateField: "ä_Hide this date field_______Ü",
      preventPastDates: "ä_Prevent past dates______Ü",
      preventFutureDates: "ä_Prevent future dates_______Ü",
      useCurrentDate: "ä_Set this field with the current date and time_______________Ü",
      configure: "ä_Configure____Ü",
      configureField: "ä_Configure Field '${fieldName}'__________Ü",
      invalidUser: "Sie verfügen leider nicht über die Berechtigungen zum Anzeigen dieses Elements",
      invalidWebmapSelectionAlert: "Die ausgewählte Webkarte enthält keinen gültigen Layer. Fügen Sie einen editierbaren Feature-Layer in Ihre Webkarte ein, um den Vorgang fortzusetzen.",
      invalidWebmapSelectionAlert2: "Weitere Informationen finden Sie unter ${openLink}Was ist ein Feature-Service?${closeLink}",
      selectFieldsText: "Formularfelder auswählen",
      selectThemeText: "Formular-Design auswählen",
      setViewerText: "ä_Configure Viewer______Ü",
      introText: "ä_Start___Ü",
      webmapText: "Webkarte",
      layerText: "Layer",
      detailsText: "Details",
      fieldsText: "Felder",
      styleText: "Style",
      viewerText: "ä_Viewer___Ü",
      optionText: "Optionen",
      previewText: "Vorschau",
      publishText: "Veröffentlichen",
      optionsApplicationText: "Optionen",
      titleText: "Builder",
      descriptionText: "GeoForm ist eine konfigurierbare Vorlage zur formularbasierten Datenbearbeitung eines ${link1}Feature-Service${closeLink}. Diese Anwendung ermöglicht die Eingabe von Daten über ein Formular statt über das Pop-up einer Karte und nutzt gleichzeitig das Potenzial der ${link2}Webkarte${closeLink} und editierbarer Feature-Services. Führen Sie die folgenden Schritte aus, um Ihre GeoForm-Vorlage anzupassen und bereitzustellen.",
      btnPreviousText: "Zurück",
      btnNextText: "Weiter",
      webmapTabTitleText: "Webkarte auswählen",
      viewWebmap: "Webkarte anzeigen",
      webmapDetailsText: "Die ausgewählte Webkarte ist ${webMapTitleLink}${webMapTitle}${closeLink}. Um eine andere Webkarte auszuwählen, klicken Sie auf die Schaltfläche \'Webkarte auswählen\'",
      btnSelectWebmapText: "Webkarte auswählen",
      btnSelectWebmapTextLoading: "Wird geladen&hellip;",
      layerTabTitleText: "ä_Select Editable Layer(s)________Ü",
      selectLayerLabelText: "Layer",
      selectLayerDefaultOptionText: "Layer auswählen",
      enableBasemapToggle: "ä_Show Basemap Toggle_______Ü",
      enableBasemapToggleDescription: "ä_You can configure the GeoForm to Show/Hide the Basemap Toggle___________________Ü",
      defaultBasemap: "Grundkarte wechseln",
      secondaryBasemap: "Standardgrundkarte",
      detailsTabTitleText: "Formulardetails",
      detailTitleLabelText: "Titel",
      detailLogoLabelText: "Logo-Bild",
      descriptionLabelText: "Formularanweisungen und Details",
      fieldDescriptionLabelText: "Hilfetext (optional)",
      fieldDescriptionHelpText: "ä_Provide a short description or instructions for this field___________________Ü.",
      fieldHintHelpText: "ä_Placeholder text for the field__________Ü.",
      fieldTabFieldHeaderText: "Feld",
      fieldTabLabelHeaderText: "Beschriftung",
      fieldTabDisplayTypeHeaderText: "Anzeigen als",
      fieldTabOrderColumnText: "Auftrag",
      fieldTabVisibleColumnText: "Aktiviert",
      displayFieldText: "Anzeigefeld",
      selectMenuOption: "Menü auswählen",
      selectRadioOption: "Optionsschaltfläche",
      selectTextOption: "Text",
      selectDateOption: "Datumsauswahl",
      selectRangeOption: "Berührungssensitives Drehfeld",
      selectCheckboxOption: "Kontrollkästchen",
      selectMailOption: "E-Mail",
      selectUrlOption: "URL",
      selectTextAreaOption: "Textbereich",
      previewApplicationText: "Vorschau der Anwendung anzeigen",
      saveApplicationText: "Anwendung speichern",
      saveText: "Speichern",
      toggleNavigationText: "Navigation ein-/ausschalten",
      formPlaceholderText: "Eigenes Formular",
      shareBuilderInProgressTitleMessage: "GeoForm wird veröffentlicht",
      shareBuilderProgressBarMessage: "Bitte warten&hellip;",
      shareBuilderTitleMessage: "Erfolgreich! Element wurde gespeichert",
      shareBuilderTextMessage: "Sie können mit der Erfassung von Informationen beginnen, indem Sie es für andere Benutzer freigeben",
      shareModalFormText: "Formular-Link",
      shareBuilderSuccess: "GeoForm wurde aktualisiert und veröffentlicht!",
      geoformTitleText: "GeoForm",
      layerTabText: "ä_This is the layer(s) that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience. If all layers are selected, the form will allow a user to choose which form layer to submit to___________________________________________________________________________________Ü.",
      detailsTabText: "Verwenden Sie die Formulardetailfelder, um den Titel anzupassen, ein benutzerdefiniertes Logo hinzuzufügen und eine kurze Beschreibung Ihrer GeoForm-Zielgruppe bereitzustellen. In der Beschreibung können Sie Links zu anderen Ressourcen sowie Kontaktinformationen hinzufügen und Ihre Zielgruppe sogar auf eine Web Mapping-Anwendung verweisen, die alle in der GeoForm-Vorlage erfassten Daten darstellt.",
      fieldsTabText: "Hier können Sie festlegen welche Felder für Ihre GeoForm-Zielgruppe sichtbar sind, die Beschriftungen bearbeiten, die sie sehen können, und eine kurze Beschreibung hinzufügen, um die Dateneingabe zu vereinfachen.",
      styleTabText: "Legen Sie das GeoForm-Design anhand der folgenden Themen nach Ihren Vorlieben fest.",
      viewerTabText: "ä_Set options for viewing submissions collected from the GeoForm____________________Ü.",
      publishTabText: "Wenn Sie Ihre GeoForm-Vorlage angepasst haben, speichern Sie die Anwendung, und teilen Sie diese mit Ihrer Zielgruppe. Sie können jederzeit zu diesem Builder zurückkehren und die Anpassung je nach Feedback fortsetzen.",
      headerSizeLabel: "Kopfzeilengröße",
      smallHeader: "Kleine Kopfzeile verwenden",
      bigHeader: "Große Kopfzeile verwenden",
      pushpinText: "Push-Pin",
      doneButtonText: "Speichern und beenden",
      fieldTabPlaceHolderHeaderText: "Hinweis (optional)",
      enableAttachmentLabelText: "${openStrong}Anlagen aktivieren${closeStrong}",
      enableAttachmentLabelHint: "Anlagen können hier aktiviert/deaktiviert werden",
      attachmentIsRequiredLabelText: "${openStrong}Anlage erforderlich${closeStrong}",
      attachmentIsRequiredLabelHint: "Bei Bedarf kann die Eingabe einer Anlage durch den Benutzer erforderlich sein.",
      attachmentLabelText: "Beschriftung der Schaltfläche \"Anlage\"",
      attachmentLabelHint: "Dieser Text wird neben der Schaltfläche \"Anlage\" angezeigt. In diesem Bereich können Sie die Elemente, die Ihre Zielgruppe anhängen soll (Foto, Video, Dokument usw.) und das erforderliche Dateiformat (.jpeg, .png, .docx, .pdf usw.) beschreiben sowie zusätzliche Anweisungen bereitstellen",
      attachmentDescription: "Anlagenbeschreibung",
      attachmentHint: "Bei Bedarf können Sie hier zusätzliche Anweisungen zu Anlagen bereitstellen.",
      jumbotronDescription: "Eine kleine oder große Überschrift für Ihr Formular verwenden. Eine große Kopfzeile vereinfacht die Definition des Zwecks Ihrer Anwendung, beansprucht jedoch auch mehr Platz auf Ihrem Bildschirm.",
      shareGeoformText: "ä_Social media sharing buttons_________Ü",
      shareDescription: "ä_Social media buttons allow your audience to easily share your GeoForm once they have made a submission________________________________Ü",
      defaultMapExtent: "Standardmäßige Kartenausdehnung",
      defaultMapExtentDescription: "Die Karte wird nach der Übermittlung in Ihrer Webkarte auf die Standardausdehnung zurückgesetzt - diese Option kann jederzeit deaktiviert werden.",
      pushpinOptionsDescription: "Treffen Sie eine Auswahl aus einer Vielzahl von Farben für den Karten-Push-Pin, der sich von der Kartensymbologie unterscheiden sollte, um dem Benutzer die Positionierung der Übermittlung auf der Karte zu erleichtern",
      selectLocationText: "Position auswählen nach",
      myLocationText: "Eigener Standort",
      searchText: "Suchen",
      coordinatesText: "Breiten- und Längengradkoordinaten",
      usng: "USNG-Koordinaten",
      mgrs: "MGRS-Koordinaten",
      utm: "UTM-Koordinaten",
      selectLocationSDescription: "Benutzern das Auswählen einer Position anhand dieser Methoden erlauben.",
      dragTooltipText: "Das Feld an die Position ziehen, an der es angezeigt werden soll",
      showHideLayerText: "Layer anzeigen",
      showHideLayerHelpText: "ä_You can configure the GeoForm to Show/Hide Layer. This option only applies to a single layer setup_______________________________Ü.",
      labelHelpMessage: "Beschriftung",
      placeHolderHintMessage: "Hinweistext",
      placeHolderHelpMessage: "Hilfetext",
      selectTextOptionValue: "Filterauswahl",
      disableLogo: "Logo deaktivieren",
      disableLogoDescription: "Sie können das GeoForm konfigurieren, um das Logo in der Formularkopfzeile ein-/auszublenden",
      locateOnLoadText: "Beim Laden suchen",
      locateOnLoadDescription: "Sie können das GeoForm konfigurieren, um die aktuelle Position auf der Seite beim Laden zu verwenden",
      selectLayerFieldTabText: "Layer auswählen",
      allLayerSelectOptionText: "ä_All Layers____Ü",
      disableViewer: "Viewer deaktivieren",
      disableViewerDescription: "ä_You can configure the GeoForm to disable/enable the viewer__________________Ü",
      displayFieldHintText: "ä_Selected display field will be shown in the viewer as a title___________________Ü"
    },
    viewer: {
      geocoderCancelText: "Abbrechen",
      viewMapTabText: "Karte",
      sortHeaderText: "Sortieren nach:",
      geocoderPlaceholderText: "Postleitzahl, Stadt usw.",
      noSearchResult: "Kein Ergebnis gefunden",
      recordsTabTooltip: "Übermittlungen anzeigen",
      legendTabTooltip: "Legende",
      aboutUsTabTooltip: "ä_About Us___Ü",
      mapTabTooltip: "Karte",
      btnDescendingText: "Absteigend",
      btnAscendingText: "Aufsteigend",
      geometryUnavailableErrorMessage: "ä_Erorr finding the geometry of the feature_____________Ü",
      infoPopupOffErrorMessage: "ä_No information to display_________Ü",
      btnLoadMoreText: "Weitere laden",
      unavailableTitleText: "Unbenannt",
      unavailableConfigMessage: "Konfiguration kann nicht geladen werden",
      share: "ä_Share___Ü",
      viewReportsTabText: "ä_Reports___Ü",
      viewLegendTabText: "Legende",
      viewAboutusTabText: "Info zu",
      btnSubmitReportText: "Bericht senden",
      appLoadingFailedMessage: "ä_There was an error loading the viewer____________Ü"
    }
  })
);