define({
  "map": {
    "error": "Karte ni mogoče ustvariti",
    "licenseError": {
      "message": "Vaš račun ni licenciran za uporabo konfigurabilnih aplikacij, ki niso javne. Prosite administratorja v vaši organizaciji, da vam dodeli tip uporabnika, ki vsebuje aplikacije Essential Apps ali licenco za dodatne aplikacije Essential Apps.",
      "title": "Brez licence"
    }
  },
  "onlineStatus": {
    "offline": "Trenutno delate brez povezave. Dokler ne bo mogoče vzpostaviti povezave s strežnikom, bo pošiljanje obrazca shranjeno lokalno.",
    "reconnecting": "Ponovno vzpostavljanje povezave&hellip;",
    "pending": "${total} čakajočih urejanj bo poslanih, ko bo povezava z omrežjem znova vzpostavljena."
  },
  "configure": {
    "mapdlg": {
      "items": {
        "organizationLabel": "Moja organizacija",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "Moja vsebina",
        "favoritesLabel": "Moje priljubljene"
      },
      "title": "Izberi spletno karto",
      "searchTitle": "Išči",
      "ok": "V redu",
      "cancel": "Prekliči",
      "placeholder": "Vnesi iskani izraz"
    },
    "groupdlg": {
      "items": {
        "organizationLabel": "Moja organizacija",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "Moja vsebina",
        "favoritesLabel": "Moje priljubljene"
      },
      "title": "Izberi skupino",
      "searchTitle": "Išči",
      "ok": "V redu",
      "cancel": "Prekliči",
      "placeholder": "Vnesi iskani izraz"
    },
    "sharedlg": {
      "items": {},
      "mailtoLinkDescription": "Tukaj je spletna povezava do GeoObrazca"
    }
  },
  "user": {
    "all": "Vse",
    "mgrs": "MGRS",
    "usng": "USNG",
    "utm": "UTM",
    "utm_northing": "Pomik proti severu",
    "utm_easting": "Pomik proti vzhodu",
    "utm_zone_number": "Številka cone",
    "selectLayerTabText": "${formSection} Izberite obrazec",
    "geoFormGeneralTabText": "${formSection} Vnesite informacije",
    "locationInformationText": "${formSection} Izberite lokacijo",
    "submitInformationText": "${formSection} Izpolnite obrazec",
    "submitInstructions": "Dodaj te informacije na karto.",
    "myLocationText": "Trenutna lokacija",
    "locationDescriptionForMoreThanOneOption": "Navedite lokacijo za ta vnos tako, da kliknete/tapnete karto ali z uporabo ene od naslednjih možnosti.",
    "locationDescriptionForOneOption": "Navedite lokacijo za ta vnos tako, da kliknete/tapnete karto ali uporabite naslednje možnosti.",
    "locationDescriptionForNoOption": "Navedite lokacijo za ta vnos tako, da kliknete/tapnete karto.",
    "addressText": "Iskanje",
    "geographic": "g.š./g.d.",
    "locationTabText": "Lokacija",
    "locationPopupTitle": "Lokacija",
    "submitButtonText": "Pošlji vnos",
    "submitButtonTextLoading": "Pošiljanje&hellip;",
    "formValidationMessageAlertText": "Naslednja polja so obvezna:",
    "selectLocation": "Izberite lokacijo za svoj prispevek",
    "emptylatitudeAlertMessage": "Vnesite koordinate ${openLink}geografske širine${closeLink}.",
    "emptylongitudeAlertMessage": "Vnesite koordinate ${openLink}geografske dolžine${closeLink}.",
    "shareUserTitleMessage": "Zahvaljujemo se vam za prispevek!",
    "entrySubmitted": "Vaš prispevek je dodan na karto.",
    "shareThisForm": "Delite ta obrazec",
    "shareUserTextMessage": "Povejte drugim, naj prispevajo s pomočjo naslednjih možnosti.",
    "addAttachmentFailedMessage": "Sloju ni mogoče dodati priloge",
    "addFeatureFailedMessage": "Sloju ni mogoče dodati geoobjekta",
    "noLayerConfiguredMessage": "Med nalaganjem ali iskanjem geoobjektnega sloja za urejanje je prišlo do napake. Za prikaz obrazca in začetek zbiranja prispevkov na spletno karto dodajte uredljiv geoobjektni sloj.",
    "placeholderLatitude": "Geografska širina (Y)",
    "placeholderLongitude": "Geografska dolžina (X)",
    "latitude": "Geografska širina",
    "longitude": "Geografska dolžina",
    "findMyLocation": "Najdi me",
    "finding": "Iskanje&hellip;",
    "backToTop": "Nazaj na vrh",
    "addressSearchText": "Vaš prispevek bo prikazan tukaj. Za popravek lokacije lahko povlečete buciko.",
    "shareModalFormText": "Spletna povezava obrazca",
    "close": "Zapri",
    "locationNotFound": "Lokacije ni bilo mogoče najti.",
    "setLocation": "Nastavi lokacijo",
    "find": "Najdi naslov ali kraj",
    "attachment": "Priloga",
    "toggleDropdown": "Preklopi spustni meni",
    "invalidString": "Vnesite veljavno vrednost.",
    "invalidSmallNumber": "Vnesite veljavno vrednost ${openStrong}celega števila${closeStrong} med –32768 in 32767.",
    "invalidNumber": "Vnesite veljavno vrednost ${openStrong}celega števila${closeStrong} med –2147483648 in 2147483647.",
    "invalidFloat": "Vnesite veljavno vrednost ${openStrong}plavajoče vejice${closeStrong}.",
    "invalidDouble": "Vnesite veljavno vrednost ${openStrong}decimalnega dvojnega${closeStrong}.",
    "invalidLatLong": "Vnesite veljavne koordinate geografske širine in geografske dolžine.",
    "invalidUTM": "Vnesite veljavne koordinate UTM.",
    "invalidUSNG": "Vnesite veljavne koordinate USNG.",
    "invalidMGRS": "Vnesite veljavne koordinate MGRS.",
    "geoformTitleText": "Geoobrazec",
    "domainDefaultText": "Izberi&hellip;",
    "applyEditsFailedMessage": "Prišlo je do napake pri pošiljanju.",
    "applyEditsFailedRobot": "Pošiljanje je zavrnjeno, ker preizkus zaznavanja robota ni bil uspešno opravljen.",
    "applyEditsAuthError": "Vašega vnosa ni mogoče poslati zaradi vašega tipa stopnje uporabnika. Za pomoč se obrnite na administratorja svoje organizacije.",
    "requiredFields": "Naslednje polje je obvezno. Ustrezno ga izpolnite.",
    "requiredField": "(obvezno)",
    "error": "Napaka",
    "textRangeHintMessage": "${openStrong}Nasvet:${closeStrong} Minimalna vrednost ${minValue} in maksimalna vrednost ${maxValue}",
    "dateRangeHintMessage": "${openStrong}Nasvet:${closeStrong} Najmanjši datum ${minValue} in največji datum ${maxValue}",
    "remainingCharactersHintMessage": "Ostaja ${value} znakov",
    "mapFullScreen": "Celozaslonski način",
    "mapRestore": "Obnovi",
    "filterSelectEmptyText": "Izberi",
    "invalidLayerMessage": "Veljavnega sloja za ustvarjanje Geoobrazca ni bilo mogoče najti. Če je bil Geoobrazec konfiguriran s slojem, ta sloj morda ni več na voljo ali pa avtorizacija ni uspela.",
    "selectedLayerText": "Vse",
    "fileUploadStatus": "Status nalaganja datoteke",
    "uploadingBadge": "&nbsp;Nalaganje&hellip;",
    "successBadge": "&nbsp; Naloženo",
    "retryBadge": "Poskusite znova",
    "errorBadge": "Napaka pri nalaganju&nbsp;&nbsp;&nbsp;",
    "fileTooLargeError": "Datoteka je prevelika za prilogo",
    "exceededFileCountError": "Preseženo maksimalno dovoljeno število prilog",
    "selectFileTitle": "Izberi datoteko",
    "btnSelectFileText": "Izberite datoteko",
    "btnViewSubmissions": "Poglej prispevke"
  },
  "builder": {
    "gettingStarted": "Pa začnimo",
    "dateSettings": "Nastavitve datuma",
    "hiddenDateField": "Skrij to polje z datumom",
    "preventPastDates": "Prepreči pretekle datume",
    "preventFutureDates": "Prepreči prihodnje datume",
    "useCurrentDate": "Nastavi to polje s trenutnim datumom in časom",
    "configure": "Konfiguriraj",
    "configureField": "Konfiguriraj polje »${fieldName}«",
    "invalidUser": "Oprostite, za ogled tega elementa nimate dovoljenja",
    "invalidWebmapSelectionAlert": "Izbrana spletna karta ne vsebuje veljavnega sloja za uporabo. Za nadaljevanje na spletno karto dodajte uredljiv geoobjektni sloj.",
    "invalidWebmapSelectionAlert2": "Za več informacij glejte ${openLink}Kaj je geoobjektna storitev?${closeLink}",
    "selectFieldsText": "Izberi polja obrazca",
    "selectThemeText": "Izberi teme za obrazce",
    "setViewerText": "Konfiguriraj pregledovalnik",
    "introText": "Začetek",
    "webmapText": "Spletna karta",
    "layerText": "Sloj",
    "detailsText": "Podrobnosti",
    "fieldsText": "Polja",
    "styleText": "Slog",
    "viewerText": "Pregledovalnik",
    "optionText": "Možnosti",
    "previewText": "Predogled",
    "publishText": "Objavi",
    "optionsApplicationText": "Možnosti",
    "submitButtonText": "Besedilo gumba za pošiljanje (izbirno)",
    "submitButtonDesc": "Označite lahko tudi gumb za pošiljanje novega vnosa. To besedilo ne bo prevedeno.",
    "viewSubmissionsText": "Poglej besedilo prispevka (izbirno)",
    "viewSubmissionsDesc": "Označite lahko tudi gumb za ogled obstoječih prispevkov. To besedilo ne bo prevedeno.",
    "titleText": "Graditelj",
    "descriptionText": "Geoobrazec je konfigurabilna predloga aplikacije za urejanje podatkov na podlagi obrazcev ${link1}geoobjektne storitve${closeLink}. Ta aplikacija uporabnikom omogoča vnos podatkov prek obrazca namesto pojavnih oken karte, ob hkratnem izkoriščanju zmogljivosti ${link2}spletne karte${closeLink} in uredljivih geoobjektnih storitev. Uporabite naslednje korake za prilagoditev in namestitev Geoobrazca.",
    "btnPreviousText": "Prejšnji",
    "btnNextText": "Naslednji",
    "webmapTabTitleText": "Izberite spletno karto",
    "viewWebmap": "Pogled spletne karte",
    "webmapDetailsText": "Izbrana spletna karta je ${webMapTitleLink}${webMapTitle}${closeLink}. Za izbiro druge spletne karte kliknite gumb »Izberi spletno karto«",
    "btnSelectWebmapText": "Izberi spletno karto",
    "btnSelectWebmapTextLoading": "Nalaganje&hellip;",
    "layerTabTitleText": "Izberite uredljive sloje",
    "selectLayerLabelText": "Sloj",
    "selectLayerDefaultOptionText": "Izberite sloj",
    "enableBasemapToggle": "Prikaži vklop temeljne karte",
    "enableBasemapToggleDescription": "Geoobrazec lahko konfigurirate tako, da prikaže/skrije vklop temeljne karte",
    "defaultBasemap": "Vklop temeljne karte",
    "secondaryBasemap": "Privzeta temeljna karta",
    "detailsTabTitleText": "Podrobnosti o obrazcu",
    "detailTitleLabelText": "Ime",
    "detailLogoLabelText": "Slika logotipa",
    "descriptionLabelText": "Navodila in podrobnosti o obrazcu",
    "fieldDescriptionLabelText": "Besedilo za pomoč (izbirno)",
    "fieldDescriptionHelpText": "Navedite kratek opis ali navodila za to polje.",
    "fieldHintHelpText": "Nadomestno besedilo za polje.",
    "fieldTabFieldHeaderText": "Polje",
    "fieldTabLabelHeaderText": "Napis",
    "fieldTabDisplayTypeHeaderText": "Prikaži kot",
    "fieldTabOrderColumnText": "Vrstni red",
    "fieldTabVisibleColumnText": "Omogočeno",
    "displayFieldText": "Prikaži polje",
    "selectMenuOption": "Izberi meni",
    "selectRadioOption": "Izbirni gumb",
    "selectTextOption": "Besedilo",
    "selectDateOption": "Izbirnik datuma",
    "selectRangeOption": "Vrtenje z dotikom",
    "selectCheckboxOption": "Izbirno polje",
    "selectMailOption": "E-pošta",
    "selectUrlOption": "URL",
    "selectTextAreaOption": "Besedilno območje",
    "previewApplicationText": "Predogled aplikacije",
    "saveApplicationText": "Shrani aplikacijo",
    "saveText": "Shrani",
    "toggleNavigationText": "Preklopi navigacijo",
    "formPlaceholderText": "Moj obrazec",
    "shareBuilderInProgressTitleMessage": "Objava Geoobrazca",
    "shareBuilderProgressBarMessage": "Počakajte&hellip;",
    "shareBuilderTitleMessage": "Uspešno! Element shranjen",
    "shareBuilderTextMessage": "Zdaj lahko začnete zbirati informacije z deljenjem z drugimi",
    "shareModalFormText": "Spletna povezava obrazca",
    "shareBuilderSuccess": "Vaš Geoobrazec je bil posodobljen in objavljen!",
    "geoformTitleText": "Geoobrazec",
    "layerTabText": "To so sloji, iz katerih bo izdelan Geoobrazec. Sloj mora biti geoobjektna storitev z omogočenim urejanjem in dovoljenji za deljenje, primernimi za vaše občinstvo. Če so izbrani vsi sloji, bo obrazec uporabniku omogočal, da izbere, kateremu sloju pošilja prispevek.",
    "detailsTabText": "Uporabite spodnja polja s podrobnosti obrazca za prilagoditev imena, dodajanje logotipa po meri in kratek opis za vaše občinstvo Geoobrazca. V opis lahko dodate spletne povezave do drugih virov, podatke za stik in svoje občinstvo celo usmerite na aplikacijo za spletno kartiranje, ki vsebuje vse podatke, zbrane s pomočjo Geoobrazca.",
    "fieldsTabText": "Tukaj lahko izberete, katere polja bodo vidna vašemu občinstvu Geoobrazca, uredite napise, ki jih bodo videli in dodate kratek opis za pomoč pri vnosu podatkov.",
    "styleTabText": "Uredite svoj Geoobrazec s pomočjo spodaj navedenih tem po lastnih željah.",
    "viewerTabText": "Nastavite možnosti za ogled prispevkov, zbranih z Geoobrazcem.",
    "publishTabText": "Če ste zaključili s prilagajanjem svojega Geoobrazca, shranite aplikacijo in jo začnite deliti s svojim občinstvom. Vedno se lahko vrnete v graditelja in nadaljujete s prilagajanjem glede na povratne informacije.",
    "headerSizeLabel": "Velikost glave",
    "smallHeader": "Uporabite majhno glavo",
    "bigHeader": "Uporabite veliko glavo",
    "pushpinText": "Vstavite buciko",
    "doneButtonText": "Shrani in zapri",
    "fieldTabPlaceHolderHeaderText": "Namig (izbirno)",
    "enableAttachmentLabelText": "${openStrong}Omogoči priloge${closeStrong}",
    "enableAttachmentLabelHint": "Tukaj lahko omogočite/onemogočite priloge",
    "attachmentIsRequiredLabelText": "${openStrong}Priloge so zahtevane${closeStrong}",
    "attachmentIsRequiredLabelHint": "Če je potrebno, lahko od uporabnikov zahtevate dodajanje prilog.",
    "attachmentLabelText": "Napis gumba priloge",
    "attachmentLabelHint": "To besedilo se bo pojavilo zraven gumba priloge. Prostor lahko uporabite za opis tega, kar bi želeli, da vaše občinstvo priloži (fotografija, video, dokument itd.), format dokumenta, ki ga zahtevate (.jpeg, .png, .docx, .pdf itd.) in morebitna dodatna navodila.",
    "attachmentDescription": "Opis priloge",
    "attachmentHint": "Po potrebi lahko napišete dodatna navodila za dodajanje prilog.",
    "jumbotronDescription": "Za svoj obrazec uporabite velike in majhne naslove. Večja glava bo pomagala pojasniti namen vaše aplikacije, vendar bo zasedla več prostora na zaslonu",
    "shareGeoformText": "Gumbi za deljenje na družbenih omrežjih",
    "shareDescription": "Gumbi za deljenje na družbenih omrežjih omogočajo vašemu občinstvu, da po oddaji prispevka zlahka deli vaš Geoobrazec",
    "defaultMapExtent": "Privzeti obseg karte",
    "defaultMapExtentDescription": "Karta se bo po oddaji prispevka ponastavila na privzeti obseg spletne karte – to možnost lahko kadarkoli onemogočite.",
    "pushpinOptionsDescription": "Izbirajte iz nabora barv bucik, ki se morajo razlikovati od simbologije karte, da uporabniku pomagajo postaviti prispevek na karto.",
    "selectLocationText": "Izberite lokacijo po",
    "myLocationText": "Moja lokacija",
    "searchText": "Išči",
    "coordinatesText": "Koordinate geografske širine in dolžine",
    "usng": "Koordinate USNG",
    "mgrs": "Koordinate MGRS",
    "utm": "Koordinate UTM",
    "selectLocationSDescription": "Omogoča uporabnikom izbiro lokacije z uporabo teh metod.",
    "dragTooltipText": "Povlecite polje tja, kjer želite, da se prikaže",
    "showHideLayerText": "Pokaži sloj",
    "showHideLayerHelpText": "Geoobrazec lahko konfigurirate tako, da prikaže/skrije sloj. Ta možnost velja samo za postavitev z enojnim slojem.",
    "enableOfflineSupport": "Omogoči podporo brez povezave",
    "enableOfflineSupportHelpText": "Shranite prispevke, ko ni omrežne povezave, in jih pošljite, ko je znova vzpostavljena.",
    "labelHelpMessage": "Napis",
    "placeHolderHintMessage": "Besedilo namiga",
    "placeHolderHelpMessage": "Besedilo pomoči",
    "selectTextOptionValue": "Izbira filtra",
    "disableLogo": "Onemogoči logotip",
    "disableLogoDescription": "Geoobrazec lahko konfigurirate tako, da prikaže/skrije logotip v glavi obrazca",
    "locateOnLoadText": "Najdi pri nalaganju",
    "locateOnLoadDescription": "Geoobrazec lahko konfigurirate tako, da pri nalaganju strani uporabi trenutno lokacijo",
    "selectLayerFieldTabText": "Izberite sloj",
    "allLayerSelectOptionText": "Vsi sloji",
    "disableViewer": "Onemogoči pregledovalnik",
    "disableViewerDescription": "Geoobrazec lahko konfigurirate tako, da onemogočite/omogočite pregledovalnik",
    "displayFieldHintText": "Izbrano prikazno polje bo v pregledovalniku prikazano kot ime"
  },
  "viewer": {
    "geocoderCancelText": "Prekliči",
    "viewMapTabText": "Karta",
    "sortHeaderText": "Razvrsti po:",
    "geocoderPlaceholderText": "Poštna številka, mesto itd.",
    "noSearchResult": "Ni najdenih rezultatov",
    "legendTabTooltip": "Legenda",
    "aboutUsTabTooltip": "O nas",
    "mapTabTooltip": "Karta",
    "btnDescendingText": "Padaj.",
    "btnAscendingText": "Naraš.",
    "geometryUnavailableErrorMessage": "Napaka pri iskanju geometrije geoobjekta",
    "infoPopupOffErrorMessage": "Ni informacij za prikaz",
    "btnLoadMoreText": "Naloži več",
    "unavailableTitleText": "Neimenovano",
    "unavailableConfigMessage": "Konfiguracije ni mogoče naložiti",
    "share": "Deli",
    "viewReportsTabText": "Poročila",
    "viewLegendTabText": "Legenda",
    "viewAboutusTabText": "Več o tem",
    "appLoadingFailedMessage": "Pri nalaganju pregledovalnika je prišlo do napake"
  }
});