define({
  "map": {
    "error": "मानचित्र बनाने में अक्षम"
  },
  "onlineStatus": {
    "offline": "आप वर्तमान में ऑफ़लाइन काम कर रहे हैं। फार्म प्रस्तुतियाँ स्थानीय रूप से सहेजी जाएंगी जब तक सर्वर से कनेक्शन नहीं हो जाता।",
    "reconnecting": "फिर से कनेक्ट करें और मदद;",
    "pending": "जब एक नेटवर्क कनेक्शन फिर से स्थापित किया जाता है, तो ${total} लंबित संशोधन प्रस्तुत किए जाएंगे।"
  },
  "configure": {
    "mapdlg": {
      "items": {
        "organizationLabel": "मेरा संगठन",
        "onlineLabel": "ArcGIS ऑनलाइन",
        "contentLabel": "मेरी सामग्री",
        "favoritesLabel": "मेरे पसंदीदा"
      },
      "title": "वेब मानचित्र चुनें",
      "searchTitle": "खोजें",
      "ok": "ठीक है",
      "cancel": "रद्द करें",
      "placeholder": "खोज शब्द दर्ज करें"
    },
    "groupdlg": {
      "items": {
        "organizationLabel": "मेरा संगठन",
        "onlineLabel": "ArcGIS ऑनलाइन",
        "contentLabel": "मेरी सामग्री",
        "favoritesLabel": "मेरे पसंदीदा"
      },
      "title": "समूह चुनें",
      "searchTitle": "खोजें",
      "ok": "ठीक है",
      "cancel": "रद्द करें",
      "placeholder": "खोज शब्द दर्ज करें"
    },
    "sharedlg": {
      "items": {},
      "mailtoLinkDescription": "यहाँ एक GeoForm लिए एक लिंक है"
    }
  },
  "user": {
    "all": "सभी",
    "mgrs": "MGRS",
    "usng": "USNG",
    "utm": "UTM",
    "utm_northing": "उत्तर की ओर",
    "utm_easting": "पूर्व की ओर",
    "utm_zone_number": "क्षेत्र संख्या",
    "selectLayerTabText": "${FormSection} फॉर्म चुनें",
    "geoFormGeneralTabText": "${FormSection} सूचना दर्ज करें",
    "locationInformationText": "${FormSection} स्थान चुनें",
    "submitInformationText": "${FormSection} पूर्ण रूप",
    "submitInstructions": "यह जानकारी मानचित्र में सम्मिलित करें।",
    "myLocationText": "वर्तमान स्थान",
    "locationDescriptionForMoreThanOneOption": "मानचित्र पर क्लिक/टैब करके या निम्न विकल्पों में से किसी एक का उपयोग कर इस प्रविष्टि के लिए स्थान निर्दिष्ट करें।",
    "locationDescriptionForOneOption": "मानचित्र पर क्लिक/टैब करके या निम्न विकल्प का उपयोग कर इस प्रविष्टि के लिए स्थान निर्दिष्ट करें।",
    "locationDescriptionForNoOption": "मानचित्र पर क्लिक/टैब करके इस प्रविष्टि के लिए स्थान निर्दिष्ट करें।",
    "addressText": "खोजें",
    "geographic": "अक्षांश/देशांतर",
    "locationTabText": "स्थान",
    "locationPopupTitle": "स्थान",
    "submitButtonText": "प्रविष्टि प्रस्तुत करें",
    "submitButtonTextLoading": "प्रस्तुत करना और मदद;",
    "formValidationMessageAlertText": "निम्नलिखित फील्ड आवश्यक हैं:",
    "selectLocation": "कृपया अपनी प्रस्तुति के लिए एक स्थान चुनें।",
    "emptylatitudeAlertMessage": "कृपया ${openLink} अक्षांश ${closeLink} निर्देशांक दर्ज करें।",
    "emptylongitudeAlertMessage": "एक $ {openLink} देशांतर ${closeLink} निर्देशांक दर्ज करें।",
    "shareUserTitleMessage": "आपके योगदान के लिए धन्यवाद!",
    "entrySubmitted": "आपकी प्रविष्टि मानचित्र के लिए प्रस्तुत कर दी गई है।",
    "shareThisForm": "यह फॉर्म साझा करें",
    "shareUserTextMessage": "दूसरों को निम्न विकल्पों का उपयोग कर योगदान देने के बारे में बताएं।",
    "addAttachmentFailedMessage": "लेयर से अनुलग्नक जोड़ने में असमर्थ",
    "addFeatureFailedMessage": "लेयर से सुविधा जोड़ने में असमर्थ",
    "noLayerConfiguredMessage": "एक संपादन योग्य विशेष लेयर को खोजने या लोड करने में त्रुटि उत्पन्न हुई। फार्म को प्रदर्शित करने और प्रस्तुतियाँ का संग्रह शुरू करने के लिए, वेब मानचित्र में एक संपादन योग्य विशेष लेयर सम्मिलित करें।",
    "placeholderLatitude": "अक्षांश (Y)",
    "placeholderLongitude": "देशांतर (X)",
    "latitude": "अक्षांश",
    "longitude": "देशान्तर",
    "findMyLocation": "मेरा पता लगाएं",
    "finding": "पता लगाया जा रहा है और मदद;",
    "backToTop": "शीर्ष पर वापस जाएँ",
    "addressSearchText": "आपकी प्रस्तुतियां यहाँ दिखाई देगी। आप स्थान सही करने के लिए पिन खींच सकते हैं।",
    "shareModalFormText": "फॉर्म का लिंक",
    "close": "बंद करें",
    "locationNotFound": "स्थान नहीं मिल सका।",
    "setLocation": "स्थान सेट करें",
    "find": "पता या स्थान खोजें",
    "attachment": "अनुलग्नक",
    "toggleDropdown": "ड्रापडाउन को टॉगल करें",
    "invalidString": "कृपया एक मान्य संख्या दर्ज करें।",
    "invalidSmallNumber": "कृपया -32768 और 32767 के बीच एक मान्य ${openStrong} पूर्णांक ${closeStrong} संख्या दर्ज करें।",
    "invalidNumber": "कृपया -2147483648 और 2147483647 के बीच मान्य ${openStrong} पूर्णांक ${closeStrong} संख्या दर्ज करें।",
    "invalidFloat": "कृपया मान्य ${openStrong} चल बिन्दु ${closeStrong} संख्या दर्ज करें।",
    "invalidDouble": "कृपया मान्य ${openStrong} डबल ${closeStrong} संख्या दर्ज करें।",
    "invalidLatLong": "कृपया मान्य अक्षांश और देशांतर निर्देशांक दर्ज करें।",
    "invalidUTM": "कृपया मान्य UTM निर्देशांक दर्ज करें।",
    "invalidUSNG": "कृपया मान्य USNG निर्देशांक दर्ज करें।",
    "invalidMGRS": "कृपया मान्य MGRS निर्देशांक दर्ज करें।",
    "geoformTitleText": "GeoForm",
    "domainDefaultText": "चुनें और मदद;",
    "applyEditsFailedMessage": "प्रस्तुतीकरण त्रुटि उत्पन्न हुई।",
    "applyEditsFailedRobot": "प्रस्तुतीकरण को अस्वीकार कर दिया गया क्योंकि यह रोबोट का पता लगाने में विफल रहा।",
    "applyEditsAuthError": "आपकी प्रविष्टि आपके उपयोगकर्ता के स्तर के प्रकार के कारण प्रस्तुत नहीं की जा सकती है। कृपया अधिक सहायता के लिए अपने संगठन के व्यवस्थापक से संपर्क करें।",
    "requiredFields": "निम्नलिखित फील्ड आवश्यक है। एक मान्य प्रविष्टि प्रदान करें।",
    "requiredField": "(आवश्यक है)",
    "error": "त्रुटि",
    "textRangeHintMessage": "${OpenStrong} संकेत: ${closeStrong} न्यूनतम संख्या ${minValue} और अधिकतम संख्या ${maxValue}",
    "dateRangeHintMessage": "${OpenStrong} संकेत: ${closeStrong} न्यूनतम संख्या ${minValue} और अधिकतम संख्या ${maxValue}",
    "remainingCharactersHintMessage": "${value} अक्षर शेष हैं",
    "mapFullScreen": "पूर्ण स्क्रीन",
    "mapRestore": "पुनर्स्थापित करें",
    "filterSelectEmptyText": "चुनें",
    "invalidLayerMessage": "GeoForm बनाने के लिए एक मान्य लेयर नहीं मिली थी। यदि GeoForm एक लेयर के साथ कॉन्फ़िगर किया गया है, तो लेयर शायद अब उपलब्ध ना हो, या प्रमाणीकरण विफल रहा।",
    "selectedLayerText": "सभी",
    "fileUploadStatus": "फाइल अपलोड की स्थिति",
    "uploadingBadge": "&nbsp; अपलोड और मदद;",
    "successBadge": "&nbsp; अपलोड किया हुआ",
    "retryBadge": "पुनः प्रयास करें",
    "errorBadge": "अपलोड करने में त्रुटि &nbsp; &nbsp; &nbsp;",
    "fileTooLargeError": "संलग्न करने के लिए फाइल बहुत बड़ी है",
    "exceededFileCountError": "अनुमति प्राप्त अनुलग्नकों की अधिकतम संख्या समाप्त हो गई है",
    "selectFileTitle": "कोई फाइल चुनें",
    "btnSelectFileText": "फ़ाइल चुनें",
    "btnViewSubmissions": "प्रस्तुतियाँ देखें"
  },
  "builder": {
    "gettingStarted": "प्रारंभ करना",
    "dateSettings": "तिथि की सेटिंग",
    "hiddenDateField": "इस तिथि की फील्ड छुपाएं",
    "preventPastDates": "पिछले तिथियों को रोकें",
    "preventFutureDates": "भविष्य की तिथियों को रोकें",
    "useCurrentDate": "यह फील्ड आज की तारीख और समय पर सेट करें",
    "configure": "कॉन्फ़िगर करें",
    "configureField": "फील्ड '${fieldName}' कॉन्फ़िगर करें",
    "invalidUser": "क्षमा करें, आप को इस आइटम को देखने की अनुमति नहीं है",
    "invalidWebmapSelectionAlert": "चुने गए वेब मैप में उपयोग करने के लिए एक मान्य लेयर शामिल नहीं है। कृपया जारी रखने के लिए अपने वेब मानचित्र में एक संपादन योग्य विशेष लेयर सम्मिलित करें।",
    "invalidWebmapSelectionAlert2": "अधिक जानकारी के लिए कृपया ${openLink} फ़ीचर सर्विस क्या है? ${closeLink} देखें",
    "selectFieldsText": "फॉर्म फ़ील्ड चुनें",
    "selectThemeText": "फार्म की थीम चुनें",
    "setViewerText": "व्यूअर कॉन्फ़िगर करें",
    "introText": "शुरू करें",
    "webmapText": "वेब मैप",
    "layerText": "लेयर",
    "detailsText": "विवरण",
    "fieldsText": "फ़ील्ड्स",
    "styleText": "शैली",
    "viewerText": "दर्शक",
    "optionText": "विकल्प",
    "previewText": "पूर्वावलोकन करें",
    "publishText": "प्रकाशित करें",
    "optionsApplicationText": "विकल्प",
    "submitButtonText": "प्रस्तुत बटन का टेक्स्ट (वैकल्पिक)",
    "submitButtonDesc": "वैकल्पिक रूप से एक नई प्रविष्टि प्रस्तुत करने के लिए बटन को लेबल दें। यह टेक्स्ट अनुवाद नहीं किया जाएगा।",
    "viewSubmissionsText": "प्रस्तुतियों का टेक्स्ट देखें (वैकल्पिक)",
    "viewSubmissionsDesc": "वैकल्पिक रूप से मौजूदा प्रविष्टियों को देखने के लिए बटन को लेबल दें। यह टेक्स्ट अनुवाद नहीं किया जाएगा।",
    "titleText": "बिल्डर",
    "descriptionText": "GeoForm एक ${link1} विशेष सेवा${closeLink} के फॉर्म-आधारित डेटा संपादन के लिए एक विन्यास योग्य टेम्पलेट है। यह ऐप्लिकेशन ${link2} वेब मानचित्र ${closeLink} और संपादन संबंधी विशेष सेवा की शक्ति का इस्तेमाल करते हुए मानचित्र के पॉप-अप के बजाए एक फॉर्म के माध्यम से डेटा प्रविष्ट करने की अनुमति देता है। अपने GeoForm डालने और सामान्य बनाने के लिए निम्न चरणों का प्रयोग करें।",
    "btnPreviousText": "पिछला",
    "btnNextText": "अगला",
    "webmapTabTitleText": "कोई वेब मैप चुनें",
    "viewWebmap": "वेब मैप देखें",
    "webmapDetailsText": "चुना गया वेब मैप ${webMapTitleLink} ${webMapTitle}${closeLink} है। एक अलग वेब मैप चुनने के लिए 'वेब मैप चुनें' बटन पर क्लिक करें",
    "btnSelectWebmapText": "वेब मैप चुनें",
    "btnSelectWebmapTextLoading": "लोड हो रहा है और मदद;",
    "layerTabTitleText": "संपादन योग्य लेयर चुनें",
    "selectLayerLabelText": "लेयर",
    "selectLayerDefaultOptionText": "लेयर चुनें",
    "enableBasemapToggle": "बेसमैप टॉगल दिखाएँ",
    "enableBasemapToggleDescription": "बेसमैपटॉगल दिखाने/छुपाने के लिए आप GeoForm को विन्यासित कर सकते हैं",
    "defaultBasemap": "बेसमैप टॉगल करें",
    "secondaryBasemap": "डिफ़ॉल्ट बेसमैप",
    "detailsTabTitleText": "फॉर्म विवरण",
    "detailTitleLabelText": "शीर्षक",
    "detailLogoLabelText": "लोगो की तस्वीर",
    "descriptionLabelText": "फॉर्म संबंधी निर्देश और विवरण",
    "fieldDescriptionLabelText": "सहायता टेक्स्ट (वैकल्पिक)",
    "fieldDescriptionHelpText": "इस फील्ड के लिए एक संक्षिप्त वर्णन या निर्देश प्रदान करें।",
    "fieldHintHelpText": "फील्ड के लिए प्लेसहोल्डर पाठ।",
    "fieldTabFieldHeaderText": "क्षेत्र",
    "fieldTabLabelHeaderText": "लेबल",
    "fieldTabDisplayTypeHeaderText": "इस रूप में प्रदर्शित करें",
    "fieldTabOrderColumnText": "क्रम",
    "fieldTabVisibleColumnText": "सक्षम किया हुआ",
    "displayFieldText": "प्रदर्शन फील्ड",
    "selectMenuOption": "मेनू चुनें",
    "selectRadioOption": "रेडियो बटन",
    "selectTextOption": "टेक्स्ट",
    "selectDateOption": "तिथि चुनने वाला",
    "selectRangeOption": "टच-स्पिनर",
    "selectCheckboxOption": "चेकबॉक्स",
    "selectMailOption": "ईमेल",
    "selectUrlOption": "URL",
    "selectTextAreaOption": "टेक्स्ट क्षेत्र",
    "previewApplicationText": "ऐप्लिकेशन का पूर्वावलोकन करें",
    "saveApplicationText": "ऐप्लिकेशन सहेजें",
    "saveText": "सहेजें",
    "toggleNavigationText": "नेविगेशन को टॉगल करें",
    "formPlaceholderText": "मेरे फॉर्म",
    "shareBuilderInProgressTitleMessage": "GeoForm को प्रकाशित किया जा रहा है",
    "shareBuilderProgressBarMessage": "कृपया प्रतीक्षा करें और मदद;",
    "shareBuilderTitleMessage": "सफलता! आइटम सहेज ली गई",
    "shareBuilderTextMessage": "आप दूसरों के साथ साझा करके जानकारी इकट्ठा करना शुरू कर सकते हैं",
    "shareModalFormText": "फॉर्म का लिंक",
    "shareBuilderSuccess": "आपके GeoForm में अपडेट और उसे प्रकाशित कर दिया गया है!",
    "geoformTitleText": "Geo Form",
    "layerTabText": "यह वह लेयर है जिससे GeoForm बनाया जाएगा। लेयर एक विशेष सेवा होनी चाहिए जो आपके दर्शकों के लिए उपयुक्त साझा करने की अनुमतियों के साथ संपादन के लिए सक्षम हो। यदि सभी लेयर्स चुनी गई हों, तो फार्म प्रयोक्ता को फार्म लेयर चुनने का विकल्प देगा कि किसे प्रस्तुत किया जाए।",
    "detailsTabText": "शीर्षक को अनुकूलित करने के लिए, एक कस्टम लोगो लगाने के लिए, और अपने GeoForm के दर्शकों के लिए एक संक्षिप्त विवरण प्रदान करने के लिए नीचे दिए फॉर्म के विवरण बॉक्स का प्रयोग करें। विवरण में आप अन्य संसाधनों, संपर्क जानकारी और आप अपने दर्शकों को GeoForm से संग्रहित सारे डेटा वाली वेब मैपिंग ऐप्लिकेशन से भी इंगित कर सकते हैं।",
    "fieldsTabText": "यहाँ आप चुन सकते हैं कि आपके GeoForm दर्शकों को कौन सी फील्ड दिखाई देगी, उनको दिखने वाले लेबल संपादित करना, और डेटा प्रविष्टि में मदद करने के लिए एक संक्षिप्त विवरण।",
    "styleTabText": "आपकी प्राथमिकता के आधार पर नीचे दिए गए विषयों का उपयोग कर अपने GeoForm को स्टाइल प्रदान करें।",
    "viewerTabText": "GeoForm से एकत्र प्रस्तुतियाँ देखने के लिए विकल्प सेट करें।",
    "publishTabText": "यदि आपके GeoForm का अनुरूपण खत्म हो गया है, तो ऐप्लिकेशन को सहेज लें और अपने दर्शकों के साथ साझा करना प्रारंभ करें। आप हमेशा इस बिल्डर पर वापस आ सकते हैं और प्रतिक्रिया के आधार पर इसका अनुरूपण जारी रख सकते हैं।",
    "headerSizeLabel": "हेडर का आकार",
    "smallHeader": "छोटे हेडर का प्रयोग करें",
    "bigHeader": "बड़े हेडर का प्रयोग करें",
    "pushpinText": "पुश पिन",
    "doneButtonText": "सहेजें और बाहर जाएं",
    "fieldTabPlaceHolderHeaderText": "संकेत (वैकल्पिक)",
    "enableAttachmentLabelText": "${OpenStrong} अनुलग्नक सक्षम करें${closeStrong}",
    "enableAttachmentLabelHint": "आप यहाँ अनुलग्नकों को सक्षम/अक्षम कर सकते हैं",
    "attachmentIsRequiredLabelText": "${OpenStrong}अनुलग्नक आवश्यक हैं${closeStrong}",
    "attachmentIsRequiredLabelHint": "यदि आवश्यक हो, प्रयोक्ताओं के लिए एक अनुलग्नक जोड़ना आवश्यक हो सकता है।",
    "attachmentLabelText": "अनुलग्नक बटन का लेबल",
    "attachmentLabelHint": "यह पाठ अनुलग्नक बटन के बगल में दिखाई देगा। आप इस जगह का प्रयोग यह वर्णन करने के लिए कर सकते हैं कि आप अपने दर्शकों से संलग्न कराना चाहते हैं (फोटो, वीडियो, दस्तावेज, आदि), फ़ाइल स्वरूप जो आप चाहते हैं (.jpeg, .png, .docx, .pdf, आदि) और कोई भी अतिरिक्त निर्देश",
    "attachmentDescription": "अनुलग्नक का विवरण",
    "attachmentHint": "यदि आवश्यक हो, तो आप अतिरिक्त अनुलग्नक निर्देश यहाँ प्रदान कर सकते हैं।",
    "jumbotronDescription": "अपने फार्म के लिए बड़े या छोटे शीर्षक का प्रयोग करें। एक बड़ा हेडर आपकी ऐप्लिकेशन के उद्देश्य को परिभाषित करने में मदद कर सकता है लेकिन यह आपकी स्क्रीन पर अधिक जगह लेता है",
    "shareGeoformText": "सोशल मीडिया साझेदारी बटन",
    "shareDescription": "सोशल मीडिया बटन आपके दर्शकों को GeoForm प्रस्तुत करने के बाद आसानी से साझा करने की अनुमति देता है",
    "defaultMapExtent": "डिफ़ॉल्ट मानचित्र सीमा",
    "defaultMapExtentDescription": "मानचित्र प्रस्तुत करने के बाद अपने वेब मैप की डिफ़ॉल्ट सीमा पर फिर से पुनर्स्थापित हो जाएगा - इसे किसी भी समय अक्षम किया जा सकता है।",
    "pushpinOptionsDescription": "मानचित्र पुशपिन के लिए रंग की विभिन्न किस्मों में से चुनें, यह प्रयोक्ता को उनकी प्रस्तुतियां मानचित्र पर करने में मदद करने के लिए मानचित्र प्रतीक से अलग होना चाहिए",
    "selectLocationText": "इसके अनुसार स्थान चुनें",
    "myLocationText": "मेरा स्थान",
    "searchText": "खोजें",
    "coordinatesText": "अक्षांश और देशांतर निर्देशांक",
    "usng": "USNG निर्देशांक",
    "mgrs": "MGRS निर्देशांक",
    "utm": "UTM निर्देशांक",
    "selectLocationSDescription": "प्रयोक्ताओं को इन तरीकों का उपयोग कर स्थान चुनने की अनुमति दें।",
    "dragTooltipText": "फील्ड को वहां ड्रैग करें जहां आप इसे देखना चाहते हैं",
    "showHideLayerText": "लेयर दिखाएँ",
    "showHideLayerHelpText": "आप GeoForm को दिखाने/छिपाने के लिए लेयर को कॉन्फ़िगर कर सकते हैं। यह विकल्प केवल एक लेयर सेटअप पर लागू होता है।",
    "enableOfflineSupport": "ऑफ़लाइन समर्थन सक्षम करें",
    "enableOfflineSupportHelpText": "जब कोई नेटवर्क कनेक्शन ना हो तो प्रस्तुतियाँ संग्रहित करें और उन्हें कनेक्शन बहाल होने के बाद प्रस्तुत करें।",
    "labelHelpMessage": "लेबल",
    "placeHolderHintMessage": "संकेत पाठ",
    "placeHolderHelpMessage": "मदद पाठ",
    "selectTextOptionValue": "फिल्टर चुनें",
    "disableLogo": "लोगो अक्षम करें",
    "disableLogoDescription": "आप लोगो को फॉर्म के हेडर में दिखाने/छुपाने के लिए GeoForm विन्यासित कर सकते हैं",
    "locateOnLoadText": "लोड पर ढूँढें",
    "locateOnLoadDescription": "आप पृष्ठ लोड पर वर्तमान स्थान का उपयोग करने के लिए GeoForm विन्यासित कर सकते हैं",
    "selectLayerFieldTabText": "लेयर चुनें",
    "allLayerSelectOptionText": "सभी लेयर्स",
    "disableViewer": "व्यूअर अक्षम करें",
    "disableViewerDescription": "आप व्यूअर को सक्षम/अक्षम करने के लिए GeoForm विन्यासित कर सकते हैं",
    "displayFieldHintText": "चयनित प्रदर्शन फील्ड एक शीर्षक के रूप में व्यूअर में दिखाई जाएगी"
  },
  "viewer": {
    "geocoderCancelText": "रद्द करें",
    "viewMapTabText": "मानचित्र",
    "sortHeaderText": "इस आधार पर सॉर्ट करें:",
    "geocoderPlaceholderText": "पिन कोड, शहर, आदि",
    "noSearchResult": "कोई परिणाम नहीं मिला",
    "legendTabTooltip": "लीजेंड",
    "aboutUsTabTooltip": "हमारे बारे में",
    "mapTabTooltip": "मानचित्र",
    "btnDescendingText": "अवरोही",
    "btnAscendingText": "आरोही",
    "geometryUnavailableErrorMessage": "सुविधा की ज्यामिति खोजने में त्रुटि",
    "infoPopupOffErrorMessage": "प्रदर्शित करने के लिए कोई सूचना नहीं है",
    "btnLoadMoreText": "और लोड करें",
    "unavailableTitleText": "शीर्षकरहित",
    "unavailableConfigMessage": "विन्यास लोड करने में असमर्थ",
    "share": "साझा करें",
    "viewReportsTabText": "रिपोर्ट",
    "viewLegendTabText": "लीजेंड",
    "viewAboutusTabText": "बारे में",
    "appLoadingFailedMessage": "व्यूअर लोड करने में त्रुटि थी"
  }
});