define({
  "map": {
    "error": "Nije moguće stvoriti kartu"
  },
  "onlineStatus": {
    "offline": "Trenutačno radite izvan mreže. Podneseni obrasci spremit će se lokalno dok se ne ostvari veza s poslužiteljem.",
    "reconnecting": "Ponovno povezivanje&hellip;",
    "pending": "${total} uređenih stavki poslat će se kada se ponovno uspostavi mrežna veza."
  },
  "configure": {
    "mapdlg": {
      "items": {
        "organizationLabel": "Moja organizacija",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "Moj sadržaj",
        "favoritesLabel": "Moji favoriti"
      },
      "title": "Odaberite web-kartu",
      "searchTitle": "Pretraži",
      "ok": "U redu",
      "cancel": "Odustani",
      "placeholder": "Unesite termin za pretraživanje"
    },
    "groupdlg": {
      "items": {
        "organizationLabel": "Moja organizacija",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "Moj sadržaj",
        "favoritesLabel": "Moji favoriti"
      },
      "title": "Odaberite grupu",
      "searchTitle": "Pretraži",
      "ok": "U redu",
      "cancel": "Odustani",
      "placeholder": "Unesite termin za pretraživanje"
    },
    "sharedlg": {
      "items": {},
      "mailtoLinkDescription": "Evo poveznica za GeoForm"
    }
  },
  "user": {
    "all": "Sve",
    "mgrs": "MGRS",
    "usng": "USNG",
    "utm": "UTM",
    "utm_northing": "Sjeverno",
    "utm_easting": "Istočno",
    "utm_zone_number": "Broj zone",
    "selectLayerTabText": "${formSection} Odaberite obrazac",
    "geoFormGeneralTabText": "${formSection} Unesite informacije",
    "locationInformationText": "${formSection} Odaberite lokaciju",
    "submitInformationText": "${formSection} Ispunite obrazac",
    "submitInstructions": "Dodaj ove informacije karti.",
    "myLocationText": "Trenutačna lokacija",
    "locationDescriptionForMoreThanOneOption": "Odredite lokaciju za ovaj unos tako da kliknete/dodirnete kartu ili s pomoću jedne od sljedećih opcija.",
    "locationDescriptionForOneOption": "Odredite lokaciju za ovaj unos tako da kliknete/dodirnete kartu ili s pomoću sljedeće opcije.",
    "locationDescriptionForNoOption": "Odredite lokaciju za ovaj unos tako da kliknete/dodirnete kartu.",
    "addressText": "Pretraži",
    "geographic": "Šir./duž.",
    "locationTabText": "Lokacija",
    "locationPopupTitle": "Lokacija",
    "submitButtonText": "Pošalji unos",
    "submitButtonTextLoading": "Slanje&hellip;",
    "formValidationMessageAlertText": "Obavezna su sljedeća polja:",
    "selectLocation": "Odaberite lokaciju za slanje.",
    "emptylatitudeAlertMessage": "Unesite koordinate ${openLink}geografske širine${closeLink}.",
    "emptylongitudeAlertMessage": "Unesite koordinate ${openLink}geografske dužine${closeLink}.",
    "shareUserTitleMessage": "Hvala vam na doprinosu!",
    "entrySubmitted": "Vaš je unos dodan na kartu.",
    "shareThisForm": "Podijeli ovaj obrazac",
    "shareUserTextMessage": "Recite ostalima da doprinesu s pomoću sljedećih opcija.",
    "addAttachmentFailedMessage": "Nije moguće dodati privitak sloju",
    "addFeatureFailedMessage": "Nije moguće dodati geoobjekt sloju",
    "noLayerConfiguredMessage": "Došlo je do pogreške pri učitavanju ili traženju sloja geoobjekta koji se može uređivati. Kako bi se prikazao obrazac i počeli prikupljati doprinosi, web-karti dodajte sloj geoobjekta koji se može uređivati.",
    "placeholderLatitude": "Geografska širina (Y)",
    "placeholderLongitude": "Geografska dužina (X)",
    "latitude": "Geografska širina",
    "longitude": "Geografska dužina",
    "findMyLocation": "Pronađi me",
    "finding": "Traženje&hellip;",
    "backToTop": "Natrag na vrh",
    "addressSearchText": "Vaš će se podnesak prikazati ovdje. Možete vući oznaku da biste ispravili lokaciju.",
    "shareModalFormText": "Poveznica obrasca",
    "close": "Zatvori",
    "locationNotFound": "Nije pronađena lokacija",
    "setLocation": "Postavi lokaciju",
    "find": "Pronađi adresu ili mjesto",
    "attachment": "Privitak",
    "toggleDropdown": "Preklopi padajući izbornik",
    "invalidString": "Unesite valjanu vrijednost.",
    "invalidSmallNumber": "Unesite valjani ${openStrong}cijeli broj${closeStrong} između -32768 i 32767.",
    "invalidNumber": "Unesite valjani ${openStrong}cijeli broj${closeStrong} između -2147483648 i 2147483647.",
    "invalidFloat": "Unesite valjanu vrijednost ${openStrong}plutajuće točke${closeStrong}.",
    "invalidDouble": "Unesite valjanu ${openStrong}dvostruku${closeStrong} vrijednost.",
    "invalidLatLong": "Unesite valjane koordinate geografske širine i dužine.",
    "invalidUTM": "Unesite valjane UTM koordinate.",
    "invalidUSNG": "Unesite valjane USNG koordinate.",
    "invalidMGRS": "Unesite valjane MGRS koordinate.",
    "geoformTitleText": "GeoForm",
    "domainDefaultText": "Odabir&hellip;",
    "applyEditsFailedMessage": "Nažalost, vaš se unos ne može poslati. Pokušajte ponovno.",
    "requiredFields": "Sljedeće je polje obavezno. Upišite valjanu vrijednost.",
    "requiredField": "(obavezno)",
    "error": "Pogreška",
    "textRangeHintMessage": "${openStrong}Podsjetnik:${closeStrong} minimalna vrijednost ${minValue} i maksimalna vrijednost ${maxValue}",
    "dateRangeHintMessage": "${openStrong}Podsjetnik:${closeStrong} minimalni datum ${minValue} i maksimalni datum ${maxValue}",
    "remainingCharactersHintMessage": "${value} znak(ov)a preostalo",
    "mapFullScreen": "Puni zaslon",
    "mapRestore": "Vrati",
    "filterSelectEmptyText": "Odaberi",
    "invalidLayerMessage": "Valjani sloj za izradu GeoForma nije pronađen. Ako je GeoForm konfiguriran sa slojem, sloj više nije dostupan ili autorizacija nije uspjela.",
    "selectedLayerText": "Sve",
    "fileUploadStatus": "Status učitavanja datoteka",
    "uploadingBadge": "&nbsp;učitavanje&hellip;",
    "successBadge": "&nbsp;Učitano",
    "retryBadge": "Pokušaj ponovno",
    "errorBadge": "Pogreška pri učitavanju&nbsp;&nbsp;&nbsp;",
    "fileTooLargeError": "Datoteka je prevelika za privitak",
    "exceededFileCountError": "Premašen je maksimalni broj dopuštenih privitaka",
    "selectFileTitle": "Odaberite datoteku",
    "btnSelectFileText": "Odabir datoteke",
    "btnViewSubmissions": "Prikaz podnesaka"
  },
  "builder": {
    "gettingStarted": "Početak rada",
    "dateSettings": "Postavke datuma",
    "hiddenDateField": "Sakrij ovo polje datuma",
    "preventPastDates": "Onemogući prošle datume",
    "preventFutureDates": "Onemogući buduće datume",
    "useCurrentDate": "Postavite ovo polje s trenutačnim datumom i vremenom",
    "configure": "Konfiguriraj",
    "configureField": "Konfiguriraj polje '${fieldName}'",
    "invalidUser": "Nažalost, nemate dopuštenje za prikaz ove stavke",
    "invalidWebmapSelectionAlert": "Odabrana web-karta ne sadrži valjani sloj za upotrebu. Dodajte sloj geoobjekta koji se može uređivati svojoj web-karti za nastavak.",
    "invalidWebmapSelectionAlert2": "Više informacija potražite u dijelu ${openLink}Što je usluga geoobjekata?${closeLink}",
    "selectFieldsText": "Odaberite polja obrasca",
    "selectThemeText": "Odaberite temu obrasca",
    "setViewerText": "Konfiguracija preglednika",
    "introText": "Početak",
    "webmapText": "Web-karta",
    "layerText": "Sloj",
    "detailsText": "Pojedinosti",
    "fieldsText": "Polja",
    "styleText": "Stil",
    "viewerText": "Preglednik",
    "optionText": "Opcije",
    "previewText": "Pretpregled",
    "publishText": "Objavi",
    "optionsApplicationText": "Opcije",
    "submitButtonText": "Gumb za slanje teksta (neobavezno)",
    "submitButtonDesc": "Također možete označiti gumb za slanje novog unosa. Ovaj se tekst ne prevodi.",
    "viewSubmissionsText": "Tekst za prikaz podnesaka (neobavezno)",
    "viewSubmissionsDesc": "Također možete označiti gumb za prikaz postojećih unosa. Ovaj se tekst ne prevodi.",
    "titleText": "Sastavljač",
    "descriptionText": "GeoForm je predložak koji se može konfigurirati za uređivanje podataka na temelju obrasca za ${link1}uslugu geoobjekata${closeLink}. Ova aplikacija omogućuje korisnicima unos podataka preko obrasca umjesto na skočne prozore karte istovremeno balansirajući između ${link2}Web-karte${closeLink} i Feature Services koje se mogu urediti. S pomoću sljedećih koraka prilagodite i implementirajte svoj GeoForm.",
    "btnPreviousText": "Prethodno",
    "btnNextText": "Sljedeće",
    "webmapTabTitleText": "Odaberite web-kartu",
    "viewWebmap": "Prikaz web-karte",
    "webmapDetailsText": "Odabrana web-karta je ${webMapTitleLink}${webMapTitle}${closeLink}. Za odabir druge web-karte kliknite na gumb „Odabir web-karte”.",
    "btnSelectWebmapText": "Odabir web-karte",
    "btnSelectWebmapTextLoading": "Učitavanje&hellip;",
    "layerTabTitleText": "Odaberite sloj(eve) koji se mogu uređivati",
    "selectLayerLabelText": "Sloj",
    "selectLayerDefaultOptionText": "Odabir sloja",
    "enableBasemapToggle": "Prikaži prebacivanje kartografske podloge",
    "enableBasemapToggleDescription": "Možete konfigurirati GeoForm za prikaz/sakrivanje prebacivanja kartografske podloge",
    "defaultBasemap": "Prebacivanje kartografske podloge",
    "secondaryBasemap": "Zadana kartografska podloga",
    "detailsTabTitleText": "Pojedinosti obrasca",
    "detailTitleLabelText": "Naziv",
    "detailLogoLabelText": "Slika logotipa",
    "descriptionLabelText": "Upute i pojedinosti obrasca",
    "fieldDescriptionLabelText": "Tekst pomoći (neobavezno)",
    "fieldDescriptionHelpText": "Upišite kratki opis ili upute za ovo polje.",
    "fieldHintHelpText": "Rezervirano mjesto teksta za polje.",
    "fieldTabFieldHeaderText": "Polje",
    "fieldTabLabelHeaderText": "Oznaka",
    "fieldTabDisplayTypeHeaderText": "Prikaži kao",
    "fieldTabOrderColumnText": "Redoslijed",
    "fieldTabVisibleColumnText": "Omogućeno",
    "displayFieldText": "Prikaži polje",
    "selectMenuOption": "Odabir izbornika",
    "selectRadioOption": "Gumb radio",
    "selectTextOption": "Tekst",
    "selectDateOption": "Date Picker",
    "selectRangeOption": "Touch-Spinner",
    "selectCheckboxOption": "Potvrdni okvir",
    "selectMailOption": "E-pošta",
    "selectUrlOption": "URL",
    "selectTextAreaOption": "Područje teksta",
    "previewApplicationText": "Pretpregled aplikacije",
    "saveApplicationText": "Spremi aplikaciju",
    "saveText": "Spremi",
    "toggleNavigationText": "Preklopi navigaciju",
    "formPlaceholderText": "Moj obrazac",
    "shareBuilderInProgressTitleMessage": "Objava GeoForma",
    "shareBuilderProgressBarMessage": "Pričekajte&hellip;",
    "shareBuilderTitleMessage": "Uspjeh! Stavka spremljena",
    "shareBuilderTextMessage": "Možete početi prikupljati informacije dijeljenjem s drugima",
    "shareModalFormText": "Poveznica obrasca",
    "shareBuilderSuccess": "Vaš GeoForm ažuriran je i objavljen!",
    "geoformTitleText": "Geo Form",
    "layerTabText": "Ovo su slojevi od kojih će se izraditi GeoForm. Sloj mora imati uslugu geoobjekata koji se mogu uređivati uz omogućeno dijeljenje prikladno za vašu publiku. Ako se odaberu svi slojevi, obrazac će omogućiti korisniku da odabere kojem obrascu sloja želi pridonijeti.",
    "detailsTabText": "Upotrijebite okvire za pojedinosti obrasca za uređivanje naslova, dodavanje prilagođenog logotipa i upišite kratki opis za svoju publiku za GeoForm. U opis možete dodati poveznice na druge resurse, kontaktne podatke te čak usmjeriti svoju publiku na aplikaciju za web-kartiranje koja sadrži sve podatke prikupljene s pomoću GeoForma.",
    "fieldsTabText": "Ovdje možete odabrati koja će polja biti vidljiva vašoj publici koja prati GeoForm, urediti oznake koje će moći vidjeti i dodati kratki opis za pomoć s unosom podataka.",
    "styleTabText": "Uredite svoj GeoForm prema vlastitom ukusu s pomoću dolje navedenih tema.",
    "viewerTabText": "Postavite opcije za prikaz podnesaka prikupljenih iz GeoForma.",
    "publishTabText": "Ako ste završili s prilagodbom svog GeoForma, spremite aplikaciju i počnite dijeljenje s publikom. Uvijek se možete vratiti sastavljaču i nastaviti ga prilagođavati na temelju povratnih informacija.",
    "headerSizeLabel": "Veličina zaglavlja",
    "smallHeader": "Upotrijebi malo zaglavlje",
    "bigHeader": "Upotrijebi veliko zaglavlje",
    "pushpinText": "Stavi pribadaču",
    "doneButtonText": "Spremi i izađi",
    "fieldTabPlaceHolderHeaderText": "Podsjetnik (neobavezno)",
    "enableAttachmentLabelText": "${openStrong}Omogući privitke${closeStrong}",
    "enableAttachmentLabelHint": "Ovdje možete omogućiti/onemogućiti privitke",
    "attachmentIsRequiredLabelText": "${openStrong}Potreban privitak${closeStrong}",
    "attachmentIsRequiredLabelHint": "Ako je potrebno, od korisnika se može zatražiti da dodaju privitak.",
    "attachmentLabelText": "Oznaka gumba za privitak",
    "attachmentLabelHint": "Ovaj će se tekst pojaviti pored gumba za privitak. Ovaj prostor možete upotrijebiti za opis stavki koje želite da vaša publika priloži (fotografije, videozapisi, dokumenti itd.), format datoteke koji vam je potreban (.jpeg, .png, .docx, .pdf itd.) i za ostale dodatne upute",
    "attachmentDescription": "Opis privitka",
    "attachmentHint": "Ako je potrebno, ovdje možete upisati dodatne upute za privitke.",
    "jumbotronDescription": "Upotrijebite veliko ili malo zaglavlje za svoj obrazac. Veliko zaglavlje može pomoći pri definiranju svrhe vaše aplikacije, ali zauzima više mjesta na zaslonu",
    "shareGeoformText": "Gumbi za dijeljenje na društvenim medijima",
    "shareDescription": "Gumbi za dijeljenje na društvenim medijima omogućuju vašoj publici da jednostavno dijeli vaš GeoForm nakon što pošalju podnesak",
    "defaultMapExtent": "Zadani obuhvat karte",
    "defaultMapExtentDescription": "Karta će vratiti izvorne postavke obuhvata na vašoj web-karti nakon podnošenja - to se bilo kada može onemogućiti.",
    "pushpinOptionsDescription": "Odaberite boju pribadače na karti među brojnim bojama, treba se razlikovati od simbologije karte da olakša korisnicima da doprinesu karti",
    "selectLocationText": "Odaberi lokaciju prema",
    "myLocationText": "Moja lokacija",
    "searchText": "Pretraži",
    "coordinatesText": "Koordinate geografske širine/dužine",
    "usng": "USNG koordinate",
    "mgrs": "MGRS koordinate",
    "utm": "UTM koordinate",
    "selectLocationSDescription": "Omogućite korisnicima da odaberu lokaciju s pomoću ovih načina.",
    "dragTooltipText": "Povucite polje gdje želite da se pojavi",
    "showHideLayerText": "Prikaži sloj",
    "showHideLayerHelpText": "Možete konfigurirati GeoForm za skrivanje/prikazivanje sloja. Ova se opcija odnosi samo na postavku s jednim slojem.",
    "enableOfflineSupport": "Omogući izvanmrežnu podršku",
    "enableOfflineSupportHelpText": "Pohranite podneske kada mrežna veza nije uspostavljena i pošaljite ih kada se veza obnovi.",
    "labelHelpMessage": "Oznaka",
    "placeHolderHintMessage": "Tekst podsjetnika",
    "placeHolderHelpMessage": "Tekst pomoći",
    "selectTextOptionValue": "Odabir filtra",
    "disableLogo": "Onemogući logotip",
    "disableLogoDescription": "Možete konfigurirati GeoForm za prikazivanje/skrivanje logotipa u obliku zaglavlja",
    "locateOnLoadText": "Pronađi pri učitavanju",
    "locateOnLoadDescription": "Možete konfigurirati GeoForm da upotrijebi trenutačnu lokaciju pri učitavanju stranice",
    "selectLayerFieldTabText": "Odabir sloja",
    "allLayerSelectOptionText": "Svi slojevi",
    "disableViewer": "Onemogući preglednik",
    "disableViewerDescription": "Možete konfigurirati GeoForm da onemogući/omogući preglednik",
    "displayFieldHintText": "Odabrano polje prikaza prikazat će se u pregledniku kao naslov"
  },
  "viewer": {
    "geocoderCancelText": "Odustani",
    "viewMapTabText": "Karta",
    "sortHeaderText": "Sortiraj prema:",
    "geocoderPlaceholderText": "Poštanski broj, grad itd.",
    "noSearchResult": "Nema rezultata",
    "legendTabTooltip": "Legenda",
    "aboutUsTabTooltip": "O nama",
    "mapTabTooltip": "Karta",
    "btnDescendingText": "Silazno",
    "btnAscendingText": "Uzlazno",
    "geometryUnavailableErrorMessage": "Pogreška pri pronalaženju geometrije geoobjekta",
    "infoPopupOffErrorMessage": "Nema informacija za prikaz",
    "btnLoadMoreText": "Učitaj više",
    "unavailableTitleText": "Neimenovano",
    "unavailableConfigMessage": "Nije moguće učitati konfiguraciju",
    "share": "Podijeli",
    "viewReportsTabText": "Izvješća",
    "viewLegendTabText": "Legenda",
    "viewAboutusTabText": "Informacije",
    "appLoadingFailedMessage": "Došlo je do pogreške pri učitavanju preglednika"
  }
});