define({
  "map": {
    "error": "Неможливо створити карту",
    "licenseError": {
      "message": "Ваш обліковий запис не має ліцензії на використання настроюваних додатків, які не є публічними Попросіть адміністратора вашої організації призначити вам тип користувача, що включає основні додатки або додаткову ліцензію на основні додатки.",
      "title": "Немає ліцензії"
    }
  },
  "onlineStatus": {
    "offline": "Зараз ви працюєте в автономному режимі. Форми внесків будуть збережені локально, поки не можливо буде встановити підключення до серверу.",
    "reconnecting": "Виконується повторне підключення&hellip;",
    "pending": "${total} очікувана зміна (очікуваних змін) буде надіслано при відновленні мережевого підключення."
  },
  "configure": {
    "mapdlg": {
      "items": {
        "organizationLabel": "Моя організація",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "Мій зміст",
        "favoritesLabel": "Моє обране"
      },
      "title": "Вибрати веб-карту",
      "searchTitle": "Пошук",
      "ok": "Ok",
      "cancel": "Скасувати",
      "placeholder": "Введіть критерій пошуку"
    },
    "groupdlg": {
      "items": {
        "organizationLabel": "Моя організація",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "Мій зміст",
        "favoritesLabel": "Моє обране"
      },
      "title": "Вибрати групу",
      "searchTitle": "Пошук",
      "ok": "Ok",
      "cancel": "Скасувати",
      "placeholder": "Введіть критерій пошуку"
    },
    "sharedlg": {
      "items": {},
      "mailtoLinkDescription": "Посилання на GeoForm"
    }
  },
  "user": {
    "all": "Всі",
    "mgrs": "MGRS",
    "usng": "USNG",
    "utm": "UTM",
    "utm_northing": "Відлік по осі ординат",
    "utm_easting": "Відлік по осі абсцис",
    "utm_zone_number": "Номер зони",
    "selectLayerTabText": "${formSection} Виберіть з",
    "geoFormGeneralTabText": "${formSection} Введіть інформацію",
    "locationInformationText": "${formSection} Виберіть місце розташування",
    "submitInformationText": "${formSection} Заповніть форму",
    "submitInstructions": "Додайте цю інформацію до карти.",
    "myLocationText": "Поточне місце розташування",
    "locationDescriptionForMoreThanOneOption": "Вкажіть місце розташування для цього запису, клацнувши на карті/торкнувшись карти або за допомогою однієї з наступних опцій.",
    "locationDescriptionForOneOption": "Вкажіть місце розташування для цього запису, клацнувши на карті/торкнувшись карти або за допомогою наступної опції.",
    "locationDescriptionForNoOption": "Вкажіть місце розташування для цього запису, клацнувши на карті/торкнувшись карти.",
    "addressText": "Пошук",
    "geographic": "Шир./довг.",
    "locationTabText": "Місце розташування",
    "locationPopupTitle": "Місце розташування",
    "submitButtonText": "Надіслати запис",
    "submitButtonTextLoading": "Надсилається&hellip;",
    "formValidationMessageAlertText": "Наступні поля є обов’язковими:",
    "selectLocation": "Виберіть місце розташування для вашого внеску.",
    "emptylatitudeAlertMessage": "Введіть координату широти ${openLink}${closeLink}.",
    "emptylongitudeAlertMessage": "Введіть координату довготи ${openLink}${closeLink}.",
    "shareUserTitleMessage": "Дякуємо за ваш внесок!",
    "entrySubmitted": "Ваш запис було надіслано у карту.",
    "shareThisForm": "Поділитися цією формою",
    "shareUserTextMessage": "Запросити інших зробити внесок за допомогою наступних опцій.",
    "addAttachmentFailedMessage": "Неможливо додати прикріплення до шару",
    "addFeatureFailedMessage": "Неможливо додати об'єкт до шару",
    "noLayerConfiguredMessage": "При завантаженні або пошуку редагованого векторного шару виникла помилка. Для відображення форми та початку збору внесків додайте редагований векторний шар до веб-карти.",
    "placeholderLatitude": "Широта (Y)",
    "placeholderLongitude": "Довгота (X)",
    "latitude": "Широта",
    "longitude": "Довгота",
    "findMyLocation": "Визначити моє місце розташування",
    "finding": "Виконується визначення місця розташування&hellip;",
    "backToTop": "Повернутися до початку сторінки",
    "addressSearchText": "Ваш внесок з'явиться тут. Ви можете перетягнути кнопку в правильне місце розташування.",
    "shareModalFormText": "Посилання на форму",
    "close": "Закрити",
    "locationNotFound": "Не вдалося знайти місце розташування.",
    "setLocation": "Задати місце розташування",
    "find": "Знайти адресу або місце",
    "attachment": "Прикріплення",
    "toggleDropdown": "Перемкнути розкривний список",
    "invalidString": "Введіть дійсне значення.",
    "invalidSmallNumber": "Введіть дійсне ${openStrong}ціле число${closeStrong} від 32768 до 32767.",
    "invalidNumber": "Введіть дійсне ${openStrong}ціле число${closeStrong} від 2147483648 до 2147483647.",
    "invalidFloat": "Введіть дійсне ${openStrong}значення з плаваючою комою${closeStrong}.",
    "invalidDouble": "Введіть дійсне ${openStrong}подвійне значення${closeStrong}.",
    "invalidLatLong": "Введіть дійсні координати широти та довготи.",
    "invalidUTM": "Введіть дійсні координати UTM.",
    "invalidUSNG": "Введіть дійсні координати USNG.",
    "invalidMGRS": "Введіть дійсні координати MGRS.",
    "geoformTitleText": "GeoForm",
    "domainDefaultText": "Вибрати&hellip;",
    "applyEditsFailedMessage": "Виникла помилка внеску.",
    "applyEditsFailedRobot": "Внесок було відхилено, оскільки він не пройшов перевірку на робота.",
    "applyEditsAuthError": "Ваш запис неможливо надіслати через ваш тип рівня користувача. Зверніться до адміністратора вашої організації для отримання додаткової підтримки.",
    "requiredFields": "Наступне поле є обов’язковим. Введіть дійсний запис.",
    "requiredField": "(потрібно)",
    "error": "Помилка",
    "textRangeHintMessage": "${openStrong}Підказка:${closeStrong} мінімальне значення ${minValue} та максимальне значення ${maxValue}",
    "dateRangeHintMessage": "${openStrong}Підказка:${closeStrong} мінімальна дата ${minValue} та максимальна дата ${maxValue}",
    "remainingCharactersHintMessage": "Залишилось ${value} символів",
    "mapFullScreen": "На весь екран",
    "mapRestore": "Відновити",
    "filterSelectEmptyText": "Вибрати",
    "invalidLayerMessage": "Не було знайдено дійсний шар для створення GeoForm. Якщо GeoForm було налаштовано з шаром, шар може більше не бути доступним або не вдалося виконати авторизацію.",
    "selectedLayerText": "Всі",
    "fileUploadStatus": "Стан передачі файлу",
    "uploadingBadge": "&nbsp;Виконується передача&hellip;",
    "successBadge": "&nbsp;Передано",
    "retryBadge": "Повторити",
    "errorBadge": "Помилка при передачі&nbsp;&nbsp;&nbsp;",
    "fileTooLargeError": "Файл занадто великий для прикріплення",
    "exceededFileCountError": "Перевищено максимальну кількість дозволених прикріплень",
    "selectFileTitle": "Виберіть файл",
    "btnSelectFileText": "Вибрати файл",
    "btnViewSubmissions": "Переглянути внески"
  },
  "builder": {
    "gettingStarted": "Початок роботи",
    "dateSettings": "Налаштування дати",
    "hiddenDateField": "Приховати це поле дати",
    "preventPastDates": "Не допускати минулих дат",
    "preventFutureDates": "Не допускати майбутніх дат",
    "useCurrentDate": "Вкажіть у цьому полі поточну дату та час",
    "configure": "Налаштувати",
    "configureField": "Налаштувати поле '${fieldName}'",
    "invalidUser": "Вибачте, ви не маєте дозволу переглядати цей елемент",
    "invalidWebmapSelectionAlert": "Вибрана веб-карта не містить дійсного шару для використання. Додайте редагований векторний шар у вашу веб-карту для продовження.",
    "invalidWebmapSelectionAlert2": "Для отримання додаткової інформації див. розділ ${openLink}«Що таке сервіс об'єктів»?${closeLink}",
    "selectFieldsText": "Вибрати поля форми",
    "selectThemeText": "Вибрати тему форми",
    "setViewerText": "Налаштувати вьюер",
    "introText": "Початок",
    "webmapText": "Веб-карта",
    "layerText": "Шар",
    "detailsText": "Детальна інформація",
    "fieldsText": "Поля",
    "styleText": "Стиль",
    "viewerText": "Вьюер",
    "optionText": "Опції",
    "previewText": "Попередній перегляд",
    "publishText": "Публікувати",
    "optionsApplicationText": "Опції",
    "submitButtonText": "Текст кнопки «Надіслати» (необов’язково)",
    "submitButtonDesc": "Необов’язково задайте напис для кнопки для надсилання нового запису. Цей текст не буде перекладатись.",
    "viewSubmissionsText": "Текст «Переглянути внески» (необов’язково)",
    "viewSubmissionsDesc": "Необов’язково задайте напис для кнопки для перегляду існуючих записів. Цей текст не буде перекладатись.",
    "titleText": "Конструктор",
    "descriptionText": "GeoForm — це настроюваний шаблон для редагування даних через форму для ${link1}сервісу об’єктів${closeLink}. Цей додаток дозволяє користувачам вводити дані через форму, а не через спливаюче вікно карти, використовуючи можливості ${link2}веб-карти${closeLink} та редагованих сервісів об'єктів. Виконайте наступні кроки для налаштування та розгортання вашої GeoForm.",
    "btnPreviousText": "Назад",
    "btnNextText": "Далі",
    "webmapTabTitleText": "Вибрати веб-карту",
    "viewWebmap": "Переглянути веб-карту",
    "webmapDetailsText": "Вибрана веб-карта ${webMapTitleLink}${webMapTitle}${closeLink}. Для вибору іншої веб-карти натисніть кнопку «Вибрати веб-карту»",
    "btnSelectWebmapText": "Вибрати веб-карту",
    "btnSelectWebmapTextLoading": "Завантаження&hellip;",
    "layerTabTitleText": "Вибрати редагований шар(-и)",
    "selectLayerLabelText": "Шар",
    "selectLayerDefaultOptionText": "Вибрати шар",
    "enableBasemapToggle": "Показати перемикач базової карти",
    "enableBasemapToggleDescription": "Ви можете налаштувати для GeoForm опцію «Показати/приховати перемикач базової карти».",
    "defaultBasemap": "Перемикач базової карти",
    "secondaryBasemap": "Базова карта за замовчуванням",
    "detailsTabTitleText": "Детальна інформація форми",
    "detailTitleLabelText": "Заголовок",
    "detailLogoLabelText": "Зображення логотипу",
    "descriptionLabelText": "Інструкції та детальна інформація про форму",
    "fieldDescriptionLabelText": "Текст довідки (необов’язково)",
    "fieldDescriptionHelpText": "Надайте короткий опис або інструкції для цього поля.",
    "fieldHintHelpText": "Текст заповнювача для поля.",
    "fieldTabFieldHeaderText": "Поле",
    "fieldTabLabelHeaderText": "Напис",
    "fieldTabDisplayTypeHeaderText": "Відобразити як",
    "fieldTabOrderColumnText": "Порядок",
    "fieldTabVisibleColumnText": "Активовано",
    "displayFieldText": "Поле відображення",
    "selectMenuOption": "Вибрати меню",
    "selectRadioOption": "Перемикач",
    "selectTextOption": "Текст",
    "selectDateOption": "Елемент вибору дати",
    "selectRangeOption": "Поле із змінним значенням",
    "selectCheckboxOption": "Прапорець",
    "selectMailOption": "Ел. пошта",
    "selectUrlOption": "URL",
    "selectTextAreaOption": "Текстова область",
    "previewApplicationText": "Виконати попередній перегляд додатку",
    "saveApplicationText": "Зберегти додаток",
    "saveText": "Зберегти",
    "toggleNavigationText": "Перемикання навігації",
    "formPlaceholderText": "Моя форма",
    "shareBuilderInProgressTitleMessage": "Виконується публікація GeoForm",
    "shareBuilderProgressBarMessage": "Зачекайте&hellip;",
    "shareBuilderTitleMessage": "Успішно! Елемент збережено",
    "shareBuilderTextMessage": "Ви можете почати збирати інформацією, надавши спільний доступ іншим",
    "shareModalFormText": "Посилання на форму",
    "shareBuilderSuccess": "Вашу GeoForm було оновлено та опубліковано!",
    "geoformTitleText": "GeoForm",
    "layerTabText": "GeoForm буде створено на основі цього шару(-ів). Шар повинен бути сервісом об'єктів, який активований для редагування з відповідними дозволами на спільний доступ для вашої аудиторії. Якщо всі шари вибрано, форма дозволить користувачу вибрати, до якого шару форми можна зробити внесок.",
    "detailsTabText": "Використовуйте поля «Детальна інформація форми» нижче для налаштування заголовку, додайте власний логотип та надайте короткий опис вашої аудиторії GeoForm. У описі можна додавати посилання на інші ресурси, контактну інформацію та навіть направляти вашу аудиторію до додатку веб-картографування, який містить всі дані, зібрані з допомогою GeoForm.",
    "fieldsTabText": "Тут можна вибрати, які поля будуть видимі для вашої аудиторії GeoForm, редагувати написи, які вона буде бачити, та додавати короткий опис для допомоги з введенням даних.",
    "styleTabText": "Створіть свій стиль GeoForm за допомогою наведених нижче тем, яким ви надаєте перевагу.",
    "viewerTabText": "Задайте опції для перегляду внесків, зібраних за допомогою GeoForm.",
    "publishTabText": "Після завершення налаштування вашої GeoForm збережіть додаток та почніть ділитися з вашою аудиторією. Ви завжди можете повернутися до цього конструктора та продовжити налаштування на основі отриманих відгуків.",
    "headerSizeLabel": "Розмір верхнього колонтитулу",
    "smallHeader": "Використовувати малий верхній колонтитул",
    "bigHeader": "Використовувати великий верхній колонтитул",
    "pushpinText": "Кнопка",
    "doneButtonText": "Зберегти та вийти",
    "fieldTabPlaceHolderHeaderText": "Підказка (необов’язково)",
    "enableAttachmentLabelText": "${openStrong}Активувати прикріплення${closeStrong}",
    "enableAttachmentLabelHint": "Ви можете активувати/деактивувати прикріплення тут",
    "attachmentIsRequiredLabelText": "${openStrong}Обов’язкове прикріплення${closeStrong}",
    "attachmentIsRequiredLabelHint": "Якщо необхідно, користувачі повинні ввести прикріплення.",
    "attachmentLabelText": "Напис кнопки «Прикріплення»",
    "attachmentLabelHint": "Цей текст буде відображатися поруч з кнопкою «Прикріплення». Ви можете використовувати це поле для опису того, що повинна прикріпити ваша аудиторія (фотографія, відео, документ і т. д.), потрібного формату файлів (.jpeg, .png, .docx, .pdf і т. д.), а також для наведення будь-яких додаткових інструкцій",
    "attachmentDescription": "Опис прикріплення",
    "attachmentHint": "Якщо необхідно, ви можете надати додаткові інструкції для прикріплень тут.",
    "jumbotronDescription": "Використовуйте великий або малий верхній колонтитул для вашої форми. Великий колонтитул може допомогти визначити ціль вашого додатку, проте займає багато місця на екрані",
    "shareGeoformText": "Кнопки надання спільного доступу в соціальних мережах",
    "shareDescription": "Кнопки соціальних мереж дозволяють вашій аудиторії легко ділитися вашою GeoForm, після того, як вони зробили внесок",
    "defaultMapExtent": "Екстент карти за замовчуванням",
    "defaultMapExtentDescription": "Карту буде скинуто до екстенту за замовчуванням у вашій веб-карті після внеску; це можна деактивувати в будь-який час.",
    "pushpinOptionsDescription": "Виберіть з набору колір для кнопки карти; він повинен відрізнятися від умовних позначень карти, щоб допомогти користувачу розмістити свій внесок на карті",
    "selectLocationText": "Вибрати місце розташування за",
    "myLocationText": "Моє місце розташування",
    "searchText": "Пошук",
    "coordinatesText": "Координати широти та довготи",
    "usng": "Координати USNG",
    "mgrs": "Координати MGRS",
    "utm": "Координати UTM",
    "selectLocationSDescription": "Дозвольте користувачам вибирати місце розташування за допомогою цих методів.",
    "dragTooltipText": "Перетягніть поле туди, де воно повинно відображатись",
    "showHideLayerText": "Показати шар",
    "showHideLayerHelpText": "Ви можете налаштувати для GeoForm функцію «Показати/приховати шар». Ця опція застосовується тільки до конфігурації з одним шаром.",
    "enableOfflineSupport": "Активувати підтримку в автономному режимі",
    "enableOfflineSupportHelpText": "Зберігати внески, коли відсутнє мережеве підключення, та надсилати їх при відновленні підключення.",
    "labelHelpMessage": "Напис",
    "placeHolderHintMessage": "Текст підказки",
    "placeHolderHelpMessage": "Текст довідки",
    "selectTextOptionValue": "Вибір фільтра",
    "disableLogo": "Деактивувати логотип",
    "disableLogoDescription": "Ви можете налаштувати для GeoForm опцію «Показати/приховати логотип у верхньому колонтитулі форми»",
    "locateOnLoadText": "Визначити місце розташування при завантаженні",
    "locateOnLoadDescription": "Ви можете налаштувати GeoForm на використання поточного місця розташування при завантаженні сторінки",
    "selectLayerFieldTabText": "Вибрати шар",
    "allLayerSelectOptionText": "Всі шари",
    "disableViewer": "Деактивувати вьюер",
    "disableViewerDescription": "Ви можете налаштувати GeoForm на деактивацію/активацію вьюера",
    "displayFieldHintText": "Вибране поле відображення буде показуватись у вьюері як заголовок"
  },
  "viewer": {
    "geocoderCancelText": "Скасувати",
    "viewMapTabText": "Карта",
    "sortHeaderText": "Сортувати за:",
    "geocoderPlaceholderText": "Поштовий індекс, місто і т. д.",
    "noSearchResult": "Результат не знайдено",
    "legendTabTooltip": "Легенда",
    "aboutUsTabTooltip": "Про нас",
    "mapTabTooltip": "Карта",
    "btnDescendingText": "У низхідному порядку",
    "btnAscendingText": "У висхідному порядку",
    "geometryUnavailableErrorMessage": "Помилка при пошуку геометрії об'єкту",
    "infoPopupOffErrorMessage": "Немає інформації для відображення",
    "btnLoadMoreText": "Завантажити більше",
    "unavailableTitleText": "Без заголовка",
    "unavailableConfigMessage": "Не вдалося завантажити конфігурацію",
    "share": "Поділитися",
    "viewReportsTabText": "Звіти",
    "viewLegendTabText": "Легенда",
    "viewAboutusTabText": "Про програму",
    "appLoadingFailedMessage": "При завантаженні вьюера виникла помилка."
  }
});