define({
  "map": {
    "error": "Nebolo možné vytvoriť mapu",
    "licenseError": {
      "message": "Váš účet nezahŕňa licenciu na použitie Konfigurovateľných aplikácií, ktoré nie sú verejné. Požiadajte správcu vašej organizácie, aby vám priradil typ používateľa, ktorý zahŕňa Esenciálne aplikácie alebo doplnkovú licenciu Esenciálnych aplikácií",
      "title": "Nelicencované"
    }
  },
  "onlineStatus": {
    "offline": "Momentálne pracujete v režime offline. Odoslané formuláre sa budú ukladať lokálne, kým nebude možné nadviazať spojenie so serverom.",
    "reconnecting": "Znovu sa pripája&hellip;",
    "pending": "${total} čakajúce úpravy budú odoslané po obnovení sieťového pripojenia."
  },
  "configure": {
    "mapdlg": {
      "items": {
        "organizationLabel": "Moja organizácia",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "Môj obsah",
        "favoritesLabel": "Moje obľúbené"
      },
      "title": "Vybrať webovú mapu",
      "searchTitle": "Vyhľadávanie",
      "ok": "Ok",
      "cancel": "Zrušiť",
      "placeholder": "Zadať hľadaný výraz"
    },
    "groupdlg": {
      "items": {
        "organizationLabel": "Moja organizácia",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "Môj obsah",
        "favoritesLabel": "Moje obľúbené"
      },
      "title": "Vybrať skupinu",
      "searchTitle": "Vyhľadávanie",
      "ok": "Ok",
      "cancel": "Zrušiť",
      "placeholder": "Zadať hľadaný výraz"
    },
    "sharedlg": {
      "items": {},
      "mailtoLinkDescription": "Tu je prepojenie na GeoForm"
    }
  },
  "user": {
    "all": "Všetky",
    "mgrs": "MGRS",
    "usng": "USNG",
    "utm": "UTM",
    "utm_northing": "Severné súradnice",
    "utm_easting": "Východné súradnice",
    "utm_zone_number": "Číslo zóny",
    "selectLayerTabText": "${formSection} Vybrať formulár",
    "geoFormGeneralTabText": "${formSection} Zadať informácie",
    "locationInformationText": "${formSection} Vybrať umiestnenie",
    "submitInformationText": "${formSection} Dokončiť formulár",
    "submitInstructions": "Pridať tieto informácie do mapy.",
    "myLocationText": "Súčasné umiestnenie",
    "locationDescriptionForMoreThanOneOption": "Zadajte umiestnenie pre tento záznam kliknutím/ťuknutím na mapu alebo použitím jednej z nasledujúcich možností.",
    "locationDescriptionForOneOption": "Zadajte umiestnenie pre tento záznam kliknutím/ťuknutím na mapu alebo použitím nasledujúcej možnosti.",
    "locationDescriptionForNoOption": "Zadajte umiestnenie pre tento záznam kliknutím/ťuknutím na mapu.",
    "addressText": "Vyhľadávanie",
    "geographic": "Zemepisná šírka/Zemepisná dĺžka",
    "locationTabText": "Umiestnenie",
    "locationPopupTitle": "Umiestnenie",
    "submitButtonText": "Odoslať záznam",
    "submitButtonTextLoading": "Odosielanie&hellip;",
    "formValidationMessageAlertText": "Sú požadované nasledujúce polia:",
    "selectLocation": "Vyberte umiestnenie pre Váš príspevok.",
    "emptylatitudeAlertMessage": "Prosím zadajte súradnicu ${openLink}latitude${closeLink}.",
    "emptylongitudeAlertMessage": "Prosím zadajte súradnicu ${openLink}longitude${closeLink}.",
    "shareUserTitleMessage": "Ďakujeme za váš príspevok!",
    "entrySubmitted": "Váš záznam bol odoslaný na mapu.",
    "shareThisForm": "Zdieľať tento formulár",
    "shareUserTextMessage": "Povedzte ostatným, aby prispeli pomocou nasledujúcich možností.",
    "addAttachmentFailedMessage": "Nie je možné pridať prílohu k vrstve.",
    "addFeatureFailedMessage": "Nie je možné pridať prvok k vrstve.",
    "noLayerConfiguredMessage": "Pri načítaní alebo nájdení editovateľnej vrstvy prvkov sa vyskytla chyba. Ak chcete zobraziť formulár a začať zhromažďovať príspevky, pridajte do webovej mapy upraviteľnú vrstvu prvkov.",
    "placeholderLatitude": "Zemepisná šírka (Y)",
    "placeholderLongitude": "Zemepisná dĺžka (X)",
    "latitude": "Zemepisná šírka",
    "longitude": "Zemepisná dĺžka",
    "findMyLocation": "Lokalizuj ma",
    "finding": "Lokalizácia&hellip;",
    "backToTop": "Späť hore",
    "addressSearchText": "Váš príspevok sa zobrazí tu. Umiestnenie môžete opraviť potiahnutím špendlíka.",
    "shareModalFormText": "Prepojenie na formulár",
    "close": "Zatvoriť",
    "locationNotFound": "Umiestnenie nie je možné nájsť.",
    "setLocation": "Nastaviť polohu",
    "find": "Nájsť adresu alebo miesto",
    "attachment": "Príloha",
    "toggleDropdown": "Prepnúť rozbaľovaciu ponuku",
    "invalidString": "Prosím zadajte platnú hodnotu.",
    "invalidSmallNumber": "Prosím zadajte platnú ${openStrong}integer${closeStrong} hodnotu medzi -32768 a 32767.",
    "invalidNumber": "Prosím zadajte platnú ${openStrong}integer${closeStrong} hodnotu medzi -2147483648 a 2147483647.",
    "invalidFloat": "Prosím zadajte platnú ${openStrong} hodnotu s pohyblivou desatinnou čiarkou${closeStrong}.",
    "invalidDouble": "Prosím zadajte platnú ${openStrong}double${closeStrong} hodnotu.",
    "invalidLatLong": "Prosím zadajte platné súradnice zemepisnej šírky a dĺžky.",
    "invalidUTM": "Prosím zadajte platné súradnice UTM.",
    "invalidUSNG": "Prosím zadajte platné súradnice USNG.",
    "invalidMGRS": "Prosím zadajte platné súradnice MGRS.",
    "geoformTitleText": "GeoForm",
    "domainDefaultText": "Vybrať&hellip;",
    "applyEditsFailedMessage": "Vyskytla sa chyba pri odoslaní.",
    "applyEditsFailedRobot": "Príspevok bol zamietnutý, pretože zlyhal na detekcii robota.",
    "applyEditsAuthError": "Váš záznam nie je možné odoslať kvôli typu Vašej užívateľskej úrovne. Ak potrebujete ďalšiu pomoc, kontaktujte svojho správcu organizácie.",
    "requiredFields": "Je požadované nasledujúce pole: Prosím zadajte platný záznam.",
    "requiredField": "(požadované)",
    "error": "Chyba",
    "textRangeHintMessage": "${openStrong}Hint:${closeStrong} Minimálna hodnota ${minValue} a Maximálna hodnota ${maxValue}",
    "dateRangeHintMessage": "${openStrong}Hint:${closeStrong} Minimálny dátum ${minValue} a Maximálny dátum ${maxValue}",
    "remainingCharactersHintMessage": "${value} zostávajúcich znakov",
    "mapFullScreen": "Režim celej obrazovky",
    "mapRestore": "Obnoviť",
    "filterSelectEmptyText": "Vybrať",
    "invalidLayerMessage": "Nebola nájdená platná vrstva na vytvorenie GeoForm. Ak bol GeoForm nakonfigurovaný s vrstvou, vrstva už nemusí byť k dispozícii alebo autorizácia zlyhala.",
    "selectedLayerText": "Všetky",
    "fileUploadStatus": "Stav nahratia súboru",
    "uploadingBadge": "&nbsp;Nahrávanie&hellip;",
    "successBadge": "&nbsp;Nahraté",
    "retryBadge": "Skúsiť znova",
    "errorBadge": "Chyba pri nahrávaní&nbsp;&nbsp;&nbsp;",
    "fileTooLargeError": "Súbor je príliš veľký na pripojenie",
    "exceededFileCountError": "Bol prekročený maximálny povolený počet príloh",
    "selectFileTitle": "Vyberte súbor",
    "btnSelectFileText": "Vybrať súbor",
    "btnViewSubmissions": "Zobraziť príspevky"
  },
  "builder": {
    "gettingStarted": "Začíname",
    "dateSettings": "Nastavenia dátumu",
    "hiddenDateField": "Skryť toto dátumové pole",
    "preventPastDates": "Predchádzajte minulým dátumom",
    "preventFutureDates": "Predchádzajte budúcim dátumom",
    "useCurrentDate": "Nastaviť toto pole na aktuálny dátum a čas",
    "configure": "Konfigurovať",
    "configureField": "Konfigurovať pole \"${fieldName}\"",
    "invalidUser": "Ľutujeme, nemáte povolenie na zobrazenie tejto položky",
    "invalidWebmapSelectionAlert": "Vybraná webová mapa neobsahuje platnú vrstvu na použitie. Ak chcete pokračovať, pridajte do svojej webovej mapy upraviteľnú vrstvu prvkov.",
    "invalidWebmapSelectionAlert2": "Ďalšie informácie nájdete v časti Čo je prvková služba (Feature Service)?${closeLink}${openLink}",
    "selectFieldsText": "Vybrať polia formulára",
    "selectThemeText": "Vybrať tému formulára",
    "setViewerText": "Konfigurovať zobrazovač",
    "introText": "Začiatok",
    "webmapText": "Webová mapa",
    "layerText": "Vrstva",
    "detailsText": "Podrobnosti",
    "fieldsText": "Stĺpce",
    "styleText": "Štýl",
    "viewerText": "Zobrazovateľ",
    "optionText": "Možnosti",
    "previewText": "Náhľad",
    "publishText": "Publikovať",
    "optionsApplicationText": "Možnosti",
    "submitButtonText": "Text tlačidla odoslania (voliteľné)",
    "submitButtonDesc": "Môžte označiť tlačidlo na odoslanie nového záznamu. Tento text nebude preložený.",
    "viewSubmissionsText": "Zobraziť text príspevkov (voliteľné)",
    "viewSubmissionsDesc": "Ak chcete zobraziť existujúce záznamy, môžte označiť tlačidlo. Tento text nebude preložený.",
    "titleText": "Prostredie Builder",
    "descriptionText": "GeoForm je konfigurovateľná šablóna pre editáciu dát na základe formulárov ${link1}Feature Service${closeLink}. Táto aplikácia umožňuje používateľom zadávať údaje prostredníctvom formulára namiesto kontextového okna mapy, pričom využíva schopnosť ${link2}webovej mapy${closeLink} a upraviteľných prvkových služieb (Feature Services). Pomocou nasledujúcich krokov prispôsobte a nasaďte svoju aplikáciu GeoForm.",
    "btnPreviousText": "Predchádzajúce",
    "btnNextText": "Ďalšie",
    "webmapTabTitleText": "Vybrať webovú mapu",
    "viewWebmap": "Zobraziť webovú mapu",
    "webmapDetailsText": "Vybraná webová mapa je ${webMapTitleLink}${webMapTitle}${closeLink}. Ak chcete vybrať inú webovú mapu, kliknite na tlačidlo „Vybrať webovú mapu“",
    "btnSelectWebmapText": "Zvoliť webovú mapu",
    "btnSelectWebmapTextLoading": "Načítavanie&hellip;",
    "layerTabTitleText": "Vybrať upraviteľné vrstvy",
    "selectLayerLabelText": "Vrstva",
    "selectLayerDefaultOptionText": "Vybrať vrstvu",
    "enableBasemapToggle": "Zobraziť prepínač podkladovej mapy",
    "enableBasemapToggleDescription": "Môžete nakonfigurovať GeoForm aby ukazoval/skryl prepínač podkladovej mapy",
    "defaultBasemap": "Prepínač podkladovej mapy",
    "secondaryBasemap": "Predvolená podkladová mapa",
    "detailsTabTitleText": "Podrobnosti formulára",
    "detailTitleLabelText": "Názov",
    "detailLogoLabelText": "Obrázok loga",
    "descriptionLabelText": "Inštrukcie & podrobnosti loga",
    "fieldDescriptionLabelText": "Pomocný text (voliteľné)",
    "fieldDescriptionHelpText": "Do tohto poľa zadajte krátky popis alebo inštrukciu.",
    "fieldHintHelpText": "Zástupný text pre pole.",
    "fieldTabFieldHeaderText": "Stĺpec",
    "fieldTabLabelHeaderText": "Popis",
    "fieldTabDisplayTypeHeaderText": "Zobraziť ako",
    "fieldTabOrderColumnText": "Poradie",
    "fieldTabVisibleColumnText": "Aktivovaný",
    "displayFieldText": "Zobraziť polia",
    "selectMenuOption": "Vybrať menu",
    "selectRadioOption": "Prepínač",
    "selectTextOption": "Text",
    "selectDateOption": "Výber dátumu",
    "selectRangeOption": "Dotykový Spinner",
    "selectCheckboxOption": "Zaškrtávacie políčko",
    "selectMailOption": "Email",
    "selectUrlOption": "URL",
    "selectTextAreaOption": "Pole pre text",
    "previewApplicationText": "Ukážka aplikácie",
    "saveApplicationText": "Uložiť aplikáciu",
    "saveText": "Uložiť",
    "toggleNavigationText": "Navigácia prepínača",
    "formPlaceholderText": "Môj formulár",
    "shareBuilderInProgressTitleMessage": "Publikuje sa GeoForm",
    "shareBuilderProgressBarMessage": "Prosím čakajte&hellip;",
    "shareBuilderTitleMessage": "Úspešné! Položka bola uložená",
    "shareBuilderTextMessage": "Zber informácií môžete začať zdieľaním s ostatnými",
    "shareModalFormText": "Prepojenie na formulár",
    "shareBuilderSuccess": "Váš GeoForm bol aktualizovaný & zverejnený!",
    "geoformTitleText": "Geo Form",
    "layerTabText": "Toto je vrstva (vrstvy), z ktorej bude GeoForm vytvorený. Vrstva musí byť prvkovou službou (Feature Service), ktorá je povolená pre úpravy s oprávneniami na zdieľanie vhodnými pre Vaše publikum. Ak sú vybrané všetky vrstvy, formulár umožní užívateľovi vybrať si, ktorú vrstvu formulára má odoslať.",
    "detailsTabText": "Pomocou polí pre podrobnosti formulára môžete prispôsobiť názov, pridať vlastné logo a poskytnúť krátky popis pre Vaše GeoForm publikum. V popise môžete pridať prepojenia na iné zdroje, kontaktné informácie a dokonca nasmerovať svoje publikum na webovú mapovú aplikáciu obsahujúcu všetky údaje zhromaždené pomocou GeoForm.",
    "fieldsTabText": "Na tomto mieste si môžete vybrať, ktoré polia budú viditeľné pre Vaše GeoForm publikum, upraviť označenia, ktoré uvidia a pridať krátky popis, ktorý Vám pomôže pri zadávaní údajov.",
    "styleTabText": "Upravte svoj GeoForm podľa nižšie uvedených tém na základe Vašich preferencií.",
    "viewerTabText": "Nastavte možnosti na prezeranie príspevkov zhromaždených z GeoForm.",
    "publishTabText": "Ak ste dokončili prispôsobovanie GeoForm, uložte aplikáciu a začnite zdieľať s publikom. Do tohto prostredia sa môžete kedykoľvek vrátiť a pokračovať v jeho prispôsobovaní na základe spätnej väzby.",
    "headerSizeLabel": "Veľkosť záhlavia",
    "smallHeader": "Použiť malé záhlavie",
    "bigHeader": "Použiť veľké záhlavie",
    "pushpinText": "Pripináčik",
    "doneButtonText": "Uložiť a ukončiť",
    "fieldTabPlaceHolderHeaderText": "Nápoveda (voliteľné)",
    "enableAttachmentLabelText": "${openStrong}Povoliť prílohy${closeStrong}",
    "enableAttachmentLabelHint": "Tu môžete povoliť/zakázať prílohy",
    "attachmentIsRequiredLabelText": "${openStrong}Vyžaduje sa príloha${closeStrong}",
    "attachmentIsRequiredLabelHint": "V prípade potreby sa od používateľov môže vyžadovať, aby zadali prílohu.",
    "attachmentLabelText": "Označenie tlačidla prílohy",
    "attachmentLabelHint": "Tento text sa zobrazí vedľa tlačidla prílohy. Na tomto mieste môžete opísať, čo chcete, aby Vaše publikum pripojilo (fotografia, video, dokument atď.), môžete zadať požadovaný formát súboru (.jpeg, .png, .docx, .pdf atď.) a akékoľvek ďalšie pokyny",
    "attachmentDescription": "Opis prílohy",
    "attachmentHint": "Ak je to potrebné, tu môžete poskytnúť doplňujúce inštrukcie k prílohám.",
    "jumbotronDescription": "Pre formulár použite veľký alebo malý nadpis. Veľké záhlavie môže pomôcť definovať účel Vašej aplikácie, ale zaberá viac miesta na obrazovke",
    "shareGeoformText": "Tlačidlo pre zdieľanie na sociálnych sieťach.",
    "shareDescription": "Tlačidlá sociálnych sietí umožňujú Vášmu publiku ľahko zdieľať Váš GeoForm, potom ako odoslali príspevok.",
    "defaultMapExtent": "Predvolený rozsah mapy",
    "defaultMapExtentDescription": "Mapa sa po odoslaní obnoví na predvolený rozsah vo Vašej webovej mape - túto funkciu môžete kedykoľvek vypnúť.",
    "pushpinOptionsDescription": "Vyberte si z rôznych farieb pre pripináčiky na mape. Mali by sa líšiť od symboliky mapy, aby pomohol používateľovi vložiť svoje príspevky na mapu.",
    "selectLocationText": "Vybrať umiestnenie podľa",
    "myLocationText": "Moje umiestnenie",
    "searchText": "Vyhľadávanie",
    "coordinatesText": "Súradnice zemepisnej šírky/zemepisnej dĺžky",
    "usng": "Súradnice USNG",
    "mgrs": "Súradnice MGRS",
    "utm": "Súradnice UTM",
    "selectLocationSDescription": "Umožnite používateľom vybrať umiestnenie pomocou týchto metód.",
    "dragTooltipText": "Potiahnite pole tam, kde sa má zobraziť",
    "showHideLayerText": "Ukázať vrstvu",
    "showHideLayerHelpText": "Môžete nakonfigurovať GeoForm aby ukazoval/skryl vrstvy. Táto voľba sa vzťahuje iba na nastavenie jednej vrstvy.",
    "enableOfflineSupport": "Povoliť offline podporu",
    "enableOfflineSupportHelpText": "Uložte príspevky, keď nie je k dispozícii sieťové pripojenie a odošlite ich pri obnovení pripojenia.",
    "labelHelpMessage": "Popis",
    "placeHolderHintMessage": "Text pomocníka",
    "placeHolderHelpMessage": "Pomocný text",
    "selectTextOptionValue": "Výber filtra",
    "disableLogo": "Zakázať logo",
    "disableLogoDescription": "Môžete nakonfigurovať GeoForm tak, aby zobrazoval/skryl logo v záhlaví formulára",
    "locateOnLoadText": "Vyhľadať pri načítaní",
    "locateOnLoadDescription": "Môžete nakonfigurovať GeoForm tak, aby používal aktuálnu polohu pri načítaní stránky",
    "selectLayerFieldTabText": "Vybrať vrstvu",
    "allLayerSelectOptionText": "Všetky vrstvy",
    "disableViewer": "Zakázať zobrazovač",
    "disableViewerDescription": "Môžete nakonfigurovať GeoFrom aby zakázal/povolil zobrazovač",
    "displayFieldHintText": "Vybraté pole pre zobrazovanie sa v prehliadači zobrazí ako názov"
  },
  "viewer": {
    "geocoderCancelText": "Zrušiť",
    "viewMapTabText": "Mapa",
    "sortHeaderText": "Zoradiť podľa:",
    "geocoderPlaceholderText": "PSČ, mesto, atď.",
    "noSearchResult": "Neboli nájdené žiadne výsledky",
    "legendTabTooltip": "Legenda",
    "aboutUsTabTooltip": "O nás",
    "mapTabTooltip": "Mapa",
    "btnDescendingText": "Zostupne",
    "btnAscendingText": "Vzostupne",
    "geometryUnavailableErrorMessage": "Pri hľadaní geometrie prvku sa vyskytla chyba",
    "infoPopupOffErrorMessage": "Nie je možné zobraziť žiadne informácie",
    "btnLoadMoreText": "Načítať viac",
    "unavailableTitleText": "Bez názvu",
    "unavailableConfigMessage": "Nie je možné načítať konfiguráciu",
    "share": "Zdieľať",
    "viewReportsTabText": "Prehľady",
    "viewLegendTabText": "Legenda",
    "viewAboutusTabText": "Informácie",
    "appLoadingFailedMessage": "Pri načítavaní zobrazovača sa vyskytla chyba."
  }
});