define(
     ({
        map: {
            error: "Impossibile creare la mappa"
        },
        onlineStatus: {
            offline: "Al momento è attiva la modalità offline. Gli invii di moduli verranno salvati in locale finché non sarà possibile stabilire una connessione al server.",
            reconnecting: "Riconnessione in corso&hellip;",
            pending: "${total} modifiche in sospeso verranno inviate non appena verrà ristabilita una connessione di rete."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "La mia organizzazione",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "I miei contenuti",
                    favoritesLabel: "I miei preferiti"
                },
                title: "Seleziona mappa Web",
                searchTitle: "Cerca",
                ok: "OK",
                cancel: "Annulla",
                placeholder: "Immettere il termine da cercare"
            },
            groupdlg: {
                items: {
                    organizationLabel: "La mia organizzazione",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "I miei contenuti",
                    favoritesLabel: "I miei preferiti"
                },
                title: "Seleziona gruppo",
                searchTitle: "Cerca",
                ok: "OK",
                cancel: "Annulla",
                placeholder: "Immettere il termine da cercare"
            },
            sharedlg: {
                items: {
                },
                mailtoLinkDescription: "Di seguito è riportato un collegamento a un modello GeoForm"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "A Nord",
            utm_easting: "Ad Est",
            utm_zone_number: "Numero zona",
            geoFormGeneralTabText: "1. Immettere le informazioni",
            locationInformationText: "2. Selezionare la posizione",
            submitInformationText: "3. Compilare il modulo",
            submitInstructions: "Aggiungere queste informazioni alla mappa.",
            myLocationText: "Posizione corrente",
            locationDescriptionForMoreThanOneOption: "Specificare la posizione per questa voce facendo clic o toccando la mappa o utilizzando una delle opzioni di seguito.",
            locationDescriptionForOneOption: "Per specificare la posizione per questa voce, toccare o fare clic sulla mappa oppure utilizzare la seguente opzione.",
            locationDescriptionForNoOption: "Per specificare la posizione per questa voce, toccare o fare clic sulla mappa.",
            addressText: "Cerca",
            geographic: "Lat/Lon",
            locationTabText: "Posizione",
            locationPopupTitle: "Posizione",
            submitButtonText: "Invia voce",
            submitButtonTextLoading: "Invio in corso&hellip;",
            formValidationMessageAlertText: "I seguenti campi sono obbligatori:",
            selectLocation: "Selezionare una posizione per l\'invio.",
            emptylatitudeAlertMessage: "Immettere una coordinata di ${openLink}latitudine${closeLink}.",
            emptylongitudeAlertMessage: "Immettere una coordinata di ${openLink}longitudine${closeLink}.",
            shareUserTitleMessage: "Grazie per il contributo!",
            entrySubmitted: "La voce è stata inviata alla mappa.",
            shareThisForm: "Condividi questo modulo",
            shareUserTextMessage: "Chiedere ad altri utenti di contribuire utilizzando le seguenti opzioni.",
            addAttachmentFailedMessage: "Impossibile aggiungere l\'allegato al layer",
            addFeatureFailedMessage: "Impossibile aggiungere la feature al layer",
            noLayerConfiguredMessage: "Si è verificato un errore durante il caricamento o la ricerca di un feature layer modificabile. Per visualizzare il modulo e avviare la raccolta degli invii, aggiungere alla mappa Web un feature layer modificabile.",
            placeholderLatitude: "Latitudine (Y)",
            placeholderLongitude: "Longitudine (X)",
            latitude: "Latitudine",
            longitude: "Longitudine",
            findMyLocation: "Trova la mia posizione",
            finding: "Individuazione in corso&hellip;",
            backToTop: "Torna all\'inizio",
            addressSearchText: "L\'invio verrà visualizzato qui. È possibile trascinare l\'indicatore per correggere la posizione.",
            shareModalFormText: "Collegamento modulo",
            close: "Chiudi",
            locationNotFound: "Posizione non trovata.",
            setLocation: "Imposta posizione",
            find: "Trova luogo o indirizzo",
            attachment: "Allegato",
            toggleDropdown: "Attiva/disattiva elenco a discesa",
            invalidString: "Immettere un valore valido.",
            invalidSmallNumber: "Immettere un valore ${openStrong}integer${closeStrong} valido compreso tra -32768 e 32767.",
            invalidNumber: "Immettere un valore ${openStrong}integer${closeStrong} valido compreso tra -2147483648 e 2147483647.",
            invalidFloat: "Immettere un valore ${openStrong}a virgola mobile${closeStrong} valido.",
            invalidDouble: "Immettere un valore ${openStrong}double${closeStrong} valido.",
            invalidLatLong: "Immettere coordinate di latitudine e longitudine valide.",
            invalidUTM: "Immettere coordinate UTM valide.",
            invalidUSNG: "Immettere coordinate USNG valide.",
            invalidMGRS: "Immettere coordinate MGRS valide.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Seleziona&hellip;",
            applyEditsFailedMessage: "Impossibile inviare i dati immessi. Riprovare.",
            requiredFields: "Sono presenti alcuni errori. Correggerli di seguito.",
            requiredField: "(obbligatorio)",
            error: "Errore",
            textRangeHintMessage: "${openStrong}Suggerimento:${closeStrong} Valore minimo ${minValue} e valore massimo ${maxValue}",
            dateRangeHintMessage: "${openStrong}Suggerimento:${closeStrong} Data minima ${minValue} e data massima ${maxValue}",
            remainingCharactersHintMessage: "${value} caratteri residui"
        },
        builder: {
            invalidUser: "Non si dispone dell\'autorizzazione per visualizzare questo elemento",
            invalidWebmapSelectionAlert: "La mappa Web selezionata non contiene un layer valido da utilizzare. Per proseguire aggiungere un FeatureLayer modificabile alla mappa Web.",
            invalidWebmapSelectionAlert2: "Per ulteriori informazioni consultare ${openLink}Cos\'è un feature service?${closeLink}",
            selectFieldsText: "Seleziona campi modulo",
            selectThemeText: "Seleziona tema modulo",
            webmapText: "Mappa Web",
            layerText: "Layer",
            detailsText: "Dettagli",
            fieldsText: "Campi",
            styleText: "Stile",
            optionText: "Opzioni",
            previewText: "Anteprima",
            publishText: "Pubblica",
            optionsApplicationText: "Opzioni",
            titleText: "Generatore",
            descriptionText: "GeoForm è un modello configurabile per la modifica di dati basata su moduli di un ${link1}Feature Service${closeLink}. Questa applicazione consente agli utenti di immettere dati utilizzando un modulo invece di un popup di mappa sfruttando la potenza della ${link2}Mappa Web${closeLink} e dei Feature Service modificabili. Per personalizzare e distribuire GeoForm utilizzare la procedura di seguito.",
            btnPreviousText: "Indietro",
            btnNextText: "Avanti",
            webmapTabTitleText: "Seleziona una mappa Web",
            viewWebmap: "Visualizza mappa Web",
            webmapDetailsText: "La mappa Web selezionata è ${webMapTitleLink}${webMapTitle}${closeLink}. Per selezionare una mappa Web diversa, fare clic sul pulsante 'Scegli mappa Web'.",
            btnSelectWebmapText: "Scegli mappa Web",
            btnSelectWebmapTextLoading: "Caricamento in corso&hellip;",
            layerTabTitleText: "Seleziona layer modificabile",
            selectLayerLabelText: "Layer",
            selectLayerDefaultOptionText: "Seleziona layer",
            detailsTabTitleText: "Dettagli modulo",
            detailTitleLabelText: "Titolo",
            detailLogoLabelText: "Immagine logo",
            descriptionLabelText: "Istruzioni modulo e dettagli",
            fieldDescriptionLabelText: "Testo guida (facoltativo)",
            fieldTabFieldHeaderText: "Campo",
            fieldTabLabelHeaderText: "Etichetta",
            fieldTabDisplayTypeHeaderText: "Visualizza come",
            fieldTabOrderColumnText: "Ordine",
            fieldTabVisibleColumnText: "Abilitato",
            selectMenuOption: "Seleziona menu",
            selectRadioOption: "Pulsante di scelta",
            selectTextOption: "Testo",
            selectDateOption: "Selettore data",
            selectRangeOption: "Selettore tocco",
            selectCheckboxOption: "Casella di controllo",
            selectMailOption: "E-mail",
            selectUrlOption: "URL",
            selectTextAreaOption: "Area di testo",
            previewApplicationText: "Anteprima applicazione",
            saveApplicationText: "Salva applicazione",
            saveText: "Salva",
            toggleNavigationText: "Attiva/disattiva navigazione",
            formPlaceholderText: "Modulo personale",
            shareBuilderInProgressTitleMessage: "Pubblicazione GeoForm in corso",
            shareBuilderProgressBarMessage: "Attendere&hellip;",
            shareBuilderTitleMessage: "Elemento salvato",
            shareBuilderTextMessage: "È possibile iniziare a raccogliere informazioni eseguendo la condivisione con altri utenti",
            shareModalFormText: "Collegamento modulo",
            shareBuilderSuccess: "GeoForm aggiornato e pubblicato.",
            geoformTitleText: "GeoForm",
            layerTabText: "Questo è il layer su cui verrà basato il GeoForm. Il layer deve essere un servizio feature abilitato per la modifica con autorizzazioni di condivisione appropriate per i destinatari.",
            detailsTabText: "Utilizzare la caselle Dettagli modulo di seguito per personalizzare il titolo, aggiungere un logo personalizzato e fornire una breve descrizione per i destinatari del GeoForm. Nella descrizione è possibile aggiungere collegamenti ad altre risorse, recapiti e persino indirizzare il pubblico a un\'applicazione di mappatura Web che presenta tutti i dati raccolti con il GeoForm.",
            fieldsTabText: "Qui è possibile selezionare i campi che saranno visibili per i destinatari del GeoForm, modificare le etichette che verranno visualizzate e aggiungere una breve descrizione per agevolare l\'immissione di dati.",
            styleTabText: "Definire lo stile del GeoForm utilizzando i seguenti temi in base alle proprie preferenze.",
            publishTabText: "Se la personalizzazione del GeoForm è stata completata, salvare l\'applicazione e iniziare la condivisione con i destinatari. È possibile tornare in qualsiasi momento a questo generatore e continuare la personalizzazione in base al feedback.",
            headerSizeLabel:"Dimensione intestazione",
            smallHeader: "Usa intestazione ridotta",
            bigHeader: "Usa intestazione grande",
            pushpinText: "Push pin",
            doneButtonText: "Salva ed esci",
            fieldTabPlaceHolderHeaderText: "Suggerimento (facoltativo)",
            enableAttachmentLabelText: "${openStrong}Abilita allegati${closeStrong}",
            enableAttachmentLabelHint: "È possibile abilitare/disabilitare gli allegati qui",
            attachmentIsRequiredLabelText: "${openStrong}Allegato richiesto${closeStrong}",
            attachmentIsRequiredLabelHint: "Se necessario, può venire richiesto agli utenti di inserire un allegato.",
            attachmentLabelText: "Etichetta pulsante Allegato",
            attachmentLabelHint: "Questo è il testo visualizzato accanto al pulsante Allegato. È possibile utilizzare questo spazio per descrivere gli allegati che gli utenti possono aggiungere (foto, video, documenti e così via), il formato di file richiesto (.jpeg, .png, .docx, .pdf) e qualsiasi altra istruzione aggiuntiva.",
            attachmentDescription: "Descrizione allegato",
            attachmentHint: "Se necessario, qui è possibile fornire ulteriori istruzioni sugli allegati.",
            jumbotronDescription: "Utilizzare un\'intestazione grande o piccola per il modulo. Un\'intestazione grande consente di definire lo scopo dell\'applicazione, ma richiede più spazio sullo schermo.",
            shareGeoformText: "Condividi GeoForm",
            shareDescription: "Grazie al pannello di condivisione il pubblico può condividere facilmente il GeoForm con altri collaboratori dopo aver effettuato un invio. Può essere disabilitata in qualsiasi momento.",
            defaultMapExtent: "Estensione mappa predefinita",
            defaultMapExtentDescription: "Dopo l\'invio per la mappa verrà reimpostata l\'estensione predefinita della mappa Web. Può essere disabilitata in qualsiasi momento.",
            pushpinOptionsDescription: "È possibile scegliere tra numerosi colori disponibili per il push pin mappa, che deve essere diverso dalla simbologia della mappa per consentire all\'utente di inserire l\'invio nella mappa",
            selectLocationText: "Seleziona posizione per",
            myLocationText: "Posizione",
            searchText: "Cerca",
            coordinatesText: "Coordinate di latitudine e longitudine",
            usng: "Coordinate USNG",
            mgrs: "Coordinate MGRS",
            utm: "Coordinate UTM",
            selectLocationSDescription: "Consente agli utenti di selezionare una posizione utilizzando questi metodi.",
            dragTooltipText:"Trascinare il campo nella posizione in cui si desidera visualizzarlo.",
            showHideLayerText:"Mostra/nascondi layer",
            showHideLayerHelpText:"È possibile configurare il modulo GeoForm in modo da visualizzare/nascondere il layer."
        }
    })
);