define(
   ({
    map: {
      error: "Impossibile creare la mappa"
    },
    onlineStatus: {
      offline: "Al momento è attiva la modalità offline. Gli invii di moduli verranno salvati in locale finché non sarà possibile stabilire una connessione al server.",
      reconnecting: "Riconnessione in corso&hellip;",
      pending: "${total} modifiche in sospeso verranno inviate non appena verrà ristabilita una connessione di rete."
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "La mia organizzazione",
          onlineLabel: "ArcGIS Online",
          contentLabel: "I miei contenuti",
          favoritesLabel: "I miei preferiti"
        },
        title: "Seleziona mappa Web",
        searchTitle: "Cerca",
        ok: "OK",
        cancel: "Annulla",
        placeholder: "Immettere il termine da cercare"
      },
      groupdlg: {
        items: {
          organizationLabel: "La mia organizzazione",
          onlineLabel: "ArcGIS Online",
          contentLabel: "I miei contenuti",
          favoritesLabel: "I miei preferiti"
        },
        title: "Seleziona gruppo",
        searchTitle: "Cerca",
        ok: "OK",
        cancel: "Annulla",
        placeholder: "Immettere il termine da cercare"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "Di seguito è riportato un collegamento a un modello GeoForm"
      }
    },
    user: {
      all: "Tutte",
      mgrs: "MGRS",
      usng: "USNG",
      utm: "UTM",
      utm_northing: "A Nord",
      utm_easting: "Ad Est",
      utm_zone_number: "Numero zona",
      selectLayerTabText: "${formSection} Selezionare il modulo",
      geoFormGeneralTabText: "${formSection} Immettere le informazioni",
      locationInformationText: "${formSection} Selezionare la posizione",
      submitInformationText: "${formSection} Completare il modulo",
      submitInstructions: "Aggiungere queste informazioni alla mappa.",
      myLocationText: "Posizione corrente",
      locationDescriptionForMoreThanOneOption: "Specificare la posizione per questa voce facendo clic o toccando la mappa o utilizzando una delle opzioni di seguito.",
      locationDescriptionForOneOption: "Per specificare la posizione per questa voce, toccare o fare clic sulla mappa oppure utilizzare la seguente opzione.",
      locationDescriptionForNoOption: "Per specificare la posizione per questa voce, toccare o fare clic sulla mappa.",
      addressText: "Cerca",
      geographic: "Lat/Lon",
      locationTabText: "Posizione",
      locationPopupTitle: "Posizione",
      submitButtonText: "Invia voce",
      submitButtonTextLoading: "Invio in corso&hellip;",
      formValidationMessageAlertText: "I seguenti campi sono obbligatori:",
      selectLocation: "Selezionare una posizione per l\'invio.",
      emptylatitudeAlertMessage: "Immettere una coordinata di ${openLink}latitudine${closeLink}.",
      emptylongitudeAlertMessage: "Immettere una coordinata di ${openLink}longitudine${closeLink}.",
      shareUserTitleMessage: "Grazie per il contributo!",
      entrySubmitted: "La voce è stata inviata alla mappa.",
      shareThisForm: "Condividi questo modulo",
      shareUserTextMessage: "Chiedere ad altri utenti di contribuire utilizzando le seguenti opzioni.",
      addAttachmentFailedMessage: "Impossibile aggiungere l\'allegato al layer",
      addFeatureFailedMessage: "Impossibile aggiungere la feature al layer",
      noLayerConfiguredMessage: "Si è verificato un errore durante il caricamento o la ricerca di un feature layer modificabile. Per visualizzare il modulo e avviare la raccolta degli invii, aggiungere alla mappa Web un feature layer modificabile.",
      placeholderLatitude: "Latitudine (Y)",
      placeholderLongitude: "Longitudine (X)",
      latitude: "Latitudine",
      longitude: "Longitudine",
      findMyLocation: "Trova la mia posizione",
      finding: "Individuazione in corso&hellip;",
      backToTop: "Torna all\'inizio",
      addressSearchText: "L\'invio verrà visualizzato qui. È possibile trascinare l\'indicatore per correggere la posizione.",
      shareModalFormText: "Collegamento modulo",
      close: "Chiudi",
      locationNotFound: "Posizione non trovata.",
      setLocation: "Imposta posizione",
      find: "Trova luogo o indirizzo",
      attachment: "Allegato",
      toggleDropdown: "Attiva/disattiva elenco a discesa",
      invalidString: "Immettere un valore valido.",
      invalidSmallNumber: "Immettere un valore ${openStrong}intero${closeStrong} valido compreso tra -32768 e 32767.",
      invalidNumber: "Immettere un valore ${openStrong}integer${closeStrong} valido compreso tra -2147483648 e 2147483647.",
      invalidFloat: "Immettere un valore ${openStrong}a virgola mobile${closeStrong} valido.",
      invalidDouble: "Immettere un valore ${openStrong}double${closeStrong} valido.",
      invalidLatLong: "Immettere coordinate di latitudine e longitudine valide.",
      invalidUTM: "Immettere coordinate UTM valide.",
      invalidUSNG: "Immettere coordinate USNG valide.",
      invalidMGRS: "Immettere coordinate MGRS valide.",
      geoformTitleText: "GeoForm",
      domainDefaultText: "Seleziona&hellip;",
      applyEditsFailedMessage: "Impossibile inviare i dati immessi. Riprovare.",
      requiredFields: "Il seguente campo è obbligatorio. Immettere una voce valida.",
      requiredField: "(obbligatorio)",
      error: "Errore",
      textRangeHintMessage: "${openStrong}Suggerimento:${closeStrong} Valore minimo ${minValue} e valore massimo ${maxValue}",
      dateRangeHintMessage: "${openStrong}Suggerimento:${closeStrong} Data minima ${minValue} e data massima ${maxValue}",
      remainingCharactersHintMessage: "${value} caratteri residui",
      mapFullScreen: "Schermo intero",
      mapRestore: "Ripristina",
      filterSelectEmptyText: "Seleziona",
      invalidLayerMessage: "é_A valid layer to create the GeoForm was not found. If the GeoForm has been configured with a layer, the layer may no longer be available, or authorization failed__________________________________________________È.",
      selectedLayerText: "Tutti",
      fileUploadStatus: "Stato caricamento file",
      uploadingBadge: "&nbsp;Caricamento in corso&hellip;",
      successBadge: "&nbsp;Caricato",
      retryBadge: "Riprova",
      errorBadge: "Errore durante il caricamento&nbsp;&nbsp;&nbsp;",
      fileTooLargeError: "File da allegare troppo grande",
      exceededFileCountError: "È stato superato il numero massimo di allegati consentito",
      selectFileTitle: "Seleziona un file",
      btnSelectFileText: "Seleziona file",
      btnViewSubmissions: "Visualizza invii"
    },
    builder: {
      gettingStarted: "Guida introduttiva",
      dateSettings: "Impostazioni data",
      hiddenDateField: "Nascondi questo campo data",
      preventPastDates: "Impedisci date passate",
      preventFutureDates: "Impedisci date future",
      useCurrentDate: "Imposta questo campo con la data e l\'ora correnti",
      configure: "Configura",
      configureField: "Configura campo \'${fieldName}\'",
      invalidUser: "Non si dispone dell\'autorizzazione per visualizzare questo elemento",
      invalidWebmapSelectionAlert: "La mappa Web selezionata non contiene alcun layer valido da utilizzare. Aggiungere un layer di feature modificabile nella mappa Web per continuare.",
      invalidWebmapSelectionAlert2: "Per ulteriori informazioni consultare ${openLink}Cos\'è un feature service?${closeLink}",
      selectFieldsText: "Seleziona campi modulo",
      selectThemeText: "Seleziona tema modulo",
      setViewerText: "Configura visualizzatore",
      introText: "Inizia",
      webmapText: "Mappa Web",
      layerText: "Layer",
      detailsText: "Dettagli",
      fieldsText: "Campi",
      styleText: "Stile",
      viewerText: "Osservatore",
      optionText: "Opzioni",
      previewText: "Anteprima",
      publishText: "Pubblica",
      optionsApplicationText: "Opzioni",
      submitButtonText: "é_Submit Button Text (Optional)__________È",
      submitButtonDesc: "é_Optionally label the button to submit a new entry. This text will not be translated__________________________È.",
      viewSubmissionsText: "é_View Submissions Text (Optional)___________È",
      viewSubmissionsDesc: "é_Optionally label the button to view existing entries. This text will not be translated___________________________È.",
      titleText: "Generatore",
      descriptionText: "GeoForm è un modello configurabile per la modifica di dati basata su moduli di un ${link1}Feature Service${closeLink}. Questa applicazione consente agli utenti di immettere dati utilizzando un modulo invece di un popup di mappa sfruttando la potenza della ${link2}Mappa Web${closeLink} e dei Feature Service modificabili. Per personalizzare e distribuire GeoForm utilizzare la procedura di seguito.",
      btnPreviousText: "Indietro",
      btnNextText: "Avanti",
      webmapTabTitleText: "Seleziona una mappa Web",
      viewWebmap: "Visualizza mappa Web",
      webmapDetailsText: "La mappa Web selezionata è ${webMapTitleLink}${webMapTitle}${closeLink}. Per selezionare una mappa Web diversa, fare clic sul pulsante 'Scegli mappa Web'.",
      btnSelectWebmapText: "Scegli mappa Web",
      btnSelectWebmapTextLoading: "Caricamento in corso&hellip;",
      layerTabTitleText: "Seleziona layer modificabile/i",
      selectLayerLabelText: "Layer",
      selectLayerDefaultOptionText: "Seleziona layer",
      enableBasemapToggle: "Mostra Attiva/Disattiva mappa di base",
      enableBasemapToggleDescription: "È possibile configurare il modulo GeoForm per mostrare/nascondere Attiva/Disattiva mappa di base",
      defaultBasemap: "Attivazione/disattivazione mappa base",
      secondaryBasemap: "Mappa di base predefinita",
      detailsTabTitleText: "Dettagli modulo",
      detailTitleLabelText: "Titolo",
      detailLogoLabelText: "Immagine logo",
      descriptionLabelText: "Istruzioni modulo e dettagli",
      fieldDescriptionLabelText: "Testo guida (facoltativo)",
      fieldDescriptionHelpText: "Fornire una breve descrizione o istruzioni per questo campo.",
      fieldHintHelpText: "Testo segnaposto per il campo.",
      fieldTabFieldHeaderText: "Campo",
      fieldTabLabelHeaderText: "Etichetta",
      fieldTabDisplayTypeHeaderText: "Visualizza come",
      fieldTabOrderColumnText: "Ordina",
      fieldTabVisibleColumnText: "Abilitato",
      displayFieldText: "Campo visualizzazione",
      selectMenuOption: "Seleziona menu",
      selectRadioOption: "Pulsante di scelta",
      selectTextOption: "Testo",
      selectDateOption: "Selettore data",
      selectRangeOption: "Selettore tocco",
      selectCheckboxOption: "Casella di controllo",
      selectMailOption: "E-mail",
      selectUrlOption: "URL",
      selectTextAreaOption: "Area di testo",
      previewApplicationText: "Anteprima applicazione",
      saveApplicationText: "Salva applicazione",
      saveText: "Salva",
      toggleNavigationText: "Attiva/disattiva navigazione",
      formPlaceholderText: "Modulo personale",
      shareBuilderInProgressTitleMessage: "Pubblicazione GeoForm in corso",
      shareBuilderProgressBarMessage: "Attendere&hellip;",
      shareBuilderTitleMessage: "Elemento salvato",
      shareBuilderTextMessage: "È possibile iniziare a raccogliere informazioni eseguendo la condivisione con altri utenti",
      shareModalFormText: "Collegamento modulo",
      shareBuilderSuccess: "GeoForm aggiornato e pubblicato.",
      geoformTitleText: "GeoForm",
      layerTabText: "Questo è il layer su cui verrà basato il modulo GeoForm. Il layer deve essere un servizio feature abilitato per la modifica con autorizzazioni di condivisione appropriate per i destinatari. Se tutti i layer sono selezionati, il modulo consentirà all\'utente di scegliere quale layer del modulo utilizzare per l\'invio.",
      detailsTabText: "Utilizzare la caselle Dettagli modulo di seguito per personalizzare il titolo, aggiungere un logo personalizzato e fornire una breve descrizione per i destinatari del GeoForm. Nella descrizione è possibile aggiungere collegamenti ad altre risorse, recapiti e persino indirizzare il pubblico a un\'applicazione di mappatura Web che presenta tutti i dati raccolti con il GeoForm.",
      fieldsTabText: "Qui è possibile selezionare i campi che saranno visibili per i destinatari del GeoForm, modificare le etichette che verranno visualizzate e aggiungere una breve descrizione per agevolare l\'immissione di dati.",
      styleTabText: "Definire lo stile del GeoForm utilizzando i seguenti temi in base alle proprie preferenze.",
      viewerTabText: "Impostare le opzioni per visualizzare gli invii raccolti dal modulo GeoForm.",
      publishTabText: "Se la personalizzazione del GeoForm è stata completata, salvare l\'applicazione e iniziare la condivisione con i destinatari. È possibile tornare in qualsiasi momento a questo generatore e continuare la personalizzazione in base al feedback.",
      headerSizeLabel: "Dimensione intestazione",
      smallHeader: "Usa intestazione ridotta",
      bigHeader: "Usa intestazione grande",
      pushpinText: "Push pin",
      doneButtonText: "Salva ed esci",
      fieldTabPlaceHolderHeaderText: "Suggerimento (facoltativo)",
      enableAttachmentLabelText: "${openStrong}Abilita allegati${closeStrong}",
      enableAttachmentLabelHint: "È possibile abilitare/disabilitare gli allegati qui",
      attachmentIsRequiredLabelText: "${openStrong}Allegato richiesto${closeStrong}",
      attachmentIsRequiredLabelHint: "Se necessario, può venire richiesto agli utenti di inserire un allegato.",
      attachmentLabelText: "Etichetta pulsante Allegato",
      attachmentLabelHint: "Questo testo verrà visualizzato accanto al pulsante Allegato. È possibile utilizzare questo spazio per descrivere cosa è possibile allegare (foto, video, documenti e cosi via), il formato di file richiesto (.jpeg, .png, .docx, .pdf e così via) e qualsiasi altra istruzione necessaria",
      attachmentDescription: "Descrizione allegato",
      attachmentHint: "Se necessario, qui è possibile fornire ulteriori istruzioni sugli allegati.",
      jumbotronDescription: "Utilizzare un\'intestazione grande o piccola per il modulo. Un\'intestazione grande consente di definire lo scopo dell\'applicazione, ma richiede più spazio sullo schermo.",
      shareGeoformText: "Pulsanti di condivisione con social media",
      shareDescription: "I pulsanti dei social media consentono al pubblico di condividere facilmente il modulo GeoForm una volta effettuato un invio",
      defaultMapExtent: "Estensione mappa predefinita",
      defaultMapExtentDescription: "Dopo l\'invio per la mappa verrà reimpostata l\'estensione predefinita della mappa Web. Può essere disabilitata in qualsiasi momento.",
      pushpinOptionsDescription: "È possibile scegliere tra numerosi colori disponibili per il push pin mappa, che deve essere diverso dalla simbologia della mappa per consentire all\'utente di inserire l\'invio nella mappa",
      selectLocationText: "Seleziona posizione per",
      myLocationText: "Posizione",
      searchText: "Cerca",
      coordinatesText: "Coordinate di latitudine e longitudine",
      usng: "Coordinate USNG",
      mgrs: "Coordinate MGRS",
      utm: "Coordinate UTM",
      selectLocationSDescription: "Consente agli utenti di selezionare una posizione utilizzando questi metodi.",
      dragTooltipText: "Trascinare il campo nella posizione in cui si desidera visualizzarlo.",
      showHideLayerText: "Mostra layer",
      showHideLayerHelpText: "È possibile configurare il modulo GeoForm in modo da visualizzare/nascondere il layer. Questa opzione si applica solo a una singola configurazione di layer.",
      enableOfflineSupport: "é_Enable offline support________È",
      enableOfflineSupportHelpText: "é_Store submissions when there is no network connection and submit them when a connection is restored_______________________________È.",
      labelHelpMessage: "Etichetta",
      placeHolderHintMessage: "Testo suggerimento",
      placeHolderHelpMessage: "Testo guida",
      selectTextOptionValue: "Selezione filtro",
      disableLogo: "Disabilita logo",
      disableLogoDescription: "È possibile configurare il GeoForm in modo che il logo venga visualizzato/nascosto nell\'intestazione del modulo",
      locateOnLoadText: "Trova durante caricamento",
      locateOnLoadDescription: "È possibile configurare il GeoForm in modo che venga utilizzata la posizione corrente durante il caricamento della pagina",
      selectLayerFieldTabText: "Seleziona layer",
      allLayerSelectOptionText: "Tutti i layer",
      disableViewer: "Disabilita viewer",
      disableViewerDescription: "È possibile configurare il modulo GeoForm in modo da abilitare/disabilitare il visualizzatore",
      displayFieldHintText: "Il campo di visualizzazione selezionato verrà mostrato nel visualizzatore come titolo"
    },
    viewer: {
      geocoderCancelText: "Annulla",
      viewMapTabText: "Mappa",
      sortHeaderText: "Ordina per:",
      geocoderPlaceholderText: "CAP, città e così via",
      noSearchResult: "Nessun risultato trovato",
      legendTabTooltip: "Legenda",
      aboutUsTabTooltip: "Informazioni",
      mapTabTooltip: "Mappa",
      btnDescendingText: "Decrescente",
      btnAscendingText: "Crescente",
      geometryUnavailableErrorMessage: "Errore nella ricerca della geometria della feature",
      infoPopupOffErrorMessage: "Nessuna informazione da visualizzare",
      btnLoadMoreText: "Carica altro",
      unavailableTitleText: "Senza titolo",
      unavailableConfigMessage: "Impossibile caricare la configurazione",
      share: "Condividi",
      viewReportsTabText: "Report",
      viewLegendTabText: "Legenda",
      viewAboutusTabText: "Informazioni",
      appLoadingFailedMessage: "Errore durante il caricamento del visualizzatore"
    }
  })
);