define(
   ({
    map: {
      error: "Impossibile creare la mappa"
    },
    onlineStatus: {
      offline: "Al momento è attiva la modalità offline. Gli invii di moduli verranno salvati in locale finché non sarà possibile stabilire una connessione al server.",
      reconnecting: "Riconnessione in corso&hellip;",
      pending: "${total} modifiche in sospeso verranno inviate non appena verrà ristabilita una connessione di rete."
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "La mia organizzazione",
          onlineLabel: "ArcGIS Online",
          contentLabel: "I miei contenuti",
          favoritesLabel: "I miei preferiti"
        },
        title: "Seleziona mappa Web",
        searchTitle: "Cerca",
        ok: "OK",
        cancel: "Annulla",
        placeholder: "Immettere il termine da cercare"
      },
      groupdlg: {
        items: {
          organizationLabel: "La mia organizzazione",
          onlineLabel: "ArcGIS Online",
          contentLabel: "I miei contenuti",
          favoritesLabel: "I miei preferiti"
        },
        title: "Seleziona gruppo",
        searchTitle: "Cerca",
        ok: "OK",
        cancel: "Annulla",
        placeholder: "Immettere il termine da cercare"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "Di seguito è riportato un collegamento a un modello GeoForm"
      }
    },
    user: {
      all: "é_All__È",
      mgrs: "MGRS",
      usng: "USNG",
      utm: "UTM",
      utm_northing: "A Nord",
      utm_easting: "Ad Est",
      utm_zone_number: "Numero zona",
      selectLayerTabText: "${formSection} Selezionare il modulo",
      geoFormGeneralTabText: "${formSection} Immettere le informazioni",
      locationInformationText: "${formSection} Selezionare la posizione",
      submitInformationText: "${formSection} Completare il modulo",
      submitInstructions: "Aggiungere queste informazioni alla mappa.",
      myLocationText: "Posizione corrente",
      locationDescriptionForMoreThanOneOption: "Specificare la posizione per questa voce facendo clic o toccando la mappa o utilizzando una delle opzioni di seguito.",
      locationDescriptionForOneOption: "Per specificare la posizione per questa voce, toccare o fare clic sulla mappa oppure utilizzare la seguente opzione.",
      locationDescriptionForNoOption: "Per specificare la posizione per questa voce, toccare o fare clic sulla mappa.",
      addressText: "Cerca",
      geographic: "Lat/Lon",
      locationTabText: "Posizione",
      locationPopupTitle: "Posizione",
      submitButtonText: "Invia voce",
      submitButtonTextLoading: "Invio in corso&hellip;",
      formValidationMessageAlertText: "I seguenti campi sono obbligatori:",
      selectLocation: "Selezionare una posizione per l\'invio.",
      emptylatitudeAlertMessage: "Immettere una coordinata di ${openLink}latitudine${closeLink}.",
      emptylongitudeAlertMessage: "Immettere una coordinata di ${openLink}longitudine${closeLink}.",
      shareUserTitleMessage: "Grazie per il contributo!",
      entrySubmitted: "La voce è stata inviata alla mappa.",
      shareThisForm: "Condividi questo modulo",
      shareUserTextMessage: "Chiedere ad altri utenti di contribuire utilizzando le seguenti opzioni.",
      addAttachmentFailedMessage: "Impossibile aggiungere l\'allegato al layer",
      addFeatureFailedMessage: "Impossibile aggiungere la feature al layer",
      noLayerConfiguredMessage: "Si è verificato un errore durante il caricamento o la ricerca di un feature layer modificabile. Per visualizzare il modulo e avviare la raccolta degli invii, aggiungere alla mappa Web un feature layer modificabile.",
      placeholderLatitude: "Latitudine (Y)",
      placeholderLongitude: "Longitudine (X)",
      latitude: "Latitudine",
      longitude: "Longitudine",
      findMyLocation: "Trova la mia posizione",
      finding: "Individuazione in corso&hellip;",
      backToTop: "Torna all\'inizio",
      addressSearchText: "L\'invio verrà visualizzato qui. È possibile trascinare l\'indicatore per correggere la posizione.",
      shareModalFormText: "Collegamento modulo",
      close: "Chiudi",
      locationNotFound: "Posizione non trovata.",
      setLocation: "Imposta posizione",
      find: "Trova luogo o indirizzo",
      attachment: "Allegato",
      toggleDropdown: "Attiva/disattiva elenco a discesa",
      invalidString: "é_Please enter a valid value_________È.",
      invalidSmallNumber: "é_Please enter a valid ${openStrong}integer${closeStrong} value between -32768 and 32767___________________________È.",
      invalidNumber: "Immettere un valore ${openStrong}integer${closeStrong} valido compreso tra -2147483648 e 2147483647.",
      invalidFloat: "Immettere un valore ${openStrong}a virgola mobile${closeStrong} valido.",
      invalidDouble: "Immettere un valore ${openStrong}double${closeStrong} valido.",
      invalidLatLong: "Immettere coordinate di latitudine e longitudine valide.",
      invalidUTM: "Immettere coordinate UTM valide.",
      invalidUSNG: "Immettere coordinate USNG valide.",
      invalidMGRS: "Immettere coordinate MGRS valide.",
      geoformTitleText: "GeoForm",
      domainDefaultText: "Seleziona&hellip;",
      applyEditsFailedMessage: "Impossibile inviare i dati immessi. Riprovare.",
      requiredFields: "é_The following field is required. Please provide a valid entry____________________È.",
      requiredField: "(obbligatorio)",
      error: "Errore",
      textRangeHintMessage: "${openStrong}Suggerimento:${closeStrong} Valore minimo ${minValue} e valore massimo ${maxValue}",
      dateRangeHintMessage: "${openStrong}Suggerimento:${closeStrong} Data minima ${minValue} e data massima ${maxValue}",
      remainingCharactersHintMessage: "${value} caratteri residui",
      mapFullScreen: "Schermo intero",
      mapRestore: "Ripristina",
      filterSelectEmptyText: "Seleziona",
      invalidLayerMessage: "Il layer del modulo non esiste. Configurare l\'applicazione, quindi impostare il layer.",
      selectedLayerText: "Tutti",
      fileUploadStatus: "Stato caricamento file",
      uploadingBadge: "&nbsp;Caricamento in corso&hellip;",
      successBadge: "&nbsp;Caricato",
      retryBadge: "Riprova",
      errorBadge: "Errore durante il caricamento&nbsp;&nbsp;&nbsp;",
      fileTooLargeError: "File da allegare troppo grande",
      exceededFileCountError: "é_Exceeded maximum number of attachments allowed_______________È",
      selectFileTitle: "Seleziona un file",
      btnSelectFileText: "é_Select File____È",
      btnViewSubmissions: "Visualizza invii"
    },
    builder: {
      gettingStarted: "é_Getting Started______È",
      dateSettings: "é_Date Settings_____È",
      hiddenDateField: "é_Hide this date field_______È",
      preventPastDates: "é_Prevent past dates______È",
      preventFutureDates: "é_Prevent future dates_______È",
      useCurrentDate: "é_Set this field with the current date and time_______________È",
      configure: "é_Configure____È",
      configureField: "é_Configure Field '${fieldName}'__________È",
      invalidUser: "Non si dispone dell\'autorizzazione per visualizzare questo elemento",
      invalidWebmapSelectionAlert: "La mappa Web selezionata non contiene alcun layer valido da utilizzare. Aggiungere un layer di feature modificabile nella mappa Web per continuare.",
      invalidWebmapSelectionAlert2: "Per ulteriori informazioni consultare ${openLink}Cos\'è un feature service?${closeLink}",
      selectFieldsText: "Seleziona campi modulo",
      selectThemeText: "Seleziona tema modulo",
      setViewerText: "é_Configure Viewer______È",
      introText: "é_Start___È",
      webmapText: "Mappa Web",
      layerText: "Layer",
      detailsText: "Dettagli",
      fieldsText: "Campi",
      styleText: "Stile",
      viewerText: "é_Viewer___È",
      optionText: "Opzioni",
      previewText: "Anteprima",
      publishText: "Pubblica",
      optionsApplicationText: "Opzioni",
      titleText: "Generatore",
      descriptionText: "GeoForm è un modello configurabile per la modifica di dati basata su moduli di un ${link1}Feature Service${closeLink}. Questa applicazione consente agli utenti di immettere dati utilizzando un modulo invece di un popup di mappa sfruttando la potenza della ${link2}Mappa Web${closeLink} e dei Feature Service modificabili. Per personalizzare e distribuire GeoForm utilizzare la procedura di seguito.",
      btnPreviousText: "Indietro",
      btnNextText: "Avanti",
      webmapTabTitleText: "Seleziona una mappa Web",
      viewWebmap: "Visualizza mappa Web",
      webmapDetailsText: "La mappa Web selezionata è ${webMapTitleLink}${webMapTitle}${closeLink}. Per selezionare una mappa Web diversa, fare clic sul pulsante 'Scegli mappa Web'.",
      btnSelectWebmapText: "Scegli mappa Web",
      btnSelectWebmapTextLoading: "Caricamento in corso&hellip;",
      layerTabTitleText: "é_Select Editable Layer(s)________È",
      selectLayerLabelText: "Layer",
      selectLayerDefaultOptionText: "Seleziona layer",
      enableBasemapToggle: "é_Show Basemap Toggle_______È",
      enableBasemapToggleDescription: "é_You can configure the GeoForm to Show/Hide the Basemap Toggle___________________È",
      defaultBasemap: "Attivazione/disattivazione mappa base",
      secondaryBasemap: "Mappa di base predefinita",
      detailsTabTitleText: "Dettagli modulo",
      detailTitleLabelText: "Titolo",
      detailLogoLabelText: "Immagine logo",
      descriptionLabelText: "Istruzioni modulo e dettagli",
      fieldDescriptionLabelText: "Testo guida (facoltativo)",
      fieldDescriptionHelpText: "é_Provide a short description or instructions for this field___________________È.",
      fieldHintHelpText: "é_Placeholder text for the field__________È.",
      fieldTabFieldHeaderText: "Campo",
      fieldTabLabelHeaderText: "Etichetta",
      fieldTabDisplayTypeHeaderText: "Visualizza come",
      fieldTabOrderColumnText: "Ordina",
      fieldTabVisibleColumnText: "Abilitato",
      displayFieldText: "Campo visualizzazione",
      selectMenuOption: "Seleziona menu",
      selectRadioOption: "Pulsante di scelta",
      selectTextOption: "Testo",
      selectDateOption: "Selettore data",
      selectRangeOption: "Selettore tocco",
      selectCheckboxOption: "Casella di controllo",
      selectMailOption: "E-mail",
      selectUrlOption: "URL",
      selectTextAreaOption: "Area di testo",
      previewApplicationText: "Anteprima applicazione",
      saveApplicationText: "Salva applicazione",
      saveText: "Salva",
      toggleNavigationText: "Attiva/disattiva navigazione",
      formPlaceholderText: "Modulo personale",
      shareBuilderInProgressTitleMessage: "Pubblicazione GeoForm in corso",
      shareBuilderProgressBarMessage: "Attendere&hellip;",
      shareBuilderTitleMessage: "Elemento salvato",
      shareBuilderTextMessage: "È possibile iniziare a raccogliere informazioni eseguendo la condivisione con altri utenti",
      shareModalFormText: "Collegamento modulo",
      shareBuilderSuccess: "GeoForm aggiornato e pubblicato.",
      geoformTitleText: "GeoForm",
      layerTabText: "é_This is the layer(s) that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience. If all layers are selected, the form will allow a user to choose which form layer to submit to___________________________________________________________________________________È.",
      detailsTabText: "Utilizzare la caselle Dettagli modulo di seguito per personalizzare il titolo, aggiungere un logo personalizzato e fornire una breve descrizione per i destinatari del GeoForm. Nella descrizione è possibile aggiungere collegamenti ad altre risorse, recapiti e persino indirizzare il pubblico a un\'applicazione di mappatura Web che presenta tutti i dati raccolti con il GeoForm.",
      fieldsTabText: "Qui è possibile selezionare i campi che saranno visibili per i destinatari del GeoForm, modificare le etichette che verranno visualizzate e aggiungere una breve descrizione per agevolare l\'immissione di dati.",
      styleTabText: "Definire lo stile del GeoForm utilizzando i seguenti temi in base alle proprie preferenze.",
      viewerTabText: "é_Set options for viewing submissions collected from the GeoForm____________________È.",
      publishTabText: "Se la personalizzazione del GeoForm è stata completata, salvare l\'applicazione e iniziare la condivisione con i destinatari. È possibile tornare in qualsiasi momento a questo generatore e continuare la personalizzazione in base al feedback.",
      headerSizeLabel: "Dimensione intestazione",
      smallHeader: "Usa intestazione ridotta",
      bigHeader: "Usa intestazione grande",
      pushpinText: "Push pin",
      doneButtonText: "Salva ed esci",
      fieldTabPlaceHolderHeaderText: "Suggerimento (facoltativo)",
      enableAttachmentLabelText: "${openStrong}Abilita allegati${closeStrong}",
      enableAttachmentLabelHint: "È possibile abilitare/disabilitare gli allegati qui",
      attachmentIsRequiredLabelText: "${openStrong}Allegato richiesto${closeStrong}",
      attachmentIsRequiredLabelHint: "Se necessario, può venire richiesto agli utenti di inserire un allegato.",
      attachmentLabelText: "Etichetta pulsante Allegato",
      attachmentLabelHint: "Questo testo verrà visualizzato accanto al pulsante Allegato. È possibile utilizzare questo spazio per descrivere cosa è possibile allegare (foto, video, documenti e cosi via), il formato di file richiesto (.jpeg, .png, .docx, .pdf e così via) e qualsiasi altra istruzione necessaria",
      attachmentDescription: "Descrizione allegato",
      attachmentHint: "Se necessario, qui è possibile fornire ulteriori istruzioni sugli allegati.",
      jumbotronDescription: "Utilizzare un\'intestazione grande o piccola per il modulo. Un\'intestazione grande consente di definire lo scopo dell\'applicazione, ma richiede più spazio sullo schermo.",
      shareGeoformText: "é_Social media sharing buttons_________È",
      shareDescription: "é_Social media buttons allow your audience to easily share your GeoForm once they have made a submission________________________________È",
      defaultMapExtent: "Estensione mappa predefinita",
      defaultMapExtentDescription: "Dopo l\'invio per la mappa verrà reimpostata l\'estensione predefinita della mappa Web. Può essere disabilitata in qualsiasi momento.",
      pushpinOptionsDescription: "È possibile scegliere tra numerosi colori disponibili per il push pin mappa, che deve essere diverso dalla simbologia della mappa per consentire all\'utente di inserire l\'invio nella mappa",
      selectLocationText: "Seleziona posizione per",
      myLocationText: "Posizione",
      searchText: "Cerca",
      coordinatesText: "Coordinate di latitudine e longitudine",
      usng: "Coordinate USNG",
      mgrs: "Coordinate MGRS",
      utm: "Coordinate UTM",
      selectLocationSDescription: "Consente agli utenti di selezionare una posizione utilizzando questi metodi.",
      dragTooltipText: "Trascinare il campo nella posizione in cui si desidera visualizzarlo.",
      showHideLayerText: "Mostra layer",
      showHideLayerHelpText: "é_You can configure the GeoForm to Show/Hide Layer. This option only applies to a single layer setup_______________________________È.",
      labelHelpMessage: "Etichetta",
      placeHolderHintMessage: "Testo suggerimento",
      placeHolderHelpMessage: "Testo guida",
      selectTextOptionValue: "Selezione filtro",
      disableLogo: "Disabilita logo",
      disableLogoDescription: "È possibile configurare il GeoForm in modo che il logo venga visualizzato/nascosto nell\'intestazione del modulo",
      locateOnLoadText: "Trova durante caricamento",
      locateOnLoadDescription: "È possibile configurare il GeoForm in modo che venga utilizzata la posizione corrente durante il caricamento della pagina",
      selectLayerFieldTabText: "Seleziona layer",
      allLayerSelectOptionText: "é_All Layers____È",
      disableViewer: "Disabilita viewer",
      disableViewerDescription: "é_You can configure the GeoForm to disable/enable the viewer__________________È",
      displayFieldHintText: "é_Selected display field will be shown in the viewer as a title___________________È"
    },
    viewer: {
      geocoderCancelText: "Annulla",
      viewMapTabText: "Mappa",
      sortHeaderText: "Ordina per:",
      geocoderPlaceholderText: "CAP, città e così via",
      noSearchResult: "Nessun risultato trovato",
      recordsTabTooltip: "Visualizza invii",
      legendTabTooltip: "Legenda",
      aboutUsTabTooltip: "é_About Us___È",
      mapTabTooltip: "Mappa",
      btnDescendingText: "Decrescente",
      btnAscendingText: "Crescente",
      geometryUnavailableErrorMessage: "é_Erorr finding the geometry of the feature_____________È",
      infoPopupOffErrorMessage: "é_No information to display_________È",
      btnLoadMoreText: "Carica altro",
      unavailableTitleText: "Senza titolo",
      unavailableConfigMessage: "Impossibile caricare la configurazione",
      share: "é_Share___È",
      viewReportsTabText: "é_Reports___È",
      viewLegendTabText: "Legenda",
      viewAboutusTabText: "Informazioni",
      btnSubmitReportText: "Invia un report",
      appLoadingFailedMessage: "é_There was an error loading the viewer____________È"
    }
  })
);