define(
     ({
        map: {
            error: "Не удалось создать карту"
        },
        onlineStatus: {
            offline: "В настоящее время вы работаете в автономном режиме. Форма представления будет сохранена локально до тех пор, пока не будет выполнено подключение к серверу.",
            reconnecting: "Повторное подключение&hellip;",
            pending: "${total} ожидающих исправлений будет выполнено после восстановления подключения к сети."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Моя организация",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Мои ресурсы",
                    favoritesLabel: "Мое избранное"
                },
                title: "Выберите веб-карту",
                searchTitle: "Поиск",
                ok: "Ok",
                cancel: "Отмена",
                placeholder: "Введите текст поиска"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Моя организация",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Мои ресурсы",
                    favoritesLabel: "Мое избранное"
                },
                title: "Выберите группу",
                searchTitle: "Поиск",
                ok: "Ok",
                cancel: "Отмена",
                placeholder: "Введите текст поиска"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "По широте",
            utm_easting: "По долготе",
            utm_zone_number: "Номер зоны",
            geoFormGeneralTabText: "1. Введите информацию",
            locationInformationText: "2. Выберите местоположение",
            submitInformationText: "3. Заполните форму",
            submitInstructions: "Добавьте эту информацию в карту.",
            myLocationText: "Текущее местоположение",
            locationDescription: "Укажите местоположение этой записи, щелкнув/нажав на карте или при помощи одной из следующих опций.",
            addressText: "Поиск",
            geographic: "Широта/Долгота",
            locationTabText: "Местоположение",
            locationPopupTitle: "Местоположение",
            submitButtonText: "Отправить запись",
            submitButtonTextLoading: "Подтверждение&hellip;",
            formValidationMessageAlertText: "Следующие поля являются обязательными:",
            selectLocation: "Выберите ${openLink}location${closeLink} для вашего представления.",
            emptylatitudeAlertMessage: "Введите координаты ${openLink}latitude${closeLink}.",
            emptylongitudeAlertMessage: "Введите координату ${openLink}долготы${closeLink}.",
            shareUserTitleMessage: "Спасибо за ваше участие!",
            entrySubmitted: "Ваша запись отправлена на карту.",
            shareThisForm: "Опубликовать эту форму",
            shareUserTextMessage: "Рассказать другим  при помощи следующих опций.",
            addAttachmentFailedMessage: "Невозможно добавить вложения к слою",
            addFeatureFailedMessage: "Невозможно добавить объект в слой",
            noLayerConfiguredMessage: "При загрузке или поиске редактируемого векторного слоя произошла ошибка. Для того, чтобы отобразить форму или начать сбор материалов, добавьте векторный слой на веб-карту.",
            placeholderLatitude: "Широта (Y)",
            placeholderLongitude: "Долгота (X)",
            latitude: "Широта",
            longitude: "Долгота",
            findMyLocation: "Найти мое местоположение",
            finding: "Поиск местоположения&hellip;",
            backToTop: "Наверх",
            addressSearchText: "Ваша запись появится здесь. Вы можете перетащить булавку в желаемое местоположение.",
            shareModalFormText: "Ссылка на форму",
            close: "Закрыть",
            locationNotFound: "Невозможно найти местоположение.",
            setLocation: "Задать местоположение",
            find: "Найти адрес или место",
            attachment: "Вложение",
            toggleDropdown: "Сброс",
            invalidLatLong: "Введите корректные значения координат ${latLink}широты${closeLink} и ${lngLink}долготы${closeLink}.",
            invalidUTM: "Введите корректные значения координат ${openLink}UTM${closeLink}.",
            invalidUSNG: "Введите корректные значения координат ${openLink}USNG${closeLink}.",
            invalidMGRS: "Введите корректные значения координат ${openLink}MGRS${closeLink}.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Выбор&hellip;",
            applyEditsFailedMessage: "Не удалось отправить введенные данные. Повторите попытку.",
            requiredFields: "Имеется несколько ошибок. Пожалуйста, исправьте их.",
            requiredField: "(обязательно)",
            error: "Ошибка",
            textRangeHintMessage: "${openStrong}Подсказка:${closeStrong} Минимальное значение ${minValue} и Максимальное значение ${maxValue}",
            dateRangeHintMessage: "${openStrong}Подсказка:${closeStrong} Минимальная дата ${minValue} и Максимальная дата ${maxValue}"
        },
        builder: {
            invalidUser: "У вас нет прав на просмотр этого элемента",
            invalidWebmapSelectionAlert: "На выбранной карте нет допустимого для использования слоя. Добавьте редактируемый FeatureLayer на вашу веб-карту для продолжения.",
            invalidWebmapSelectionAlert2: "За подробной информацией обратитесь к ${openLink}Что такое сервис пространственных объектов?${closeLink}",
            selectFieldsText: "Выберите поля формы",
            selectThemeText: "Выберите тему формы",
            webmapText: "Веб-карта",
            layerText: "Слой",
            detailsText: "Детали",
            fieldsText: "Поля",
            styleText: "Стиль",
            optionText: "Опции",
            previewText: "Просмотр",
            publishText: "Опубликовать",
            optionsApplicationText: "Опции",
            titleText: "Конструктор",
            descriptionText: "GeoForm - это настраиваемый шаблон для редактирования данных на основе формы ${link1}Сервиса объектов${closeLink}. Это приложение дает пользователям возможность вводить данные при помощи формы, а не всплывающих окон карты, максимально используя преимущества ${link2}Веб-карты${closeLink} и редактируемых сервисов объектов. Используйте следующие шаги для настройки и развертывания вашего GeoForm.",
            btnPreviousText: "Предыдущий",
            btnNextText: "Следующий",
            webmapTabTitleText: "Выбрать веб-карту",
            viewWebmap: "Просмотреть веб-карту",
            btnSelectWebmapText: "Выбрать веб-карту",
            btnSelectWebmapTextLoading: "Загрузка&hellip (Loading&hellip);",
            layerTabTitleText: "Выбрать редактируемый слой",
            selectLayerLabelText: "Слой",
            selectLayerDefaultOptionText: "Выбрать слой",
            detailsTabTitleText: "Детали формы",
            detailTitleLabelText: "Заголовок",
            detailLogoLabelText: "Изображение логотипа",
            descriptionLabelText: "Текст справки (дополнительно)",
            fieldTabFieldHeaderText: "Поле",
            fieldTabLabelHeaderText: "Надпись",
            fieldTabDisplayTypeHeaderText: "Отобразить как",
            selectMenuOption: "Выбрать меню",
            selectRadioOption: "Переключатель",
            selectTextOption: "Текст",
            selectCheckboxOption: "Окошко метки",
            selectMailOption: "Email",
            selectUrlOption: "URL-адрес",
            selectTextAreaOption: "Область текста",
            previewApplicationText: "Просмотр приложения",
            saveApplicationText: "Сохранить приложение",
            saveText: "Сохранить",
            toggleNavigationText: "Переключение навигации",
            formPlaceholderText: "Моя форма",
            shareBuilderInProgressTitleMessage: "Публикация GeoForm",
            shareBuilderProgressBarMessage: "Пожалуйста, подождите...",
            shareBuilderTitleMessage: "Успешно! Элемент сохранен",
            shareBuilderTextMessage: "Открытие общего доступа - первый шаг для старта сбора информации",
            shareModalFormText: "Ссылка на форму",
            shareBuilderSuccess: "Ваш GeoForm был изменен и опубликован!",
            geoformTitleText: "Geo Form",
            layerTabText: "Из этого слоя будет построен GeoForm. Слой должен быть сервисом объектов, который допускает редактирование и предоставление общего доступа для вашей аудитории.",
            detailsTabText: "С помощью текстовых окон страницы Детали формы, настройте заголовок, добавьте собственный логотип и краткое описание для аудитории GeoForm. В описании вы можете добавить ссылки на другие ресурсы, контактную информацию и даже доступ к картографическому веб-приложению, где используются все данные, собранные с помощью  GeoForm.",
            fieldsTabText: "Здесь вы можете выбрать, какие поля будут видны для вашей аудитории GeoForm, измените отображаемые надписи, и добавьте краткое описание в справку, которая сопровождает данные.",
            styleTabText: "Оформите ваш GeoForm, выбрав тему из представленных ниже.",
            publishTabText: "Если вы завершили настройку вашего GeoForm, сохраните приложение и откройте общий доступ к нему для вашей аудитории. Вы можете всегда вернуться к конструктору и продолжить настройку, на основе отзывов.",
            smallHeader: "Используйте небольшой колонтитул",
            pushpinText: "Кнопка",
            doneButtonText: "Просмотр элемента приложения",
            fieldTabPlaceHolderHeaderText: "Подсказка (дополнительно)",
            attachmentLabelText: "Подпись вложения",
            attachmentLabelHint: "Сообщить пользователям, какой тип файлов вложить.",
            attachmentDescription: "Описание вложения",
            attachmentHint: "При необходимости вы можете предоставить дополнительные инструкции к вложению здесь.",
            jumbotronDescription: "Bootstrap Jumbotron упрощает определение назначения вашего приложения. Оно отображается в любое время.",
            shareGeoformText: "Опубликовать Geoform",
            shareDescription: "Панель общего доступа позволяет вашей аудитории быстро предоставлять доступ к GeoForm своим сотрудникам, выполнившим вход - эту опцию в любой момент можно отключить.",
            defaultMapExtent: "Экстент карты по умолчанию",
            defaultMapExtentDescription: "После входа карта будет переключена к экстенту веб-карты по умолчанию - эту опцию в любой момент можно отключить.",
            pushpinOptionsDescription: "Для кнопки на карте можно выбрать любой их множества цветов, он должен отличаться от символов на карте, что облегчает пользователю нанесение на карту собственных знаков",
            selectLocationText: "Выбрать местоположение по",
            myLocationText: "Мое местоположение",
            searchText: "Поиск",
            coordinatesText: "Координаты широты-долготы",
            usng: "Координаты USNG",
            mgrs: "Координаты MGRS",
            utm: "Координаты UTM",
            selectLocationSDescription: "Позволяет выбирать местоположения одним из этих методов."
        }
    })
);