define(
     ({
        map: {
            error: "Kan ikke oprette kort"
        },
        onlineStatus: {
            offline: "Du arbejder offline på nuværende tidspunkt. Formularafsendelser vil blive gemt lokalt, indtil der oprettes forbindelse til serveren.",
            reconnecting: "Opretter forbindelse igen&hellip;",
            pending: "${total} ventende redigeringer sendes, når netværksforbindelsen genoprettes."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Min organisation",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Mit indhold",
                    favoritesLabel: "Mine favoritter"
                },
                title: "Vælg webkort",
                searchTitle: "Søg",
                ok: "OK",
                cancel: "Annullér",
                placeholder: "Angiv søgeterm"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Min organisation",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Mit indhold",
                    favoritesLabel: "Mine favoritter"
                },
                title: "Vælg gruppe",
                searchTitle: "Søg",
                ok: "OK",
                cancel: "Annullér",
                placeholder: "Angiv søgeterm"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Nordlig",
            utm_easting: "Østlig",
            utm_zone_number: "Zonenummer",
            geoFormGeneralTabText: "1. Indtast oplysninger",
            locationInformationText: "2. Vælg placering",
            submitInformationText: "3. Udfyld formularen",
            submitInstructions: "Føj disse oplysninger til kortet.",
            myLocationText: "Nuværende placering",
            locationDescription: "Angiv en placering til din post ved at klikke på/berøre kortet eller vha. en af følgende muligheder.",
            addressText: "Søg",
            geographic: "Bredde-/længdegrad",
            locationTabText: "Placering",
            locationPopupTitle: "Placering",
            submitButtonText: "Send post",
            submitButtonTextLoading: "Afsender&hellip;",
            formValidationMessageAlertText: "Følgende felter er obligatoriske:",
            selectLocation: "Vælg en ${openLink}placering${closeLink} til din afsendelse.",
            emptylatitudeAlertMessage: "Vælg en koordinat for ${openLink}breddegrad${closeLink}.",
            emptylongitudeAlertMessage: "Vælg en koordinat for ${openLink}længdegrad${closeLink}.",
            shareUserTitleMessage: "Tak for dit bidrag!",
            entrySubmitted: "Din post er sendt til kortet.",
            shareThisForm: "Del denne formular",
            shareUserTextMessage: "Bed andre om at bidrage vha. følgende indstillinger.",
            addAttachmentFailedMessage: "Kan ikke tilføje vedhæftning til laget",
            addFeatureFailedMessage: "Kan ikke føje objekt til laget",
            noLayerConfiguredMessage: "Der opstod en fejl under indlæsning eller søgning efter et redig\érbart objektlag. Føj et redig\érbart objektlag til webkortet for at få formularen vist og starte indsamlingen af afsendelserne.",
            placeholderLatitude: "Bredde (Y)",
            placeholderLongitude: "Længde (X)",
            latitude: "Breddegrad",
            longitude: "Længdegrad",
            findMyLocation: "Find mig",
            finding: "Lokaliserer&hellip;",
            backToTop: "Tilbage til toppen",
            addressSearchText: "Din afsendelse vil blive vist her. Du kan trække nålen til den korrekte position.",
            shareModalFormText: "Formular-link",
            close: "Luk",
            locationNotFound: "Placeringen blev ikke fundet.",
            setLocation: "Angiv placering",
            find: "Find adresse eller sted",
            attachment: "Vedhæftning",
            toggleDropdown: "Skift rullemenu",
            invalidLatLong: "Angiv gyldige koordinater for ${latLink}bredde-${closeLink} og ${lngLink}længdegrad${closeLink}.",
            invalidUTM: "Angiv gyldige ${openLink}UTM${closeLink}-koordinater.",
            invalidUSNG: "Angiv gyldige ${openLink}USNG${closeLink}-koordinater.",
            invalidMGRS: "Angiv gyldige ${openLink}MGRS${closeLink}-koordinater.",
            geoformTitleText: "GeoFormular",
            domainDefaultText: "Vælg&hellip;",
            applyEditsFailedMessage: "Beklager, men din post kan ikke sendes. Prøv igen.",
            requiredFields: "Der opstod fejl. Ret dem nedenfor.",
            requiredField: "(obligatorisk)",
            error: "Fejl",
            textRangeHintMessage: "${openStrong}Hint:${closeStrong} Minimumværdi ${minValue} og maksimumværdi ${maxValue}",
            dateRangeHintMessage: "${openStrong}Hint:${closeStrong} Minimumdato ${minValue} og maksimumdato ${maxValue}"
        },
        builder: {
            invalidUser: "Du har desværre ikke tilladelse til at få dette element vist",
            invalidWebmapSelectionAlert: "Det valgte webkort indeholder ikke noget gyldigt lag, som kan anvendes. Føj et redig\érbart vektorlag til dit webkort for at fortsætte.",
            invalidWebmapSelectionAlert2: "Der er flere oplysninger under  ${openLink}Hvad er en featuretjeneste?${closeLink}",
            selectFieldsText: "Vælg formularfelter",
            selectThemeText: "Vælg formulartema",
            webmapText: "Webkort",
            layerText: "Lag",
            detailsText: "Detaljer",
            fieldsText: "Felter",
            styleText: "Typografi",
            optionText: "Indstillinger",
            previewText: "Forhåndsvisning",
            publishText: "Offentliggør",
            optionsApplicationText: "Indstillinger",
            titleText: "Builder",
            descriptionText: "GeoForm er en skabelon, der kan konfigureres til formularbaseret dataredigering af en ${link1}featuretjeneste${closeLink}. Med denne applikation kan brugerne indtaste data via en formular i stedet for kortets pop-op-vindue, samtidigt med at styrken ved ${link2}webkort${closeLink} og de redigérbare featuretjenester udnyttes. Følg trinene i det følgende for at tilpasse og udbrede din GeoForm.",
            btnPreviousText: "Tidligere",
            btnNextText: "Næste",
            webmapTabTitleText: "Vælg et webkort",
            viewWebmap: "Vis webkort",
            btnSelectWebmapText: "Vælg webkort",
            btnSelectWebmapTextLoading: "Indlæser &Hjælp;",
            layerTabTitleText: "Vælg redigérbart lag",
            selectLayerLabelText: "Lag",
            selectLayerDefaultOptionText: "Vælg lag",
            detailsTabTitleText: "Formularoplysninger",
            detailTitleLabelText: "Titel",
            detailLogoLabelText: "Logobillede",
            descriptionLabelText: "Hjælptekst (valgfri)",
            fieldTabFieldHeaderText: "Felt",
            fieldTabLabelHeaderText: "Mærke",
            fieldTabDisplayTypeHeaderText: "Vis som",
            selectMenuOption: "Vælg menu",
            selectRadioOption: "Alternativknap",
            selectTextOption: "Tekst",
            selectCheckboxOption: "Afkrydsningsfelt",
            selectMailOption: "E-mail",
            selectUrlOption: "URL",
            selectTextAreaOption: "Tekstområde",
            previewApplicationText: "Få vist eksempel på applikation",
            saveApplicationText: "Gem applikation",
            saveText: "Gem",
            toggleNavigationText: "Skift navigation",
            formPlaceholderText: "Min formular",
            shareBuilderInProgressTitleMessage: "Publicerer GeoForm",
            shareBuilderProgressBarMessage: "Vent&hellip;",
            shareBuilderTitleMessage: "Det lykkedes! Elementet er gemt",
            shareBuilderTextMessage: "Du kan starte indsamling af oplysninger ved at dele med andre",
            shareModalFormText: "Formular-link",
            shareBuilderSuccess: "Din GeoForm er blevet opdateret og publiceret!",
            geoformTitleText: "GeoForm",
            layerTabText: "GeoForm vil blive oprettet ud fra dette lag. Laget skal være en featuretjeneste, der er aktiveret for redigering med de delingsrettigheder, der er relevante for dit publikum.",
            detailsTabText: "Brug felterne med formularoplysninger til at tilpasse titlen, tilføje et brugerdefineret logo og indtaste en kort beskrivelse til dit GeoForm-publikum. I beskrivelsen kan du tilføje links til andre ressourcer og kontaktoplysninger og sågar dirigere dit publikum til en webkortapplikation med alle dataene, der er indsamlet med GeoForm.",
            fieldsTabText: "Her kan du vælge, hvilke felter der skal være synlige for dit GeoForm-publikum, redigere de labels, de får vist, og tilføje en kort beskrivelse til hjælp for dataindtastning.",
            styleTabText: "Forsyn din GeoForm med en typografi ved hjælp af temaerne nedenfor på grundlag af dine præferencer.",
            publishTabText: "Hvis du er færdig med at tilpasse din GeoForm, kan du gemme applikationen og begynde at dele med dit publikum. Du kan altid vende tilbage til dette builder-program og fortsætte tilpasningen på grundlag af feedback.",
            smallHeader: "Brug lille overskrift",
            pushpinText: "Markeringsnål",
            doneButtonText: "Vis applikationselement",
            fieldTabPlaceHolderHeaderText: "Tip (valgfrit)",
            attachmentLabelText: "Label til vedhæftede filer",
            attachmentLabelHint: "Fortæl brugerne, hvilken type fil der kan vedhæftes.",
            attachmentDescription: "Beskrivelse af vedhæftelse",
            attachmentHint: "Du kan om nødvendigt give yderligere vejledning til vedhæftede filer her.",
            jumbotronDescription: "Med Bootstrap Jumbotron er det nemt at definere formålet med applikationen. Dette kan når som helst deaktiveres.",
            shareGeoformText: "Del Geoform",
            shareDescription: "Delingspanelet gør det nemt for dit publikum at dele en GeoForm med andre kollegaer, når du har oprettet en afsendelse. Dette kan når som helst deaktiveres.",
            defaultMapExtent: "Standardkortudstrækning",
            defaultMapExtentDescription: "Dette kort nulstiller standardudstærkningen efter afsendelse. Dette kan når som helst deaktiveres.",
            pushpinOptionsDescription: "Vælg blandt forskellige farver til kortmarkeringsnåle, som skal adskille sig fra kortsymbolerne, for at hjælpe brugeren med at anbringe deres indsendelse på kortet",
            selectLocationText: "Vælg placering efter",
            myLocationText: "Min position",
            searchText: "Søg",
            coordinatesText: "Koordinater for længde- og breddegrad",
            usng: "USNG-koordinater",
            mgrs: "MGRS-koordinater",
            utm: "UTM-koordinater",
            selectLocationSDescription: "Tillad brugerne at vælge en placering vha. disse metoder."
        }
    })
);