define(
     ({
        map: {
            error: "לא ניתן ליצור מפה"
        },
        onlineStatus: {
            offline: "אתה עובד כרגע במצב לא מקוון. הטופס ישמר באופן מקומי עד שחיבור לשרת יכול להתבצע.",
            reconnecting: "מתקשר מחש&hellip;",
            pending: "${total} עריכות ממתינות ישלחו כאשר חיבור לרשת ייווצר מחדש."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "הארגון שלי",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "התוכן שלי",
                    favoritesLabel: "המועדפים שלי"
                },
                title: "בחר Web Map",
                searchTitle: "חפש",
                ok: "אישור",
                cancel: "ביטול",
                placeholder: "הכנס מונח לחיפוש"
            },
            groupdlg: {
                items: {
                    organizationLabel: "הארגון שלי",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "התוכן שלי",
                    favoritesLabel: "המועדפים שלי"
                },
                title: "בחר קבוצה",
                searchTitle: "חפש",
                ok: "אישור",
                cancel: "ביטול",
                placeholder: "הכנס מונח לחיפוש"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "כלפי צפון",
            utm_easting: "כלפי מזרח",
            utm_zone_number: "מספר אזור",
            geoFormGeneralTabText: "1. הכנס מידע",
            locationInformationText: "2. בחר מיקום",
            submitInformationText: "3. השלם טופס",
            submitInstructions: "הוסף מידע זה למפה.",
            myLocationText: "כן_Current Location_ש",
            locationDescription: "כן_Specify the location for this entry by clicking/tapping the map or by using one of the following options._ש",
            addressText: "חיפוש",
            geographic: "כן_Lat/Lon_ש",
            locationTabText: "מיקום",
            locationPopupTitle: "כן_Location_ש",
            submitButtonText: "כן_Submit Entry_ש",
            submitButtonTextLoading: "מגיש",
            formValidationMessageAlertText: "השדות הבאים דרושים:",
            selectLocation: "בחר ${openLink}מיקום${closeLink} עבור ההגשה שלך.",
            emptylatitudeAlertMessage: "הזן קואורדינטת ${openLink}קו רוחב${closeLink}.",
            emptylongitudeAlertMessage: "הזן קואורדינטת ${openLink}קו אורך${closeLink}.",
            shareUserTitleMessage: "תודה רבה עבור התרומה שלך!",
            entrySubmitted: "כן_Your entry has been submitted to the map._ש",
            shareThisForm: "כן_Share This Form_ש",
            shareUserTextMessage: "כן_Tell others to contribute using the following options._ש",
            addAttachmentFailedMessage: "לא ניתן להוסיף קישור לשכבה",
            addFeatureFailedMessage: "לא ניתן להוסיף ישות לשכבה",
            noLayerConfiguredMessage: "אופס! אין מה לראות פה. על מנת להתחיל באוסף מתוך טפסי ההגשה התאם את ה-GeoForm הזה ובחר שכבת שירות ישויות הניתנת לעריכה.",
            placeholderLatitude: "קו רוחב (Y)",
            placeholderLongitude: "קו אורך (X)",
            latitude: "קו רוחב",
            longitude: "קו אורך",
            findMyLocation: "כן_Locate Me_ש",
            finding: "מאתר",
            backToTop: "חזור לראש הדף",
            addressSearchText: "המידע שלך יווצג פה. אתה יכול לגרור את סמן הסיכה כדי לתקן את המיקום.",
            shareModalFormText: "קישור טופס",
            close: "סגור",
            locationNotFound: "לא ניתן למצוא מיקום.",
            setLocation: "כן_Set Location_ש",
            find: "כן_Find address or place_ש",
            attachment: "קישור",
            toggleDropdown: "שנה מצב רשימה נפתחת",
            invalidLatLong: "הזן קואורדינטות ${latLink}קו רוחב${closeLink} ו${lngLink}קו אורך${closeLink} חוקיות.",
            invalidUTM: "הזן קואורדינטות ${openLink}UTM${closeLink} חוקיות.",
            invalidUSNG: "הזן קואורדינטות ${openLink}USNG${closeLink} חוקיות.",
            invalidMGRS: "הזן קואורדינטות ${openLink}MGRS${closeLink} חוקיות.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "בחר",
            applyEditsFailedMessage: "מצטערים, לא ניתן להגיש את הערך שלך. נסה שוב.",
            requiredFields: "קיימות שגיאות. תקן אותן להלן.",
            requiredField: "כן_(required)_ש",
            error: "שגיאה",
            textRangeHintMessage: "כן_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_ש",
            dateRangeHintMessage: "כן_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_ש"
        },
        builder: {
            invalidUser: "כן_Sorry, you dont have permission to view this item_ש",
            invalidWebmapSelectionAlert: "כן_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._ש",
            invalidWebmapSelectionAlert2: "כן_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_ש",
            selectFieldsText: "כן_Select Form Fields_ש",
            selectThemeText: "כן_Select Form Theme_ש",
            webmapText: "כן_Webmap_ש",
            layerText: "כן_Layer_ש",
            detailsText: "כן_Details_ש",
            fieldsText: "כן_Fields_ש",
            styleText: "כן_Style_ש",
            optionText: "כן_Options_ש",
            previewText: "כן_Preview_ש",
            publishText: "כן_Publish_ש",
            optionsApplicationText: "כן_Options_ש",
            titleText: "כן_Builder_ש",
            descriptionText: "כן_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a map’s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm._ש",
            btnPreviousText: "כן_Previous_ש",
            btnNextText: "כן_Next_ש",
            webmapTabTitleText: "כן_Select a Webmap_ש",
            viewWebmap: "כן_View webmap_ש",
            btnSelectWebmapText: "כן_Choose Webmap_ש",
            btnSelectWebmapTextLoading: "כן_Loading&hellip;_ש",
            layerTabTitleText: "כן_Select Editable Layer_ש",
            selectLayerLabelText: "כן_Layer_ש",
            selectLayerDefaultOptionText: "כן_Select Layer_ש",
            detailsTabTitleText: "כן_Form Details_ש",
            detailTitleLabelText: "כן_Title_ש",
            detailLogoLabelText: "כן_Logo Image_ש",
            descriptionLabelText: "כן_Help Text (optional)_ש",
            fieldTabFieldHeaderText: "כן_Field_ש",
            fieldTabLabelHeaderText: "כן_Label_ש",
            fieldTabDisplayTypeHeaderText: "כן_Display As_ש",
            selectMenuOption: "כן_Select Menu_ש",
            selectRadioOption: "כן_Radio Button_ש",
            selectTextOption: "כן_Text_ש",
            selectCheckboxOption: "כן_Checkbox_ש",
            selectMailOption: "כן_Email_ש",
            selectUrlOption: "כן_URL_ש",
            selectTextAreaOption: "כן_Textarea_ש",
            previewApplicationText: "כן_Preview Application_ש",
            saveApplicationText: "כן_Save Application_ש",
            saveText: "כן_Save_ש",
            toggleNavigationText: "כן_Toggle navigation_ש",
            formPlaceholderText: "כן_My Form_ש",
            shareBuilderInProgressTitleMessage: "כן_Publishing GeoForm_ש",
            shareBuilderProgressBarMessage: "כן_Please Wait&hellip;_ש",
            shareBuilderTitleMessage: "כן_Success! Item saved_ש",
            shareBuilderTextMessage: "כן_You can start collecting information by sharing with others_ש",
            shareModalFormText: "כן_Form Link_ש",
            shareBuilderSuccess: "כן_Your GeoForm has been updated & published!_ש",
            geoformTitleText: "כן_Geo Form_ש",
            layerTabText: "כן_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._ש",
            detailsTabText: "כן_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm._ש",
            fieldsTabText: "כן_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._ש",
            styleTabText: "כן_Style your GeoForm using the themes below based on your preference._ש",
            publishTabText: "כן_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._ש",
            smallHeader: "כן_Use Small Header_ש",
            pushpinText: "כן_Push pin_ש",
            doneButtonText: "כן_View Application Item_ש",
            fieldTabPlaceHolderHeaderText: "כן_Hint (optional)_ש",
            attachmentLabelText: "כן_Attchment Label_ש",
            attachmentLabelHint: "כן_Tell users what type of file to attach._ש",
            attachmentDescription: "כן_Attachment Description_ש",
            attachmentHint: "כן_If necessary, you can provide additional attachment instructions here._ש",
            jumbotronDescription: "כן_The Bootstrap Jumbotron makes it easy to define the purpose of your application. This can be disabled at any time._ש",
            shareGeoformText: "כן_Share Geoform_ש",
            shareDescription: "כן_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time._ש",
            defaultMapExtent: "כן_Default Map Extent_ש",
            defaultMapExtentDescription: "כן_The map will reset to the default extent in your web map after submission - this can be disabled at any time._ש",
            pushpinOptionsDescription: "כן_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_ש",
            selectLocationText: "כן_Select Location By_ש",
            myLocationText: "כן_My Location_ש",
            searchText: "כן_Search_ש",
            coordinatesText: "כן_Latitude & Longitude Coordinates_ש",
            usng: "כן_USNG Coordinates_ש",
            mgrs: "כן_MGRS Coordinates_ש",
            utm: "כן_UTM Coordinates_ש",
            selectLocationSDescription: "כן_Allow users to select a location using these methods._ש"
        }
    })
);