define(
     ({
        map: {
            error: "Imposibil de creat harta"
        },
        onlineStatus: {
            offline: "În prezent, lucraţi offline. Trimiterea formularelor va fi salvată local până când se va putea stabili o conexiune la server.",
            reconnecting: "Se reconectează&hellip;",
            pending: "${total} editări în aşteptare vor fi trimise la restabilirea unei conexiuni de reţea."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Organizaţia mea",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Resursele mele",
                    favoritesLabel: "Preferinţele mele"
                },
                title: "Selectare hartă Web",
                searchTitle: "Căutare",
                ok: "OK",
                cancel: "Anulare",
                placeholder: "Introducere termen de căutare"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Organizaţia mea",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Resursele mele",
                    favoritesLabel: "Preferinţele mele"
                },
                title: "Selectare grup",
                searchTitle: "Căutare",
                ok: "OK",
                cancel: "Anulare",
                placeholder: "Introducere termen de căutare"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Spre nord",
            utm_easting: "Spre est",
            utm_zone_number: "Număr zonă",
            geoFormGeneralTabText: "1. Introduceţi informaţii",
            locationInformationText: "2. Selectaţi o locaţie",
            submitInformationText: "3. Completaţi un formular",
            submitInstructions: "Adăugaţi aceste informaţii în hartă.",
            myLocationText: "Locaţie curentă",
            locationDescription: "Specificaţi locaţia acestei intrări făcând clic pe / atingând harta sau utilizând una din următoarele opţiuni.",
            addressText: "Căutare",
            geographic: "Lat/Lon",
            locationTabText: "Locaţie",
            locationPopupTitle: "Locaţie",
            submitButtonText: "Trimitere date",
            submitButtonTextLoading: "Se trimite&hellip;",
            formValidationMessageAlertText: "Următoarele câmpuri sunt obligatorii:",
            selectLocation: "Selectaţi o ${openLink}locaţie${closeLink} pentru trimitere.",
            emptylatitudeAlertMessage: "Introduceţi o coordonată de ${openLink}latitudine${closeLink}.",
            emptylongitudeAlertMessage: "Introduceţi o coordonată de ${openLink}longitudine${closeLink}.",
            shareUserTitleMessage: "Vă mulţumim pentru contribuţie!",
            entrySubmitted: "Datele dvs. au fost trimise către hartă.",
            shareThisForm: "Partajaţi acest formular",
            shareUserTextMessage: "Recomandaţi şi altor utilizatori să contribuie folosind următoarele opţiuni.",
            addAttachmentFailedMessage: "Nu se poate adăuga o ataşare la stratul tematic",
            addFeatureFailedMessage: "Nu se poate adăuga un obiect spaţial la stratul tematic",
            noLayerConfiguredMessage: "A survenit o eroare la încărcarea sau găsirea unui strat tematic de obiecte spaţiale editabil. Pentru a afişa formularul şi începe colectarea elementelor trimise, adăugaţi un strat tematic de obiecte spaţiale editabile în harta web.",
            placeholderLatitude: "Latitudine (Y)",
            placeholderLongitude: "Longitudine (X)",
            latitude: "Latitudine",
            longitude: "Longitudine",
            findMyLocation: "Localizare proprie",
            finding: "Se localizează&hellip;",
            backToTop: "Înapoi sus",
            addressSearchText: "Datele introduse vor apărea aici. Puteţi trage marcajul pentru a corecta locaţia.",
            shareModalFormText: "Link formular",
            close: "Închidere",
            locationNotFound: "Locaţia nu a putut fi găsită.",
            setLocation: "Setare locaţie",
            find: "Găsire adresă sau loc",
            attachment: "Ataşare",
            toggleDropdown: "Comutare listă derulantă",
            invalidLatLong: "Introduceţi coordonate valide pentru ${latLink}latitudine${closeLink} şi ${lngLink}longitudine${closeLink}.",
            invalidUTM: "Introduceţi coordonate ${openLink}UTM${closeLink} valide.",
            invalidUSNG: "Introduceţi coordonate ${openLink}USNG${closeLink} valide.",
            invalidMGRS: "Introduceţi coordonate ${openLink}MGRS${closeLink} valide.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Selectare&hellip;",
            applyEditsFailedMessage: "Ne pare rău, intrarea dvs. nu poate fi trimisă. Încercaţi din nou.",
            requiredFields: "Există erori. Corectaţi-le mai jos.",
            requiredField: "(obligatoriu)",
            error: "Eroare",
            textRangeHintMessage: "${openStrong}Sugestie:${closeStrong} Valoarea minimă ${minValue} şi Valoarea maximă ${maxValue}",
            dateRangeHintMessage: "${openStrong}Sugestie:${closeStrong} Data minimă ${minValue} şi Data maximă ${maxValue}"
        },
        builder: {
            invalidUser: "Ne pare rău, nu aveţi permisiunea de a vizualiza acest element",
            invalidWebmapSelectionAlert: "Harta web selectată nu conţine niciun strat tematic valid pentru utilizare. Pentru a continua, adăugaţi un strat tematic de obiecte spaţiale editabil în harta web.",
            invalidWebmapSelectionAlert2: "Pentru informaţii suplimentare, consultaţi ${openLink}Ce este un serviciu de obiecte spaţiale?${closeLink}",
            selectFieldsText: "Selectare câmpuri din formular",
            selectThemeText: "Selectare temă formular",
            webmapText: "Hartă web",
            layerText: "Strat tematic",
            detailsText: "Detalii",
            fieldsText: "Câmpuri",
            styleText: "Stil",
            optionText: "Opţiuni",
            previewText: "Previzualizare",
            publishText: "Publicare",
            optionsApplicationText: "Opţiuni",
            titleText: "Aplicaţie de creare",
            descriptionText: "GeoForm este un şablon configurabil pentru editarea datelor bazate pe formulare dintr-un ${link1}serviciul de obiecte spaţiale${closeLink}. Această aplicaţie le permite utilizatorilor să introducă date prin intermediul unui formular, în locul unei ferestre pop-up din hartă, exploatând astfel capacitatea ${link2}hărţii web${closeLink} şi a serviciilor de obiecte spaţiale editabile. Folosiţi următoarele etape pentru a personaliza şi pune în funcţiune formularul geografic.",
            btnPreviousText: "Anterior",
            btnNextText: "Următor",
            webmapTabTitleText: "Selectare hartă web",
            viewWebmap: "Vizualizare hartă web",
            btnSelectWebmapText: "Alegere hartă web",
            btnSelectWebmapTextLoading: "Se încarcă&hellip;",
            layerTabTitleText: "Selectare strat tematic editabil",
            selectLayerLabelText: "Strat tematic",
            selectLayerDefaultOptionText: "Selectare strat tematic",
            detailsTabTitleText: "Detalii formular",
            detailTitleLabelText: "Titlu",
            detailLogoLabelText: "Imagine siglă",
            descriptionLabelText: "Text de ajutor (opţional)",
            fieldTabFieldHeaderText: "Câmp",
            fieldTabLabelHeaderText: "Etichetă",
            fieldTabDisplayTypeHeaderText: "Afişare ca",
            selectMenuOption: "Meniu de selectare",
            selectRadioOption: "Buton radio",
            selectTextOption: "Text",
            selectCheckboxOption: "Casetă de selectare",
            selectMailOption: "E-mail",
            selectUrlOption: "URL",
            selectTextAreaOption: "Zonă de text",
            previewApplicationText: "Previzualizare aplicaţie",
            saveApplicationText: "Salvare aplicaţie",
            saveText: "Salvare",
            toggleNavigationText: "Comutare navigaţie",
            formPlaceholderText: "Formularul meu",
            shareBuilderInProgressTitleMessage: "Publicare GeoForm în curs",
            shareBuilderProgressBarMessage: "Aşteptaţi&hellip;",
            shareBuilderTitleMessage: "Succes! Element salvat",
            shareBuilderTextMessage: "Puteţi începe să conectaţi informaţii partajându-le cu alţii",
            shareModalFormText: "Link formular",
            shareBuilderSuccess: "Serviciul dvs. GeoForm a fost actualizat şi publicat!",
            geoformTitleText: "GeoForm",
            layerTabText: "Acesta este stratul tematic din care va fi creat serviciul GeoForm. Stratul tematic trebuie să fie un serviciu de obiecte spaţiale editabil cu permisiuni de partajare adaptate audienţei dvs.",
            detailsTabText: "Utilizaţi casetele Detalii formular de mai jos pentru a particulariza titlul, adăuga o siglă particularizată şi furniza o scurtă descriere pentru audienţa serviciului GeoForm. În descriere, puteţi adăuga linkuri către alte resurse, informaţii de contact şi chiar îndruma audienţa către o aplicaţie de cartografiere web cu toate datele colectate cu ajutorul GeoForm.",
            fieldsTabText: "Aici puteţi selecta ce câmpuri vor fi vizibile pentru audienţa GeoForm, edita etichetele pe care aceştia le vor vedea şi adăuga o scurtă descriere pentru a ajuta la introducerea datelor.",
            styleTabText: "Modelaţi-vă serviciul GeoForm utilizând temele de mai jos, în funcţie de propriile preferinţe.",
            publishTabText: "Dacă aţi terminat particularizarea formularului geografic, salvaţi aplicaţia şi începeţi să o partajaţi cu audienţa. Puteţi reveni oricând la această aplicaţie de creare şi continua particularizarea în funcţie de feedback.",
            smallHeader: "Utilizare antet mic",
            pushpinText: "Piuneză",
            doneButtonText: "Vizualizare element de aplicaţie",
            fieldTabPlaceHolderHeaderText: "Sugestie (opţional)",
            attachmentLabelText: "Etichetă ataşare",
            attachmentLabelHint: "Recomandaţi utilizatorilor ce tip de fişier să ataşeze.",
            attachmentDescription: "Descriere ataşare",
            attachmentHint: "Dacă este necesar, puteţi furniza aici instrucţiuni suplimentare pentru ataşări.",
            jumbotronDescription: "Bootstrap Jumbotron permite definirea uşoară a scopului aplicaţiei. Acesta poate fi dezactivat în orice moment.",
            shareGeoformText: "Partajare GeoForm",
            shareDescription: "Acest panou de partajare permite audienţei să partajeze cu uşurinţă GeoForm cu alţi colaboratori după ce trimit un element; acesta poate fi dezactivat în orice moment.",
            defaultMapExtent: "Extindere implicită a hărţii",
            defaultMapExtentDescription: "Harta va fi resetată la extinderea implicită în harta dvs. web după trimitere; acest lucru poate fi dezactivat în orice moment.",
            pushpinOptionsDescription: "Alegeţi dintr-o multitudine de culori pentru piuneza de pe hartă; aceasta trebuie să difere de simbolurile hărţii pentru a ajuta utilizatorul să plaseze propriul element pe hartă",
            selectLocationText: "Selectare locaţie după",
            myLocationText: "Locaţia mea",
            searchText: "Căutare",
            coordinatesText: "Coordonate de latitudine şi longitudine",
            usng: "Coordonate USNG",
            mgrs: "Coordonate MGRS",
            utm: "Coordonate UTM",
            selectLocationSDescription: "Permite utilizatorilor să selecteze o locaţie cu ajutorul acestor metode."
        }
    })
);