define(
   ({
    map: {
      error: "Nu se poate crea harta"
    },
    onlineStatus: {
      offline: "În prezent, lucraţi offline. Trimiterea formularelor va fi salvată local până când se va putea stabili o conexiune la server.",
      reconnecting: "Se reconectează&hellip;",
      pending: "${total} editări în aşteptare vor fi trimise la restabilirea unei conexiuni la reţea."
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "Organizaţia mea",
          onlineLabel: "ArcGIS Online",
          contentLabel: "Resursele mele",
          favoritesLabel: "Preferinţele mele"
        },
        title: "Selectare hartă web",
        searchTitle: "Căutare",
        ok: "OK",
        cancel: "Anulare",
        placeholder: "Introducere termen de căutat"
      },
      groupdlg: {
        items: {
          organizationLabel: "Organizaţia mea",
          onlineLabel: "ArcGIS Online",
          contentLabel: "Resursele mele",
          favoritesLabel: "Preferinţele mele"
        },
        title: "Selectare grup",
        searchTitle: "Căutare",
        ok: "OK",
        cancel: "Anulare",
        placeholder: "Introducere termen de căutat"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "Iată un link către GeoForm"
      }
    },
    user: {
      mgrs: "MGRS",
      usng: "USNG",
      utm: "UTM",
      utm_northing: "Spre nord",
      utm_easting: "Spre est",
      utm_zone_number: "Număr zonă",
      selectLayerTabText: "${formSection} Selectaţi formularul",
      geoFormGeneralTabText: "${formSection} Introduceţi informaţii",
      locationInformationText: "${formSection} Selectaţi o locaţie",
      submitInformationText: "${formSection} Completaţi un formular",
      submitInstructions: "Adăugaţi aceste informaţii în hartă.",
      myLocationText: "Locaţie curentă",
      locationDescriptionForMoreThanOneOption: "Specificaţi locaţia acestei intrări făcând clic pe/atingând harta sau utilizând una din următoarele opţiuni.",
      locationDescriptionForOneOption: "Specificaţi locaţia acestei intrări făcând clic pe/atingând harta sau utilizând următoarea opţiune.",
      locationDescriptionForNoOption: "Specificaţi locaţia acestei intrări făcând clic pe/atingând harta.",
      addressText: "Căutare",
      geographic: "Lat/Lon",
      locationTabText: "Locaţie",
      locationPopupTitle: "Locaţie",
      submitButtonText: "Trimitere date",
      submitButtonTextLoading: "Se trimite&hellip;",
      formValidationMessageAlertText: "Următoarele câmpuri sunt obligatorii:",
      selectLocation: "Selectaţi o locaţie pentru trimitere.",
      emptylatitudeAlertMessage: "Introduceţi o coordonată de ${openLink}latitudine${closeLink}.",
      emptylongitudeAlertMessage: "Introduceţi o coordonată de ${openLink}longitudine${closeLink}.",
      shareUserTitleMessage: "Vă mulţumim pentru contribuţie!",
      entrySubmitted: "Intrarea dvs. a fost trimisă pentru hartă.",
      shareThisForm: "Se partajează acest formular",
      shareUserTextMessage: "Comunicaţi celorlalţi să contribuie folosind următoarele opţiuni.",
      addAttachmentFailedMessage: "Nu se poate adăuga ataşarea la stratul tematic",
      addFeatureFailedMessage: "Nu se poate adăuga obiectul spaţial la stratul tematic",
      noLayerConfiguredMessage: "A survenit o eroare la încărcarea sau găsirea unui strat tematic de obiecte spaţiale editabil. Pentru a afişa formularul şi a începe colectarea elementelor trimise, adăugaţi un strat tematic de obiecte spaţiale editabil la harta web.",
      placeholderLatitude: "Latitudine (Y)",
      placeholderLongitude: "Longitudine (X)",
      latitude: "Latitudine",
      longitude: "Longitudine",
      findMyLocation: "Localizează-mă",
      finding: "Se localizează&hellip;",
      backToTop: "Înapoi sus",
      addressSearchText: "Datele introduse vor apărea aici. Puteţi trage marcajul pentru a corecta locaţia.",
      shareModalFormText: "Link formular",
      close: "Închidere",
      locationNotFound: "Locaţia nu a putut fi găsită.",
      setLocation: "Setare locaţie",
      find: "Găsire adresă sau loc",
      attachment: "Ataşare",
      toggleDropdown: "Comutare listă derulantă",
      invalidString: "Introduceţi o valoare validă.",
      invalidSmallNumber: "Introduceţi o valoare de număr ${openStrong}întreg${closeStrong} validă între -32768 şi 32767.",
      invalidNumber: "Introduceţi o valoare de număr ${openStrong}întreg${closeStrong} validă între -2147483648 şi 2147483647.",
      invalidFloat: "Introduceţi o valoare de ${openStrong}virgulă mobilă${closeStrong} validă.",
      invalidDouble: "Introduceţi o valoare ${openStrong}dublă${closeStrong} validă.",
      invalidLatLong: "Introduceţi coordonate valide pentru latitudine şi longitudine.",
      invalidUTM: "Introduceţi coordonate UTM valide.",
      invalidUSNG: "Introduceţi coordonate USNG valide.",
      invalidMGRS: "Introduceţi coordonate MGRS valide.",
      geoformTitleText: "GeoForm",
      domainDefaultText: "Selectare&hellip;",
      applyEditsFailedMessage: "Ne pare rău, înregistrarea dvs. nu se poate trimite. Încercaţi din nou.",
      requiredFields: "Există erori. Corectaţi-le mai jos.",
      requiredField: "(obligatoriu)",
      error: "Eroare",
      textRangeHintMessage: "${openStrong}Sugestie:${closeStrong} Valoare minimă ${minValue} şi Valoare maximă ${maxValue}",
      dateRangeHintMessage: "${openStrong}Sugestie:${closeStrong} Dată minimă ${minValue} şi Dată maximă ${maxValue}",
      remainingCharactersHintMessage: "${value} caractere rămase",
      mapFullScreen: "Pe tot ecranul",
      mapRestore: "Restaurare",
      filterSelectEmptyText: "Selectare",
      invalidLayerMessage: "Stratul tematic pentru formular nu există. Configuraţi aplicaţia şi setaţi stratul tematic.",
      selectedLayerText: "Toate",
      fileUploadStatus: "Stare încărcare fişier",
      uploadingBadge: "&nbsp;Se încarcă&hellip;",
      successBadge: "&nbsp;Încărcat",
      retryBadge: "Reîncercare",
      errorBadge: "Eroare la încărcarea&nbsp;&nbsp;&nbsp;",
      fileTooLargeError: "Fişier prea mare pentru ataşare",
      exceededFileCountError: "S-a depăşit numărul maxim de ataşări permis.",
      selectFileTitle: "Selectaţi un fişier",
      btnViewSubmissions: "Vizualizare trimiteri",
      dateFormat: "LL/ZZ/AAAA h:mm a"
    },
    builder: {
      invalidUser: "Ne pare rău, nu aveţi permisiunea de a vizualiza acest element",
      invalidWebmapSelectionAlert: "Harta web selectată nu conţine niciun strat tematic valid pentru utilizare. Pentru a continua, adăugaţi un strat tematic de obiecte spaţiale editabil în harta web.",
      invalidWebmapSelectionAlert2: "Pentru informaţii suplimentare, consultaţi ${openLink}Ce este un serviciu de obiecte spaţiale?${closeLink}",
      selectFieldsText: "Selectare câmpuri din formular",
      selectThemeText: "Selectare temă formular",
      webmapText: "Hartă web",
      layerText: "Strat tematic",
      detailsText: "Detalii",
      fieldsText: "Câmpuri",
      styleText: "Stil",
      optionText: "Opţiuni",
      previewText: "Previzualizare",
      publishText: "Publicare",
      optionsApplicationText: "Opţiuni",
      titleText: "Generator",
      descriptionText: "GeoForm este un şablon configurabil pentru editarea datelor bazate pe formulare ale unui ${link1}Serviciu de obiecte spaţiale${closeLink}. Această aplicaţie le permite utilizatorilor să introducă date printr-un formular în locul unei ferestre pop-up de hartă, beneficiind astfel de capacităţile ${link2}hărţilor web${closeLink} şi ale serviciilor de obiecte spaţiale editabile. Urmați pașii de mai jos pentru a particulariza şi utiliza serviciul GeoForm.",
      btnPreviousText: "Anterior",
      btnNextText: "Următor",
      webmapTabTitleText: "Selectare hartă web",
      viewWebmap: "Vizualizare hartă web",
      webmapDetailsText: "Harta web selectată este ${webMapTitleLink}${webMapTitle}${closeLink}. Pentru a selecta o altă hartă web, faceţi clic pe butonul „Selectare hartă web”.",
      btnSelectWebmapText: "Selectare hartă web",
      btnSelectWebmapTextLoading: "Se încarcă&hellip;",
      layerTabTitleText: "Selectare strat tematic editabil",
      selectLayerLabelText: "Strat tematic",
      selectLayerDefaultOptionText: "Selectare strat tematic",
      defaultBasemap: "Comutare hartă fundal",
      secondaryBasemap: "Hartă fundal implicită",
      detailsTabTitleText: "Detalii formular",
      detailTitleLabelText: "Titlu",
      detailLogoLabelText: "Imagine siglă",
      descriptionLabelText: "Instrucţiuni şi detalii formular",
      fieldDescriptionLabelText: "Text de ajutor (opțional)",
      fieldTabFieldHeaderText: "Câmp",
      fieldTabLabelHeaderText: "Etichetă",
      fieldTabDisplayTypeHeaderText: "Afişare ca",
      fieldTabOrderColumnText: "Ordine",
      fieldTabVisibleColumnText: "Activat",
      displayFieldText: "Câmp de afişare",
      selectMenuOption: "Selectare meniu",
      selectRadioOption: "Buton radio",
      selectTextOption: "Text",
      selectDateOption: "Selector dată",
      selectRangeOption: "Contor tactil",
      selectCheckboxOption: "Casetă de selectare",
      selectMailOption: "E-mail",
      selectUrlOption: "URL",
      selectTextAreaOption: "Zonă de text",
      previewApplicationText: "Previzualizare aplicaţie",
      saveApplicationText: "Salvare aplicaţie",
      saveText: "Salvare",
      toggleNavigationText: "Comutare navigaţie",
      formPlaceholderText: "Formularul meu",
      shareBuilderInProgressTitleMessage: "Publicare GeoForm în curs",
      shareBuilderProgressBarMessage: "Aşteptaţi&hellip;",
      shareBuilderTitleMessage: "Success! Element salvat",
      shareBuilderTextMessage: "Puteţi începe să colectaţi informaţii partajându-le cu alţii",
      shareModalFormText: "Link formular",
      shareBuilderSuccess: "Serviciul dvs. GeoForm a fost actualizat şi publicat!",
      geoformTitleText: "GeoForm",
      layerTabText: "Acesta este stratul tematic din care va fi creat serviciul GeoForm. Stratul tematic trebuie să fie un serviciu de obiecte spaţiale editabil cu permisiuni de partajare adaptate publicului dvs.",
      detailsTabText: "Utilizaţi casetele Detalii formular de mai jos pentru a particulariza titlul, adăuga o siglă particularizată şi furniza o scurtă descriere pentru publicul serviciului GeoForm. În descriere, puteţi adăuga linkuri către alte resurse, informaţii de contact şi chiar îndruma publicul către o aplicaţie de cartografiere web cu toate datele colectate cu ajutorul GeoForm.",
      fieldsTabText: "Aici puteţi selecta ce câmpuri vor fi vizibile pentru audienţa GeoForm, edita etichetele pe care aceştia le vor vedea şi adăuga o scurtă descriere pentru a ajuta la introducerea datelor.",
      styleTabText: "Modelaţi-vă serviciul GeoForm utilizând temele de mai jos, în funcţie de propriile preferinţe.",
      publishTabText: "După ce terminaţi de particularizat serviciul GeoForm, salvaţi aplicaţia şi începeţi să o partajaţi cu publicul. Puteţi reveni oricând la acest instrument de creare şi continua particularizarea în funcţie de feedbackul primit.",
      headerSizeLabel: "Mărime antet",
      smallHeader: "Utilizare antet mic",
      bigHeader: "Utilizare antet mare",
      pushpinText: "Piuneză",
      doneButtonText: "Salvare şi ieşire",
      fieldTabPlaceHolderHeaderText: "Sugestie (opţional)",
      enableAttachmentLabelText: "${openStrong}Activare ataşări${closeStrong}",
      enableAttachmentLabelHint: "Puteţi activa/dezactiva ataşările de aici",
      attachmentIsRequiredLabelText: "${openStrong}Ataşare necesară${closeStrong}",
      attachmentIsRequiredLabelHint: "Dacă este necesar, utilizatorilor li se poate cere să introducă o atașare.",
      attachmentLabelText: "Etichetă buton ataşare",
      attachmentLabelHint: "Acest text va apărea în dreptul butonului de ataşare. Puteţi folosi acest spaţiu pentru a descrie ceea ce doriţi să ataşeze publicul dvs. (fotografii, clipuri video, documente etc.), formatul de fişier cerut (.jpeg, .png, .docx, .pdf etc.) şi orice alte instrucţiuni suplimentare.",
      attachmentDescription: "Descriere ataşare",
      attachmentHint: "Dacă este necesar, puteți oferi instrucțiuni suplimentare despre atașare în acest spațiu.",
      jumbotronDescription: "Utilizaţi un antet mare sau mic pentru formularul dvs. Un antet mare poate ajuta la definirea scopului aplicaţiei dvs., dar va ocupa mai mult loc pe ecran.",
      shareGeoformText: "Partajare GeoForm",
      shareDescription: "Panoul de partajare permite publicului să partajeze cu uşurinţă GeoForm cu alţi colaboratori după ce trimit un element; acesta poate fi dezactivat în orice moment.",
      defaultMapExtent: "Extindere implicită a hărţii",
      defaultMapExtentDescription: "Harta va fi resetată la extinderea implicită în harta dvs. web după trimitere; acest lucru poate fi dezactivat în orice moment.",
      pushpinOptionsDescription: "Alegeţi dintr-o multitudine de culori pentru piuneza de pe hartă; aceasta trebuie să difere de simbolurile hărţii pentru a ajuta utilizatorul să plaseze propriul element pe hartă",
      selectLocationText: "Selectare locaţie după",
      myLocationText: "Locaţia mea",
      searchText: "Căutare",
      coordinatesText: "Coordonate latitudine și longitudine",
      usng: "Coordonate USNG",
      mgrs: "Coordonate MGRS",
      utm: "Coordonate UTM",
      selectLocationSDescription: "Permite utilizatorilor să selecteze o locaţie cu ajutorul acestor metode.",
      dragTooltipText: "Glisaţi câmpul acolo unde doriţi să apară",
      showHideLayerText: "Afişare strat tematic",
      showHideLayerHelpText: "Puteţi configura GeoForm pentru a afişa/ascunde stratul tematic. Această opţiune se aplică doar pentru configurarea unui singur strat tematic.",
      labelHelpMessage: "Etichetă",
      placeHolderHintMessage: "Text de sugestie",
      placeHolderHelpMessage: "Text de ajutor",
      selectTextOptionValue: "Selectare filtru",
      disableLogo: "Dezactivare siglă",
      disableLogoDescription: "Puteţi configura GeoForm pentru a afişa/ascunde sigla din antetul formularului",
      locateOnLoadText: "Localizare la încărcare",
      locateOnLoadDescription: "Puteţi configura GeoForm pentru a utiliza locaţia curentă la încărcarea paginii",
      selectLayerFieldTabText: "Selectare strat tematic",
      allLayerSelectOptionText: "Toate",
      disableViewer: "Dezactivare vizualizator",
      disableViewerDescription: "Puteţi configura GeoForm pentru a afişa/ascunde aplicaţia de vizualizare",
      displayFieldHintText: "Câmpul de afişare selectat va fi afişat în modul vizualizator drept câmp titlu."
    },
    viewer: {
      geocoderCancelText: "Anulare",
      viewReportsTabText: "Trimiteri",
      viewLegendTabText: "Legendă",
      viewAboutusTabText: "Despre",
      viewMapTabText: "Hartă",
      sortHeaderText: "Sortare după:",
      btnSubmitReportText: "Trimitere raport",
      geocoderPlaceholderText: "Cod zip, oraş etc.",
      noSearchResult: "Niciun rezultat găsit",
      recordsTabTooltip: "Vizualizare trimiteri",
      legendTabTooltip: "Legendă",
      aboutUsTabTooltip: "Despre noi",
      mapTabTooltip: "Hartă",
      appLoadingFailedMessage: "Mod vizualizator nedisponibil",
      btnDescendingText: "Desc",
      btnAscendingText: "Asc",
      geometryUnavailableErrorMessage: "Nu se poate găsi geometria obiectului spaţial",
      infoPopupOffErrorMessage: "Fereastră pop-up informativă dezactivată",
      btnLoadMoreText: "Se încarcă mai multe",
      unavailableTitleText: "Fără titlu",
      unavailableConfigMessage: "Imposibil de încărcat configuraţia"
    }
  })
);