define({  
    map: {
      error: "Krijimi i hartës i pamundur"
    },
    onlineStatus: {
      offline: "Për momentin nuk keni rrjet. Kërkesat do të ruhen derisa të ktheheni në rrjet.",
      reconnecting: "Duke u rikyqur&hellip;",
      pending: "${total} ndryshimet në pritje do të kryhen pas rikyqjes në rrjet."
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "Organizata ime",
          onlineLabel: "ArcGIS Online",
          contentLabel: "Përmbajtja ime",
          favoritesLabel: "Përmbajtja ime e preferuar"
        },
        title: "Zgjedh hartën",
        searchTitle: "Kërko",
        ok: "Në rregull",
        cancel: "Anulo",
        placeholder: "Shkruaj fjalën për kërkim"
      },
      groupdlg: {
        items: {
          organizationLabel: "Organizata ime",
          onlineLabel: "ArcGIS Online",
          contentLabel: "Përmbajtja ime",
          favoritesLabel: "Përmbajtja ime e preferuar"
        },
        title: "Zgjedh grupin",
        searchTitle: "Kërko",
        ok: "Në rregull",
        cancel: "Anulo",
        placeholder: "Shkruaj fjalën për kërkim"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "Këtu gjendet linku per aplikacionin Geoform"
      }
    },
    user: {
      all: "Të gjitha",
      mgrs: "MGRS",
      usng: "USNG",
      utm: "UTM",
      utm_northing: "Northing",
      utm_easting: "Easting",
      utm_zone_number: "Numri i zonës",
      selectLayerTabText: "${formSection} Zgjedh Formularin",
      geoFormGeneralTabText: "${formSection} Fut Informacionin",
      locationInformationText: "${formSection} Zgjedh Vendndodhjen",
      submitInformationText: "${formSection} Kompleto Kërkesën",
      submitInstructions: "Shto këtë informatë në hartë.",
      myLocationText: "Vendndodhja e tanishme",
      locationDescriptionForMoreThanOneOption: "Specifiko lokacionin për këtë shënim duke klikuar/prekur hartën ose duke përdorur njëren nga opcionet e mëposhtme.",
      locationDescriptionForOneOption: "Specifiko lokacionin për këtë shënim duke klikuar/prekur hartën ose duke përdorur opcionin e mëposhtëm.",
      locationDescriptionForNoOption: "Specifiko lokacionin për këtë shënim duke klikuar/prekur hartën.",
      addressText: "Kërko",
      geographic: "Gjer./Gjat.",
      locationTabText: "Lokacioni",
      locationPopupTitle: "Lokacioni",
      submitButtonText: "Dërgo Kërkesësn",
      submitButtonTextLoading: "Duke dërguar&hellip;",
      formValidationMessageAlertText: "Fushat në vijim janë të domosdoshme:",
      selectLocation: "Zgjedh lokacionin për kërkesën tënde.",
      emptylatitudeAlertMessage: "Fut koordinatat e ${openLink}gjerësisë gjeografike${closeLink}.",
      emptylongitudeAlertMessage: "Fut koordinatat e ${openLink}gjatësisë gjeografike${closeLink}.",
      shareUserTitleMessage: "Faleminderit për kontributin tuaj!",
      entrySubmitted: "Kërkesa juaj është vendosur në hartë.",
      shareThisForm: "Shpërndaje këtë Formular",
      shareUserTextMessage: "Tregoju të tjerëve të kontribuojnë duke përdorur opcionet e mëposhtme.",
      addAttachmentFailedMessage: "Vendosja e shtojcës në shtresë e pamundur",
      addFeatureFailedMessage: "Vendosja e gjeoobjektit në shtresë e pamundur",
      noLayerConfiguredMessage: "Ka ndodhur një gabim gjatë vendosjes apo kërkimit të shtresës. Për të shfaqur formularin dhe për të filluar pranimin e kërkesave, shto një shtresë në web hartë.",
      placeholderLatitude: "Gjerësia gjeografike (Y)",
      placeholderLongitude: "Gjatësia gjeografike (X)",
      latitude: "Gjerësia gjeografike",
      longitude: "Gjatësia gjeografike",
      findMyLocation: "Ma përcakto vendndodhjen",
      finding: "Përcaktimi i vendndodhjes&hellip;",
      backToTop: "Kthehu në fillim",
      addressSearchText: "Kërkesa juaj do të shfaqet këtu. Mund ta lëvizni pikën për ta korrigjuar vendndodhjen.",
      shareModalFormText: "Linku i formularit",
      close: "Mbyll",
      locationNotFound: "Gjetja e lokacionit e pamundur.",
      setLocation: "Cakto lokacionin",
      find: "Gjej adresen apo vendin",
      attachment: "Shtojca",
      toggleDropdown: "Ndez/Fike listen",
      invalidString: "Shkruaj vlerën valide.",
      invalidSmallNumber: "Shkruaj vlerën valide ${openStrong}të numrit${closeStrong} në mes -32768 dhe 32767.",
      invalidNumber: "Shkruaj vlerën valide ${openStrong}të numrit${closeStrong} në mes -2147483648 dhe 2147483647.",
      invalidFloat: "Shkruaj vlerën valide ${openStrong}të pikës${closeStrong}.",
      invalidDouble: "Shkruaj vlerën valide ${openStrong}të numrit${closeStrong}.",
      invalidLatLong: "Shkruaj koordinatat valide të gjerësisë dhe gjatësisë gjeografike.",
      invalidUTM: "Shkruaj koordinatat valide UTM.",
      invalidUSNG: "Shkruaj koordinatat valide USNG.",
      invalidMGRS: "Shkruaj koordinatat valide MGRS.",
      geoformTitleText: "GeoForm",
      domainDefaultText: "Zgjedh&hellip;",
      applyEditsFailedMessage: "Ka ndodhur një gabim gjatë dërgimit.",
      applyEditsFailedRobot: "Dërgimi është refuzuar sepse ka dështuar gjatë detektimit të robotit.",
      applyEditsAuthError: "Kërkesa juaj nuk mund të dërgohet për shkak të llojit të nivelit të përdoruesit. Kontakto administratorin e organizatës tuaj për asistencë.",
      requiredFields: "Fusha në vijim është e domosdoshme. Shkruaj të dhëna valide.",
      requiredField: "(domosdoshme)",
      error: "Gabim",
      textRangeHintMessage: "${openStrong}Përkujtues:${closeStrong} Vlera minimale ${minValue} dhe vlera maksimale ${maxValue}",
      dateRangeHintMessage: "${openStrong}Përkujtues:${closeStrong} Data minimale ${minValue} dhe data maksimale ${maxValue}",
      remainingCharactersHintMessage: "${value} shkronjat e mbetura",
      mapFullScreen: "Ekran i plotë",
      mapRestore: "Kthe",
      filterSelectEmptyText: "Zgjedh",
      invalidLayerMessage: "Nuk është gjetur shtresa valide për krijimin e Gjeoformës. Nëse Gjeoforma është konfiguruar me një shtresë, shtresa nuk është më në dispozicion, ose autorizimi ka dështuar.",
      selectedLayerText: "Të gjitha",
      fileUploadStatus: "Statusi i ngarkimit të skedarit",
      uploadingBadge: "&nbsp;Ngarkimi&hellip;",
      successBadge: "&nbsp;Ngarkuar",
      retryBadge: "Provo përsëri",
      errorBadge: "Gabim gjatë ngarkimit&nbsp;&nbsp;&nbsp;",
      fileTooLargeError: "Skedari shumë i madh për t'u shtuar",
      exceededFileCountError: "Është tejkaluar numri i lejuar i shtojcave",
      selectFileTitle: "Zgjedh skedarin",
      btnSelectFileText: "Zgjedh skedarin",
      btnViewSubmissions: "Shiqo kërkesat"
    },
    builder: {
      gettingStarted: "Getting Started",
      dateSettings: "Date Settings",
      hiddenDateField: "Hide this date field",
      preventPastDates: "Prevent past dates",
      preventFutureDates: "Prevent future dates",
      useCurrentDate: "Set this field with the current date and time",
      configure: "Configure",
      configureField: "Configure Field '${fieldName}'",
      invalidUser: "Sorry, you don't have permission to view this item",
      invalidWebmapSelectionAlert: "The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue.",
      invalidWebmapSelectionAlert2: "For More Information please refer to ${openLink}What is Feature Service?${closeLink}",
      selectFieldsText: "Select Form Fields",
      selectThemeText: "Select Form Theme",
      setViewerText: "Configure Viewer",
      introText: "Start",
      webmapText: "Webmap",
      layerText: "Layer",
      detailsText: "Details",
      fieldsText: "Fields",
      styleText: "Style",
      viewerText: "Viewer",
      optionText: "Options",
      previewText: "Preview",
      publishText: "Publish",
      optionsApplicationText: "Options",
      submitButtonText: "Submit Button Text (Optional)",
      submitButtonDesc: "Optionally label the button to submit a new entry. This text will not be translated.",
      viewSubmissionsText: "View Submissions Text (Optional)",
      viewSubmissionsDesc: "Optionally label the button to view existing entries. This text will not be translated.",
      titleText: "Builder",
      descriptionText: "GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a map’s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm.",
      btnPreviousText: "Previous",
      btnNextText: "Next",
      webmapTabTitleText: "Select a Webmap",
      viewWebmap: "View webmap",
      webmapDetailsText: "The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button",
      btnSelectWebmapText: "Choose Webmap",
      btnSelectWebmapTextLoading: "Loading&hellip;",
      layerTabTitleText: "Select Editable Layer(s)",
      selectLayerLabelText: "Layer",
      selectLayerDefaultOptionText: "Select Layer",
      enableBasemapToggle: "Show Basemap Toggle",
      enableBasemapToggleDescription: "You can configure the GeoForm to Show/Hide the Basemap Toggle",
      defaultBasemap: "Basemap Toggle",
      secondaryBasemap: "Default Basemap",
      detailsTabTitleText: "Form Details",
      detailTitleLabelText: "Title",
      detailLogoLabelText: "Logo Image",
      descriptionLabelText: "Form Instructions & Details",
      fieldDescriptionLabelText: "Help Text (optional)",
      fieldDescriptionHelpText: "Provide a short description or instructions for this field.",
      fieldHintHelpText: "Placeholder text for the field.",
      fieldTabFieldHeaderText: "Field",
      fieldTabLabelHeaderText: "Label",
      fieldTabDisplayTypeHeaderText: "Display As",
      fieldTabOrderColumnText: "Order",
      fieldTabVisibleColumnText: "Enabled",
      displayFieldText: "Display Field",
      selectMenuOption: "Select Menu",
      selectRadioOption: "Radio Button",
      selectTextOption: "Text",
      selectDateOption: "Date Picker",
      selectRangeOption: "Touch-Spinner",
      selectCheckboxOption: "Checkbox",
      selectMailOption: "Email",
      selectUrlOption: "URL",
      selectTextAreaOption: "Text Area",
      previewApplicationText: "Preview Application",
      saveApplicationText: "Save Application",
      saveText: "Save",
      toggleNavigationText: "Toggle navigation",
      formPlaceholderText: "My Form",
      shareBuilderInProgressTitleMessage: "Publishing GeoForm",
      shareBuilderProgressBarMessage: "Please Wait&hellip;",
      shareBuilderTitleMessage: "Success! Item saved",
      shareBuilderTextMessage: "You can start collecting information by sharing with others",
      shareModalFormText: "Form Link",
      shareBuilderSuccess: "Your GeoForm has been updated & published!",
      geoformTitleText: "Geo Form",
      layerTabText: "This is the layer(s) that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience. If all layers are selected, the form will allow a user to choose which form layer to submit to.",
      detailsTabText: "Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm.",
      fieldsTabText: "Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry.",
      styleTabText: "Style your GeoForm using the themes below based on your preference.",
      viewerTabText: "Set options for viewing submissions collected from the GeoForm.",
      publishTabText: "If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback.",
      headerSizeLabel: "Header Size",
      smallHeader: "Use Small Header",
      bigHeader: "Use Large Header",
      pushpinText: "Push pin",
      doneButtonText: "Save and Exit",
      fieldTabPlaceHolderHeaderText: "Hint (optional)",
      enableAttachmentLabelText: "${openStrong}Enable Attachments${closeStrong}",
      enableAttachmentLabelHint: "You can enable/disable the attachments here",
      attachmentIsRequiredLabelText: "${openStrong}Attachment Required${closeStrong}",
      attachmentIsRequiredLabelHint: "If necessary, users can be required to enter an attachment.",
      attachmentLabelText: "Attachment Button Label",
      attachmentLabelHint: "This text will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions",
      attachmentDescription: "Attachment Description",
      attachmentHint: "If necessary, you can provide additional attachment instructions here.",
      jumbotronDescription: "Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen",
      shareGeoformText: "Social media sharing buttons",
      shareDescription: "Social media buttons allow your audience to easily share your GeoForm once they have made a submission",
      defaultMapExtent: "Default Map Extent",
      defaultMapExtentDescription: "The map will reset to the default extent in your web map after submission - this can be disabled at any time.",
      pushpinOptionsDescription: "Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map",
      selectLocationText: "Select Location By",
      myLocationText: "My Location",
      searchText: "Search",
      coordinatesText: "Latitude & Longitude Coordinates",
      usng: "USNG Coordinates",
      mgrs: "MGRS Coordinates",
      utm: "UTM Coordinates",
      selectLocationSDescription: "Allow users to select a location using these methods.",
      dragTooltipText: "Drag the field where you want it to appear",
      showHideLayerText: "Show Layer",
      showHideLayerHelpText: "You can configure the GeoForm to Show/Hide Layer. This option only applies to a single layer setup.",
      enableOfflineSupport: "Enable offline support",
      enableOfflineSupportHelpText: "Store submissions when there is no network connection and submit them when a connection is restored.",
      labelHelpMessage: "Label",
      placeHolderHintMessage: "Hint Text",
      placeHolderHelpMessage: "Help Text",
      selectTextOptionValue: "Filter Select",
      disableLogo: "Disable Logo",
      disableLogoDescription: "You can configure the GeoForm to Show/Hide the Logo in the form header",
      locateOnLoadText: "Locate On Load",
      locateOnLoadDescription: "You can configure the GeoForm to use the current location on page load",
      selectLayerFieldTabText: "Select Layer",
      allLayerSelectOptionText: "All Layers",
      disableViewer: "Disable Viewer",
      disableViewerDescription: "You can configure the GeoForm to disable/enable the viewer",
      displayFieldHintText: "Selected display field will be shown in the viewer as a title"
    },
    viewer: {
      geocoderCancelText: "Cancel",
      viewMapTabText: "Map",
      sortHeaderText: "Sort By:",
      geocoderPlaceholderText: "Zip Code, city, etc.",
      noSearchResult: "No result found",
      legendTabTooltip: "Legend",
      aboutUsTabTooltip: "About Us",
      mapTabTooltip: "Map",
      btnDescendingText: "Desc",
      btnAscendingText: "Asc",
      geometryUnavailableErrorMessage: "Error finding the geometry of the feature",
      infoPopupOffErrorMessage: "No information to display",
      btnLoadMoreText: "Load More",
      unavailableTitleText: "Untitled",
      unavailableConfigMessage: "Unable to load config",
      share: "Share",
      viewReportsTabText: "Reports",
      viewLegendTabText: "Legend",
      viewAboutusTabText: "About",
      appLoadingFailedMessage: "There was an error loading the viewer"
    }  
});
