define(
     ({
        map: {
            error: "Nie można utworzyć mapy"
        },
        onlineStatus: {
            offline: "Aktualnie pracujesz w trybie offline. Formularze zgłoszeniowe będą zapisywane lokalnie do momentu, gdy nawiązane zostanie połączenie z serwerem.",
            reconnecting: "Ponowne łączenie&hellip;",
            pending: "Po ponownym nawiązaniu połączenia sieciowego zostanie zgłoszone ${total} oczekujących zmian."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Moja instytucja",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Moje zasoby",
                    favoritesLabel: "Moje ulubione"
                },
                title: "Wybierz mapę internetową",
                searchTitle: "Wyszukaj",
                ok: "OK",
                cancel: "Anuluj",
                placeholder: "Wprowadź wyszukiwane wyrażenie"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Moja instytucja",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Moje zasoby",
                    favoritesLabel: "Moje ulubione"
                },
                title: "Wybierz grupę",
                searchTitle: "Wyszukaj",
                ok: "OK",
                cancel: "Anuluj",
                placeholder: "Wprowadź wyszukiwane wyrażenie"
            },
            sharedlg: {
                items: {
                },
                mailtoLinkDescription: "Oto łącze formularza geograficznego"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Współrzędne północne",
            utm_easting: "Współrzędne wschodnie",
            utm_zone_number: "Numer strefy",
            geoFormGeneralTabText: "1. Wpisz informacje",
            locationInformationText: "2. Wybierz lokalizację",
            submitInformationText: "3. Wypełnij formularz",
            submitInstructions: "Dodaj te informacje do mapy.",
            myLocationText: "Bieżąca lokalizacja",
            locationDescriptionForMoreThanOneOption: "Wybierz lokalizację dla tego obiektu poprzez kliknięcie/dotknięcie mapy lub za pomocą jednej z następujących opcji.",
            locationDescriptionForOneOption: "Wybierz lokalizację dla tego obiektu poprzez kliknięcie/dotknięcie mapy lub za pomocą następującej opcji.",
            locationDescriptionForNoOption: "Wybierz lokalizację dla tego obiektu poprzez kliknięcie/dotknięcie mapy.",
            addressText: "Wyszukaj",
            geographic: "Szer./dł. geog.",
            locationTabText: "Lokalizacja",
            locationPopupTitle: "Lokalizacja",
            submitButtonText: "Prześlij wpis",
            submitButtonTextLoading: "Wysyłanie&hellip;",
            formValidationMessageAlertText: "Następujące pola są wymagane:",
            selectLocation: "Wybierz lokalizację do wysłania.",
            emptylatitudeAlertMessage: "Wprowadź współrzędną ${openLink}szerokości geograficznej${closeLink}.",
            emptylongitudeAlertMessage: "Wprowadź współrzędną ${openLink}długości geograficznej${closeLink}.",
            shareUserTitleMessage: "Dziękujemy za udostępnienie informacji!",
            entrySubmitted: "Twój wpis został przesłany na mapę.",
            shareThisForm: "Udostępnij ten formularz",
            shareUserTextMessage: "Zachęć innych do udziału, korzystając z poniższych opcji.",
            addAttachmentFailedMessage: "Nie udało się dodać załącznika do warstwy",
            addFeatureFailedMessage: "Nie udało się dodać obiektu do warstwy",
            noLayerConfiguredMessage: "Wystąpił błąd wczytywania lub wyszukiwania edytowalnej warstwy obiektów. Aby wyświetlić formularz i rozpocząć zbieranie zgłoszeń, należy dodać edytowalną warstwę obiektów do mapy internetowej.",
            placeholderLatitude: "Szerokość geograficzna (Y)",
            placeholderLongitude: "Długość geograficzna (X)",
            latitude: "Szerokość geograficzna",
            longitude: "Długość geograficzna",
            findMyLocation: "Zlokalizuj mnie",
            finding: "Lokalizowanie&hellip;",
            backToTop: "Powrót na górę",
            addressSearchText: "W tym miejscu pojawi się zgłoszenie. Aby poprawić lokalizację, można przeciągnąć pineskę.",
            shareModalFormText: "Łącze do formularza",
            close: "Zamknij",
            locationNotFound: "Nie można odnaleźć lokalizacji.",
            setLocation: "Ustaw lokalizację",
            find: "Znajdź adres lub miejsce",
            attachment: "Załącznik",
            toggleDropdown: "Włącz listę rozwijaną",
            invalidString: "Podaj poprawną wartość.",
            invalidSmallNumber: "Podaj poprawną ${openStrong}liczbę całkowitą${closeStrong} pomiędzy -32768 a 32767.",
            invalidNumber: "Podaj poprawną ${openStrong}liczbę całkowitą${closeStrong} pomiędzy -2147483648 a 2147483647.",
            invalidFloat: "Podaj poprawną wartość ${openStrong}zmiennoprzecinkową${closeStrong}.",
            invalidDouble: "Podaj poprawną wartość ${openStrong}o podwójnej precyzji${closeStrong}.",
            invalidLatLong: "Wprowadź poprawne współrzędne szerokości i długości geograficznej.",
            invalidUTM: "Wprowadź poprawne współrzędne UTM.",
            invalidUSNG: "Wprowadź poprawne współrzędne USNG.",
            invalidMGRS: "Wprowadź poprawne współrzędne MGRS.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Wybierz&hellip;",
            applyEditsFailedMessage: "Przepraszamy, wpis nie mógł zostać wysłany. Spróbuj ponownie.",
            requiredFields: "Wykryto kilka błędów. Dokonaj poprawek poniżej.",
            requiredField: "(wymagane)",
            error: "Błąd",
            textRangeHintMessage: "${openStrong}Wskazówka:${closeStrong} Wartość minimalna ${minValue} i Wartość maksymalna ${maxValue}",
            dateRangeHintMessage: "${openStrong}Wskazówka:${closeStrong} Data minimalna ${minValue} i Data maksymalna ${maxValue}",
            remainingCharactersHintMessage: "pozostały(-o) ${value} znaki(-ów)"
        },
        builder: {
            invalidUser: "Przepraszamy, nie masz uprawnień do wyświetlania tego elementu",
            invalidWebmapSelectionAlert: "Wybrana mapa internetowa nie obejmuje prawidłowej warstwy, z której można by skorzystać. Należy dodać edytowalną warstwę FeatureLayer do mapy internetowej, aby móc przejść dalej.",
            invalidWebmapSelectionAlert2: "Aby móc zapoznać się z dodatkowymi informacjami, należy przejść do tematu ${openLink}Czym jest usługa obiektowa?${closeLink}",
            selectFieldsText: "Wybierz pola formularza",
            selectThemeText: "Wybierz motyw formularza",
            webmapText: "Mapa internetowa",
            layerText: "Warstwa",
            detailsText: "Szczegóły",
            fieldsText: "Pola",
            styleText: "Styl",
            optionText: "Opcje",
            previewText: "Podgląd",
            publishText: "Publikuj",
            optionsApplicationText: "Opcje",
            titleText: "Kreator",
            descriptionText: "GeoForm to konfigurowalny szablon umożliwiający edytowanie danych  ${link1}usługi obiektowej${closeLink} w formularzu. Aplikacja ta umożliwia użytkownikom wprowadzanie danych za pośrednictwem formularza bez konieczności korzystania z okna podręcznego mapy, z jednoczesnym wykorzystaniem potencjału ${link2}mapy internetowej${closeLink} i edytowalnych usług obiektowych. W celu spersonalizowania i wdrożenia formularza GeoForm należy wykonać czynności przedstawione w poniższych etapach.",
            btnPreviousText: "Wstecz",
            btnNextText: "Dalej",
            webmapTabTitleText: "Wybierz mapę internetową",
            viewWebmap: "Wyświetl mapę internetową",
            webmapDetailsText: "Wybrana mapa internetowa to ${webMapTitleLink}${webMapTitle}${closeLink}. Aby wybrać inną mapę internetową, kliknij przycisk 'Wybierz mapę internetową'",
            btnSelectWebmapText: "Wybierz mapę internetową",
            btnSelectWebmapTextLoading: "Loading&hellip;",
            layerTabTitleText: "Wybierz warstwę edytowalną",
            selectLayerLabelText: "Warstwa",
            selectLayerDefaultOptionText: "Wybierz warstwę",
            detailsTabTitleText: "Szczegóły formularza",
            detailTitleLabelText: "Tytuł",
            detailLogoLabelText: "Obraz logo",
            descriptionLabelText: "Instrukcje i szczegóły formularza",
            fieldDescriptionLabelText: "Tekst pomocy (opcjonalny)",
            fieldTabFieldHeaderText: "Pole",
            fieldTabLabelHeaderText: "Etykieta",
            fieldTabDisplayTypeHeaderText: "Wyświetl jako",
            fieldTabOrderColumnText: "Kolejność",
            fieldTabVisibleColumnText: "Włączone",
            selectMenuOption: "Wybierz menu",
            selectRadioOption: "Przycisk radiowy",
            selectTextOption: "Tekst",
            selectDateOption: "Wybór daty",
            selectRangeOption: "Pokrętło dotykowe",
            selectCheckboxOption: "Pole wyboru",
            selectMailOption: "E-mail",
            selectUrlOption: "URL",
            selectTextAreaOption: "Obszar tekstu",
            previewApplicationText: "Podgląd aplikacji",
            saveApplicationText: "Zapisz aplikację",
            saveText: "Zapisz",
            toggleNavigationText: "Przełącz nawigację",
            formPlaceholderText: "Mój formularz",
            shareBuilderInProgressTitleMessage: "Publikowanie formularza geograficznego",
            shareBuilderProgressBarMessage: "Proszę czekać&hellip;",
            shareBuilderTitleMessage: "Udało się! Element został zapisany",
            shareBuilderTextMessage: "Można zacząć zbierać informacje, udostępniając je innym osobom",
            shareModalFormText: "Łącze do formularza",
            shareBuilderSuccess: "Formularz geograficzny został zaktualizowany i opublikowany!",
            geoformTitleText: "Geo Form",
            layerTabText: "Jest to warstwa, na podstawie której będzie tworzony formularz geograficzny. Warstwa musi być usługą obiektową, dla której włączone są opcje edycji w ramach uprawnień do publikowania, dostosowaną do odbiorców.",
            detailsTabText: "Za pomocą poniższych pól Szczegółów formularza należy podać niestandardowy Tytuł, dodać niestandardowe logo oraz podać krótki opis dla odbiorców formularza geograficznego. W opisie możesz zawrzeć łącza do innych zasobów, informacje kontaktowe, a nawet odniesienia do aplikacji map internetowych zawierającej wszystkie dane zebrane za pomocą formularza geograficznego.",
            fieldsTabText: "W tym miejscu można wybrać pola, które będą widoczne dla odbiorców formularza geograficznego, przeprowadzić edycję Etykiet, które będą widzieli, a także dodać krótki Opis ułatwiający wprowadzanie danych.",
            styleTabText: "Za pomocą poniższych motywów dla formularza geograficznego może być nadany wybrany styl.",
            publishTabText: "Na koniec personalizowania GeoForm należy zapisać tę aplikację i zacząć udostępniać ją odbiorcom. Można zawsze powrócić do tego kreatora i dalej ją personalizować w oparciu o uzyskane opinie.",
            headerSizeLabel:"Rozmiar nagłówka",
            smallHeader: "Użyj małego nagłówka",
            bigHeader: "Użyj dużego nagłówka",
            pushpinText: "Pinezka",
            doneButtonText: "Zapisz i zamknij",
            fieldTabPlaceHolderHeaderText: "Wskazówka (opcjonalna)",
            enableAttachmentLabelText: "${openStrong}Włącz załączniki${closeStrong}",
            enableAttachmentLabelHint: "Tu możesz włączyć/wyłączyć załączniki",
            attachmentIsRequiredLabelText: "${openStrong}Załącznik wymagany${closeStrong}",
            attachmentIsRequiredLabelHint: "W razie konieczności od użytkowników można wymagać dodania załącznika.",
            attachmentLabelText: "Etykieta przycisku załącznika",
            attachmentLabelHint: "Ten tekst pojawi się obok przycisku załącznika. Możesz wykorzystać to miejsce do opisania, jakich załączników oczekujesz od odbiorców (zdjęcie, film, dokument itd.) i w jakim formacie (.jpeg, .png, .docx, .pdf itd.), a także do zamieszczenia wszelkich dodatkowych instrukcji",
            attachmentDescription: "Opis załącznika",
            attachmentHint: "W razie potrzeby możesz w tym miejscu przekazać dodatkowe instrukcje dotyczące załącznika.",
            jumbotronDescription: "Użyj dużego lub małego nagłówka formularza. Duży nagłówek może pomóc określić cel Twojej aplikacji, ale zajmuje więcej miejsca na ekranie",
            shareGeoformText: "Udostępnij formularz geograficzny",
            shareDescription: "Panel udostępniania pozwala odbiorcom łatwo udostępnić formularz geograficzny innym jego współtwórcom po złożeniu przez nich wniosku. Funkcję tę można w dowolnej chwili wyłączyć.",
            defaultMapExtent: "Domyślny zasięg mapy",
            defaultMapExtentDescription: "Po przesłaniu wniosku zasięg mapy internetowej powróci do ustawienia domyślnego. Funkcję tę można w dowolnej chwili wyłączyć.",
            pushpinOptionsDescription: "Kolor pinezki używanej na mapie można zmieniać. Powinien on być inny niż w przypadku pozostałych symboli mapy tak, aby ułatwić użytkownikom umieszczanie zgłoszeń na mapie.",
            selectLocationText: "Wybierz lokalizację według",
            myLocationText: "Moja lokalizacja",
            searchText: "Szukaj",
            coordinatesText: "Współrzędne szerokości i długości geograficznej",
            usng: "Współrzędne USNG",
            mgrs: "Współrzędne MGRS",
            utm: "Współrzędne UTM",
            selectLocationSDescription: "Zezwalaj użytkownikom na wybór lokalizacji za pomocą tych metod.",
            dragTooltipText:"Przeciągnij pole do miejsca, w którym ma być wyświetlane",
            showHideLayerText:"Pokaż/ukryj warstwę",
            showHideLayerHelpText:"Możesz skonfigurować formularz geograficzny, aby pokazał/ukrył warstwę"
        }
    })
);