define(
     ({
        map: {
            error: "Harita oluşturulamıyor"
        },
        onlineStatus: {
            offline: "Şu anda çevrimdışı çalışıyorsunuz. Form iletimleri, sunucu ile bir bağlantı kurulana kadar yerel olarak kaydedilecek.",
            reconnecting: "Yeniden bağlanıyor&hellip;",
            pending: "${total} bekleyen düzenleme, bir ağ bağlantısı yeniden kurulduğunda gönderilecektir."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Kuruluşum",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "İçeriğim",
                    favoritesLabel: "Favorilerim"
                },
                title: "Web Haritası Seç",
                searchTitle: "Ara",
                ok: "Tamam",
                cancel: "İptal",
                placeholder: "Arama terimini gir"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Kuruluşum",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "İçeriğim",
                    favoritesLabel: "Favorilerim"
                },
                title: "Grup Seç",
                searchTitle: "Ara",
                ok: "Tamam",
                cancel: "İptal",
                placeholder: "Arama terimini gir"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Kuzeye Yöneltme",
            utm_easting: "Doğuya Yöneltme",
            utm_zone_number: "Bölge Numarası",
            geoFormGeneralTabText: "1. Bilgileri girin",
            locationInformationText: "2. Konumu seçin",
            submitInformationText: "3. Formu doldurun",
            submitInstructions: "Bu bilgileri haritaya ekleyin.",
            myLocationText: "Mevcut Konum",
            locationDescription: "Haritaya dokunarak/tıklayarak ya da aşağıdaki seçeneklerden birini kullanarak bu giriş için bir konum belirtin.",
            addressText: "Ara",
            geographic: "Enlem/Boylam",
            locationTabText: "Konum",
            locationPopupTitle: "Konum",
            submitButtonText: "Giriş Gönder",
            submitButtonTextLoading: "Gönderiliyor&hellip;",
            formValidationMessageAlertText: "Aşağıdaki alanlar gereklidir:",
            selectLocation: "İletiminiz için bir ${openLink}konum${closeLink} seçin.",
            emptylatitudeAlertMessage: "Bir ${openLink}latitude${closeLink} koordinatı girin.",
            emptylongitudeAlertMessage: "Bir ${openLink}longitude${closeLink} koordinatı girin.",
            shareUserTitleMessage: "Katkılarınız için teşekkürler!",
            entrySubmitted: "Girişiniz haritaya gönderildi.",
            shareThisForm: "Bu Formu Paylaş",
            shareUserTextMessage: "Aşağıdaki seçenekleri kullanarak diğerlerine katkıda bulunmasını söyleyin.",
            addAttachmentFailedMessage: "Eklenti katmana eklenemiyor",
            addFeatureFailedMessage: "Özellik katmana eklenemiyor",
            noLayerConfiguredMessage: "Düzenlenebilir bir detay katmanı yüklenirken ya da bulunurken bir hata oluştu. Formu görüntülemek ve iletimleri toplama işlemini başlatmak amacıyla Web haritasına düzenlenebilir bir Detay Katmanı ekleyin.",
            placeholderLatitude: "Enlem (Y)",
            placeholderLongitude: "Boylam (X)",
            latitude: "Enlem",
            longitude: "Boylam",
            findMyLocation: "Beni Bul",
            finding: "&hellip; bulunuyor",
            backToTop: "Başa dön",
            addressSearchText: "Gönderiminiz burada görünecek. Konumu düzeltmek için raptiyeyi sürükleyebilirsiniz.",
            shareModalFormText: "Form Bağlantısı",
            close: "Kapat",
            locationNotFound: "Konum bulunamadı.",
            setLocation: "Konum Ayarla",
            find: "Adres veya yer bul",
            attachment: "İlişik",
            toggleDropdown: "Açılır Menüyü Değiştir",
            invalidLatLong: "Geçerli ${latLink}latitude${closeLink} ve ${lngLink}longitude${closeLink} koordinatları girin.",
            invalidUTM: "Geçerli ${openLink}UTM${closeLink} koordinatları girin.",
            invalidUSNG: "Geçerli ${openLink}USNG${closeLink} koordinatları girin.",
            invalidMGRS: "Geçerli ${openLink}MGRS${closeLink} koordinatları girin.",
            geoformTitleText: "GeoForm",
            domainDefaultText: "Seç&hellip;",
            applyEditsFailedMessage: "Üzgünüz girişiniz gönderilemedi. Yeniden deneyin.",
            requiredFields: "Bazı hatalar var. Bunları aşağıda düzeltin.",
            requiredField: "(gerekli)",
            error: "Hata",
            textRangeHintMessage: "${openStrong}İpucu:${closeStrong} Minimum değer ${minValue} ve Maksimum değer ${maxValue}",
            dateRangeHintMessage: "${openStrong}İpucu:${closeStrong} Minimum Tarih ${minValue} ve Maksimum Tarih ${maxValue}"
        },
        builder: {
            invalidUser: "Üzgünüz, bu öğeyi görüntüleme izniniz yok",
            invalidWebmapSelectionAlert: "Seçilen web haritası kullanılacak geçerli bir katman içermiyor. Devam etmek için web haritanıza düzenlenebilir bir FeatureLayer ekleyin.",
            invalidWebmapSelectionAlert2: "Daha fazla bilgi için bkz. ${openLink}Özellik Hizmeti nedir?${closeLink}",
            selectFieldsText: "Form Alanlarını Seç",
            selectThemeText: "Form Teması Seç",
            webmapText: "Web haritası",
            layerText: "Katman",
            detailsText: "Ayrıntılar",
            fieldsText: "Alanlar",
            styleText: "Stil",
            optionText: "Seçenekler",
            previewText: "Önizleme",
            publishText: "Yayınla",
            optionsApplicationText: "Seçenekler",
            titleText: "Oluşturucu",
            descriptionText: "GeoForm, bir ${link1}Özellik Hizmetinin${closeLink} form tabanlı veri düzenlemesi için yapılandırılabilir bir şablondur. Bu uygulama kullanıcıların veriyi haritanın açılır penceresi yerine bir form ile girmesine, aynı zamanda ${link2}Web Haritası${closeLink} ve düzenlenebilir Detay Servislerinin gücünden yararlanmasına olanak tanır. GeoForm//'unuzu özelleştirmek ve dağıtmak için aşağıdaki adımları kullanın.",
            btnPreviousText: "Önceki",
            btnNextText: "Sonraki",
            webmapTabTitleText: "Web haritası seç",
            viewWebmap: "Web haritasını görüntüle",
            btnSelectWebmapText: "Web Haritası Seç",
            btnSelectWebmapTextLoading: "Yükleniyor&hellip;",
            layerTabTitleText: "Düzenlenebilir Katman Seç",
            selectLayerLabelText: "Katman",
            selectLayerDefaultOptionText: "Katman seç",
            detailsTabTitleText: "Form Ayrıntıları",
            detailTitleLabelText: "Başlık",
            detailLogoLabelText: "Logo Görseli",
            descriptionLabelText: "Yardım Metni (isteğe bağlı)",
            fieldTabFieldHeaderText: "Alan",
            fieldTabLabelHeaderText: "Etiket",
            fieldTabDisplayTypeHeaderText: "Farklı Görüntüle",
            selectMenuOption: "Menü seç",
            selectRadioOption: "Radyo Butonu",
            selectTextOption: "Metin",
            selectCheckboxOption: "Onay Kutusu",
            selectMailOption: "E-posta",
            selectUrlOption: "URL",
            selectTextAreaOption: "Metin alanı",
            previewApplicationText: "Uygulamayı Önizle",
            saveApplicationText: "Uygulamayı Kaydet",
            saveText: "Kaydet",
            toggleNavigationText: "Gezinmeye geç",
            formPlaceholderText: "Formum",
            shareBuilderInProgressTitleMessage: "GeoForm Yayınlanıyor",
            shareBuilderProgressBarMessage: "Bekleyin&hellip;",
            shareBuilderTitleMessage: "Başarılı! Öğe kaydedildi",
            shareBuilderTextMessage: "Diğerleri ile paylaşarak bilgiyi toplamaya başlayabilirsiniz",
            shareModalFormText: "Form Bağlantısı",
            shareBuilderSuccess: "GeoForm\'unuz güncellenmiş ve yayınlanmış!",
            geoformTitleText: "Geo Form",
            layerTabText: "Bu, GeoForm\'un üretileceği katmandır. Katman, hedef kitleniz için uygun paylaşım izinleri ile düzenleme için etkinleştirilmiş bir detay servisi olmalıdır.",
            detailsTabText: "Başlığı düzenlemek için aşağıdaki Form Ayrıntısı kutularını kullanın, özel bir logo ekleyin ve GeoForm hedef kitleniz için kısa bir açıklama girin. Açıklamada diğer kaynaklara bağlantılar, iletişim bilgileri ekleyebilir ve hatta hedef kitlenizi GeoForm ile toplanan tüm veriyi içeren web haritalama uygulamasına yönlendirebilirsiniz.",
            fieldsTabText: "Burada hangi alanların GeoForm hedef kitleniz için görünür olacağını seçebilir, bunların göreceği etiketleri düzenleyebilir ve veri girişine yardımcı olmak için kısa bir Açıklama ekleyebilirsiniz.",
            styleTabText: "Tercihinize göre aşağıdaki temaları kullanarak GeoForm\'unuzu biçimlendirin.",
            publishTabText: "GeoForm\'unuzu özelleştirmeyi bitirdiyseniz, uygulamayı kaydedin ve kitlenizle paylaşmaya başlayın. Her zaman bu oluşturucuya geri dönebilir ve geri bildirimlere bağlı olarak özelleştirmeye devam edebilirsiniz.",
            smallHeader: "Küçük Başlık Kullan",
            pushpinText: "Raptiye",
            doneButtonText: "Uygulama Öğesini Görüntüle",
            fieldTabPlaceHolderHeaderText: "İpucu (isteğe bağlı)",
            attachmentLabelText: "İlişik Etiketi",
            attachmentLabelHint: "Kullanıcılara hangi dosya türünün ekleneceğini söyleyin.",
            attachmentDescription: "İlişik Tanımı",
            attachmentHint: "Gerekiyorsa, burada ilave eklenti talimatları sunun.",
            jumbotronDescription: "Bootstrap Jumbotron uygulamanızın amacını tanımlamayı kolaylaştırır. Bu işlev istenildiğinde devre dışı bırakılabilir.",
            shareGeoformText: "Geoform Paylaş",
            shareDescription: "Paylaşım paneli izleyici kitlenizin bir iletim yaptıklarında GeoForm\'u diğer ortak çalışanlarla paylaşmasını kolaylaştırır - bu işlev istenildiğinde devre dışı bırakılabilir.",
            defaultMapExtent: "Varsayılan Harita Yayılımı",
            defaultMapExtentDescription: "Harita, iletimden sonra web haritanızın varsayılan yayılımına sıfırlanacak - bu işlev istenildiğinde devre dışı bırakılabilir.",
            pushpinOptionsDescription: "Harita raptiyesi için çeşitli renkler arasından seçim yapın, kullanıcının haritada kendi iletimini yerleştirmesi için harita sembolojisinden farklı olmalıdır",
            selectLocationText: "Konum Seçme Kriteri:",
            myLocationText: "Konumum",
            searchText: "Ara",
            coordinatesText: "Enlem ve Boylam Koordinatları",
            usng: "USNG Koordinatları",
            mgrs: "MGRS Koordinatları",
            utm: "UTM Koordinatları",
            selectLocationSDescription: "Kullanıcıların bu yöntemleri kullanarak bir konum seçmesine izin verin."
        }
    })
);