define(
   ({
    map: {
      error: "ก้_Unable to create map_ษฺ"
    },
    onlineStatus: {
      offline: "ก้_You are currently working offline. Form submissions will be saved locally until a connection to the server can be made_ษฺ.",
      reconnecting: "ก้_Reconnecting&hellip;_ษฺ",
      pending: "ก้_${total} pending edit(s) will be submitted when a network connection is re-established_ษฺ."
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "ก้_My Organization_ษฺ",
          onlineLabel: "ก้_ArcGIS Online_ษฺ",
          contentLabel: "ก้_My Content_ษฺ",
          favoritesLabel: "ก้_My Favorites_ษฺ"
        },
        title: "ก้_Select Web Map_ษฺ",
        searchTitle: "ก้_Search_ษฺ",
        ok: "ก้_Ok_ษฺ",
        cancel: "ก้_Cancel_ษฺ",
        placeholder: "ก้_Enter search term_ษฺ"
      },
      groupdlg: {
        items: {
          organizationLabel: "ก้_My Organization_ษฺ",
          onlineLabel: "ก้_ArcGIS Online_ษฺ",
          contentLabel: "ก้_My Content_ษฺ",
          favoritesLabel: "ก้_My Favorites_ษฺ"
        },
        title: "ก้_Select Group_ษฺ",
        searchTitle: "ก้_Search_ษฺ",
        ok: "ก้_Ok_ษฺ",
        cancel: "ก้_Cancel_ษฺ",
        placeholder: "ก้_Enter search term_ษฺ"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "ก้_Here is a link to a GeoForm_ษฺ"
      }
    },
    user: {
      mgrs: "ก้_MGRS_ษฺ",
      usng: "ก้_USNG_ษฺ",
      utm: "ก้_UTM_ษฺ",
      utm_northing: "ก้_Northing_ษฺ",
      utm_easting: "ก้_Easting_ษฺ",
      utm_zone_number: "ก้_Zone Number_ษฺ",
      selectLayerTabText: "ก้_${formSection} Select Form_ษฺ",
      geoFormGeneralTabText: "ก้_${formSection} Enter Information_ษฺ",
      locationInformationText: "ก้_${formSection} Select Location_ษฺ",
      submitInformationText: "ก้_${formSection} Complete Form_ษฺ",
      submitInstructions: "ก้_Add this information to the map_ษฺ.",
      myLocationText: "ก้_Current Location_ษฺ",
      locationDescriptionForMoreThanOneOption: "ก้_Specify the location for this entry by clicking/tapping the map or by using one of the following options_ษฺ.",
      locationDescriptionForOneOption: "ก้_Specify the location for this entry by clicking/tapping the map or by using the following option_ษฺ.",
      locationDescriptionForNoOption: "ก้_Specify the location for this entry by clicking/tapping the map_ษฺ.",
      addressText: "ก้_Search_ษฺ",
      geographic: "ก้_Lat/Lon_ษฺ",
      locationTabText: "ก้_Location_ษฺ",
      locationPopupTitle: "ก้_Location_ษฺ",
      submitButtonText: "ก้_Submit Entry_ษฺ",
      submitButtonTextLoading: "ก้_Submitting&hellip;_ษฺ",
      formValidationMessageAlertText: "ก้_The following fields are required_ษฺ:",
      selectLocation: "ก้_Please select a location for your submission_ษฺ.",
      emptylatitudeAlertMessage: "ก้_Please enter a ${openLink}latitude${closeLink} coordinate_ษฺ.",
      emptylongitudeAlertMessage: "ก้_Please enter a ${openLink}longitude${closeLink} coordinate_ษฺ.",
      shareUserTitleMessage: "ก้_Thank you for your contribution_ษฺ!",
      entrySubmitted: "ก้_Your entry has been submitted to the map_ษฺ.",
      shareThisForm: "ก้_Share This Form_ษฺ",
      shareUserTextMessage: "ก้_Tell others to contribute using the following options_ษฺ.",
      addAttachmentFailedMessage: "ก้_Unable to add attachment to layer_ษฺ",
      addFeatureFailedMessage: "ก้_Unable to add feature to layer_ษฺ",
      noLayerConfiguredMessage: "ก้_An error occurred loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap_ษฺ.",
      placeholderLatitude: "ก้_Latitude (Y)_ษฺ",
      placeholderLongitude: "ก้_Longitude (X)_ษฺ",
      latitude: "ก้_Latitude_ษฺ",
      longitude: "ก้_Longitude_ษฺ",
      findMyLocation: "ก้_Locate Me_ษฺ",
      finding: "ก้_Locating&hellip;_ษฺ",
      backToTop: "ก้_Back to top_ษฺ",
      addressSearchText: "ก้_Your submission will appear here. You can drag the pin to correct the location_ษฺ.",
      shareModalFormText: "ก้_Form Link_ษฺ",
      close: "ก้_Close_ษฺ",
      locationNotFound: "ก้_Location could not be found_ษฺ.",
      setLocation: "ก้_Set Location_ษฺ",
      find: "ก้_Find address or place_ษฺ",
      attachment: "ก้_Attachment_ษฺ",
      toggleDropdown: "ก้_Toggle Dropdown_ษฺ",
      invalidString: "ก้_Please enter valid value_ษฺ.",
      invalidSmallNumber: "ก้_Please enter valid ${openStrong}integer${closeStrong} value between -32768 and 32767_ษฺ.",
      invalidNumber: "ก้_Please enter valid ${openStrong}integer${closeStrong} value between -2147483648 and 2147483647_ษฺ.",
      invalidFloat: "ก้_Please enter valid ${openStrong}floating point${closeStrong} value_ษฺ.",
      invalidDouble: "ก้_Please enter valid ${openStrong}double${closeStrong} value_ษฺ.",
      invalidLatLong: "ก้_Please enter valid latitude and longitude coordinates_ษฺ.",
      invalidUTM: "ก้_Please enter valid UTM coordinates_ษฺ.",
      invalidUSNG: "ก้_Please enter valid USNG coordinates_ษฺ.",
      invalidMGRS: "ก้_Please enter valid MGRS coordinates_ษฺ.",
      geoformTitleText: "ก้_GeoForm_ษฺ",
      domainDefaultText: "ก้_Select&hellip;_ษฺ",
      applyEditsFailedMessage: "ก้_Sorry your entry cannot be submitted. Please try again_ษฺ.",
      requiredFields: "ก้_There are some errors. Please correct them below_ษฺ.",
      requiredField: "ก้_(required)_ษฺ",
      error: "ก้_Error_ษฺ",
      textRangeHintMessage: "ก้_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_ษฺ",
      dateRangeHintMessage: "ก้_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_ษฺ",
      remainingCharactersHintMessage: "ก้_${value} characters remaining_ษฺ",
      mapFullScreen: "ก้_Full Screen_ษฺ",
      mapRestore: "ก้_Restore_ษฺ",
      filterSelectEmptyText: "ก้_Select_ษฺ",
      invalidLayerMessage: "ก้_Form layer does not exist. Please configure the application and set the layer_ษฺ.",
      selectedLayerText: "ก้_All_ษฺ",
      fileUploadStatus: "ก้_File Upload Status_ษฺ",
      uploadingBadge: "ก้_&nbsp;Uploading&hellip;_ษฺ",
      successBadge: "ก้_&nbsp;Uploaded_ษฺ",
      retryBadge: "ก้_Retry_ษฺ",
      errorBadge: "ก้_Error uploading&nbsp;&nbsp;&nbsp;_ษฺ",
      fileTooLargeError: "ก้_File too large to attach_ษฺ",
      exceededFileCountError: "ก้_Exceeded maximum no. of attachments allowed_ษฺ",
      selectFileTitle: "ก้_Select a file_ษฺ",
      btnViewSubmissions: "ก้_View Submissions_ษฺ",
      dateFormat: "ก้_MM/DD/YYYY h:mm a_ษฺ"
    },
    builder: {
      invalidUser: "ก้_Sorry, you don't have permission to view this item_ษฺ",
      invalidWebmapSelectionAlert: "ก้_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue_ษฺ.",
      invalidWebmapSelectionAlert2: "ก้_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_ษฺ",
      selectFieldsText: "ก้_Select Form Fields_ษฺ",
      selectThemeText: "ก้_Select Form Theme_ษฺ",
      webmapText: "ก้_Webmap_ษฺ",
      layerText: "ก้_Layer_ษฺ",
      detailsText: "ก้_Details_ษฺ",
      fieldsText: "ก้_Fields_ษฺ",
      styleText: "ก้_Style_ษฺ",
      optionText: "ก้_Options_ษฺ",
      previewText: "ก้_Preview_ษฺ",
      publishText: "ก้_Publish_ษฺ",
      optionsApplicationText: "ก้_Options_ษฺ",
      titleText: "ก้_Builder_ษฺ",
      descriptionText: "ก้_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a mapâ€™s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm_ษฺ.",
      btnPreviousText: "ก้_Previous_ษฺ",
      btnNextText: "ก้_Next_ษฺ",
      webmapTabTitleText: "ก้_Select a Webmap_ษฺ",
      viewWebmap: "ก้_View webmap_ษฺ",
      webmapDetailsText: "ก้_The selected webmap is ${webMapTitleLink}${webMapTitle}${closeLink}. To select a different webmap please click on 'Choose Webmap' button_ษฺ",
      btnSelectWebmapText: "ก้_Choose Webmap_ษฺ",
      btnSelectWebmapTextLoading: "ก้_Loading&hellip;_ษฺ",
      layerTabTitleText: "ก้_Select Editable Layer_ษฺ",
      selectLayerLabelText: "ก้_Layer_ษฺ",
      selectLayerDefaultOptionText: "ก้_Select Layer_ษฺ",
      defaultBasemap: "ก้_Basemap Toggle_ษฺ",
      secondaryBasemap: "ก้_Default Basemap_ษฺ",
      detailsTabTitleText: "ก้_Form Details_ษฺ",
      detailTitleLabelText: "ก้_Title_ษฺ",
      detailLogoLabelText: "ก้_Logo Image_ษฺ",
      descriptionLabelText: "ก้_Form Instructions & Details_ษฺ",
      fieldDescriptionLabelText: "ก้_Help Text (optional)_ษฺ",
      fieldTabFieldHeaderText: "ก้_Field_ษฺ",
      fieldTabLabelHeaderText: "ก้_Label_ษฺ",
      fieldTabDisplayTypeHeaderText: "ก้_Display As_ษฺ",
      fieldTabOrderColumnText: "ก้_Order_ษฺ",
      fieldTabVisibleColumnText: "ก้_Enabled_ษฺ",
      displayFieldText: "ก้_Display Field_ษฺ",
      selectMenuOption: "ก้_Select Menu_ษฺ",
      selectRadioOption: "ก้_Radio Button_ษฺ",
      selectTextOption: "ก้_Text_ษฺ",
      selectDateOption: "ก้_Date Picker_ษฺ",
      selectRangeOption: "ก้_Touch-Spinner_ษฺ",
      selectCheckboxOption: "ก้_Checkbox_ษฺ",
      selectMailOption: "ก้_Email_ษฺ",
      selectUrlOption: "ก้_URL_ษฺ",
      selectTextAreaOption: "ก้_Text Area_ษฺ",
      previewApplicationText: "ก้_Preview Application_ษฺ",
      saveApplicationText: "ก้_Save Application_ษฺ",
      saveText: "ก้_Save_ษฺ",
      toggleNavigationText: "ก้_Toggle navigation_ษฺ",
      formPlaceholderText: "ก้_My Form_ษฺ",
      shareBuilderInProgressTitleMessage: "ก้_Publishing GeoForm_ษฺ",
      shareBuilderProgressBarMessage: "ก้_Please Wait&hellip;_ษฺ",
      shareBuilderTitleMessage: "ก้_Success! Item saved_ษฺ",
      shareBuilderTextMessage: "ก้_You can start collecting information by sharing with others_ษฺ",
      shareModalFormText: "ก้_Form Link_ษฺ",
      shareBuilderSuccess: "ก้_Your GeoForm has been updated & published_ษฺ!",
      geoformTitleText: "ก้_Geo Form_ษฺ",
      layerTabText: "ก้_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience_ษฺ.",
      detailsTabText: "ก้_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm_ษฺ.",
      fieldsTabText: "ก้_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry_ษฺ.",
      styleTabText: "ก้_Style your GeoForm using the themes below based on your preference_ษฺ.",
      publishTabText: "ก้_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback_ษฺ.",
      headerSizeLabel: "ก้_Header Size_ษฺ",
      smallHeader: "ก้_Use Small Header_ษฺ",
      bigHeader: "ก้_Use Large Header_ษฺ",
      pushpinText: "ก้_Push pin_ษฺ",
      doneButtonText: "ก้_Save and Exit_ษฺ",
      fieldTabPlaceHolderHeaderText: "ก้_Hint (optional)_ษฺ",
      enableAttachmentLabelText: "ก้_${openStrong}Enable Attachments${closeStrong}_ษฺ",
      enableAttachmentLabelHint: "ก้_You can enable/disable the attachments here_ษฺ",
      attachmentIsRequiredLabelText: "ก้_${openStrong}Attachment Required${closeStrong}_ษฺ",
      attachmentIsRequiredLabelHint: "ก้_If necessary, users can be required to enter an attachment_ษฺ.",
      attachmentLabelText: "ก้_Attachment Button Label_ษฺ",
      attachmentLabelHint: "ก้_This text will appear next to the Attachment Button. You can use this space to describe what you would like your audience to attach (photo, video, document, etc.), the file format you are asking for (.jpeg, .png, .docx, .pdf, etc.), and any additional instructions_ษฺ",
      attachmentDescription: "ก้_Attachment Description_ษฺ",
      attachmentHint: "ก้_If necessary, you can provide additional attachment instructions here_ษฺ.",
      jumbotronDescription: "ก้_Use large or small heading for your form. A large header may help define the purpose of your application but it takes up more room on your screen_ษฺ",
      shareGeoformText: "ก้_Share Geoform_ษฺ",
      shareDescription: "ก้_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time_ษฺ.",
      defaultMapExtent: "ก้_Default Map Extent_ษฺ",
      defaultMapExtentDescription: "ก้_The map will reset to the default extent in your web map after submission - this can be disabled at any time_ษฺ.",
      pushpinOptionsDescription: "ก้_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_ษฺ",
      selectLocationText: "ก้_Select Location By_ษฺ",
      myLocationText: "ก้_My Location_ษฺ",
      searchText: "ก้_Search_ษฺ",
      coordinatesText: "ก้_Latitude & Longitude Coordinates_ษฺ",
      usng: "ก้_USNG Coordinates_ษฺ",
      mgrs: "ก้_MGRS Coordinates_ษฺ",
      utm: "ก้_UTM Coordinates_ษฺ",
      selectLocationSDescription: "ก้_Allow users to select a location using these methods_ษฺ.",
      dragTooltipText: "ก้_Drag the field where you want it to appear_ษฺ",
      showHideLayerText: "ก้_Show Layer_ษฺ",
      showHideLayerHelpText: "ก้_You can configure the GeoForm to Show/Hide Layer.This option only applies to a single layer setup_ษฺ.",
      labelHelpMessage: "ก้_Label_ษฺ",
      placeHolderHintMessage: "ก้_Hint Text_ษฺ",
      placeHolderHelpMessage: "ก้_Help Text_ษฺ",
      selectTextOptionValue: "ก้_Filter Select_ษฺ",
      disableLogo: "ก้_Disable Logo_ษฺ",
      disableLogoDescription: "ก้_You can configure the GeoForm to Show/Hide the Logo in the form header_ษฺ",
      locateOnLoadText: "ก้_Locate On Load_ษฺ",
      locateOnLoadDescription: "ก้_You can configure the GeoForm to use the current location on page load_ษฺ",
      selectLayerFieldTabText: "ก้_Select Layer_ษฺ",
      allLayerSelectOptionText: "ก้_All_ษฺ",
      disableViewer: "ก้_Disable Viewer_ษฺ",
      disableViewerDescription: "ก้_You can configure the GeoForm to disable/enable Viewer_ษฺ",
      displayFieldHintText: "ก้_Selected display field will be shown in viewerMode as title field_ษฺ"
    },
    viewer: {
      geocoderCancelText: "ก้_Cancel_ษฺ",
      viewReportsTabText: "ก้_Submissions_ษฺ",
      viewLegendTabText: "ก้_Legend_ษฺ",
      viewAboutusTabText: "ก้_About_ษฺ",
      viewMapTabText: "ก้_Map_ษฺ",
      sortHeaderText: "ก้_Sort By_ษฺ:",
      btnSubmitReportText: "ก้_Submit a Report_ษฺ",
      geocoderPlaceholderText: "ก้_Zip Code, city, etc_ษฺ.",
      noSearchResult: "ก้_No result found_ษฺ",
      recordsTabTooltip: "ก้_View Submissions_ษฺ",
      legendTabTooltip: "ก้_Legend_ษฺ",
      aboutUsTabTooltip: "ก้_AboutUs_ษฺ",
      mapTabTooltip: "ก้_Map_ษฺ",
      appLoadingFailedMessage: "ก้_ViewerMode is Unavailable_ษฺ",
      btnDescendingText: "ก้_Desc_ษฺ",
      btnAscendingText: "ก้_Asc_ษฺ",
      geometryUnavailableErrorMessage: "ก้_Unable to find the geometry of the feature_ษฺ",
      infoPopupOffErrorMessage: "ก้_InfoPopup is off_ษฺ",
      btnLoadMoreText: "ก้_Load More_ษฺ",
      unavailableTitleText: "ก้_Untitled_ษฺ",
      unavailableConfigMessage: "ก้_Unable to load config_ษฺ"
    }
  })
);