define(
     ({
        map: {
            error: "Nevar izveidot karti"
        },
        onlineStatus: {
            offline: "Jūs pašreiz strādājat bezsaistē. Iesniegtās formas tiks saglabātas lokāli, līdz tiks izveidots savienojums ar serveri.",
            reconnecting: "Notiek atkārtota savienošana&hellip;",
            pending: "Kad tiks atkārtoti izveidots savienojums ar tīklu, tiks iesniegts(i) ${total} gaidīšanā esošais(ie) rediģējums(i)."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Organizācija",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Mans saturs",
                    favoritesLabel: "Mani favorīti"
                },
                title: "Izvēlēties web karti",
                searchTitle: "Meklēšana",
                ok: "Labi",
                cancel: "Atcelt",
                placeholder: "Ievadīt meklēšanas kritēriju"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Organizācija",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Mans saturs",
                    favoritesLabel: "Mani favorīti"
                },
                title: "Atlasīt grupu",
                searchTitle: "Meklēšana",
                ok: "Labi",
                cancel: "Atcelt",
                placeholder: "Ievadīt meklēšanas kritēriju"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Novirzīšanās uz ziemeļiem",
            utm_easting: "Novirzīšanās uz austrumiem",
            utm_zone_number: "Joslas numurs",
            geoFormGeneralTabText: "1. Ievadiet informāciju",
            locationInformationText: "2. Atlasiet atrašanās vietu",
            submitInformationText: "3. Aizpildiet veidlapu",
            submitInstructions: "Pievienot šo informāciju kartei.",
            myLocationText: "ķ_Current Location_ū",
            locationDescription: "ķ_Specify the location for this entry by clicking/tapping the map or by using one of the following options._ū",
            addressText: "Meklēt",
            geographic: "ķ_Lat/Lon_ū",
            locationTabText: "Izvietojums",
            locationPopupTitle: "ķ_Location_ū",
            submitButtonText: "ķ_Submit Entry_ū",
            submitButtonTextLoading: "Iesniegšana&hellip;",
            formValidationMessageAlertText: "Tālāk ir minēti obligāti aizpildāmie lauki:",
            selectLocation: "Izvēlieties ${openLink}izvietojumus${closeLink} iesniegšanai.",
            emptylatitudeAlertMessage: "Ievadiet ${openLink}ģeogrāfiskā platuma${closeLink} koordinātu.",
            emptylongitudeAlertMessage: "Ievadiet ${openLink}ģeogrāfiskā garuma${closeLink} koordinātu.",
            shareUserTitleMessage: "Pateicamies par ieguldījumu!",
            entrySubmitted: "ķ_Your entry has been submitted to the map._ū",
            shareThisForm: "ķ_Share This Form_ū",
            shareUserTextMessage: "ķ_Tell others to contribute using the following options._ū",
            addAttachmentFailedMessage: "Slānim nevar pievienot pielikumu",
            addFeatureFailedMessage: "Slānim nevar pievienot elementu",
            noLayerConfiguredMessage: "Ak vai! Šeit nekā nav. Lai sāktu apkopot iesniegtās veidlapas, konfigurējiet GeoForm un atlasiet rediģējamu elementu servisu, kuru izmantot.",
            placeholderLatitude: "Platums (Y)",
            placeholderLongitude: "Garums (X)",
            latitude: "Platums",
            longitude: "Garums",
            findMyLocation: "ķ_Locate Me_ū",
            finding: "Izvietojuma atrašana&hellip;",
            backToTop: "Atpakaļ uz augšu",
            addressSearchText: "Jūsu iesniegtā informācija būs redzama šeit. Varat vilkt spraudīti, lai koriģētu atrašanās vietu.",
            shareModalFormText: "Veidlapas saite",
            close: "Aizvērt",
            locationNotFound: "Izvietojumu nevar atrast.",
            setLocation: "ķ_Set Location_ū",
            find: "ķ_Find address or place_ū",
            attachment: "Pielikums",
            toggleDropdown: "Pārslēgt nolaižamo izvēlni",
            invalidLatLong: "Ievadiet derīgas ${latLink}ģeogrāfiskā platuma${closeLink} un ${lngLink}ģeogrāfiskā garuma${closeLink} koordinātas.",
            invalidUTM: "Ievadiet derīgas ${openLink}UTM${closeLink} koordinātas.",
            invalidUSNG: "Ievadiet derīgas ${openLink}USNG${closeLink} koordinātas.",
            invalidMGRS: "Ievadiet derīgas ${openLink}MGRS${closeLink} koordinātas.",
            geoformTitleText: "Ģeoveidlapa",
            domainDefaultText: "Izvēlēties&hellip;",
            applyEditsFailedMessage: "Diemžēl jūsu ierakstu nevar iesniegt. Lūdzu, mēģiniet vēlreiz.",
            requiredFields: "Pastāv dažas kļūdas. Tās izlabojiet tālāk.",
            requiredField: "ķ_(required)_ū",
            error: "Kļūda",
            textRangeHintMessage: "ķ_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_ū",
            dateRangeHintMessage: "ķ_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_ū"
        },
        builder: {
            invalidUser: "ķ_Sorry, you dont have permission to view this item_ū",
            invalidWebmapSelectionAlert: "ķ_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._ū",
            invalidWebmapSelectionAlert2: "ķ_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_ū",
            selectFieldsText: "ķ_Select Form Fields_ū",
            selectThemeText: "ķ_Select Form Theme_ū",
            webmapText: "ķ_Webmap_ū",
            layerText: "ķ_Layer_ū",
            detailsText: "ķ_Details_ū",
            fieldsText: "ķ_Fields_ū",
            styleText: "ķ_Style_ū",
            optionText: "ķ_Options_ū",
            previewText: "ķ_Preview_ū",
            publishText: "ķ_Publish_ū",
            optionsApplicationText: "ķ_Options_ū",
            titleText: "ķ_Builder_ū",
            descriptionText: "ķ_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a map’s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm._ū",
            btnPreviousText: "ķ_Previous_ū",
            btnNextText: "ķ_Next_ū",
            webmapTabTitleText: "ķ_Select a Webmap_ū",
            viewWebmap: "ķ_View webmap_ū",
            btnSelectWebmapText: "ķ_Choose Webmap_ū",
            btnSelectWebmapTextLoading: "ķ_Loading&hellip;_ū",
            layerTabTitleText: "ķ_Select Editable Layer_ū",
            selectLayerLabelText: "ķ_Layer_ū",
            selectLayerDefaultOptionText: "ķ_Select Layer_ū",
            detailsTabTitleText: "ķ_Form Details_ū",
            detailTitleLabelText: "ķ_Title_ū",
            detailLogoLabelText: "ķ_Logo Image_ū",
            descriptionLabelText: "ķ_Help Text (optional)_ū",
            fieldTabFieldHeaderText: "ķ_Field_ū",
            fieldTabLabelHeaderText: "ķ_Label_ū",
            fieldTabDisplayTypeHeaderText: "ķ_Display As_ū",
            selectMenuOption: "ķ_Select Menu_ū",
            selectRadioOption: "ķ_Radio Button_ū",
            selectTextOption: "ķ_Text_ū",
            selectCheckboxOption: "ķ_Checkbox_ū",
            selectMailOption: "ķ_Email_ū",
            selectUrlOption: "ķ_URL_ū",
            selectTextAreaOption: "ķ_Textarea_ū",
            previewApplicationText: "ķ_Preview Application_ū",
            saveApplicationText: "ķ_Save Application_ū",
            saveText: "ķ_Save_ū",
            toggleNavigationText: "ķ_Toggle navigation_ū",
            formPlaceholderText: "ķ_My Form_ū",
            shareBuilderInProgressTitleMessage: "ķ_Publishing GeoForm_ū",
            shareBuilderProgressBarMessage: "ķ_Please Wait&hellip;_ū",
            shareBuilderTitleMessage: "ķ_Success! Item saved_ū",
            shareBuilderTextMessage: "ķ_You can start collecting information by sharing with others_ū",
            shareModalFormText: "ķ_Form Link_ū",
            shareBuilderSuccess: "ķ_Your GeoForm has been updated & published!_ū",
            geoformTitleText: "ķ_Geo Form_ū",
            layerTabText: "ķ_This is the layer that the GeoForm will be built from. The layer must be a feature service that is enabled for editing with sharing permissions appropriate for your audience._ū",
            detailsTabText: "ķ_Use the Form Detail boxes below to customize the Title, add a custom logo, and provide a short description for your GeoForm audience. In the description you can add links to other resources, contact information, and even point your audience to a web mapping application featuring all of the data collected with the GeoForm._ū",
            fieldsTabText: "ķ_Here you can select which fields will be visible to your GeoForm audience, edit the Labels they will see, and add a short Description to help with data entry._ū",
            styleTabText: "ķ_Style your GeoForm using the themes below based on your preference._ū",
            publishTabText: "ķ_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._ū",
            smallHeader: "ķ_Use Small Header_ū",
            pushpinText: "ķ_Push pin_ū",
            doneButtonText: "ķ_View Application Item_ū",
            fieldTabPlaceHolderHeaderText: "ķ_Hint (optional)_ū",
            attachmentLabelText: "ķ_Attchment Label_ū",
            attachmentLabelHint: "ķ_Tell users what type of file to attach._ū",
            attachmentDescription: "ķ_Attachment Description_ū",
            attachmentHint: "ķ_If necessary, you can provide additional attachment instructions here._ū",
            jumbotronDescription: "ķ_The Bootstrap Jumbotron makes it easy to define the purpose of your application. This can be disabled at any time._ū",
            shareGeoformText: "ķ_Share Geoform_ū",
            shareDescription: "ķ_The sharing panel makes it easy for your audience to share the GeoForm with other collaborators once they have made a submission - this can be disabled at any time._ū",
            defaultMapExtent: "ķ_Default Map Extent_ū",
            defaultMapExtentDescription: "ķ_The map will reset to the default extent in your web map after submission - this can be disabled at any time._ū",
            pushpinOptionsDescription: "ķ_Choose from a variety of colors for the map pushpin, it should be different from the map symbology to help the user put their submission on the map_ū",
            selectLocationText: "ķ_Select Location By_ū",
            myLocationText: "ķ_My Location_ū",
            searchText: "ķ_Search_ū",
            coordinatesText: "ķ_Latitude & Longitude Coordinates_ū",
            usng: "ķ_USNG Coordinates_ū",
            mgrs: "ķ_MGRS Coordinates_ū",
            utm: "ķ_UTM Coordinates_ū",
            selectLocationSDescription: "ķ_Allow users to select a location using these methods._ū"
        }
    })
);