define(
     ({
        map: {
            error: "Nevar izveidot karti"
        },
        onlineStatus: {
            offline: "Jūs pašreiz strādājat bezsaistē. Iesniegtās formas tiks saglabātas lokāli, līdz tiks izveidots savienojums ar serveri.",
            reconnecting: "Notiek atkārtota savienošana&hellip;",
            pending: "Kad tīkla savienojums tiks atjaunots, tiks iesniegti ${total} neapstrādāti labojumi."
        },
        configure: {
            mapdlg: {
                items: {
                    organizationLabel: "Organizācija",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Mans saturs",
                    favoritesLabel: "Mani favorīti"
                },
                title: "Izvēlēties web karti",
                searchTitle: "Meklēšana",
                ok: "Labi",
                cancel: "Atcelt",
                placeholder: "Ievadīt meklēšanas kritēriju"
            },
            groupdlg: {
                items: {
                    organizationLabel: "Organizācija",
                    onlineLabel: "ArcGIS Online",
                    contentLabel: "Mans saturs",
                    favoritesLabel: "Mani favorīti"
                },
                title: "Atlasīt grupu",
                searchTitle: "Meklēšana",
                ok: "Labi",
                cancel: "Atcelt",
                placeholder: "Ievadīt meklēšanas kritēriju"
            }
        },
        user: {
            mgrs: "MGRS",
            usng: "USNG",
            utm: "UTM",
            utm_northing: "Virzība uz ziemeļiem",
            utm_easting: "Virzība uz austrumiem",
            utm_zone_number: "Zonas numurs",
            geoFormGeneralTabText: "1. Ievadiet informāciju",
            locationInformationText: "2. Atlasiet atrašanās vietu",
            submitInformationText: "3. Aizpildiet veidlapu",
            submitInstructions: "Pievienot šo informāciju kartei.",
            myLocationText: "Pašreizējais izvietojums",
            locationDescription: "ķ_Specify the location for this entry by clicking/tapping the map or by using one of the following options._ū",
            addressText: "Meklēt",
            geographic: "ķ_Lat/Lon_ū",
            locationTabText: "Izvietojums",
            locationPopupTitle: "ķ_Location_ū",
            submitButtonText: "Iesniegt jaunu ierakstu",
            submitButtonTextLoading: "Iesniegšana&hellip;",
            formValidationMessageAlertText: "Tālāk norādītie lauki ir obligāti.",
            selectLocation: "Lūdzu, atlasiet iesniedzamo ${openLink}izvietojumu${closeLink}.",
            emptylatitudeAlertMessage: "Lūdzu, ievadiet ${openLink}platuma${closeLink} koordinātu.",
            emptylongitudeAlertMessage: "Lūdzu, ievadiet ${openLink}garuma${closeLink} koordinātu.",
            shareUserTitleMessage: "Pateicamies par ieguldījumu!",
            entrySubmitted: "ķ_Your entry has been submitted to the map._ū",
            shareThisForm: "ķ_Share This Form_ū",
            shareUserTextMessage: "Jūsu ieraksts ir iesniegts. Kopīgojiet ar citiem, izmantojot tālāk minētās iespējas.",
            addAttachmentFailedMessage: "Slānim nevar pievienot pielikumu",
            addFeatureFailedMessage: "Slānim nevar pievienot elementu",
            noLayerConfiguredMessage: "ķ_An error occured loading or finding an editable feature layer. In order to display the form and start collecting submissions, add an editable Feature Layer to the Webmap._ū",
            placeholderLatitude: "Platums (Y)",
            placeholderLongitude: "Garums (X)",
            latitude: "Platums",
            longitude: "Garums",
            findMyLocation: "ķ_Locate Me_ū",
            finding: "Izvietojuma noteikšana&hellip;",
            backToTop: "Augšup",
            addressSearchText: "Jūsu iesniegtā informācija būs redzama šeit. Varat vilkt spraudīti, lai koriģētu atrašanās vietu.",
            shareModalFormText: "Veidlapas saite",
            close: "Aizvērt",
            locationNotFound: "Izvietojumu nevar atrast.",
            setLocation: "ķ_Set Location_ū",
            find: "Atrast adresi vai vietu",
            attachment: "Pielikums",
            toggleDropdown: "Pārslēgt nolaižamo izvēlni",
            invalidLatLong: "Lūdzu, ievadiet derīgas ${latLink}platuma${closeLink} un ${lngLink}garuma${closeLink} koordinātas.",
            invalidUTM: "Lūdzu, ievadiet derīgas ${openLink}UTM${closeLink} koordinātas.",
            invalidUSNG: "Lūdzu, ievadiet derīgas ${openLink}USNG${closeLink} koordinātas.",
            invalidMGRS: "Lūdzu, ievadiet derīgas ${openLink}MGRS${closeLink} koordinātas.",
            geoformTitleText: "Ģeoveidlapa",
            domainDefaultText: "Atlasīt&hellip;",
            applyEditsFailedMessage: "Atvainojiet, jūsu informāciju nevar iesniegt. Lūdzu, mēģiniet vēlreiz.",
            requiredFields: "Radās kļūdas. Lūdzu, izlabojiet tās tālāk.",
            requiredField: "ķ_(required)_ū",
            error: "Kļūda",
            textRangeHintMessage: "ķ_${openStrong}Hint:${closeStrong} Minimum value ${minValue} and Maximum value ${maxValue}_ū",
            dateRangeHintMessage: "ķ_${openStrong}Hint:${closeStrong} Minimum Date ${minValue} and Maximum Date ${maxValue}_ū"
        },
        builder: {
            invalidUser: "Diemžēl jums nav atļaujas skatīt šo vienību",
            invalidWebmapSelectionAlert: "ķ_The selected webmap does not contain a valid layer to use. Please add an editable FeatureLayer into your webmap to continue._ū",
            invalidWebmapSelectionAlert2: "ķ_For More Information please refer to ${openLink}What is Feature Service?${closeLink}_ū",
            selectFieldsText: "Atlasīt veidlapas laukus",
            selectThemeText: "Atlasīt formas dizainu",
            webmapText: "Web karte",
            layerText: "Slānis",
            detailsText: "Detaļas",
            fieldsText: "Lauki",
            styleText: "Stils",
            optionText: "Opcijas",
            previewText: "Priekšskatījums",
            publishText: "Publicēt",
            optionsApplicationText: "Opcijas",
            titleText: "ķ_Builder_ū",
            descriptionText: "ķ_GeoForm is a configurable template for form-based data editing of a ${link1}Feature Service${closeLink}. This application allows users to enter data through a form instead of a map’s pop-up while leveraging the power of the ${link2}Web Map${closeLink} and editable Feature Services. Use the following steps to customize and deploy your GeoForm._ū",
            btnPreviousText: "ķ_Previous_ū",
            btnNextText: "ķ_Next_ū",
            webmapTabTitleText: "ķ_Select a Webmap_ū",
            viewWebmap: "Skatīt web karti",
            btnSelectWebmapText: "ķ_Choose Webmap_ū",
            btnSelectWebmapTextLoading: "Notiek ielāde&hellip;",
            layerTabTitleText: "Atlasiet rediģējamu slāni",
            selectLayerLabelText: "Slānis",
            selectLayerDefaultOptionText: "Atlasīt slāni",
            detailsTabTitleText: "Formas detaļas",
            detailTitleLabelText: "ķ_Title_ū",
            detailLogoLabelText: "Logotipa attēls",
            descriptionLabelText: "ķ_Help Text (optional)_ū",
            fieldTabFieldHeaderText: "Lauks",
            fieldTabLabelHeaderText: "Kartes teksts",
            fieldTabDisplayTypeHeaderText: "Parādīt kā",
            selectMenuOption: "ķ_Select Menu_ū",
            selectRadioOption: "ķ_Radio Button_ū",
            selectTextOption: "Teksts",
            selectCheckboxOption: "ķ_Checkbox_ū",
            selectMailOption: "ķ_Email_ū",
            selectUrlOption: "URL",
            selectTextAreaOption: "ķ_Textarea_ū",
            previewApplicationText: "Priekšskatīt aplikāciju",
            saveApplicationText: "Saglabāt aplikāciju",
            saveText: "Saglabāt",
            toggleNavigationText: "Pārslēgt navigāciju",
            formPlaceholderText: "Mana veidlapa",
            shareBuilderInProgressTitleMessage: "GeoForm publicēšana",
            shareBuilderProgressBarMessage: "Lūdzu, uzgaidiet&hellip;",
            shareBuilderTitleMessage: "ķ_Success! Item saved_ū",
            shareBuilderTextMessage: "Varat sākt apkopot infomāciju, kopīgojot ar citiem.",
            shareModalFormText: "Veidlapas saite",
            shareBuilderSuccess: "Jūsu GeoForm ir atjaunināta un publicēta.",
            geoformTitleText: "Geo Form",
            layerTabText: "Šis ir slānis, no kura tiks veidota GeoForm. Slānim ir jābūt elementu servisam ar iespējotu rediģēšanu un kopīgošanas atļaujām, kas ir piemērotas jūsu auditorijai.",
            detailsTabText: "Izmantojiet tālāk esošos veidlapas informācijas lodziņus, lai pielāgotu virsrakstu un pievienotu pielāgotu logotipu, kā arī sniedziet īsu aprakstu, kas paredzēts GeoForm auditorijai. Aprakstā varat pievienot saites uz citiem resursiem, kontaktinformāciju un norādīt auditorijai uz web kartēšanas lietotni, kurā attēloti visi dati, kas apkopoti, izmantojot GeoForm.",
            fieldsTabText: "Šeit varat atlasīt, kuri lauki būs redzami jūsu GeoForm auditorijai, rediģēt apzīmējumus, kurus viņi redzēs, un pievienot īsu aprakstu, lai atvieglotu datu ievadi.",
            styleTabText: "Veidojiet savas GeoForm stilu, atbilstoši savām vēlmēm izmantojot tālāk esošos motīvus.",
            publishTabText: "ķ_If you are finished customizing your GeoForm, save the application and begin sharing with your audience. You can always return to this builder and continue customizing it based on feedback._ū",
            smallHeader: "Izmantojiet mazo galveni",
            pushpinText: "Spraudīte",
            doneButtonText: "Skatīt lietotnes vienību",
            fieldTabPlaceHolderHeaderText: "ķ_Hint (optional)_ū",
            attachmentLabelText: "ķ_Attchment Label_ū",
            attachmentLabelHint: "ķ_Tell users what type of file to attach._ū",
            attachmentDescription: "Pielikuma apraksts",
            attachmentHint: "ķ_If necessary, you can provide additional attachment instructions here._ū",
            jumbotronDescription: "ķ_The Bootstrap Jumbotron makes it easy to define the purpose of your application. This can be disabled at any time._ū",
            shareGeoformText: "Kopīgot ģeoveidlapu",
            shareDescription: "Koplietošanas panelis atvieglo auditorijai iespēju koplietot GeoForm ar citiem sadarbības partneriem pēc iesniegšanas pabeigšanas — šo darbību jebkurā laikā var atspējot.",
            defaultMapExtent: "Noklusējuma kartes paplašinājums",
            defaultMapExtentDescription: "Pēc iesniegšanas karte tiks atiestatīta uz noklusējuma paplašinājumu jūsu web kartē — šo darbību jebkurā laikā var atspējot.",
            pushpinOptionsDescription: "Kartes spraudītei izvēlieties kādu no plašā krāsu klāsta; spraudītei vajadzētu atšķirties no kartes simboliem lietotajām krāsām, lai lietotājiem būtu vieglāk piedalīties kartes veidošanā.",
            selectLocationText: "Izvēlēties izvietojumu pēc",
            myLocationText: "ķ_My Location_ū",
            searchText: "ķ_Search_ū",
            coordinatesText: "Ģeogrāfiskā platuma un garuma koordinātas",
            usng: "USNG koordinātas",
            mgrs: "MGRS koordinātas",
            utm: "UTM koordinātas",
            selectLocationSDescription: "Atļaujiet lietotājiem izvēlēties izvietojumu, izmantojot šīs metodes."
        }
    })
);